OFF: OFF
OFF
Programs
Functions/Subroutines
program off
OFF is an Open source Finite volumes Fluid dynamics code.
Detailed Description
Function/Subroutine Documentation
program off ()
OFF is an Open source Finite volumes Fluid dynamics code.
It is written in in standard (compliant) Fortran 2003 with highly modularity as design target.
The aim of OFF is to solve, numerically, the compressible Navier-Stokes equations of fluid dynamics (see governing equations) by means of Finite Volumes techniques. The main features of OFF code are the following:
Finite Volume, Godunov-like scheme based on Euler conservation Laws written in fully conservative formulation:
the extension to viscous Navier-Stokes equations is under developing;
Underling Riemann Problem solver for convective fluxes:
Approximate Riemann solver based on (local) Lax-Friedrichs (known also as Rusanov) algorithm;
Approximate Riemann solver based on Primitive Variables Linearization algorithm;
Approximate Riemann solver based on Two Rarefactions algorithm;
Approximate Riemann solver based on Two Shocks algorithm;
Approximate Riemann solver based on Adaptive (non iterative) PVL-TR-TS algorithm;
Approximate Riemann solver based on Adaptive (non iterative) LF-TR algorithm;
Approximate Riemann solver based on HLLC algorithm;
Approximate Riemann solver based on Roe linearization.
Exact Riemann solver based on iterative solution of u-function;
Multi-Species fluids models:
Partial Densities species conservation (Standard Thermodynamic Model);
New multi-dimensional conservation models of Favini, B. et al (under developing);
Multi-Phases fluids models:
Fully-coupled Lagrangian particles transport model (under developing);
Space numerical integration models:
order piece-wise constant reconstruction;
order TVD linear-wise reconstruction;
, , order WENO non-linear reconstruction;
Time approximation models:
order forward Euler integration;
, , order Strong-Stability-Preserving explicit Runge-Kutta integration;
Local pseudo-time convergence acceleration for steady simulations;
Multi-grid time convergence acceleration:
Multi-grid model has been already developed, but it is affected by some not still recognized bugs. Testing and bugs fixing are in progress.
Underling numerical grid models:
3D, general curvilinear, body-fitted, structured multi-blocks mesh;
Adaptive Mesh Refinement, AMR model (under developing);
Blocks overlapping, overset (Chimera) model (to be developed in future);
Computational parallelism ability:
Domain decomposition by means of Message Passing Interface (MPI) paradigm providing the ability to use distributed-memory cluster facilities;
Fine, local parallelism by means of OpenMP paradigm providing the ability to use shared-memory cluster facilities;
Fine, local parallelism by means of GPU programming (e.g. CUDA framework) providing the ability to use GPUs cluster facilities (to be developed in future).
Author
Stefano Zaghi
Version
0.0.5
Date
2012-04-24
Copyright
GNU Public License version 3.
Note
Compiling Instructions
OFF is shipped with a makefile for compiling the codes on Unix/GNU Linux architectures. Other OS are not supported. For more details see Compiling Instructions.
Bug:
Multi-grid Models:
Multi-grid time convergence acceleration has been developed, but it is affected by some bugs that blow up steady simulations.
Todo:
MultiSpeciesModel: Introducing new multi-dimensional conservation models of Favini, B. et al
MultiPhaseModel: Introducing fully-coupled Lagrangian particles transport model
AMR: Introducing AMR (Adaptive Mesh Refinement) model
Chimera: Introducing blocks overlapping, overset (Chimera) model
GPU: Introducing fine, local parallelism by means of GPU programming (e.g. CUDA framework)
DocImprove: Improve the documentation
Definition at line 98 of file OFF.f90.
References lib_io_misc::basename(), lib_parallel::blockmap, lib_fluidynamic::boundary_conditions(), lib_fluidynamic::conservative2primitive(), ir_precision::fr_p, lib_io_misc::get_unit(), lib_parallel::init_sendrecv(), lib_parallel::nproc, lib_parallel::nthreads, off_init(), lib_thermodynamic_laws_ideal::p(), lib_fluidynamic::primitive2conservative(), lib_parallel::procmap_load(), lib_profiling::profile(), lib_io_misc::remove_file(), lib_runge_kutta::rk_init(), lib_fluidynamic::solve_grl(), data_type_tensor::sq_norm::sq_norm_ten(), lib_weno::weno_init(), and data_type_primitive::write_primitive().