OFF: Data_Type_Time
Data_Type_Time
Derived Types
Data Types
type data_type_time::type_time
Derived type containing time variables.
Detailed Description
Data Type Documentation
type data_type_time::type_time
Derived type containing time variables.
Definition at line 59 of file Data_Type_Time.f90.
Public Member Functions
procedure, non_overridable sec2time
Public Attributes
integer(i4p) days
Number of days.
integer(i4p) hours
Number of hours.
integer(i4p) minutes
Number of minutes.
real(r8p) seconds
Number of seconds.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_time::type_time::sec2time ()
Definition at line 65 of file Data_Type_Time.f90.
References data_type_time::operator(==)::eq(), data_type_time::operator(>)::great(), data_type_time::operator(>=)::great_eq(), data_type_time::operator(<)::low(), data_type_time::operator(<=)::low_eq(), and data_type_time::operator(/=)::not_eq().
Member Data Documentation
integer(i4p) data_type_time::type_time::days
Number of days.
Definition at line 60 of file Data_Type_Time.f90.
integer(i4p) data_type_time::type_time::hours
Number of hours.
Definition at line 61 of file Data_Type_Time.f90.
integer(i4p) data_type_time::type_time::minutes
Number of minutes.
Definition at line 62 of file Data_Type_Time.f90.
real(r8p) data_type_time::type_time::seconds
Number of seconds.
Definition at line 63 of file Data_Type_Time.f90.