OFF: Data_Type_Primitive
Data_Type_Primitive
Derived Types
Data Types
type data_type_primitive::type_primitive
Derived type containing primitive variables.
Detailed Description
Data Type Documentation
type data_type_primitive::type_primitive
Derived type containing primitive variables.
Note
This derived type can represent multi species fluids. The density component, r, is a dynamic memory component defined as an allocatable 1D array. r is allocated at runtime with the number of initial species that constitute the initial fluid mixture. Due to the presence of a dynamic component a freeing memory "method" for this component is necessary. Before deallocate a variable defined as Type_Primitive the free function must be invoked to free the memory of the dynamic component.
Definition at line 55 of file Data_Type_Primitive.f90.
Public Member Functions
procedure, non_overridable init
procedure, non_overridable free
procedure, non_overridable prim2array
procedure, non_overridable array2prim
procedure, non_overridable pprint
Public Attributes
real(r8p), dimension(:),
allocatable r
Density of single species [1:Ns].
type(type_vector) v
Velocity vector.
real(r8p) p = 0._R8P
Pressure.
real(r8p) d = 0._R8P
Density = sum(r(1:Ns)).
real(r8p) g = 0._R8P
Specific heats ratio .
Member Function/Subroutine Documentation
procedure, non_overridable data_type_primitive::type_primitive::init ()
Definition at line 62 of file Data_Type_Primitive.f90.
References data_type_conservative::type_conservative::pprint().
procedure, non_overridable data_type_primitive::type_primitive::free ()
Definition at line 63 of file Data_Type_Primitive.f90.
procedure, non_overridable data_type_primitive::type_primitive::prim2array ()
Definition at line 64 of file Data_Type_Primitive.f90.
procedure, non_overridable data_type_primitive::type_primitive::array2prim ()
Definition at line 65 of file Data_Type_Primitive.f90.
procedure, non_overridable data_type_primitive::type_primitive::pprint ()
Definition at line 66 of file Data_Type_Primitive.f90.
References data_type_primitive::assignment(=)::assign_prim(), and data_type_vector::assign_scalr16p().
Member Data Documentation
real(r8p), dimension(:), allocatable data_type_primitive::type_primitive::r
Density of single species [1:Ns].
Definition at line 56 of file Data_Type_Primitive.f90.
type(type_vector) data_type_primitive::type_primitive::v
Velocity vector.
Definition at line 57 of file Data_Type_Primitive.f90.
real(r8p) data_type_primitive::type_primitive::p = 0._R8P
Pressure.
Definition at line 58 of file Data_Type_Primitive.f90.
real(r8p) data_type_primitive::type_primitive::d = 0._R8P
Density = sum(r(1:Ns)).
Definition at line 59 of file Data_Type_Primitive.f90.
real(r8p) data_type_primitive::type_primitive::g = 0._R8P
Specific heats ratio .
Definition at line 60 of file Data_Type_Primitive.f90.