OFF: Data_Type_OS
Data_Type_OS
Global Variables and Parameters
character(3), parameter, public data_type_os::c_uix_id = "UIX"
Unix/Linux string identifier.
integer(i1p), parameter, public data_type_os::uix_id = 1_I1P
Unix/Linux identifier.
character(1), parameter, public data_type_os::uix_sep = "/"
Unix/Linux directories separator.
character(2), parameter, public data_type_os::uix_remove = "rm"
Unix/Linux remove command.
character(2), parameter, public data_type_os::uix_copy = "cp"
Unix/Linux copy command.
character(5), parameter, public data_type_os::uix_mkdir = "mkdir"
Unix/Linux make dir command.
character(3), parameter, public data_type_os::c_win_id = "WIN"
MS Windows string identifier.
integer(i1p), parameter, public data_type_os::win_id = 2_I1P
MS Windows identifier.
character(3), parameter, public data_type_os::win_remove = "del"
MS Windows remove command.
character(4), parameter, public data_type_os::win_copy = "copy"
MS Windows copy command.
character(5), parameter, public data_type_os::win_mkdir = "mkdir"
MS Windows make dir command.
Detailed Description
Variable Documentation
character(3), parameter, public data_type_os::c_uix_id = "UIX"
Unix/Linux string identifier.
Definition at line 44 of file Data_Type_OS.f90.
integer(i1p), parameter, public data_type_os::uix_id = 1_I1P
Unix/Linux identifier.
Definition at line 45 of file Data_Type_OS.f90.
Referenced by lib_io_misc::string_os_sep().
character(1), parameter, public data_type_os::uix_sep = "/"
Unix/Linux directories separator.
Definition at line 46 of file Data_Type_OS.f90.
Referenced by lib_io_misc::string_os_sep().
character(2), parameter, public data_type_os::uix_remove = "rm"
Unix/Linux remove command.
Definition at line 47 of file Data_Type_OS.f90.
character(2), parameter, public data_type_os::uix_copy = "cp"
Unix/Linux copy command.
Definition at line 48 of file Data_Type_OS.f90.
character(5), parameter, public data_type_os::uix_mkdir = "mkdir"
Unix/Linux make dir command.
Definition at line 49 of file Data_Type_OS.f90.
character(3), parameter, public data_type_os::c_win_id = "WIN"
MS Windows string identifier.
Definition at line 50 of file Data_Type_OS.f90.
integer(i1p), parameter, public data_type_os::win_id = 2_I1P
MS Windows identifier.
Definition at line 51 of file Data_Type_OS.f90.
Referenced by lib_io_misc::string_os_sep().
character(3), parameter, public data_type_os::win_remove = "del"
MS Windows remove command.
Definition at line 55 of file Data_Type_OS.f90.
character(4), parameter, public data_type_os::win_copy = "copy"
MS Windows copy command.
Definition at line 56 of file Data_Type_OS.f90.
character(5), parameter, public data_type_os::win_mkdir = "mkdir"
MS Windows make dir command.
Definition at line 57 of file Data_Type_OS.f90.