OFF: Lib_Profiling
Lib_Profiling
Public Procedures
Functions/Subroutines
subroutine, public lib_profiling::profile (Np, fnamep, header, p, pstart, pstop, finalize, myrank)
Subroutine for profiling the code.
Detailed Description
Function/Subroutine Documentation
subroutine, public lib_profiling::profile (integer(i_p), intent(in), optional Np, character(*), intent(in), optional fnamep, character(*), dimension(:), intent(in), optional header, integer(i_p), intent(in), optional p, logical, intent(in), optional pstart, logical, intent(in), optional pstop, logical, intent(in), optional finalize, integer(i_p), intent(in) myrank)
Subroutine for profiling the code.
Parameters
[in] np Number of parts of the code profiled. Initializing the profiling if passed.
[in] fnamep Prefix name of profiling files: can be passed only with Np.
[in] header Headers of profiling files: can be passed only with Np.
[in] p Number of part of the code currently profiled.
[in] pstart Flag for start the profiling of the current profiled part of the code.
[in] pstop Flag for stop the profiling of the current profiled part of the code.
[in] finalize Flag for finilizing the profiling of the code.
[in] myrank Current rank process.
Definition at line 54 of file Lib_Profiling.f90.
References lib_io_misc::get_unit(), lib_profiling::instant0, lib_profiling::npp, lib_parallel::nproc, lib_parallel::nthreads, lib_thermodynamic_laws_ideal::p(), and lib_profiling::partial.
Referenced by off(), off_init(), and lib_fluidynamic::solve_grl().