OFF: data_type_amrblock Module Reference
data_type_amrblock Module Reference
Module Data_Type_AMRBlock contains the definition of Type_AMRBlock type and useful procedures for its handling.
Data Types
type type_amrblock
Derived type containing AMR (hierarchical, dynamic) grid data.
Public Member Functions
elemental function, public level (ID)
Function for computing the level correspoinding to the passed ID.
elemental function, public firstid (level)
Function for computing the first ID of the passed level.
elemental function, public lastid (level)
Function for computing the last ID of the passed level.
pure function, public siblings (ID)
Function for computing the IDs of siblings of a given ID.
elemental function, public child (pID)
Function for computing the ID of child of a given (parent) ID.
elemental function, public directparent (ID)
Function for computing the direct parent ID of a given ID.
elemental function, public parentatlevel (ID, l)
Function for computing the parent ID of a given ID at a given level.
pure function, public directchildren (ID)
Function for computing the direct children IDs of a given ID.
subroutine init_amrblock (block, b)
Subroutine for initializing the AMR grid.
integer(i_p) function load_basemesh_dims (block, ascii, filename)
Function for loading the base mesh data dimensions of block from the mesh file 'filename'.
Detailed Description
Module Data_Type_AMRBlock contains the definition of Type_AMRBlock type and useful procedures for its handling.
Definition at line 21 of file Data_Type_AMRBlock.f90.
Member Function/Subroutine Documentation
subroutine data_type_amrblock::init_amrblock (class(type_amrblock), intent(inout) block, integer(i2p), intent(in) b)
Subroutine for initializing the AMR grid.
Parameters
[in,out] block AMR block.
[in] b Block number (in the global ordering).
Definition at line 129 of file Data_Type_AMRBlock.f90.
References lib_thermodynamic_laws_ideal::p().
integer(i_p) function data_type_amrblock::load_basemesh_dims (class(type_amrblock), intent(inout) block, logical, intent(in), optional ascii, character(*), intent(in) filename) private
Function for loading the base mesh data dimensions of block from the mesh file 'filename'.
Returns
err integer(I_P) variable.
Parameters
[in,out] block Block level data.
[in] ascii Flag for ascii file.
[in] filename Name of file where mesh variables are saved.
Definition at line 161 of file Data_Type_AMRBlock.f90.
References lib_vtk_io::ascii, lib_io_misc::file_not_found(), and lib_io_misc::get_unit().
The documentation for this module was generated from the following file:
Data_Type_AMRBlock.f90