OFF: Lib_Parallel
Lib_Parallel
Global Variables and Parameters
integer(i_p), public lib_parallel::nthreads = 1_I_P
Number of OpenMP threads.
integer(i_p), public lib_parallel::nproc = 1_I_P
Number of processes (for MPI parallelization).
integer(i_p), dimension(:),
allocatable, public lib_parallel::procmap
Processes/blocks map [1:Nb_tot].
integer(i_p), dimension(:),
allocatable, public lib_parallel::blockmap
Local/global blocks map [1:Nb].
Detailed Description
Variable Documentation
integer(i_p), public lib_parallel::nthreads = 1_I_P
Number of OpenMP threads.
Definition at line 68 of file Lib_Parallel.f90.
Referenced by off(), off_init(), and lib_profiling::profile().
integer(i_p), public lib_parallel::nproc = 1_I_P
Number of processes (for MPI parallelization).
Definition at line 69 of file Lib_Parallel.f90.
Referenced by lib_parallel::alloc_sr(), lib_parallel::compute_bbs(), lib_parallel::compute_ncr(), lib_parallel::compute_recv_maps(), lib_parallel::mapsendrecv(), lib_parallel::ncrsendrecv(), off(), off_init(), lib_parallel::printsendrecvmaps(), lib_parallel::procmap_load(), lib_profiling::profile(), and lib_parallel::psendrecv().
integer(i_p), dimension(:), allocatable, public lib_parallel::procmap
Processes/blocks map [1:Nb_tot].
Definition at line 70 of file Lib_Parallel.f90.
Referenced by lib_parallel::compute_ncr(), lib_parallel::procmap_load(), lib_parallel::procmap_save(), scan_block(), and set_in1().
integer(i_p), dimension(:), allocatable, public lib_parallel::blockmap
Local/global blocks map [1:Nb].
Definition at line 71 of file Lib_Parallel.f90.
Referenced by lib_fluidynamic::boundary_conditions(), off(), off_init(), lib_parallel::procmap_load(), lib_parallel::psendrecv(), lib_fluidynamic::rk_stages_sum(), set_ext_l(), set_in1(), and lib_fluidynamic::solve_grl().