OFF: Data_Type_Global
Data_Type_Global
Private Procedures
character(len_trim(basename)+4+5+len_trim(suffix))
function data_type_global::block_file_name (basename, suffix, blk, grl)
Function for building block-clean file name.
character(len_trim(basename)+4+5+13+len_trim(suffix))
function data_type_global::block_step_file_name (basename, suffix, blk, grl, n)
Function for building block-time_step file name.
character(len_trim(basename)+3+4+5+len_trim(suffix))
function data_type_global::block_flip_file_name (basename, suffix, blk, grl, flip)
Function for building block-flip_flop file name.
subroutine data_type_global::compute_values0 (global)
Subroutine for computing the reference values for non-dimensional quantities.
subroutine data_type_global::alloc_gbc (global)
Subroutine for allocating dynamic data of Type_Global boundary conditions variables.
subroutine data_type_global::alloc_gfluid (global)
Subroutine for allocating dynamic data of Type_Global fluid dynamic variables.
integer(i_p) function data_type_global::load_gbc_in1 (global, filename, in1)
Function for loading inflow 1 boundary conditions.
integer(i_p) function data_type_global::load_gfluid_soption (global, filename)
Function for loading solver option variables.
integer(i_p) function data_type_global::load_gfluid_ns (global, binary, filename)
Function for loading the number of species from fluid dynamic file "filename".
integer(i_p) function data_type_global::load_gfluid_0species (global, filename)
Function for loading initial species from ascii file.
Detailed Description
Function/Subroutine Documentation
character(len_trim(basename)+4+5+len_trim(suffix)) function data_type_global::block_file_name (character(*), intent(in) basename, character(*), intent(in) suffix, integer(i_p), intent(in) blk, integer(i_p), intent(in) grl) private
Function for building block-clean file name.
Returns
filename character(len_trim(basename)+4+5+len_trim(suffix)) variable.
Parameters
[in] basename Base name of file name.
[in] suffix Suffix of file name.
[in] blk Block number.
[in] grl Grid refinement level.
Definition at line 153 of file Data_Type_Global.f90.
References lib_io_misc::basename().
character(len_trim(basename)+4+5+13+len_trim(suffix)) function data_type_global::block_step_file_name (character(*), intent(in) basename, character(*), intent(in) suffix, integer(i_p), intent(in) blk, integer(i_p), intent(in) grl, integer(i8p), intent(in) n) private
Function for building block-time_step file name.
Returns
filename character(len_trim(basename)+4+5+13+len_trim(suffix)) variable.
Parameters
[in] basename Base name of file name.
[in] suffix Suffix of file name.
[in] blk Block number.
[in] grl Grid refinement level.
[in] n Time step number.
Definition at line 171 of file Data_Type_Global.f90.
References lib_io_misc::basename().
character(len_trim(basename)+3+4+5+len_trim(suffix)) function data_type_global::block_flip_file_name (character(*), intent(in) basename, character(*), intent(in) suffix, integer(i_p), intent(in) blk, integer(i_p), intent(in) grl, integer(i1p), intent(in) flip) private
Function for building block-flip_flop file name.
Returns
filename character(len_trim(basename)+3+4+5+len_trim(suffix)) variable.
Parameters
[in] basename Base name of file name.
[in] suffix Suffix of file name.
[in] blk Block number.
[in] grl Grid refinement level.
[in] flip Flip-flop number.
Definition at line 190 of file Data_Type_Global.f90.
References lib_io_misc::basename().
subroutine data_type_global::compute_values0 (type(type_global), intent(inout) global) private
Subroutine for computing the reference values for non-dimensional quantities.
Parameters
[in,out] global Global level data.
Definition at line 208 of file Data_Type_Global.f90.
Referenced by data_type_global::load_gfluid_soption().
subroutine data_type_global::alloc_gbc (class(type_global), intent(inout) global) private
Subroutine for allocating dynamic data of Type_Global boundary conditions variables.
Parameters
[in,out] global Global data.
Definition at line 234 of file Data_Type_Global.f90.
subroutine data_type_global::alloc_gfluid (class(type_global), intent(inout) global) private
Subroutine for allocating dynamic data of Type_Global fluid dynamic variables.
Parameters
[in,out] global Global data.
Definition at line 250 of file Data_Type_Global.f90.
Referenced by data_type_global::type_global::load_bc_in1().
integer(i_p) function data_type_global::load_gbc_in1 (class(type_global), intent(inout) global, character(*), intent(in) filename, integer(i_p), intent(in) in1) private
Function for loading inflow 1 boundary conditions.
Returns
err integer(I4P) variable.
Parameters
[in,out] global Global level data.
[in] filename Name of file where boundary conditions variables are saved.
[in] in1 Actual in1 index.
Definition at line 265 of file Data_Type_Global.f90.
References lib_io_misc::file_not_found(), lib_io_misc::get_unit(), and data_type_primitive::read_primitive().
integer(i_p) function data_type_global::load_gfluid_soption (class(type_global), intent(inout) global, character(*), intent(in) filename) private
Function for loading solver option variables.
Returns
err integer(I4P) variable.
Parameters
[in,out] global Global level data.
[in] filename Name of file where option variables are saved.
Definition at line 295 of file Data_Type_Global.f90.
References data_type_global::compute_values0(), lib_io_misc::file_not_found(), lib_io_misc::get_unit(), and lib_io_misc::upper_case().
integer(i_p) function data_type_global::load_gfluid_ns (class(type_global), intent(inout) global, logical, intent(in), optional binary, character(*), intent(in) filename) private
Function for loading the number of species from fluid dynamic file "filename".
Returns
err integer(I4P) variable.
Parameters
[in,out] global Global level data.
[in] binary Flag for binary of ascii input file.
[in] filename Name of file where mesh variables are saved.
Definition at line 344 of file Data_Type_Global.f90.
References lib_vtk_io::binary, lib_io_misc::file_not_found(), and lib_io_misc::get_unit().
integer(i_p) function data_type_global::load_gfluid_0species (class(type_global), intent(inout) global, character(*), intent(in) filename) private
Function for loading initial species from ascii file.
Returns
err integer(I4P) variable.
Parameters
[in,out] global Global level data.
[in] filename Name of file where initial species are saved.
Definition at line 376 of file Data_Type_Global.f90.
References lib_io_misc::file_not_found(), lib_io_misc::get_unit(), and lib_thermodynamic_laws_ideal::r().
Referenced by data_type_global::type_global::alloc_bc().