OFF: Lib_Multigrid.f90 File Reference
Lib_Multigrid.f90 File Reference
Data Types
module lib_multigrid
This module contains the definition of multigrid procedures.
Functions/Subroutines
subroutine fine2coarse_u (gc, Ni_f, Nj_f, Nk_f, Ni_c, Nj_c, Nk_c, Nc, V_f, V_c, U_f, U_c)
subroutine fine2coarse_r (gc, Ni_f, Nj_f, Nk_f, Ni_c, Nj_c, Nk_c, Nc, R_f, R_c)
subroutine te_estimation (gc, Ni, Nj, Nk, Nc, U, R, UR, TE)
subroutine get_correction (gc, Ni, Nj, Nk, Nc, UR, U, CU)
subroutine coarse2fine_u (gc, Ni_c, Nj_c, Nk_c, Ni_f, Nj_f, Nk_f, Nc, U_c, U_f)
subroutine update_fine (gc, Ni, Nj, Nk, Nc, CU, U)
Function/Subroutine Documentation
subroutine restrict::fine2coarse_u (integer(i_p), dimension(1:6), intent(in) gc, integer(i_p), intent(in) Ni_f, integer(i_p), intent(in) Nj_f, integer(i_p), intent(in) Nk_f, integer(i_p), intent(in) Ni_c, integer(i_p), intent(in) Nj_c, integer(i_p), intent(in) Nk_c, integer(i_p), intent(in) Nc, real(r_p), dimension(1-gc(1):ni_f+gc(2),1-gc(3):nj_f+gc(4),1-gc(5):nk_f+gc(6)), intent(in) V_f, real(r_p), dimension(1-gc(1):ni_c+gc(2),1-gc(3):nj_c+gc(4),1-gc(5):nk_c+gc(6)), intent(in) V_c, real(r_p), dimension(1:nc,1-gc(1):ni_f+gc(2),1-gc(3):nj_f+gc(4),1-gc(5):nk_f+gc(6)), intent(in) U_f, real(r_p), dimension(1:nc,1-gc(1):ni_c+gc(2),1-gc(3):nj_c+gc(4),1-gc(5):nk_c+gc(6)), intent(out) U_c) private
Definition at line 212 of file Lib_Multigrid.f90.
Referenced by lib_multigrid::restrict().
subroutine restrict::fine2coarse_r (integer(i_p), dimension(1:6), intent(in) gc, integer(i_p), intent(in) Ni_f, integer(i_p), intent(in) Nj_f, integer(i_p), intent(in) Nk_f, integer(i_p), intent(in) Ni_c, integer(i_p), intent(in) Nj_c, integer(i_p), intent(in) Nk_c, integer(i_p), intent(in) Nc, real(r_p), dimension(1:nc,1-gc(1):ni_f+gc(2),1-gc(3):nj_f+gc(4),1-gc(5):nk_f+gc(6)), intent(in) R_f, real(r_p), dimension(1:nc,1-gc(1):ni_c+gc(2),1-gc(3):nj_c+gc(4),1-gc(5):nk_c+gc(6)), intent(out) R_c) private
Definition at line 251 of file Lib_Multigrid.f90.
Referenced by lib_multigrid::restrict().
subroutine restrict::te_estimation (integer(i_p), dimension(1:6), intent(in) gc, integer(i_p), intent(in) Ni, integer(i_p), intent(in) Nj, integer(i_p), intent(in) Nk, integer(i_p), intent(in) Nc, real(r_p), dimension (1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(in) U, real(r_p), dimension (1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(in) R, real(r_p), dimension(1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(out) UR, real(r_p), dimension(1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(inout) TE) private
Definition at line 289 of file Lib_Multigrid.f90.
References lib_thermodynamic_laws_ideal::r().
Referenced by lib_multigrid::restrict().
subroutine correct::get_correction (integer(i_p), dimension(1:6), intent(in) gc, integer(i_p), intent(in) Ni, integer(i_p), intent(in) Nj, integer(i_p), intent(in) Nk, integer(i_p), intent(in) Nc, real(r_p), dimension(1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(in) UR, real(r_p), dimension (1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(in) U, real(r_p), dimension(1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(out) CU) private
Definition at line 473 of file Lib_Multigrid.f90.
Referenced by lib_multigrid::correct().
subroutine correct::coarse2fine_u (integer(i_p), dimension(1:6), intent(in) gc, integer(i_p), intent(in) Ni_c, integer(i_p), intent(in) Nj_c, integer(i_p), intent(in) Nk_c, integer(i_p), intent(in) Ni_f, integer(i_p), intent(in) Nj_f, integer(i_p), intent(in) Nk_f, integer(i_p), intent(in) Nc, real(r_p), dimension(1:nc,1-gc(1):ni_c+gc(2),1-gc(3):nj_c+gc(4),1-gc(5):nk_c+gc(6)), intent(in) U_c, real(r_p), dimension(1:nc,1-gc(1):ni_f+gc(2),1-gc(3):nj_f+gc(4),1-gc(5):nk_f+gc(6)), intent(out) U_f) private
Definition at line 509 of file Lib_Multigrid.f90.
Referenced by lib_multigrid::correct().
subroutine correct::update_fine (integer(i_p), dimension(1:6), intent(in) gc, integer(i_p), intent(in) Ni, integer(i_p), intent(in) Nj, integer(i_p), intent(in) Nk, integer(i_p), intent(in) Nc, real(r_p), dimension(1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(in) CU, real(r_p), dimension (1:nc,1-gc(1):ni+gc(2),1-gc(3):nj+gc(4),1-gc(5):nk+gc(6)), intent(inout) U) private
Definition at line 570 of file Lib_Multigrid.f90.
Referenced by lib_multigrid::correct().