OFF: Lib_PostProcessing.f90 File Reference
Lib_PostProcessing.f90 File Reference
Data Types
module lib_postprocessing
This module contains the definition of procedures and variables useful for post-process the OFF data.
type lib_postprocessing::type_pp_format
Derived type containing the post-processing options.
Functions/Subroutines
subroutine tec_init ()
integer(i_p) function tec_blk_data (b, global, block)
integer(i_p) function tec_dat (N, dat)
integer(i_p) function vtk_blk_data (global, block, filename)
integer(i_p) function gnu_blk_data (block, filename)
Function/Subroutine Documentation
subroutine tec_output::tec_init () private
Definition at line 227 of file Lib_PostProcessing.f90.
References lib_io_misc::get_unit(), and tec_blk_data().
integer(i_p) function tec_output::tec_blk_data (integer(i_p), intent(in) b, type(type_global), intent(in) global, type(type_sblock), intent(inout) block) private
Definition at line 290 of file Lib_PostProcessing.f90.
References lib_postprocessing::compute_dimensions(), ir_precision::fr_p, lib_postprocessing::interpolate_primitive(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by tec_init().
integer(i_p) function tec_output::tec_dat (integer(i_p), intent(in) N, real(r_p), dimension(1:n), intent(in) dat) private
Definition at line 414 of file Lib_PostProcessing.f90.
References lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_postprocessing::vtk_output().
integer(i_p) function vtk_output::vtk_blk_data (type(type_global), intent(in) global, type(type_sblock), intent(inout) block, character(*), intent(in) filename) private
Definition at line 470 of file Lib_PostProcessing.f90.
References lib_postprocessing::compute_dimensions(), ir_precision::fr_p, lib_postprocessing::interpolate_primitive(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
integer(i_p) function gnu_output::gnu_blk_data (type(type_sblock), intent(inout) block, character(*), intent(in) filename) private
Definition at line 612 of file Lib_PostProcessing.f90.
References lib_postprocessing::compute_dimensions(), ir_precision::fr8p, lib_io_misc::get_unit(), lib_postprocessing::interpolate_primitive(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), lib_vtk_io::vtk_dat_xml(), and lib_vtk_io::vtk_end_xml().