OFF: Lib_Morton
Lib_Morton
Private Variables and Parameters
integer(i8p), parameter lib_morton::mask32_32 = Z'FFFFFFFF'
0000000000000000000000000000000011111111111111111111111111111111.
integer(i8p), parameter lib_morton::mask16_48 = Z'FFFF'
0000000000000000000000000000000000000000000000001111111111111111.
integer(i8p), parameter lib_morton::mask16_32 = Z'FFFF00000000FFFF'
integer(i8p), parameter lib_morton::mask16_16 = Z'FFFF0000FFFF'
0000000000000000111111111111111100000000000000001111111111111111.
integer(i8p), parameter lib_morton::mask8_56 = Z'FF'
0000000000000000000000000000000000000000000000000000000011111111.
integer(i8p), parameter lib_morton::mask8_16 = Z'FF0000FF0000FF'
0000000011111111000000000000000011111111000000000000000011111111.
integer(i8p), parameter lib_morton::mask8_8 = Z'FF00FF00FF00FF'
0000000011111111000000001111111100000000111111110000000011111111.
integer(i8p), parameter lib_morton::mask4_60 = Z'F'
0000000000000000000000000000000000000000000000000000000000001111.
integer(i8p), parameter lib_morton::mask4_8 = Z'F00F00F00F00F00F'
integer(i8p), parameter lib_morton::mask4_4 = Z'F0F0F0F0F0F0F0F'
0000111100001111000011110000111100001111000011110000111100001111.
integer(i8p), parameter lib_morton::mask2_62 = Z'3'
0000000000000000000000000000000000000000000000000000000000000011.
integer(i8p), parameter lib_morton::mask2_4 = z'30C30C30C30C30C3'
0011000011000011000011000011000011000011000011000011000011000011.
integer(i8p), parameter lib_morton::mask2_2 = Z'3333333333333333'
0011001100110011001100110011001100110011001100110011001100110011.
integer(i8p), parameter lib_morton::mask1_2 = Z'9249249249249249'
integer(i8p), parameter lib_morton::mask1_1 = Z'5555555555555555'
0101010101010101010101010101010101010101010101010101010101010101.
integer(i8p), dimension(1:5),
parameter lib_morton::signif = (/mask2_62,mask4_60,mask8_56,mask16_48,mask32_32/)
Binary mask for selecting significant bits.
integer(i8p), dimension(1:6,
1:2), parameter lib_morton::mask = reshape((/mask1_1,mask2_2,mask4_4,mask8_8, mask16_16,mask32_32, mask1_2,mask2_4,mask4_8,mask8_16,mask16_32,mask32_32/), (/6,2/))
Binary mask for perfoming significant bits shifting.
integer(i1p), dimension(1:6,
1:2), parameter lib_morton::shft = reshape((/1_I1P,2_I1P,4_I1P,8_I1P, 16_I1P,32_I1P, 2_I1P,4_I1P,8_I1P,16_I1P,32_I1P,64_I1P/), (/6,2/))
Shift number array.
real(r4p), parameter lib_morton::log10_2_inv = 1._R4P/log10(2._R4P)
Real parameter for computing the number of shifts (Ns).
Detailed Description
Variable Documentation
integer(i8p), parameter lib_morton::mask32_32 = Z'FFFFFFFF' private
0000000000000000000000000000000011111111111111111111111111111111.
Definition at line 50 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask16_48 = Z'FFFF' private
0000000000000000000000000000000000000000000000001111111111111111.
Definition at line 51 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask16_32 = Z'FFFF00000000FFFF' private
Definition at line 52 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask16_16 = Z'FFFF0000FFFF' private
0000000000000000111111111111111100000000000000001111111111111111.
Definition at line 53 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask8_56 = Z'FF' private
0000000000000000000000000000000000000000000000000000000011111111.
Definition at line 54 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask8_16 = Z'FF0000FF0000FF' private
0000000011111111000000000000000011111111000000000000000011111111.
Definition at line 55 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask8_8 = Z'FF00FF00FF00FF' private
0000000011111111000000001111111100000000111111110000000011111111.
Definition at line 56 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask4_60 = Z'F' private
0000000000000000000000000000000000000000000000000000000000001111.
Definition at line 57 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask4_8 = Z'F00F00F00F00F00F' private
Definition at line 58 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask4_4 = Z'F0F0F0F0F0F0F0F' private
0000111100001111000011110000111100001111000011110000111100001111.
Definition at line 59 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask2_62 = Z'3' private
0000000000000000000000000000000000000000000000000000000000000011.
Definition at line 60 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask2_4 = z'30C30C30C30C30C3' private
0011000011000011000011000011000011000011000011000011000011000011.
Definition at line 61 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask2_2 = Z'3333333333333333' private
0011001100110011001100110011001100110011001100110011001100110011.
Definition at line 62 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask1_2 = Z'9249249249249249' private
Definition at line 63 of file Lib_Morton.f90.
integer(i8p), parameter lib_morton::mask1_1 = Z'5555555555555555' private
0101010101010101010101010101010101010101010101010101010101010101.
Definition at line 64 of file Lib_Morton.f90.
integer(i8p), dimension(1:5), parameter lib_morton::signif = (/mask2_62,mask4_60,mask8_56,mask16_48,mask32_32/) private
Binary mask for selecting significant bits.
Definition at line 66 of file Lib_Morton.f90.
integer(i8p), dimension(1:6,1:2), parameter lib_morton::mask = reshape((/mask1_1,mask2_2,mask4_4,mask8_8, mask16_16,mask32_32, mask1_2,mask2_4,mask4_8,mask8_16,mask16_32,mask32_32/), (/6,2/)) private
Binary mask for perfoming significant bits shifting.
Definition at line 68 of file Lib_Morton.f90.
Referenced by cspline(), lib_parallel::psendrecv(), and set_in1().
integer(i1p), dimension(1:6,1:2), parameter lib_morton::shft = reshape((/1_I1P,2_I1P,4_I1P,8_I1P, 16_I1P,32_I1P, 2_I1P,4_I1P,8_I1P,16_I1P,32_I1P,64_I1P/), (/6,2/)) private
Shift number array.
Definition at line 72 of file Lib_Morton.f90.
real(r4p), parameter lib_morton::log10_2_inv = 1._R4P/log10(2._R4P) private
Real parameter for computing the number of shifts (Ns).
The number of shifts is computed by where 'b' is the significant bits. As a consequence , therefore it is convenient to store the value of .
Definition at line 77 of file Lib_Morton.f90.