OFF: Lib_Riemann Module Reference
Lib_Riemann Module Reference
This module contains procedures for computing the solution of a Riemann Problem.
Public Member Functions
logical function, public chk_smooth_z (p1, r1, u1, g1, p4, r4, u4, g4)
Function for evaluating the smoothness of an interface using a Riemann solver-like algorithm.
logical function, public chk_smooth_limiter (pm1, pp1, rm1, rp1, um1, up1, gm1, gp1)
Function for evaluating the smoothness of a cell using a discontinuity detector based on slope limiter function.
logical function, public chk_smooth_liu (pm1, rm1, um1, gm1, cpm1, cvm1, p1, r1, u1m, u1p, g1, cp1, cv1, pp1, rp1, up1, gp1, cpp1, cvp1)
Function for evaluating the smoothness of a cell using the Liu's entropy conditions.
elemental subroutine, public Riem_Solver_LaxFriedrichs (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on (local) Lax-Friedrichs (known also as Rusanov) algorithm.
subroutine, public Riem_Solver_PVL (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Primitive Variables Linearization algorithm.
subroutine, public Riem_Solver_TR (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Two Rarefactions algorithm.
elemental subroutine, public Riem_Solver_TS (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Two Shocks algorithm.
subroutine, public Riem_Solver_APRS (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Adaptive (non iterative) PVL-TR-TS algorithm.
subroutine, public Riem_Solver_ALFR (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Adaptive (non iterative) LF-TR algorithm.
elemental subroutine, public Riem_Solver_HLLC (p1, r1, u1, g1,
Approximate Riemann solver based on HLLC algorithm.
elemental subroutine, public Riem_Solver_Roe (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, F_r, F_u, F_E)
Approximate Riemann solver based on Roe linearization.
subroutine, public Riem_Solver_Exact_U (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Exact Riemann solver based on iterative solution of u-function.
Private Member Functions
elemental subroutine fluxes (p, r, u, g, F_r, F_u, F_E)
elemental subroutine Rarefaction (sgn, g, delta, eta, u0, p0, a0, ux, rx, px, ax, s0, sx)
elemental subroutine Shock (sgn, g, gm1, gp1, u0, p0, a0, ux, rx, px, ax, ss)
elemental subroutine WavesSpeed14u (u1, a1, g1, u4, a4, g4, u23, S1, S4)
elemental subroutine WavesSpeed14up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, S1, S4)
elemental subroutine WavesSpeed1234u (u1, a1, g1, u4, a4, g4, u23, S1, S2, S3, S4)
elemental subroutine WavesSpeed1234up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, S1, S2, S3, S4)
elemental subroutine InterStates23u (p1, u1, a1, g1, gm1_1, gp1_1, delta1, eta1, p4, u4, a4, g4, gm1_4, gp1_4, delta4, eta4, u23, r2, p2, a2, r3, p3, a3, S1, S2, S3, S4)
elemental subroutine InterStates23up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
subroutine sampling_fluxes (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, p23, r2, r3, S, S1, S2, S3, S4, F_r, F_u, F_E)
elemental subroutine sampling_fluxes_old (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, p23, r2, r3, S, S1, S2, S3, S4, F_r, F_u, F_E)
elemental subroutine sampling_fluxes_vacuum (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, S1, S2, S3, S4, F_r, F_u, F_E)
elemental function VanLeer_limiter (Sm1, Sp1)
elemental function VanAlbada_limiter (Sm1, Sp1)
elemental function Harten_limiter (Sm1, Sp1)
elemental subroutine PVL_u23 (p1, r1, u1, a1, p4, r4, u4, a4, u23)
elemental subroutine PVL_p23 (p1, r1, u1, a1, p4, r4, u4, a4, p23)
elemental subroutine PVL_up23 (p1, r1, u1, a1, p4, r4, u4, a4, u23, p23)
elemental subroutine PVL_WavesSpeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine PVL_WavesSpeed1234 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S2, S3, S4)
elemental subroutine PVL_States (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine CVL_u23 (p1, r1, u1, a1, p4, r4, u4, a4, u23)
elemental subroutine CVL_up23 (p1, r1, u1, a1, p4, r4, u4, a4, u23, p23)
elemental subroutine CVL_WavesSpeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine CVL_States (p1, r1, u1, g1, p4, r4, u4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine TR_u23 (p1, u1, a1, g1, p4, u4, a4, g4, u23)
elemental subroutine TR_up23 (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23)
elemental subroutine TR_WavesSpeed14 (p1, u1, a1, g1, p4, u4, a4, g4, S, S1, S4)
elemental subroutine TR_States (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine TS_up23 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23)
elemental subroutine TS_WavesSpeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine TS_States (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine Roe_up23 (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, u23, p23)
elemental subroutine Roe_WavesSpeed14 (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, S, S1, S4)
elemental subroutine Roe_ua (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, u_roe, a_roe)
elemental subroutine Roe_State (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, r_roe, u_roe, a_roe, H_roe)
elemental subroutine BCLC_WavesSpeed14 (p1, r1, u1, a1, g1, cp1, cv1, p4, r4, u4, a4, g4, cp4, cv4, S, S1, S4)
elemental subroutine Z_WavesSpeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
Private Attributes
real(R_P), parameter toll = 1.D-10
Detailed Description
This module contains procedures for computing the solution of a Riemann Problem.
This is a library module.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 8 of file Lib_Riemann.f90.
Member Function/Subroutine Documentation
elemental subroutine Lib_Riemann::fluxes (real(R_P), intent(in) p, real(R_P), intent(in) r, real(R_P), intent(in) u, real(R_P), intent(in) g, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E) [private]
Definition at line 39 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Rarefaction (real(R_P), intent(in) sgn, real(R_P), intent(in) g, real(R_P), intent(in) delta, real(R_P), intent(in) eta, real(R_P), intent(in) u0, real(R_P), intent(in) p0, real(R_P), intent(in) a0, real(R_P), intent(in) ux, real(R_P), intent(out) rx, real(R_P), intent(out) px, real(R_P), intent(out) ax, real(R_P), intent(out) s0, real(R_P), intent(out) sx) [private]
Definition at line 63 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Shock (real(R_P), intent(in) sgn, real(R_P), intent(in) g, real(R_P), intent(in) gm1, real(R_P), intent(in) gp1, real(R_P), intent(in) u0, real(R_P), intent(in) p0, real(R_P), intent(in) a0, real(R_P), intent(in) ux, real(R_P), intent(out) rx, real(R_P), intent(out) px, real(R_P), intent(out) ax, real(R_P), intent(out) ss) [private]
Definition at line 92 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::WavesSpeed14u (real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 125 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::WavesSpeed14up (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(in) p23, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 167 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::WavesSpeed1234u (real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 209 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::WavesSpeed1234up (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(in) p23, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 255 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::InterStates23u (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) gm1_1, real(R_P), intent(in) gp1_1, real(R_P), intent(in) delta1, real(R_P), intent(in) eta1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) gm1_4, real(R_P), intent(in) gp1_4, real(R_P), intent(in) delta4, real(R_P), intent(in) eta4, real(R_P), intent(in) u23, real(R_P), intent(out) r2, real(R_P), intent(out) p2, real(R_P), intent(out) a2, real(R_P), intent(out) r3, real(R_P), intent(out) p3, real(R_P), intent(out) a3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 301 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::InterStates23up (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(in) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 427 of file Lib_Riemann.f90.
subroutine Lib_Riemann::sampling_fluxes (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) delta1, real(R_P), intent(in) eta1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) delta4, real(R_P), intent(in) eta4, real(R_P), intent(in) p23, real(R_P), intent(in) r2, real(R_P), intent(in) r3, real(R_P), intent(in) S, real(R_P), intent(in) S1, real(R_P), intent(in) S2, real(R_P), intent(in) S3, real(R_P), intent(in) S4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E) [private]
Definition at line 492 of file Lib_Riemann.f90.
References fluxes().
elemental subroutine Lib_Riemann::sampling_fluxes_old (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) delta1, real(R_P), intent(in) eta1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) delta4, real(R_P), intent(in) eta4, real(R_P), intent(in) p23, real(R_P), intent(in) r2, real(R_P), intent(in) r3, real(R_P), intent(in) S, real(R_P), intent(in) S1, real(R_P), intent(in) S2, real(R_P), intent(in) S3, real(R_P), intent(in) S4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E) [private]
Definition at line 554 of file Lib_Riemann.f90.
References fluxes().
elemental subroutine Lib_Riemann::sampling_fluxes_vacuum (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) delta1, real(R_P), intent(in) eta1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) delta4, real(R_P), intent(in) eta4, real(R_P), intent(in) S1, real(R_P), intent(in) S2, real(R_P), intent(in) S3, real(R_P), intent(in) S4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E) [private]
Definition at line 640 of file Lib_Riemann.f90.
References fluxes().
elemental function Lib_Riemann::VanLeer_limiter (real(R_P), intent(in) Sm1, real(R_P), intent(in) Sp1) [private]
Definition at line 698 of file Lib_Riemann.f90.
elemental function Lib_Riemann::VanAlbada_limiter (real(R_P), intent(in) Sm1, real(R_P), intent(in) Sp1) [private]
Definition at line 721 of file Lib_Riemann.f90.
elemental function Lib_Riemann::Harten_limiter (real(R_P), intent(in) Sm1, real(R_P), intent(in) Sp1) [private]
Definition at line 744 of file Lib_Riemann.f90.
logical function, public Lib_Riemann::chk_smooth_z (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4)
Function for evaluating the smoothness of an interface using a Riemann solver-like algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
Definition at line 769 of file Lib_Riemann.f90.
logical function, public Lib_Riemann::chk_smooth_limiter (real(R_P), intent(in) pm1, real(R_P), intent(in) pp1, real(R_P), intent(in) rm1, real(R_P), intent(in) rp1, real(R_P), intent(in) um1, real(R_P), intent(in) up1, real(R_P), intent(in) gm1, real(R_P), intent(in) gp1)
Function for evaluating the smoothness of a cell using a discontinuity detector based on slope limiter function.
Parameters:
[in] pm1 Upwind difference of pressure.
[in] pp1 Downwind difference of pressure.
[in] rm1 Upwind difference of density.
[in] rp1 Downwind difference of density.
[in] um1 Upwind difference of speed.
[in] up1 Downwind difference of speed.
[in] gm1 Upwind difference of specific heats ratio.
[in] gp1 Downwind difference of specific heats ratio.
Definition at line 809 of file Lib_Riemann.f90.
logical function, public Lib_Riemann::chk_smooth_liu (real(R_P), intent(in) pm1, real(R_P), intent(in) rm1, real(R_P), intent(in) um1, real(R_P), intent(in) gm1, real(R_P), intent(in) cpm1, real(R_P), intent(in) cvm1, real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1m, real(R_P), intent(in) u1p, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) pp1, real(R_P), intent(in) rp1, real(R_P), intent(in) up1, real(R_P), intent(in) gp1, real(R_P), intent(in) cpp1, real(R_P), intent(in) cvp1)
Function for evaluating the smoothness of a cell using the Liu's entropy conditions.
Parameters:
[in] pm1 Pressure of state i-1.
[in] rm1 Density of state i-1.
[in] um1 Velocity of state i-1.
[in] gm1 Specific heats ratio of state i-1.
[in] cpm1 Specific heats cp of state i-1.
[in] cvm1 Specific heats cv of state i-1.
[in] p1 Pressure of state i.
[in] r1 Density of state i.
[in] u1m Velocity of state i at left interface.
[in] u1p Velocity of state i at left interface.
[in] g1 Specific heats ratio of state i.
[in] cp1 Specific heats cp of state i.
[in] cv1 Specific heats cv of state i.
[in] pp1 Pressure of state i+1.
[in] rp1 Density of state i+1.
[in] up1 Velocity of state i+1.
[in] gp1 Specific heats ratio of state i+1.
[in] cpp1 Specific heats cp of state i+1.
[in] cvp1 Specific heats cv of state i+1.
Definition at line 843 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_u23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) u23) [private]
Definition at line 900 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_p23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) p23) [private]
Definition at line 924 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 948 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 976 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_WavesSpeed1234 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1020 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_States (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1062 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::CVL_u23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) u23) [private]
Definition at line 1098 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::CVL_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 1126 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::CVL_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1159 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::CVL_States (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1203 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TR_u23 (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23) [private]
Definition at line 1241 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TR_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 1275 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TR_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1311 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TR_States (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1353 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TS_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 1396 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TS_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1429 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TS_States (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1461 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Roe_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 1509 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Roe_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1552 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Roe_ua (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) u_roe, real(R_P), intent(out) a_roe) [private]
Definition at line 1591 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Roe_State (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) r_roe, real(R_P), intent(out) u_roe, real(R_P), intent(out) a_roe, real(R_P), intent(out) H_roe) [private]
Definition at line 1630 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::BCLC_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1673 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Z_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1713 of file Lib_Riemann.f90.
elemental subroutine, public Lib_Riemann::Riem_Solver_LaxFriedrichs (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on (local) Lax-Friedrichs (known also as Rusanov) algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1758 of file Lib_Riemann.f90.
subroutine, public Lib_Riemann::Riem_Solver_PVL (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Primitive Variables Linearization algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1808 of file Lib_Riemann.f90.
References fluxes().
subroutine, public Lib_Riemann::Riem_Solver_TR (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Two Rarefactions algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1850 of file Lib_Riemann.f90.
elemental subroutine, public Lib_Riemann::Riem_Solver_TS (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Two Shocks algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1892 of file Lib_Riemann.f90.
subroutine, public Lib_Riemann::Riem_Solver_APRS (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Adaptive (non iterative) PVL-TR-TS algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1940 of file Lib_Riemann.f90.
References fluxes().
subroutine, public Lib_Riemann::Riem_Solver_ALFR (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Adaptive (non iterative) LF-TR algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 2003 of file Lib_Riemann.f90.
elemental subroutine, public Lib_Riemann::Riem_Solver_HLLC (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1)
Approximate Riemann solver based on HLLC algorithm.
Note:
Five variants are provided: HLLCb, using BCLC estimation of waves speed, HLLCc using CVL algorithm, HLLCp using PVL algorithm, HLLCt using TR algorithm and HLLCz using Z one.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
Definition at line 2090 of file Lib_Riemann.f90.
elemental subroutine, public Lib_Riemann::Riem_Solver_Roe (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Roe linearization.
Note:
The Harten-Hyman entropy fix is used to avoid shock-expansions (entropy violation).
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] cp1 Specific heats cp of state 1.
[in] cv1 Specific heats cv of state 1.
[in] p4 pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[in] cp4 Specific heats cp of state 4.
[in] cv4 Specific heats cv of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 2179 of file Lib_Riemann.f90.
References fluxes().
subroutine, public Lib_Riemann::Riem_Solver_Exact_U (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Exact Riemann solver based on iterative solution of u-function.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 U speed of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 U speed of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 2279 of file Lib_Riemann.f90.
References fluxes().
Member Data Documentation
real(R_P), parameter Lib_Riemann::toll = 1.D-10 [private]
Definition at line 35 of file Lib_Riemann.f90.
The documentation for this module was generated from the following file:
Lib_Riemann.f90