OFF: Lib_Fluidynamic.f90 File Reference
Lib_Fluidynamic.f90 File Reference
Data Types
module lib_fluidynamic
This module contains the definition of fluid dynamic procedures.
Functions/Subroutines
pure subroutine set_ext_l (gc, ic, N, C)
Subroutine for imposing extrapolation of ghost cells from internal ones (left boundary).
pure subroutine set_ext_r (gc, ic, N, C)
Subroutine for imposing extrapolation of ghost cells from internal ones (right boundary).
pure subroutine set_ref_l (gc, ic, N, NF, C)
Subroutine for imposing reflective boundary conditions (left boundary).
pure subroutine set_ref_r (gc, ic, N, NF, C)
Subroutine for imposing reflective boundary conditions (right boundary).
pure subroutine set_per (gc, ic, N, boundary, C)
Subroutine for imposing periodic boundary conditions.
pure subroutine set_adj (global, block, blockmap, gc, F, C)
Subroutine for imposing adjacent boundary conditions.
pure subroutine set_in1 (global, gc, F, C)
Subroutine for imposing inflow 1 boundary conditions.
pure subroutine rk_stages_sum_backend (s1, Ns, Nc, cp0, cv0, Dt, U, KS, P)
pure subroutine rk_time_integration_backend (Ns, rk_ord, Dt, KS, U, R)
Function/Subroutine Documentation
pure subroutine set_bc::set_ext_l (integer(i1p), intent(in) gc, integer(i_p), intent(in) ic, integer(i_p), intent(in) N, type(type_cell), dimension(1-gc:), intent(inout) C) private
Subroutine for imposing extrapolation of ghost cells from internal ones (left boundary).
Note
For avoiding the creation of temporary arrays (improving the efficiency) the array P is declared as assumed-shape with only the lower bound defined. Its extentions is: P [1-gc:0+gc].
Parameters
[in] gc Number of ghost cells.
[in] ic Number of internal cells used for extrapolation (1 or gc).
[in] n Number of internal cells.
[in,out] c Cells data [1-gc:0+gc].
Definition at line 518 of file Lib_Fluidynamic.f90.
References data_type_bc::bc_adj, data_type_bc::bc_ext, data_type_bc::bc_in1, data_type_bc::bc_per, data_type_bc::bc_ref, lib_parallel::blockmap, lib_vtk_io::f, set_adj(), set_ext_r(), set_in1(), set_per(), and set_ref_r().
Referenced by lib_fluidynamic::set_bc().
pure subroutine set_bc::set_ext_r (integer(i1p), intent(in) gc, integer(i_p), intent(in) ic, integer(i_p), intent(in) N, type(type_cell), dimension(n-gc:), intent(inout) C) private
Subroutine for imposing extrapolation of ghost cells from internal ones (right boundary).
Note
For avoiding the creation of temporary arrays (improving the efficiency) the array P is declared as assumed-shape with only the lower bound defined. Its extentions is: P [N-gc:N+gc].
Parameters
[in] gc Number of ghost cells.
[in] ic Number of internal cells used for extrapolation (1 or gc).
[in] n Number of internal cells.
[in,out] c Cells data [N-gc:N+gc].
Definition at line 547 of file Lib_Fluidynamic.f90.
Referenced by set_ext_l().
pure subroutine set_bc::set_ref_l (integer(i1p), intent(in) gc, integer(i_p), intent(in) ic, integer(i_p), intent(in) N, type(type_vector), intent(in) NF, type(type_cell), dimension(1-gc:), intent(inout) C) private
Subroutine for imposing reflective boundary conditions (left boundary).
Note
For avoiding the creation of temporary arrays (improving the efficiency) the array P is declared as assumed-shape with only the lower bound defined. Its extentions is: P [1-gc:0+gc].
Parameters
[in] gc Number of ghost cells.
[in] ic Number of internal cells used for extrapolation (1 or gc).
[in] n Number of internal cells.
[in] nf Left face normal.
[in,out] c Cells data [1-gc:0+gc].
Definition at line 576 of file Lib_Fluidynamic.f90.
Referenced by lib_fluidynamic::set_bc().
pure subroutine set_bc::set_ref_r (integer(i1p), intent(in) gc, integer(i_p), intent(in) ic, integer(i_p), intent(in) N, type(type_vector), intent(in) NF, type(type_cell), dimension(n-gc:), intent(inout) C) private
Subroutine for imposing reflective boundary conditions (right boundary).
Note
For avoiding the creation of temporary arrays (improving the efficiency) the array P is declared as assumed-shape with only the lower bound defined. Its extentions is: P [N-gc:N+gc].
Parameters
[in] gc Number of ghost cells.
[in] ic Number of internal cells used for extrapolation (1 or gc).
[in] n Number of internal cells.
[in] nf Right face normal.
[in,out] c Cells data [N-gc:N+gc].
Definition at line 617 of file Lib_Fluidynamic.f90.
Referenced by set_ext_l().
pure subroutine set_bc::set_per (integer(i1p), intent(in) gc, integer(i_p), intent(in) ic, integer(i_p), intent(in) N, character(1), intent(in) boundary, type(type_cell), dimension(1-gc:), intent(inout) C) private
Subroutine for imposing periodic boundary conditions.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the array P is declared as assumed-shape with only the lower bound defined. Its extentions is: P [1-gc:N+gc].
Parameters
[in] gc Number of ghost cells.
[in] ic Number of internal cells used for extrapolation (1 or gc).
[in] n Number of internal cells.
[in] boundary Boundary left ('l') or right ('r').
[in,out] c Cells data [1-gc:N+gc].
Definition at line 658 of file Lib_Fluidynamic.f90.
Referenced by set_ext_l().
pure subroutine set_bc::set_adj (type(type_global), intent(in) global, type(type_sblock), dimension(1:), intent(in) block, integer(i_p), dimension(1:), intent(in) blockmap, integer(i1p), intent(in) gc, type(type_face), dimension(1-gc:), intent(in) F, type(type_cell), dimension(1-gc:), intent(inout) C) private
Subroutine for imposing adjacent boundary conditions.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the arrays bc and P are declared as assumed-shape with only the lower bound defined. Their extentions are: bc [1-gc:0], P [1-gc:0].
When this subroutine is called for a 'right' (Ni,Nj,Nk) boundary the section of arrays BC and P must be properly remapped: in the section [1-gc:0] must be passed the actual section [N:N+gc-1] for BC and [N+1:N+gc] for P.
Parameters
[in] global Global-level data.
[in] block Block-level data.
[in] blockmap Local/global blocks map [1:Nb].
[in] gc Number of ghost cells.
[in] f Faces data [1-gc:0].
[in,out] c Cells data [1-gc:0].
Definition at line 705 of file Lib_Fluidynamic.f90.
Referenced by set_ext_l().
pure subroutine set_bc::set_in1 (type(type_global), intent(in) global, integer(i1p), intent(in) gc, type(type_face), dimension(1-gc:), intent(in) F, type(type_cell), dimension(1-gc:), intent(inout) C) private
Subroutine for imposing inflow 1 boundary conditions.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the arrays bc and P are declared as assumed-shape with only the lower bound defined. Their extentions are: bc [1-gc:0], P [1-gc:0].
When this subroutine is called for a 'right' (Ni,Nj,Nk) boundary the section of arrays BC and P must be properly remapped: in the section [1-gc:0] must be passed the actual section [N:N+gc-1] for BC and [N+1:N+gc] for P.
Parameters
[in] global Global-level data.
[in] gc Number of ghost cells.
[in] f Faces data [1-gc:0].
[in,out] c Cells data [1-gc:0].
Definition at line 736 of file Lib_Fluidynamic.f90.
References data_type_sl_list::type_sl_link::array(), lib_parallel::blockmap, lib_vtk_io::f, lib_morton::mask, and lib_parallel::procmap.
Referenced by set_ext_l().
pure subroutine rk_stages_sum::rk_stages_sum_backend (integer(i1p), intent(in) s1, integer(i_p), intent(in) Ns, integer(i_p), intent(in) Nc, real(r_p), dimension(1:), intent(in) cp0, real(r_p), dimension(1:), intent(in) cv0, real(r_p), intent(in) Dt, type(type_conservative), intent(in) U, type(type_conservative), dimension(1:), intent(in) KS, type(type_primitive), intent(inout) P) private
Parameters
[in] s1 Current Runge-Kutta stage.
[in] ns Number of species.
[in] nc Number of conservative variables.
[in] cp0 Specific heat at constant p of initial species.
[in] cv0 Specific heat at constant v of initial species.
[in] dt Current time step.
[in] u Conservative variables.
[in] ks Runge-Kutta stages.
[in,out] p Primitive variables.
Definition at line 851 of file Lib_Fluidynamic.f90.
References lib_thermodynamic_laws_ideal::p().
pure subroutine rk_time_integration::rk_time_integration_backend (integer(i_p), intent(in) Ns, integer(i1p), intent(in) rk_ord, real(r_p), intent(in) Dt, type(type_conservative), dimension(1:), intent(in) KS, type(type_conservative), intent(inout) U, real(r_p), dimension(1:), intent(out) R) private
Parameters
[in] ns Number of species.
[in] rk_ord Number of Runge-Kutta stages.
[in] dt Current time step.
[in] ks Runge-Kutta stages.
[in,out] u Conservative variables.
[out] r Residuals of conservative variables.
Definition at line 919 of file Lib_Fluidynamic.f90.
References lib_thermodynamic_laws_ideal::r().