OFF: Data_Type_SBlock
Data_Type_SBlock
Derived Types
Data Types
type data_type_sblock::type_sblock
Derived type containing structured block-level data.
Detailed Description
Data Type Documentation
type data_type_sblock::type_sblock
Derived type containing structured block-level data.
Structured block-level type contains data (mesh, boundary conditions and fluid dynamic data) of structured (implicit connectivity) numerical grid.
Definition at line 41 of file Data_Type_SBlock.f90.
Public Member Functions
procedure, non_overridable alloc => alloc_block
procedure, non_overridable free => free_block
procedure, non_overridable save_mesh => save_bmesh
procedure, non_overridable load_mesh_dims => load_bmesh_dims
procedure, non_overridable load_mesh => load_bmesh
procedure, non_overridable print_info_mesh => print_info_bmesh
procedure, non_overridable save_bc => save_bbc
procedure, non_overridable load_bc => load_bbc
procedure, non_overridable save_fluid => save_bfluid
procedure, non_overridable load_fluid => load_bfluid
procedure, non_overridable print_info_fluid => print_info_bfluid
procedure, non_overridable metrics
procedure, non_overridable metrics_correction
procedure, non_overridable node2center
Public Attributes
type(type_global), pointer global
Pointer to global-level data.
integer(i1p), dimension(1:6) gc = [1_I1P,1_I1P, 1_I1P,1_I1P, 1_I1P,1_I1P ]
Number of ghost cells for the 6 faces of the block.
integer(i4p) ni = 0_I4P
Number of cells in i direction.
integer(i4p) nj = 0_I4P
Number of cells in j direction.
integer(i4p) nk = 0_I4P
Number of cells in k direction.
type(type_vector), dimension(:,:,:),
allocatable node
Nodes coord.
type(type_face), dimension(:,:,:),
allocatable fi
Faces i data [0-gc(1):Ni+gc(2),1-gc(3):Nj+gc(4),1-gc(5):Nk+gc(6)].
type(type_face), dimension(:,:,:),
allocatable fj
Faces j data [1-gc(1):Ni+gc(2),0-gc(3):Nj+gc(4),1-gc(5):Nk+gc(6)].
type(type_face), dimension(:,:,:),
allocatable fk
Faces k data [1-gc(1):Ni+gc(2),1-gc(3):Nj+gc(4),0-gc(5):Nk+gc(6)].
type(type_cell), dimension(:,:,:),
allocatable c
Cells data [1-gc(1):Ni+gc(2),1-gc(3):Nj+gc(4),1-gc(5):Nk+gc(6)].
Member Function/Subroutine Documentation
procedure, non_overridable data_type_sblock::type_sblock::alloc ()
Definition at line 57 of file Data_Type_SBlock.f90.
References data_type_sblock::load_bmesh(), and load_mesh().
procedure, non_overridable data_type_sblock::type_sblock::free ()
Definition at line 58 of file Data_Type_SBlock.f90.
References data_type_sblock::print_info_bmesh(), and print_info_mesh().
procedure, non_overridable data_type_sblock::type_sblock::save_mesh ()
Definition at line 59 of file Data_Type_SBlock.f90.
References data_type_sblock::save_bbc(), and save_bc().
procedure, non_overridable data_type_sblock::type_sblock::load_mesh_dims ()
Definition at line 60 of file Data_Type_SBlock.f90.
References data_type_sblock::load_bbc(), and load_bc().
procedure, non_overridable data_type_sblock::type_sblock::load_mesh ()
Definition at line 61 of file Data_Type_SBlock.f90.
References data_type_sblock::save_bfluid(), and save_fluid().
Referenced by alloc().
procedure, non_overridable data_type_sblock::type_sblock::print_info_mesh ()
Definition at line 62 of file Data_Type_SBlock.f90.
References data_type_sblock::load_bfluid(), and load_fluid().
Referenced by free().
procedure, non_overridable data_type_sblock::type_sblock::save_bc ()
Definition at line 63 of file Data_Type_SBlock.f90.
References data_type_sblock::print_info_bfluid(), and print_info_fluid().
Referenced by save_mesh().
procedure, non_overridable data_type_sblock::type_sblock::load_bc ()
Definition at line 64 of file Data_Type_SBlock.f90.
References metrics().
Referenced by load_mesh_dims().
procedure, non_overridable data_type_sblock::type_sblock::save_fluid ()
Definition at line 65 of file Data_Type_SBlock.f90.
References metrics_correction().
Referenced by load_mesh().
procedure, non_overridable data_type_sblock::type_sblock::load_fluid ()
Definition at line 66 of file Data_Type_SBlock.f90.
References node2center().
Referenced by print_info_mesh().
procedure, non_overridable data_type_sblock::type_sblock::print_info_fluid ()
Definition at line 67 of file Data_Type_SBlock.f90.
Referenced by save_bc().
procedure, non_overridable data_type_sblock::type_sblock::metrics ()
Definition at line 68 of file Data_Type_SBlock.f90.
Referenced by load_bc().
procedure, non_overridable data_type_sblock::type_sblock::metrics_correction ()
Definition at line 69 of file Data_Type_SBlock.f90.
Referenced by save_fluid().
procedure, non_overridable data_type_sblock::type_sblock::node2center ()
Definition at line 70 of file Data_Type_SBlock.f90.
Referenced by load_fluid().
Member Data Documentation
type(type_global), pointer data_type_sblock::type_sblock::global
Pointer to global-level data.
Definition at line 42 of file Data_Type_SBlock.f90.
integer(i1p), dimension(1:6) data_type_sblock::type_sblock::gc = [1_I1P,1_I1P, 1_I1P,1_I1P, 1_I1P,1_I1P ]
Number of ghost cells for the 6 faces of the block.
Definition at line 43 of file Data_Type_SBlock.f90.
integer(i4p) data_type_sblock::type_sblock::ni = 0_I4P
Number of cells in i direction.
Definition at line 48 of file Data_Type_SBlock.f90.
integer(i4p) data_type_sblock::type_sblock::nj = 0_I4P
Number of cells in j direction.
Definition at line 49 of file Data_Type_SBlock.f90.
integer(i4p) data_type_sblock::type_sblock::nk = 0_I4P
Number of cells in k direction.
Definition at line 50 of file Data_Type_SBlock.f90.
type(type_vector), dimension(:,:,:), allocatable data_type_sblock::type_sblock::node
Nodes coord.
[0-gc(1):Ni+gc(2),0-gc(3):Nj+gc(4),0-gc(5):Nk+gc(6)].
Definition at line 51 of file Data_Type_SBlock.f90.
type(type_face), dimension(:,:,:), allocatable data_type_sblock::type_sblock::fi
Faces i data [0-gc(1):Ni+gc(2),1-gc(3):Nj+gc(4),1-gc(5):Nk+gc(6)].
Definition at line 52 of file Data_Type_SBlock.f90.
type(type_face), dimension(:,:,:), allocatable data_type_sblock::type_sblock::fj
Faces j data [1-gc(1):Ni+gc(2),0-gc(3):Nj+gc(4),1-gc(5):Nk+gc(6)].
Definition at line 53 of file Data_Type_SBlock.f90.
type(type_face), dimension(:,:,:), allocatable data_type_sblock::type_sblock::fk
Faces k data [1-gc(1):Ni+gc(2),1-gc(3):Nj+gc(4),0-gc(5):Nk+gc(6)].
Definition at line 54 of file Data_Type_SBlock.f90.
type(type_cell), dimension(:,:,:), allocatable data_type_sblock::type_sblock::c
Cells data [1-gc(1):Ni+gc(2),1-gc(3):Nj+gc(4),1-gc(5):Nk+gc(6)].
Definition at line 55 of file Data_Type_SBlock.f90.