OFF: Lib_Math
Lib_Math
Private Procedures
pure subroutine lib_math::isort_r16 (array)
Subroutine for computing prime factors of input integer number (I8P).
pure subroutine lib_math::isort_r8 (array)
Subroutine for performing InsertionSort with ascending order (R8P).
pure subroutine lib_math::isort_r4 (array)
Subroutine for performing InsertionSort with ascending order (R4P).
pure subroutine lib_math::isort_i8 (array)
Subroutine for performing InsertionSort with ascending order (I8P).
pure subroutine lib_math::isort_i4 (array)
Subroutine for performing InsertionSort with ascending order (I4P).
pure subroutine lib_math::isort_i2 (array)
Subroutine for performing InsertionSort with ascending order (I2P).
pure subroutine lib_math::isort_i1 (array)
Subroutine for performing InsertionSort with ascending order (I1P).
subroutine lib_math::qsort_r16 (array)
Subroutine for performing QuickSort with ascending order (R16P).
subroutine lib_math::qsort_r8 (array)
Subroutine for performing QuickSort with ascending order (R8P).
subroutine lib_math::qsort_r4 (array)
Subroutine for performing QuickSort with ascending order (R4P).
subroutine lib_math::qsort_i8 (array)
Subroutine for performing QuickSort with ascending order (I8P).
subroutine lib_math::qsort_i4 (array)
Subroutine for performing QuickSort with ascending order (I4P).
subroutine lib_math::qsort_i2 (array)
Subroutine for performing QuickSort with ascending order (I2P).
subroutine lib_math::qsort_i1 (array)
Subroutine for performing QuickSort with ascending order (I1P).
pure function lib_math::spline3_r16 (bc1, bcn, x, v, xi)
Function for computing cubic spline interpolation of an array of values (R16P).
pure function lib_math::spline3_r8 (bc1, bcn, x, v, xi)
Function for computing cubic spline interpolation of an array of values (R8P).
pure function lib_math::spline3_r4 (bc1, bcn, x, v, xi)
Function for computing cubic spline interpolation of an array of values (R4P).
Detailed Description
Function/Subroutine Documentation
pure subroutine lib_math::isort_r16 (real(r16p), dimension(1:), intent(inout) array) private
Subroutine for computing prime factors of input integer number (I8P).
The results is an array of integers containing the prime factors list. Subroutine for computing prime factors of input integer number (I4P). The results is an array of integers containing the prime factors list. Subroutine for computing prime factors of input integer number (I2P). The results is an array of integers containing the prime factors list. Subroutine for computing prime factors of input integer number (I1P). The results is an array of integers containing the prime factors list. Subroutine for performing InsertionSort with ascending order (R16P).
Parameters
[in,out] array Array to be sorted.
Definition at line 400 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array().
Referenced by lib_math::qsort_r16().
pure subroutine lib_math::isort_r8 (real(r8p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (R8P).
Parameters
[in,out] array Array to be sorted.
Definition at line 423 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array().
pure subroutine lib_math::isort_r4 (real(r4p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (R4P).
Parameters
[in,out] array Array to be sorted.
Definition at line 446 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array().
pure subroutine lib_math::isort_i8 (integer(i8p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (I8P).
Parameters
[in,out] array Array to be sorted.
Definition at line 469 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array().
pure subroutine lib_math::isort_i4 (integer(i4p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (I4P).
Parameters
[in,out] array Array to be sorted.
Definition at line 492 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array().
pure subroutine lib_math::isort_i2 (integer(i2p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (I2P).
Parameters
[in,out] array Array to be sorted.
Definition at line 515 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array().
pure subroutine lib_math::isort_i1 (integer(i1p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (I1P).
Parameters
[in,out] array Array to be sorted.
Definition at line 538 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array().
subroutine lib_math::qsort_r16 (real(r16p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (R16P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 563 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), lib_math::isort_r16(), and subsor().
subroutine lib_math::qsort_r8 (real(r8p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (R8P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 636 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), lib_math::isort::isort_r8(), and subsor().
subroutine lib_math::qsort_r4 (real(r4p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (R4P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 709 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), lib_math::isort::isort_r4(), and subsor().
subroutine lib_math::qsort_i8 (integer(i8p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (I8P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 782 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), lib_math::isort::isort_i8(), and subsor().
subroutine lib_math::qsort_i4 (integer(i4p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (I4P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 855 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), lib_math::isort::isort_i4(), and subsor().
subroutine lib_math::qsort_i2 (integer(i2p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (I2P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 928 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), lib_math::isort::isort_i2(), and subsor().
subroutine lib_math::qsort_i1 (integer(i1p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (I1P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 1001 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), lib_math::isort::isort_i1(), and subsor().
pure function lib_math::spline3_r16 (real(r16p), intent(in), optional bc1, real(r16p), intent(in), optional bcn, real(r16p), dimension(1:), intent(in) x, real(r16p), dimension(1:), intent(in) v, real(r16p), dimension(1:), intent(in) xi) private
Function for computing cubic spline interpolation of an array of values (R16P).
Parameters
[in] bc1 Boundary conditions of second derivative at first node.
[in] bcn Boundary conditions of second derivative at last node.
[in] x Independent variable abscissa of original data.
[in] v Dependent variable (to be interpolated) of original data.
[in] xi Independent variable abscissa of interpolating points.
Definition at line 1074 of file Lib_Math.f90.
References compute_cd2(), and cspline().
pure function lib_math::spline3_r8 (real(r8p), intent(in), optional bc1, real(r8p), intent(in), optional bcn, real(r8p), dimension(1:), intent(in) x, real(r8p), dimension(1:), intent(in) v, real(r8p), dimension(1:), intent(in) xi) private
Function for computing cubic spline interpolation of an array of values (R8P).
Parameters
[in] bc1 Boundary conditions of second derivative at first node.
[in] bcn Boundary conditions of second derivative at last node.
[in] x Independent variable abscissa of original data.
[in] v Dependent variable (to be interpolated) of original data.
[in] xi Independent variable abscissa of interpolating points.
Definition at line 1164 of file Lib_Math.f90.
References compute_cd2(), cspline(), and lib_thermodynamic_laws_ideal::p().
pure function lib_math::spline3_r4 (real(r4p), intent(in), optional bc1, real(r4p), intent(in), optional bcn, real(r4p), dimension(1:), intent(in) x, real(r4p), dimension(1:), intent(in) v, real(r4p), dimension(1:), intent(in) xi) private
Function for computing cubic spline interpolation of an array of values (R4P).
Parameters
[in] bc1 Boundary conditions of second derivative at first node.
[in] bcn Boundary conditions of second derivative at last node.
[in] x Independent variable abscissa of original data.
[in] v Dependent variable (to be interpolated) of original data.
[in] xi Independent variable abscissa of interpolating points.
Definition at line 1254 of file Lib_Math.f90.
References compute_cd2(), cspline(), and lib_thermodynamic_laws_ideal::p().