OFF: Data_Type_HashTCell
Data_Type_HashTCell
Derived Types
Data Types
type data_type_hashtcell::type_sll
Derived type containing single linked list data of cell one.
type data_type_hashtcell::type_hashtcell
Derived type containing the hash table of cells data.
Detailed Description
Data Type Documentation
type data_type_hashtcell::type_sll
Derived type containing single linked list data of cell one.
The Single Linked List data structure is used to resolve collisions into the hash table of the cells data.
Definition at line 40 of file Data_Type_HashTCell.f90.
Public Member Functions
procedure, non_overridable put =>put_sll
procedure, non_overridable get =>get_sll
procedure, non_overridable free => free_sll
Public Attributes
type(type_sll), pointer next => NULL()
Pointer to the next link of the list.
type(type_hashid), allocatable id
ID (unique) of the current link node.
type(type_cell), allocatable d
Link data.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_hashtcell::type_sll::put ()
Definition at line 45 of file Data_Type_HashTCell.f90.
Referenced by data_type_sl_list::type_sl_link::gett(), and data_type_sl_list::type_sl_list::gett().
procedure, non_overridable data_type_hashtcell::type_sll::get ()
Definition at line 46 of file Data_Type_HashTCell.f90.
Referenced by data_type_sl_list::type_sl_list::homogeneous(), and data_type_sl_list::type_sl_link::link().
procedure, non_overridable data_type_hashtcell::type_sll::free ()
Definition at line 47 of file Data_Type_HashTCell.f90.
Member Data Documentation
type(type_sll), pointer data_type_hashtcell::type_sll::next => NULL()
Pointer to the next link of the list.
Definition at line 41 of file Data_Type_HashTCell.f90.
type(type_hashid), allocatable data_type_hashtcell::type_sll::id
ID (unique) of the current link node.
Definition at line 42 of file Data_Type_HashTCell.f90.
type(type_cell), allocatable data_type_hashtcell::type_sll::d
Link data.
Definition at line 43 of file Data_Type_HashTCell.f90.
type data_type_hashtcell::type_hashtcell
Derived type containing the hash table of cells data.
The the collisions of different (unique) IDs into the same hash buckets are resolved by the "chaining" technique by means of a single linked list data structure.
Definition at line 53 of file Data_Type_HashTCell.f90.
Public Member Functions
procedure, non_overridable init => init_hasht
procedure, non_overridable put =>put_hasht
procedure, non_overridable get =>get_hasht
procedure, non_overridable free => free_hasht
Public Attributes
type(type_sll), dimension(:),
allocatable ht
Hash table.
integer(i4p) leng = 0_I4P
Lenght of the hash table.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_hashtcell::type_hashtcell::init ()
Definition at line 57 of file Data_Type_HashTCell.f90.
procedure, non_overridable data_type_hashtcell::type_hashtcell::put ()
Definition at line 58 of file Data_Type_HashTCell.f90.
procedure, non_overridable data_type_hashtcell::type_hashtcell::get ()
Definition at line 59 of file Data_Type_HashTCell.f90.
procedure, non_overridable data_type_hashtcell::type_hashtcell::free ()
Definition at line 60 of file Data_Type_HashTCell.f90.
Member Data Documentation
type(type_sll), dimension(:), allocatable data_type_hashtcell::type_hashtcell::ht
Hash table.
Definition at line 54 of file Data_Type_HashTCell.f90.
integer(i4p) data_type_hashtcell::type_hashtcell::leng = 0_I4P
Lenght of the hash table.
Definition at line 55 of file Data_Type_HashTCell.f90.