OFF: Lib_IO_Misc
Lib_IO_Misc
Public Procedures
integer function, public lib_io_misc::get_unit (Free_Unit)
The Get_Unit function returns a free logic unit for opening a file.
integer(i4p) function, public lib_io_misc::make_dir (myrank, directory)
Function for creating a directory if it doesn't exist.
integer(i4p) function, public lib_io_misc::remove_file (filename)
Function for removing a file.
integer(i4p) function, public lib_io_misc::copy_file (source_file, target_file)
Function for coping a file.
integer(i4p) function, public lib_io_misc::lc_file (filename)
Function for calculating the number of lines (records) of a sequential file.
character(len=len(filename))
function, public lib_io_misc::basedir (filename)
The basedir function strip last component from file name providing the base directory name.
character(len=len(filename))
function, public lib_io_misc::basename (filename)
The basename function strip directory from file name.
character(len=len(string))
function, public lib_io_misc::upper_case (string)
The Upper_Case function converts the lower case characters of a string to upper case one.
character(len=len(string))
function, public lib_io_misc::lower_case (string)
The Lower_Case function converts the upper case characters of a string to lower case one.
character(len=len(string))
function, public lib_io_misc::string_os_sep (string)
The string_OS_sep function converts directories separators into a string to the correct OS's separators.
subroutine, public lib_io_misc::tokenize (strin, delimiter, Nt, toks)
Subroutine for tokenizing a string in order to parse it.
subroutine, public lib_io_misc::file_not_found (myrank, filename, cpn)
Subroutine for printing to stderr a "file not found error".
Detailed Description
Function/Subroutine Documentation
integer function, public lib_io_misc::get_unit (integer, intent(out), optional Free_Unit)
The Get_Unit function returns a free logic unit for opening a file.
The unit value is returned by the function, and also by the optional argument "Free_Unit". This allows the function to be used directly in an open statement like: open(unit=Get_Unit(myunit),...) ; read(myunit)... If no units are available, -1 is returned.
Parameters
[out] free_unit Free logic unit.
Definition at line 65 of file Lib_IO_Misc.f90.
Referenced by lib_vtk_io::get_unit(), gnu_blk_data(), lib_io_misc::lc_file(), data_type_amrblock::load_basemesh_dims(), data_type_sblock::load_bbc(), data_type_sblock::load_bfluid(), load_blocks(), data_type_sblock::load_bmesh(), data_type_sblock::load_bmesh_dims(), data_type_global::load_gbc_in1(), data_type_global::load_gfluid_0species(), data_type_global::load_gfluid_ns(), data_type_global::load_gfluid_soption(), load_icemcfd(), load_off_option_file(), load_option_file(), lib_io_misc::make_dir(), off(), off_init(), lib_parallel::procmap_load(), lib_parallel::procmap_save(), lib_profiling::profile(), lib_vtk_io::pvtk_ini_xml(), data_type_sblock::save_bbc(), data_type_sblock::save_bfluid(), data_type_sblock::save_bmesh(), tec_init(), lib_vtk_io::vtk_ini(), lib_vtk_io::vtk_ini_xml(), and lib_vtk_io::vtm_ini_xml().
integer(i4p) function, public lib_io_misc::make_dir (integer(i_p), intent(in), optional myrank, character(*), intent(in) directory)
Function for creating a directory if it doesn't exist.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in] myrank Actual rank process necessary for concurrent multi-processes calls.
[in] directory Name of the directory that must be created.
Definition at line 96 of file Lib_IO_Misc.f90.
References lib_io_misc::get_unit(), lib_io_misc::os, and lib_io_misc::remove_file().
Referenced by load_option_file(), and off_init().
integer(i4p) function, public lib_io_misc::remove_file (character(*), intent(in) filename)
Function for removing a file.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in] filename Name of file that must be copied.
Definition at line 130 of file Lib_IO_Misc.f90.
References lib_io_misc::os.
Referenced by lib_io_misc::make_dir(), and off().
integer(i4p) function, public lib_io_misc::copy_file (character(*), intent(in) source_file, character(*), intent(in) target_file)
Function for coping a file.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in] source_file Name of file that must be copied.
[in] target_file Destination path.
Definition at line 157 of file Lib_IO_Misc.f90.
References lib_io_misc::os.
Referenced by off_init().
integer(i4p) function, public lib_io_misc::lc_file (character(*), intent(in) filename)
Function for calculating the number of lines (records) of a sequential file.
Returns
n integer(I4P) variable
Definition at line 191 of file Lib_IO_Misc.f90.
References lib_io_misc::get_unit(), and lib_io_misc::upper_case().
character(len=len(filename)) function, public lib_io_misc::basedir (character(len=*), intent(in) filename)
The basedir function strip last component from file name providing the base directory name.
Returns
basedir character(*) variable
Parameters
[in] filename File name.
Definition at line 232 of file Lib_IO_Misc.f90.
References lib_io_misc::os.
character(len=len(filename)) function, public lib_io_misc::basename (character(len=*), intent(in) filename)
The basename function strip directory from file name.
Returns
basename character(*) variable
Parameters
[in] filename File name.
Definition at line 247 of file Lib_IO_Misc.f90.
References lib_io_misc::os.
Referenced by data_type_global::block_file_name(), data_type_global::block_flip_file_name(), data_type_global::block_step_file_name(), off(), off_init(), and lib_fluidynamic::solve_grl().
character(len=len(string)) function, public lib_io_misc::upper_case (character(len=*), intent(in) string)
The Upper_Case function converts the lower case characters of a string to upper case one.
Returns
Upper_Case character(*) variable
Parameters
[in] string String to be converted.
Definition at line 262 of file Lib_IO_Misc.f90.
Referenced by lib_io_misc::lc_file(), data_type_global::load_gfluid_soption(), load_off_option_file(), load_option_file(), parsing_command_line(), lib_vtk_io::pvtk_dat_xml(), lib_vtk_io::upper_case(), lib_vtk_io::vtk_dat(), lib_vtk_io::vtk_dat_xml(), lib_vtk_io::vtk_fld_xml_oc(), lib_vtk_io::vtk_ini(), lib_vtk_io::vtk_ini_xml(), lib_vtk_io::vtk_update(), lib_vtk_io::vtk_var_vect_r4(), lib_vtk_io::vtk_var_vect_r8(), and lib_vtk_io::vtm_blk_xml().
character(len=len(string)) function, public lib_io_misc::lower_case (character(len=*), intent(in) string)
The Lower_Case function converts the upper case characters of a string to lower case one.
Returns
Lower_Case character(*) variable
Parameters
[in] string String to be converted.
Definition at line 284 of file Lib_IO_Misc.f90.
character(len=len(string)) function, public lib_io_misc::string_os_sep (character(len=*), intent(in) string)
The string_OS_sep function converts directories separators into a string to the correct OS's separators.
Returns
string_OS_sep character(*) variable
Definition at line 306 of file Lib_IO_Misc.f90.
References lib_io_misc::os, data_type_os::uix_id, data_type_os::uix_sep, and data_type_os::win_id.
Referenced by icg_init(), load_off_option_file(), load_option_file(), off_init(), and parsing_command_line().
subroutine, public lib_io_misc::tokenize (character(len=*), intent(in) strin, character(len=*), intent(in) delimiter, integer(i4p), intent(out), optional Nt, character(len=len(strin)), dimension(:), intent(out), allocatable toks)
Subroutine for tokenizing a string in order to parse it.
Note
The dummy array containing tokens must allocatable and its character elements must have the same lenght of the input string. If the length of the delimiter is higher than the input string one then the output tokens array is allocated with only one element set to char(0).
Parameters
[in] strin String to be tokenized.
[in] delimiter Delimiter of tokens.
[out] nt Number of tokens.
[out] toks Tokens.
Definition at line 338 of file Lib_IO_Misc.f90.
subroutine, public lib_io_misc::file_not_found (integer(i_p), intent(in), optional myrank, character(*), intent(in) filename, character(*), intent(in) cpn)
Subroutine for printing to stderr a "file not found error".
Parameters
[in] myrank Actual rank process.
[in] filename Name of file where option variables are saved.
[in] cpn Calling procedure name.
Definition at line 380 of file Lib_IO_Misc.f90.
Referenced by data_type_amrblock::load_basemesh_dims(), data_type_sblock::load_bbc(), data_type_sblock::load_bfluid(), load_blocks(), data_type_sblock::load_bmesh(), data_type_sblock::load_bmesh_dims(), data_type_global::load_gbc_in1(), data_type_global::load_gfluid_0species(), data_type_global::load_gfluid_ns(), data_type_global::load_gfluid_soption(), load_icemcfd(), load_off_option_file(), load_option_file(), and lib_parallel::procmap_load().