OFF: Lib_PostProcessing
Lib_PostProcessing
Public Procedures
integer(i_p) function, public lib_postprocessing::tec_output (meshonly, block, filename)
Function for writing OFF block data to Tecplot file.
integer(i_p) function, public lib_postprocessing::vtk_output (meshonly, block, filename)
Function for writing OFF block data to VTK file.
integer(i_p) function, public lib_postprocessing::gnu_output (meshonly, block, filename)
Function for writing OFF block data to Gnuplot file.
Detailed Description
Function/Subroutine Documentation
integer(i_p) function, public lib_postprocessing::tec_output (logical, intent(in) meshonly, type(type_sblock), dimension(1:), intent(inout) block, character(*), intent(in) filename)
Function for writing OFF block data to Tecplot file.
Parameters
[in] meshonly Flag for post-process only mesh.
[in,out] block Block-level data.
[in] filename File name of the output file.
Definition at line 158 of file Lib_PostProcessing.f90.
Referenced by pog().
integer(i_p) function, public lib_postprocessing::vtk_output (logical, intent(in) meshonly, type(type_sblock), dimension(1:), intent(inout) block, character(*), intent(in) filename)
Function for writing OFF block data to VTK file.
Parameters
[in] meshonly Flag for post-process only mesh.
[in,out] block Block-level data.
[in] filename File name of the output file.
Definition at line 440 of file Lib_PostProcessing.f90.
References ir_precision::fr_p, lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), and tec_dat().
Referenced by pog().
integer(i_p) function, public lib_postprocessing::gnu_output (logical, intent(in) meshonly, type(type_sblock), dimension(1:), intent(inout) block, character(*), intent(in) filename)
Function for writing OFF block data to Gnuplot file.
Parameters
[in] meshonly Flag for post-process only mesh.
[in,out] block Block-level data.
[in] filename File name of the output file.
Definition at line 588 of file Lib_PostProcessing.f90.
References lib_thermodynamic_laws_ideal::r(), and lib_vtk_io::vtk_ini_xml().
Referenced by pog().