OFF: Lib_Multigrid
Lib_Multigrid
Modules Libraries
Data Types
module lib_multigrid
This module contains the definition of multigrid procedures.
Detailed Description
Data Type Documentation
module lib_multigrid
This module contains the definition of multigrid procedures.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 13 of file Lib_Multigrid.f90.
Public Member Functions
subroutine, public alloc_multigrid (Nc, bb1, bb2)
subroutine, public restrict (myrank, l, Nb, gco, gc, Ni_f, Nj_f, Nk_f, Ni_c, Nj_c, Nk_c, bb_f, bb_c, bb_Fi_c, bb_Fj_c, bb_Fk_c, Np, Nc, Ns, NFi_c, NFj_c, NFk_c, BCi_c, BCj_c, BCk_c, Nin1, in1, Nin2, bb_in2, in2, Si_c, Sj_c, Sk_c, V_f, V_c, U_f, R_f, t, U_c, UR, TE)
subroutine, public correct (myrank, l, Nb, gco, gc, Ni_f, Nj_f, Nk_f, Ni_c, Nj_c, Nk_c, bb_f, bb_c, bb_Fi_f, bb_Fj_f, bb_Fk_f, Np, Nc, Ns, NFi_f, NFj_f, NFk_f, BCi_f, BCj_f, BCk_f, Nin1, in1, Nin2, bb_in2, in2, Si_f, Sj_f, Sk_f, V_f, UR, U_c, t, U_f, P_f)
Public Attributes
real(r_p), dimension(:,:),
allocatable, public ur
Restriction of conservative variables [1:Nc,bb1:bb2].
real(r_p), dimension(:,:),
allocatable, public te
Truncation error of conservative variables [1:Nc,bb1:bb2].
Member Function/Subroutine Documentation
subroutine, public lib_multigrid::alloc_multigrid (integer(i_p), intent(in) Nc, integer(i_p), intent(in) bb1, integer(i_p), intent(in) bb2)
Definition at line 40 of file Lib_Multigrid.f90.
subroutine, public lib_multigrid::restrict (integer(i_p), intent(in) myrank, integer(i_p), intent(in) l, integer(i_p), intent(in) Nb, integer(i_p), intent(in) gco, integer(i_p), dimension(1:6,1:nb), intent(in) gc, integer(i_p), dimension(1:nb), intent(in) Ni_f, integer(i_p), dimension(1:nb), intent(in) Nj_f, integer(i_p), dimension(1:nb), intent(in) Nk_f, integer(i_p), dimension(1:nb), intent(in) Ni_c, integer(i_p), dimension(1:nb), intent(in) Nj_c, integer(i_p), dimension(1:nb), intent(in) Nk_c, integer(i_p), dimension (1:2,1:nb), intent(in) bb_f, integer(i_p), dimension (1:2,1:nb), intent(in) bb_c, integer(i_p), dimension(1:2,1:nb), intent(in) bb_Fi_c, integer(i_p), dimension(1:2,1:nb), intent(in) bb_Fj_c, integer(i_p), dimension(1:2,1:nb), intent(in) bb_Fk_c, integer(i_p), intent(in) Np, integer(i_p), intent(in) Nc, integer(i_p), intent(in) Ns, type(type_vector), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) NFi_c, type(type_vector), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) NFj_c, type(type_vector), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) NFk_c, type(type_bc), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) BCi_c, type(type_bc), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) BCj_c, type(type_bc), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) BCk_c, integer(i_p), intent(in) Nin1, real(r_p), dimension(1:np,1:nin1), intent(in) in1, integer(i_p), intent(in) Nin2, integer(i_p), dimension(1:2,1:nin2), intent(in) bb_in2, real(r_p), dimension(1:np+1,bb_in2(1,1):bb_in2(2,nin2)), intent(in) in2, real(r_p), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) Si_c, real(r_p), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) Sj_c, real(r_p), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) Sk_c, real(r_p), dimension (bb_f (1,1):bb_f (2,nb)), intent(in) V_f, real(r_p), dimension (bb_c (1,1):bb_c (2,nb)), intent(in) V_c, real(r_p), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(in) U_f, real(r_p), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(in) R_f, real(r_p), intent(in) t, real(r_p), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) U_c, real(r_p), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) UR, real(r_p), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) TE)
Definition at line 58 of file Lib_Multigrid.f90.
References lib_fluidynamic::boundary_conditions(), lib_fluidynamic::conservative2primitive(), fine2coarse_r(), fine2coarse_u(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), and te_estimation().
subroutine, public lib_multigrid::correct (integer(i_p), intent(in) myrank, integer(i_p), intent(in) l, integer(i_p), intent(in) Nb, integer(i_p), intent(in) gco, integer(i_p), dimension(1:6,1:nb), intent(in) gc, integer(i_p), dimension(1:nb), intent(in) Ni_f, integer(i_p), dimension(1:nb), intent(in) Nj_f, integer(i_p), dimension(1:nb), intent(in) Nk_f, integer(i_p), dimension(1:nb), intent(in) Ni_c, integer(i_p), dimension(1:nb), intent(in) Nj_c, integer(i_p), dimension(1:nb), intent(in) Nk_c, integer(i_p), dimension(1:2,1:nb), intent(in) bb_f, integer(i_p), dimension(1:2,1:nb), intent(in) bb_c, integer(i_p), dimension(1:2,1:nb), intent(in) bb_Fi_f, integer(i_p), dimension(1:2,1:nb), intent(in) bb_Fj_f, integer(i_p), dimension(1:2,1:nb), intent(in) bb_Fk_f, integer(i_p), intent(in) Np, integer(i_p), intent(in) Nc, integer(i_p), intent(in) Ns, type(type_vector), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) NFi_f, type(type_vector), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) NFj_f, type(type_vector), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) NFk_f, type(type_bc), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) BCi_f, type(type_bc), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) BCj_f, type(type_bc), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) BCk_f, integer(i_p), intent(in) Nin1, real(r_p), dimension(1:np,1:nin1), intent(in) in1, integer(i_p), intent(in) Nin2, integer(i_p), dimension(1:2,1:nin2), intent(in) bb_in2, real(r_p), dimension(1:np+1,bb_in2(1,1):bb_in2(2,nin2)), intent(in) in2, real(r_p), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) Si_f, real(r_p), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) Sj_f, real(r_p), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) Sk_f, real(r_p), dimension (bb_f (1,1):bb_f (2,nb)), intent(in) V_f, real(r_p), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(in) UR, real(r_p), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(in) U_c, real(r_p), intent(in) t, real(r_p), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(inout) U_f, real(r_p), dimension (1:np,bb_f (1,1):bb_f (2,nb)), intent(out) P_f)
Definition at line 328 of file Lib_Multigrid.f90.
References lib_fluidynamic::boundary_conditions(), coarse2fine_u(), lib_fluidynamic::conservative2primitive(), get_correction(), lib_thermodynamic_laws_ideal::p(), and update_fine().
Referenced by data_type_sblock::metrics_correction().
Member Data Documentation
real(r_p), dimension(:,:), allocatable, public lib_multigrid::ur
Restriction of conservative variables [1:Nc,bb1:bb2].
Definition at line 36 of file Lib_Multigrid.f90.
real(r_p), dimension(:,:), allocatable, public lib_multigrid::te
Truncation error of conservative variables [1:Nc,bb1:bb2].
Definition at line 37 of file Lib_Multigrid.f90.