OFF: Data_Type_Tensor
Data_Type_Tensor
Derived Types
Data Types
type data_type_tensor::type_tensor
Derived type defining tensors.
Detailed Description
Data Type Documentation
type data_type_tensor::type_tensor
Derived type defining tensors.
Note
The components of the tensor are 3 vectors arranged as following:
Definition at line 72 of file Data_Type_Tensor.f90.
Public Member Functions
procedure, non_overridable set
procedure, non_overridable sq_norm => sq_norm_ten
procedure, non_overridable norml2 => normL2_ten
procedure, non_overridable normalize => normalize_self
procedure, non_overridable transpose => transpose_self
procedure, non_overridable determinant
procedure, non_overridable invert => invert_self
procedure, non_overridable invertible
procedure, non_overridable rotox
procedure, non_overridable rotoy
procedure, non_overridable rotoz
procedure, non_overridable rotou
Public Attributes
type(type_vector) x
Cartesian vector component in x direction.
type(type_vector) y
Cartesian vector component in y direction.
type(type_vector) z
Cartesian vector component in z direction.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_tensor::type_tensor::set ()
Definition at line 77 of file Data_Type_Tensor.f90.
References data_type_tensor::transpose_self().
procedure, non_overridable data_type_tensor::type_tensor::sq_norm ()
Definition at line 78 of file Data_Type_Tensor.f90.
References determinant().
Referenced by lib_fluidynamic::cons2prim(), and preconstruct_n().
procedure, non_overridable data_type_tensor::type_tensor::norml2 ()
Definition at line 79 of file Data_Type_Tensor.f90.
References invert(), and data_type_tensor::invert_self().
Referenced by data_type_sblock::metrics(), data_type_sblock::metrics_correction(), data_type_vector::normalize(), data_type_vector::normalize_self(), data_type_vector::vec_eq_i1p(), data_type_vector::vec_eq_i2p(), data_type_vector::vec_eq_i4p(), data_type_vector::vec_eq_i8p(), data_type_vector::vec_eq_r16p(), data_type_vector::vec_eq_r4p(), data_type_vector::vec_eq_r8p(), data_type_vector::vec_eq_vec(), data_type_vector::vec_great_eq_i1p(), data_type_vector::vec_great_eq_i2p(), data_type_vector::vec_great_eq_i4p(), data_type_vector::vec_great_eq_i8p(), data_type_vector::vec_great_eq_r16p(), data_type_vector::vec_great_eq_r4p(), data_type_vector::vec_great_eq_r8p(), data_type_vector::vec_great_eq_vec(), data_type_vector::vec_great_i1p(), data_type_vector::vec_great_i2p(), data_type_vector::vec_great_i4p(), data_type_vector::vec_great_i8p(), data_type_vector::vec_great_r16p(), data_type_vector::vec_great_r4p(), data_type_vector::vec_great_r8p(), data_type_vector::vec_great_vec(), data_type_vector::vec_low_eq_i1p(), data_type_vector::vec_low_eq_i2p(), data_type_vector::vec_low_eq_i4p(), data_type_vector::vec_low_eq_i8p(), data_type_vector::vec_low_eq_r16p(), data_type_vector::vec_low_eq_r4p(), data_type_vector::vec_low_eq_r8p(), data_type_vector::vec_low_eq_vec(), data_type_vector::vec_low_i1p(), data_type_vector::vec_low_i2p(), data_type_vector::vec_low_i4p(), data_type_vector::vec_low_i8p(), data_type_vector::vec_low_r16p(), data_type_vector::vec_low_r4p(), data_type_vector::vec_low_r8p(), data_type_vector::vec_low_vec(), data_type_vector::vec_not_eq_i1p(), data_type_vector::vec_not_eq_i2p(), data_type_vector::vec_not_eq_i4p(), data_type_vector::vec_not_eq_i8p(), data_type_vector::vec_not_eq_r16p(), data_type_vector::vec_not_eq_r4p(), data_type_vector::vec_not_eq_r8p(), and data_type_vector::vec_not_eq_vec().
procedure, non_overridable data_type_tensor::type_tensor::normalize ()
Definition at line 80 of file Data_Type_Tensor.f90.
References invertible().
Referenced by data_type_vector::face_normal3(), data_type_vector::face_normal4(), data_type_sblock::metrics(), data_type_sblock::metrics_correction(), data_type_vector::parallel(), data_type_vector::type_vector::set(), data_type_vector::vec_eq_vec(), and data_type_vector::vec_not_eq_vec().
procedure, non_overridable data_type_tensor::type_tensor::transpose ()
Definition at line 81 of file Data_Type_Tensor.f90.
References rotox().
procedure, non_overridable data_type_tensor::type_tensor::determinant ()
Definition at line 82 of file Data_Type_Tensor.f90.
References rotoy().
Referenced by data_type_tensor::invert(), data_type_tensor::invert_self(), data_type_tensor::invertible(), and sq_norm().
procedure, non_overridable data_type_tensor::type_tensor::invert ()
Definition at line 83 of file Data_Type_Tensor.f90.
References rotoz().
Referenced by norml2().
procedure, non_overridable data_type_tensor::type_tensor::invertible ()
Definition at line 84 of file Data_Type_Tensor.f90.
References rotou().
Referenced by normalize().
procedure, non_overridable data_type_tensor::type_tensor::rotox ()
Definition at line 85 of file Data_Type_Tensor.f90.
Referenced by transpose().
procedure, non_overridable data_type_tensor::type_tensor::rotoy ()
Definition at line 86 of file Data_Type_Tensor.f90.
Referenced by determinant().
procedure, non_overridable data_type_tensor::type_tensor::rotoz ()
Definition at line 87 of file Data_Type_Tensor.f90.
Referenced by invert().
procedure, non_overridable data_type_tensor::type_tensor::rotou ()
Definition at line 88 of file Data_Type_Tensor.f90.
Referenced by invertible().
Member Data Documentation
type(type_vector) data_type_tensor::type_tensor::x
Cartesian vector component in x direction.
Definition at line 73 of file Data_Type_Tensor.f90.
type(type_vector) data_type_tensor::type_tensor::y
Cartesian vector component in y direction.
Definition at line 74 of file Data_Type_Tensor.f90.
type(type_vector) data_type_tensor::type_tensor::z
Cartesian vector component in z direction.
Definition at line 75 of file Data_Type_Tensor.f90.