OFF: Lib_Parallel
Lib_Parallel
Public Procedures
subroutine, public lib_parallel::init_sendrecv (block)
Subroutine for initializing the send/receive communications data.
subroutine, public lib_parallel::psendrecv (l, block)
Subroutine for performing send/receive of primitive variables of myrank to other processes.
integer(i_p) function, public lib_parallel::procmap_load (filename, global)
Function for loading the processes/blocks map and local/global blocks map.
integer(i_p) function, public lib_parallel::procmap_save (filename, global)
Function for saving the processes/blocks map.
Detailed Description
Function/Subroutine Documentation
subroutine, public lib_parallel::init_sendrecv (type(type_sblock), dimension(1:,1:), intent(in) block)
Subroutine for initializing the send/receive communications data.
Parameters
[in] block Block-level data.
Definition at line 503 of file Lib_Parallel.f90.
References lib_parallel::alloc_sendrecv(), lib_parallel::alloc_sr(), lib_parallel::compute_bbs(), lib_parallel::compute_ncr(), lib_parallel::compute_recv_maps(), lib_parallel::mapsendrecv(), lib_parallel::ncrsendrecv(), and lib_parallel::printsendrecvmaps().
Referenced by off(), and off_init().
integer(i_p) function, public lib_parallel::procmap_load (character(*), intent(in) filename, type(type_global), intent(inout) global)
Function for loading the processes/blocks map and local/global blocks map.
Returns
err integer(I4P) variable.
Parameters
[in] filename File name processes/blocks map.
[in,out] global Global-level data.
Definition at line 596 of file Lib_Parallel.f90.
References lib_parallel::blockmap, lib_io_misc::file_not_found(), lib_io_misc::get_unit(), lib_parallel::nproc, and lib_parallel::procmap.
Referenced by off(), and off_init().
subroutine, public lib_parallel::psendrecv (integer(i_p), intent(in) l, type(type_sblock), dimension(1:), intent(inout) block)
Subroutine for performing send/receive of primitive variables of myrank to other processes.
Parameters
[in] l Grid level.
[in,out] block Block-level data.
Definition at line 526 of file Lib_Parallel.f90.
References data_type_sl_list::type_sl_link::array(), lib_parallel::blockmap, lib_morton::mask, and lib_parallel::nproc.
Referenced by lib_fluidynamic::boundary_conditions().
integer(i_p) function, public lib_parallel::procmap_save (character(*), intent(in) filename, type(type_global), intent(in) global)
Function for saving the processes/blocks map.
Returns
err integer(I4P) variable.
Parameters
[in] filename File name processes/blocks map.
[in] global Global-level data.
Definition at line 647 of file Lib_Parallel.f90.
References lib_io_misc::get_unit(), and lib_parallel::procmap.