OFF: Lib_Riemann
Lib_Riemann
Public Procedures
logical function, public lib_riemann::chk_smooth_z (p1, r1, u1, g1, p4, r4, u4, g4)
Function for evaluating the smoothness of an interface using a Riemann solver-like algorithm.
logical function, public lib_riemann::chk_smooth_limiter (pm1, pp1, rm1, rp1, um1, up1, gm1, gp1)
Function for evaluating the smoothness of a cell using a discontinuity detector based on slope limiter function.
logical function, public lib_riemann::chk_smooth_liu (pm1, rm1, um1, gm1, cpm1, cvm1, p1, r1, u1m, u1p, g1, cp1, cv1, pp1, rp1, up1, gp1, cpp1, cvp1)
Function for evaluating the smoothness of a cell using the Liu's entropy conditions.
elemental subroutine, public lib_riemann::riem_solver_laxfriedrichs (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on (local) Lax-Friedrichs (known also as Rusanov) algorithm.
subroutine, public lib_riemann::riem_solver_pvl (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Primitive Variables Linearization algorithm.
subroutine, public lib_riemann::riem_solver_tr (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Two Rarefactions algorithm.
elemental subroutine, public lib_riemann::riem_solver_ts (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Two Shocks algorithm.
subroutine, public lib_riemann::riem_solver_aprs (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Adaptive (non iterative) PVL-TR-TS algorithm.
subroutine, public lib_riemann::riem_solver_alfr (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Adaptive (non iterative) LF-TR algorithm.
elemental subroutine, public lib_riemann::riem_solver_hllc (p1, r1, u1, g1,
Approximate Riemann solver based on HLLC algorithm.
elemental subroutine, public lib_riemann::riem_solver_roe (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, F_r, F_u, F_E)
Approximate Riemann solver based on Roe linearization.
subroutine, public lib_riemann::riem_solver_exact_u (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Exact Riemann solver based on iterative solution of u-function.
Detailed Description
Function/Subroutine Documentation
logical function, public lib_riemann::chk_smooth_z (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4)
Function for evaluating the smoothness of an interface using a Riemann solver-like algorithm.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
Definition at line 800 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), lib_riemann::pvl_up23(), lib_thermodynamic_laws_ideal::r(), lib_riemann::tr_u23(), and lib_riemann::ts_up23().
elemental subroutine, public lib_riemann::riem_solver_laxfriedrichs (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E)
Approximate Riemann solver based on (local) Lax-Friedrichs (known also as Rusanov) algorithm.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] f_r Flux of mass conservation.
[out] f_u Flux of momentum conservation.
[out] f_e Flux of energy conservation.
Definition at line 1795 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), lib_riemann::pvl_wavesspeed14(), lib_thermodynamic_laws_ideal::r(), lib_riemann::ts_up23(), lib_riemann::wavesspeed14up(), and lib_riemann::z_wavesspeed14().
Referenced by lib_riemann::riem_solver_hllc().
logical function, public lib_riemann::chk_smooth_limiter (real(r_p), intent(in) pm1, real(r_p), intent(in) pp1, real(r_p), intent(in) rm1, real(r_p), intent(in) rp1, real(r_p), intent(in) um1, real(r_p), intent(in) up1, real(r_p), intent(in) gm1, real(r_p), intent(in) gp1)
Function for evaluating the smoothness of a cell using a discontinuity detector based on slope limiter function.
Parameters
[in] pm1 Upwind difference of pressure.
[in] pp1 Downwind difference of pressure.
[in] rm1 Upwind difference of density.
[in] rp1 Downwind difference of density.
[in] um1 Upwind difference of speed.
[in] up1 Downwind difference of speed.
[in] gm1 Upwind difference of specific heats ratio.
[in] gp1 Downwind difference of specific heats ratio.
Definition at line 840 of file Lib_Riemann.f90.
References lib_riemann::harten_limiter(), lib_riemann::vanalbada_limiter(), and lib_riemann::vanleer_limiter().
logical function, public lib_riemann::chk_smooth_liu (real(r_p), intent(in) pm1, real(r_p), intent(in) rm1, real(r_p), intent(in) um1, real(r_p), intent(in) gm1, real(r_p), intent(in) cpm1, real(r_p), intent(in) cvm1, real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1m, real(r_p), intent(in) u1p, real(r_p), intent(in) g1, real(r_p), intent(in) cp1, real(r_p), intent(in) cv1, real(r_p), intent(in) pp1, real(r_p), intent(in) rp1, real(r_p), intent(in) up1, real(r_p), intent(in) gp1, real(r_p), intent(in) cpp1, real(r_p), intent(in) cvp1)
Function for evaluating the smoothness of a cell using the Liu's entropy conditions.
Parameters
[in] pm1 Pressure of state i-1.
[in] rm1 Density of state i-1.
[in] um1 Velocity of state i-1.
[in] gm1 Specific heats ratio of state i-1.
[in] cpm1 Specific heats cp of state i-1.
[in] cvm1 Specific heats cv of state i-1.
[in] p1 Pressure of state i.
[in] r1 Density of state i.
[in] u1m Velocity of state i at left interface.
[in] u1p Velocity of state i at left interface.
[in] g1 Specific heats ratio of state i.
[in] cp1 Specific heats cp of state i.
[in] cv1 Specific heats cv of state i.
[in] pp1 Pressure of state i+1.
[in] rp1 Density of state i+1.
[in] up1 Velocity of state i+1.
[in] gp1 Specific heats ratio of state i+1.
[in] cpp1 Specific heats cp of state i+1.
[in] cvp1 Specific heats cv of state i+1.
Definition at line 874 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), and lib_riemann::roe_ua().
subroutine, public lib_riemann::riem_solver_pvl (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E)
Approximate Riemann solver based on Primitive Variables Linearization algorithm.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] f_r Flux of mass conservation.
[out] f_u Flux of momentum conservation.
[out] f_e Flux of energy conservation.
Definition at line 1845 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::e(), lib_riemann::fluxes(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
subroutine, public lib_riemann::riem_solver_tr (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E)
Approximate Riemann solver based on Two Rarefactions algorithm.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] f_r Flux of mass conservation.
[out] f_u Flux of momentum conservation.
[out] f_e Flux of energy conservation.
Definition at line 1887 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), lib_riemann::pvl_states(), lib_thermodynamic_laws_ideal::r(), and lib_riemann::sampling_fluxes().
Referenced by lib_riemann::riem_solver_hllc().
elemental subroutine, public lib_riemann::riem_solver_ts (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E)
Approximate Riemann solver based on Two Shocks algorithm.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] f_r Flux of mass conservation.
[out] f_u Flux of momentum conservation.
[out] f_e Flux of energy conservation.
Definition at line 1929 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), lib_riemann::sampling_fluxes(), lib_riemann::tr_states(), and lib_riemann::ts_states().
subroutine, public lib_riemann::riem_solver_aprs (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E)
Approximate Riemann solver based on Adaptive (non iterative) PVL-TR-TS algorithm.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] f_r Flux of mass conservation.
[out] f_u Flux of momentum conservation.
[out] f_e Flux of energy conservation.
Definition at line 1977 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_riemann::fluxes(), lib_thermodynamic_laws_ideal::p(), lib_riemann::pvl_states(), lib_riemann::pvl_up23(), lib_thermodynamic_laws_ideal::r(), lib_riemann::tr_states(), and lib_riemann::ts_states().
subroutine, public lib_riemann::riem_solver_alfr (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E)
Approximate Riemann solver based on Adaptive (non iterative) LF-TR algorithm.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] f_r Flux of mass conservation.
[out] f_u Flux of momentum conservation.
[out] f_e Flux of energy conservation.
Definition at line 2040 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), lib_riemann::rarefaction(), and lib_riemann::sampling_fluxes().
elemental subroutine, public lib_riemann::riem_solver_hllc (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1)
Approximate Riemann solver based on HLLC algorithm.
Note
Five variants are provided: HLLCb, using BCLC estimation of waves speed, HLLCc using CVL algorithm, HLLCp using PVL algorithm, HLLCt using TR algorithm and HLLCz using Z one.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
Definition at line 2127 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_riemann::bclc_wavesspeed14(), lib_riemann::cvl_wavesspeed14(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), lib_riemann::riem_solver_laxfriedrichs(), lib_riemann::riem_solver_tr(), and lib_riemann::sampling_fluxes_vacuum().
elemental subroutine, public lib_riemann::riem_solver_roe (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) cp1, real(r_p), intent(in) cv1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(in) cp4, real(r_p), intent(in) cv4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E)
Approximate Riemann solver based on Roe linearization.
Note
The Harten-Hyman entropy fix is used to avoid shock-expansions (entropy violation).
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] cp1 Specific heats cp of state 1.
[in] cv1 Specific heats cv of state 1.
[in] p4 pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[in] cp4 Specific heats cp of state 4.
[in] cv4 Specific heats cv of state 4.
[out] f_r Flux of mass conservation.
[out] f_u Flux of momentum conservation.
[out] f_e Flux of energy conservation.
Definition at line 2216 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::e(), lib_riemann::fluxes(), lib_thermodynamic_laws_ideal::p(), lib_riemann::pvl_wavesspeed1234(), lib_riemann::pvl_wavesspeed14(), lib_thermodynamic_laws_ideal::r(), lib_riemann::roe_state(), lib_riemann::tr_wavesspeed14(), and lib_riemann::z_wavesspeed14().
subroutine, public lib_riemann::riem_solver_exact_u (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E)
Exact Riemann solver based on iterative solution of u-function.
Parameters
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 U speed of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 U speed of state 4.
[in] g4 Specific heats ratio of state 4.
[out] f_r Flux of mass conservation.
[out] f_u Flux of momentum conservation.
[out] f_e Flux of energy conservation.
Definition at line 2316 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_riemann::fluxes(), lib_riemann::interstates23u(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), lib_riemann::roe_state(), and lib_riemann::sampling_fluxes().