OFF: POG
POG
Programs
Functions/Subroutines
program pog
POG, Post-processor Output Generator for OFF (Open Finite volume Fluid dynamics code).
Detailed Description
Function/Subroutine Documentation
program pog ()
POG, Post-processor Output Generator for OFF (Open Finite volume Fluid dynamics code).
This is an auxiliary tool useful for post-processing OFF simulations outputs. It can manipulate OFF outputs and it can produce files ready to be visualized. Two different visualization standards are supported:
Tecplot, Inc.: Tecplot is a wide-used visualization tool (http://www.tecplot.com/). POG can produce both ascii and binary files in Tecplot standard.
VTK: The Visualization Toolkit (VTK) is an open-source, freely available software system for 3D computer graphics, image processing and visualization (http://www.vtk.org/). A lot of visualization tools support VTK standard. Among those tools Paraview (http://www.paraview.org/) seems to be one of the most complete. POG can produce both ascii and binary files in VTK standard. To this aim the Lib_VTK_IO is used.
Note
In order to produce binary Tecplot file the Tecplot, Inc.'s library tecio.a (or tecio64.a) must be available during the compilation of POG. If you are using the makefile shipped with OFF code there is a dedicated option: TECIO=yes/no. If during the compilation this option is set to yes (e.g. make POG TECIO=yes) the make search the correct library into ./lib/. Edit the makefile to point to the correct path where tecio.a (or tecio64.a) is placed. For more details see Compiling Instructions.
Todo:
DocImprove: Improve the documentation
Definition at line 26 of file POG.f90.
References lib_vtk_io::binary, lib_postprocessing::gnu_output(), ir_precision::ir_init(), parsing_command_line(), lib_postprocessing::pp_format, lib_postprocessing::tec_output(), and lib_postprocessing::vtk_output().