OFF: Lib_Morton
Lib_Morton
Interfaces
Data Types
interface lib_morton::dil
Function for dilating 1 integer(I1P/I2P/I4P) (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
interface lib_morton::ctc
Subroutine for contracting 1 integer of 64 bits (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
interface lib_morton::morton2
Function for encoding 2 integer(I1P/I2P/I4P) indexes into 1 integer(I8P) Morton's key.
interface lib_morton::demorton2
Subroutine for decoding 1 integer(I8P) Morton's key into 2 integer(I1P/I2P/I4P) indexes.
interface lib_morton::morton3
Function for encoding 3 integer(I1P/I2P) indexes into 1 integer(I8P) Morton's key.
interface lib_morton::demorton3
Subroutine for decoding 1 integer(I8P) Morton's key into 3 integer(I1P/I2P) indexes.
Detailed Description
Data Type Documentation
interface lib_morton::dil
Function for dilating 1 integer(I1P/I2P/I4P) (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
The resulting integer has 64 bits; it has only 'b' significant bits interleaved by 'z' zeros: bb/zx0/bb-1/zx0../b1/zx0/b0; e.g. for (b=4,z=1): b3/b2/b1/b0 => b3/0/b2/0/b1/0/b0.
Definition at line 86 of file Lib_Morton.f90.
Private Member Functions
elemental function dil_i1p (i, b, z)
Function for dilating integers (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
elemental function dil_i2p (i, b, z)
Function for dilating integers (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
elemental function dil_i4p (i, b, z)
Function for dilating integers (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
Member Function/Subroutine Documentation
elemental function lib_morton::dil::dil_i1p (integer(i1p), intent(in) i, integer(i2p), intent(in) b, integer(i1p), intent(in) z) private
Function for dilating integers (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
The resulting integer has 64 bits; it has only 'b' significant bits interleaved by 'z' zeros: bb/zx0/bb-1/zx0../b1/zx0/b0; e.g. for (b=4,z=1): b3/b2/b1/b0 => b3/0/b2/0/b1/0/b0.
Parameters
[in] i Input integer.
[in] b Number of significant bits of 'i' (2/4/8).
[in] z Number of zero 'i' (1/2).
Definition at line 124 of file Lib_Morton.f90.
Referenced by lib_morton::morton2_i1p(), and lib_morton::morton3_i1p().
elemental function lib_morton::dil::dil_i2p (integer(i2p), intent(in) i, integer(i2p), intent(in) b, integer(i1p), intent(in) z) private
Function for dilating integers (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
The resulting integer has 64 bits; it has only 'b' significant bits interleaved by 'z' zeros: bb/zx0/bb-1/zx0../b1/zx0/b0; e.g. for (b=4,z=1): b3/b2/b1/b0 => b3/0/b2/0/b1/0/b0.
Parameters
[in] i Input integer.
[in] b Number of significant bits of 'i' (2/4/8/16).
[in] z Number of zero 'i' (1/2).
Definition at line 148 of file Lib_Morton.f90.
Referenced by lib_morton::morton2_i2p(), and lib_morton::morton3_i2p().
elemental function lib_morton::dil::dil_i4p (integer(i4p), intent(in) i, integer(i2p), intent(in) b, integer(i1p), intent(in) z) private
Function for dilating integers (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
The resulting integer has 64 bits; it has only 'b' significant bits interleaved by 'z' zeros: bb/zx0/bb-1/zx0../b1/zx0/b0; e.g. for (b=4,z=1): b3/b2/b1/b0 => b3/0/b2/0/b1/0/b0.
Parameters
[in] i Input integer.
[in] b Number of significant bits of 'i' (2/4/8/16/32).
[in] z Number of zero 'i' (1/2).
Definition at line 172 of file Lib_Morton.f90.
Referenced by lib_morton::morton2_i4p().
interface lib_morton::ctc
Subroutine for contracting 1 integer of 64 bits (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
The resulting integer(I1P/I2P/I4P) has only 'b' significant bits obtained by the following contraction: if bb/zx0/bb-1/zx0../b1/zx0/b0 => bb/bb-1/.../b1/b0; e.g. for (b=4,z=1): b3/0/b2/0/b1/0/b0 => b3/b2/b1/b0.
Definition at line 94 of file Lib_Morton.f90.
Private Member Functions
elemental subroutine ctc_i1p (i, b, z, c)
Subroutine for contracting integer of 64 bits (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
elemental subroutine ctc_i2p (i, b, z, c)
Subroutine for contracting integer of 64 bits (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
elemental subroutine ctc_i4p (i, b, z, c)
Subroutine for contracting integer of 64 bits (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
Member Function/Subroutine Documentation
elemental subroutine lib_morton::ctc::ctc_i1p (integer(i8p), intent(in) i, integer(i2p), intent(in) b, integer(i1p), intent(in) z, integer(i1p), intent(out) c) private
Subroutine for contracting integer of 64 bits (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
The resulting integer has only 'b' significant bits obtained by the following contraction: if bb/zx0/bb-1/zx0../b1/zx0/b0 => bb/bb-1/.../b1/b0; e.g. for (b=4,z=1): b3/0/b2/0/b1/0/b0 => b3/b2/b1/b0.
Parameters
[in] i Input integer.
[in] b Number of significant bits of 'i' (2/4/8).
[in] z Number of zero 'i' (1/2).
[out] c Contracted integer.
Definition at line 197 of file Lib_Morton.f90.
elemental subroutine lib_morton::ctc::ctc_i2p (integer(i8p), intent(in) i, integer(i2p), intent(in) b, integer(i1p), intent(in) z, integer(i2p), intent(out) c) private
Subroutine for contracting integer of 64 bits (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
The resulting integer has only 'b' significant bits obtained by the following contraction: if bb/zx0/bb-1/zx0../b1/zx0/b0 => bb/bb-1/.../b1/b0; e.g. for (b=4,z=1): b3/0/b2/0/b1/0/b0 => b3/b2/b1/b0.
Parameters
[in] i Input integer.
[in] b Number of significant bits of 'i' (2/4/8/16).
[in] z Number of zero 'i' (1/2).
[out] c Contracted integer.
Definition at line 222 of file Lib_Morton.f90.
elemental subroutine lib_morton::ctc::ctc_i4p (integer(i8p), intent(in) i, integer(i2p), intent(in) b, integer(i1p), intent(in) z, integer(i4p), intent(out) c) private
Subroutine for contracting integer of 64 bits (ref On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009).
The resulting integer has only 'b' significant bits obtained by the following contraction: if bb/zx0/bb-1/zx0../b1/zx0/b0 => bb/bb-1/.../b1/b0; e.g. for (b=4,z=1): b3/0/b2/0/b1/0/b0 => b3/b2/b1/b0.
Parameters
[in] i Input integer.
[in] b Number of significant bits of 'i' (2/4/8/16/32).
[in] z Number of zero 'i' (1/2).
[out] c Contracted integer.
Definition at line 247 of file Lib_Morton.f90.
interface lib_morton::morton2
Function for encoding 2 integer(I1P/I2P/I4P) indexes into 1 integer(I8P) Morton's key.
Definition at line 99 of file Lib_Morton.f90.
Private Member Functions
elemental function morton2_i1p (i, j, b)
Function for encoding 2 integer(I1P) indexes into 1 integer(I8P) Morton's key.
elemental function morton2_i2p (i, j, b)
Function for encoding 2 integer(I2P) indexes into 1 integer(I8P) Morton's key.
elemental function morton2_i4p (i, j, b)
Function for encoding 2 integer(I4P) indexes into 1 integer(I8P) Morton's key.
Member Function/Subroutine Documentation
elemental function lib_morton::morton2::morton2_i1p (integer(i1p), intent(in) i, integer(i1p), intent(in) j, integer(i2p), intent(in), optional b) private
Function for encoding 2 integer(I1P) indexes into 1 integer(I8P) Morton's key.
Parameters
[in] i I index.
[in] j J index.
[in] b Number of significant bits of 'i' (2/4/8).
Definition at line 269 of file Lib_Morton.f90.
elemental function lib_morton::morton2::morton2_i2p (integer(i2p), intent(in) i, integer(i2p), intent(in) j, integer(i2p), intent(in), optional b) private
Function for encoding 2 integer(I2P) indexes into 1 integer(I8P) Morton's key.
Parameters
[in] i I index.
[in] j J index.
[in] b Number of significant bits of 'i' (2/4/8/16).
Definition at line 293 of file Lib_Morton.f90.
elemental function lib_morton::morton2::morton2_i4p (integer(i4p), intent(in) i, integer(i4p), intent(in) j, integer(i2p), intent(in), optional b) private
Function for encoding 2 integer(I4P) indexes into 1 integer(I8P) Morton's key.
Parameters
[in] i I index.
[in] j J index.
[in] b Number of significant bits of 'i' (2/4/8/16/32).
Definition at line 317 of file Lib_Morton.f90.
interface lib_morton::demorton2
Subroutine for decoding 1 integer(I8P) Morton's key into 2 integer(I1P/I2P/I4P) indexes.
Definition at line 104 of file Lib_Morton.f90.
Private Member Functions
elemental subroutine demorton2_i1p (key, i, j, b)
Subroutine for decoding 1 integer(I8P) Morton's key into 2 integer(I1P) indexes.
elemental subroutine demorton2_i2p (key, i, j, b)
Subroutine for decoding 1 integer(I8P) Morton's key into 2 integer(I2P) indexes.
elemental subroutine demorton2_i4p (key, i, j, b)
Subroutine for decoding 1 integer(I8P) Morton's key into 2 integer(I4P) indexes.
Member Function/Subroutine Documentation
elemental subroutine lib_morton::demorton2::demorton2_i1p (integer(i8p), intent(in) key, integer(i1p), intent(inout) i, integer(i1p), intent(inout) j, integer(i2p), intent(in), optional b) private
Subroutine for decoding 1 integer(I8P) Morton's key into 2 integer(I1P) indexes.
Parameters
[in] key Morton's key.
[in,out] i I index.
[in,out] j J index.
[in] b Number of significant bits of 'i' (2/4/8).
Definition at line 341 of file Lib_Morton.f90.
elemental subroutine lib_morton::demorton2::demorton2_i2p (integer(i8p), intent(in) key, integer(i2p), intent(inout) i, integer(i2p), intent(inout) j, integer(i2p), intent(in), optional b) private
Subroutine for decoding 1 integer(I8P) Morton's key into 2 integer(I2P) indexes.
Parameters
[in] key Morton's key.
[in,out] i I index.
[in,out] j J index.
[in] b Number of significant bits of 'i' (2/4/8/16).
Definition at line 363 of file Lib_Morton.f90.
elemental subroutine lib_morton::demorton2::demorton2_i4p (integer(i8p), intent(in) key, integer(i4p), intent(inout) i, integer(i4p), intent(inout) j, integer(i2p), intent(in), optional b) private
Subroutine for decoding 1 integer(I8P) Morton's key into 2 integer(I4P) indexes.
Parameters
[in] key Morton's key.
[in,out] i I index.
[in,out] j J index.
[in] b Number of significant bits of 'i' (2/4/8/16/32).
Definition at line 385 of file Lib_Morton.f90.
interface lib_morton::morton3
Function for encoding 3 integer(I1P/I2P) indexes into 1 integer(I8P) Morton's key.
Definition at line 109 of file Lib_Morton.f90.
Private Member Functions
elemental function morton3_i1p (i, j, k, b)
Function for encoding 3 integer(I1P) indexes into 1 integer(I8P) Morton's key.
elemental function morton3_i2p (i, j, k, b)
Function for encoding 3 integer(I2P) indexes into 1 integer(I8P) Morton's key.
Member Function/Subroutine Documentation
elemental function lib_morton::morton3::morton3_i1p (integer(i1p), intent(in) i, integer(i1p), intent(in) j, integer(i1p), intent(in) k, integer(i2p), intent(in), optional b) private
Function for encoding 3 integer(I1P) indexes into 1 integer(I8P) Morton's key.
Parameters
[in] i I index.
[in] j J index.
[in] k K index.
[in] b Number of significant bits of 'i' (2/4/8).
Definition at line 407 of file Lib_Morton.f90.
elemental function lib_morton::morton3::morton3_i2p (integer(i2p), intent(in) i, integer(i2p), intent(in) j, integer(i2p), intent(in) k, integer(i2p), intent(in), optional b) private
Function for encoding 3 integer(I2P) indexes into 1 integer(I8P) Morton's key.
Parameters
[in] i I index.
[in] j J index.
[in] k K index.
[in] b Number of significant bits of 'i' (2/4/8/16).
Definition at line 435 of file Lib_Morton.f90.
interface lib_morton::demorton3
Subroutine for decoding 1 integer(I8P) Morton's key into 3 integer(I1P/I2P) indexes.
Definition at line 114 of file Lib_Morton.f90.
Private Member Functions
elemental subroutine demorton3_i1p (key, i, j, k, b)
Subroutine for decoding 1 integer(I8P) Morton's key into 3 integer(I1P) indexes.
elemental subroutine demorton3_i2p (key, i, j, k, b)
Subroutine for decoding 1 integer(I8P) Morton's key into 3 integer(I2P) indexes.
Member Function/Subroutine Documentation
elemental subroutine lib_morton::demorton3::demorton3_i1p (integer(i8p), intent(in) key, integer(i1p), intent(inout) i, integer(i1p), intent(inout) j, integer(i1p), intent(inout) k, integer(i2p), intent(in), optional b) private
Subroutine for decoding 1 integer(I8P) Morton's key into 3 integer(I1P) indexes.
Parameters
[in] key Morton's key.
[in,out] i I index.
[in,out] j J index.
[in,out] k K index.
[in] b Number of significant bits of 'i' (2/4/8).
Definition at line 463 of file Lib_Morton.f90.
elemental subroutine lib_morton::demorton3::demorton3_i2p (integer(i8p), intent(in) key, integer(i2p), intent(inout) i, integer(i2p), intent(inout) j, integer(i2p), intent(inout) k, integer(i2p), intent(in), optional b) private
Subroutine for decoding 1 integer(I8P) Morton's key into 3 integer(I2P) indexes.
Parameters
[in] key Morton's key.
[in,out] i I index.
[in,out] j J index.
[in,out] k K index.
[in] b Number of significant bits of 'i' (2/4/8/16).
Definition at line 494 of file Lib_Morton.f90.