OFF: Data_Type_HashTCell
Data_Type_HashTCell
Private Procedures
recursive subroutine data_type_hashtcell::put_sll (list, ID, d)
Recursive subroutine for inserting a link data into the list.
recursive subroutine data_type_hashtcell::get_sll (list, ID, d)
Recursive subroutine for getting a link data from the list.
recursive subroutine data_type_hashtcell::free_sll (list)
Recursive subroutine for freeing (destroyng) the list.
elemental subroutine data_type_hashtcell::init_hasht (htable, leng)
Subroutine for initializing the hash table.
subroutine data_type_hashtcell::put_hasht (htable, ID, d)
Subroutine for inserting a link data into the hash table.
subroutine data_type_hashtcell::get_hasht (htable, ID, d)
Subroutine for getting a link data from hash table.
subroutine data_type_hashtcell::free_hasht (htable)
Subroutine for freeing (destroyng) the hash table.
Detailed Description
Function/Subroutine Documentation
recursive subroutine data_type_hashtcell::put_sll (class(type_sll), intent(inout) list, type(type_hashid), intent(in) ID, type(type_cell), intent(in) d)
Recursive subroutine for inserting a link data into the list.
Parameters
[in,out] list Single linked list.
[in] id ID (unique) of the current link.
[in] d Data of the current link.
Definition at line 67 of file Data_Type_HashTCell.f90.
Referenced by data_type_hashtface::put_sll(), and data_type_hashtnode::put_sll().
recursive subroutine data_type_hashtcell::get_sll (class(type_sll), intent(in) list, type(type_hashid), intent(in) ID, type(type_cell), intent(out), allocatable d) private
Recursive subroutine for getting a link data from the list.
Parameters
[in] list Single linked list.
[in] id ID (unique) of the current link.
[out] d Data of the current link.
Definition at line 90 of file Data_Type_HashTCell.f90.
Referenced by data_type_hashtface::get_sll(), and data_type_hashtnode::get_sll().
recursive subroutine data_type_hashtcell::free_sll (class(type_sll), intent(inout) list) private
Recursive subroutine for freeing (destroyng) the list.
Parameters
[in,out] list Single linked list.
Definition at line 111 of file Data_Type_HashTCell.f90.
Referenced by data_type_hashtface::free_sll(), and data_type_hashtnode::free_sll().
elemental subroutine data_type_hashtcell::init_hasht (class(type_hashtcell), intent(inout) htable, integer(i4p), intent(in), optional leng) private
Subroutine for initializing the hash table.
Parameters
[in,out] htable Hash table.
[in] leng Lenght of the hash table.
Definition at line 130 of file Data_Type_HashTCell.f90.
References data_type_hashid::ht_def_leng, and data_type_sl_list::type_sl_link::leng().
subroutine data_type_hashtcell::put_hasht (class(type_hashtcell), intent(inout) htable, type(type_hashid), intent(in) ID, type(type_cell), intent(in) d) private
Subroutine for inserting a link data into the hash table.
Parameters
[in,out] htable Hash table.
[in] id ID (unique) of the current link.
[in] d Data of the current link.
Definition at line 150 of file Data_Type_HashTCell.f90.
subroutine data_type_hashtcell::get_hasht (class(type_hashtcell), intent(in) htable, type(type_hashid), intent(in) ID, type(type_cell), intent(out), allocatable d) private
Subroutine for getting a link data from hash table.
Parameters
[in] htable Hash table.
[in] id ID (unique) of the current link.
[out] d Data of the current link.
Definition at line 167 of file Data_Type_HashTCell.f90.
subroutine data_type_hashtcell::free_hasht (class(type_hashtcell), intent(inout) htable) private
Subroutine for freeing (destroyng) the hash table.
Parameters
[in,out] htable Hash table.
Definition at line 184 of file Data_Type_HashTCell.f90.