OFF: Data_Type_Conservative
Data_Type_Conservative
Derived Types
Data Types
type data_type_conservative::type_conservative
Derived type containing conservative variables.
Detailed Description
Data Type Documentation
type data_type_conservative::type_conservative
Derived type containing conservative variables.
Note
This derived type can represent multi species fluids. The density component, rs, is a dynamic memory component defined as an allocatable 1D array. rs is allocated at runtime with the number of initial species that constitute the initial fluid mixture. Due to the presence of a dynamic component a freeing memory "method" for this component is necessary. Before deallocate a variable defined as Type_Conservative the free function must be invoked to free the memory of the dynamic component.
Definition at line 57 of file Data_Type_Conservative.f90.
Public Member Functions
procedure, non_overridable init
procedure, non_overridable free => free_cons
procedure, non_overridable cons2array
procedure, non_overridable array2cons
procedure, non_overridable pprint
Public Attributes
real(r8p), dimension(:),
allocatable rs
Density of single species [1:Ns].
type(type_vector) rv
Momentum vector.
real(r8p) re = 0._R8P
Product of density for specific total internal energy (sum(r)*E).
Member Function/Subroutine Documentation
procedure, non_overridable data_type_conservative::type_conservative::init ()
Definition at line 62 of file Data_Type_Conservative.f90.
References pprint().
procedure, non_overridable data_type_conservative::type_conservative::free ()
Definition at line 63 of file Data_Type_Conservative.f90.
procedure, non_overridable data_type_conservative::type_conservative::cons2array ()
Definition at line 64 of file Data_Type_Conservative.f90.
procedure, non_overridable data_type_conservative::type_conservative::array2cons ()
Definition at line 65 of file Data_Type_Conservative.f90.
procedure, non_overridable data_type_conservative::type_conservative::pprint ()
Definition at line 66 of file Data_Type_Conservative.f90.
References data_type_conservative::assignment(=)::assign_cons(), and data_type_vector::assign_scalr16p().
Referenced by init(), and data_type_primitive::type_primitive::init().
Member Data Documentation
real(r8p), dimension(:), allocatable data_type_conservative::type_conservative::rs
Density of single species [1:Ns].
Definition at line 58 of file Data_Type_Conservative.f90.
type(type_vector) data_type_conservative::type_conservative::rv
Momentum vector.
Definition at line 59 of file Data_Type_Conservative.f90.
real(r8p) data_type_conservative::type_conservative::re = 0._R8P
Product of density for specific total internal energy (sum(r)*E).
Definition at line 60 of file Data_Type_Conservative.f90.