OFF: Lib_VTK_IO
Lib_VTK_IO
Private Variables and Parameters
integer(i4p), parameter lib_vtk_io::maxlen = 500
Max number of characters of static string.
character(1), parameter lib_vtk_io::end_rec = char(10)
End-character for binary-record finalize.
integer(i4p), parameter lib_vtk_io::ascii = 0
Ascii-output-format parameter identifier.
integer(i4p), parameter lib_vtk_io::binary = 1
Base64-output-format parameter identifier.
integer(i4p), parameter lib_vtk_io::raw = 2
Raw-appended-binary-output-format parameter identifier.
integer(i4p), parameter lib_vtk_io::bin_app = 3
Base64-appended-output-format parameter identifier.
type(type_vtk_file), dimension(:),
allocatable lib_vtk_io::vtk
Global data of VTK files [1:Nvtk].
integer(i4p) lib_vtk_io::nvtk = 0_I4P
Number of (concurrent) VTK files.
integer(i4p) lib_vtk_io::f = 0_I4P
Current VTK file index.
type(type_vtm_file) lib_vtk_io::vtm
Global data of VTM files.
Detailed Description
Variable Documentation
integer(i4p), parameter lib_vtk_io::maxlen = 500 private
Max number of characters of static string.
Definition at line 443 of file Lib_VTK_IO.f90.
character(1), parameter lib_vtk_io::end_rec = char(10) private
End-character for binary-record finalize.
Definition at line 444 of file Lib_VTK_IO.f90.
Referenced by lib_vtk_io::vtk_con(), lib_vtk_io::vtk_con_xml(), lib_vtk_io::vtk_dat(), lib_vtk_io::vtk_dat_xml(), lib_vtk_io::vtk_end_xml(), lib_vtk_io::vtk_fld_xml_i1(), lib_vtk_io::vtk_fld_xml_i2(), lib_vtk_io::vtk_fld_xml_i4(), lib_vtk_io::vtk_fld_xml_i8(), lib_vtk_io::vtk_fld_xml_oc(), lib_vtk_io::vtk_fld_xml_r4(), lib_vtk_io::vtk_fld_xml_r8(), lib_vtk_io::vtk_geo_rect_r4(), lib_vtk_io::vtk_geo_rect_r8(), lib_vtk_io::vtk_geo_strg_1da_r4(), lib_vtk_io::vtk_geo_strg_1da_r8(), lib_vtk_io::vtk_geo_strg_1dap_r4(), lib_vtk_io::vtk_geo_strg_1dap_r8(), lib_vtk_io::vtk_geo_strg_3da_r4(), lib_vtk_io::vtk_geo_strg_3da_r8(), lib_vtk_io::vtk_geo_strg_3dap_r4(), lib_vtk_io::vtk_geo_strg_3dap_r8(), lib_vtk_io::vtk_geo_strp_r4(), lib_vtk_io::vtk_geo_strp_r8(), lib_vtk_io::vtk_geo_unst_p_r4(), lib_vtk_io::vtk_geo_unst_p_r8(), lib_vtk_io::vtk_geo_unst_r4(), lib_vtk_io::vtk_geo_unst_r8(), lib_vtk_io::vtk_geo_xml_closep(), lib_vtk_io::vtk_geo_xml_rect_r4(), lib_vtk_io::vtk_geo_xml_rect_r8(), lib_vtk_io::vtk_geo_xml_strg_1da_r4(), lib_vtk_io::vtk_geo_xml_strg_1da_r8(), lib_vtk_io::vtk_geo_xml_strg_1dap_r4(), lib_vtk_io::vtk_geo_xml_strg_1dap_r8(), lib_vtk_io::vtk_geo_xml_strg_3da_r4(), lib_vtk_io::vtk_geo_xml_strg_3da_r8(), lib_vtk_io::vtk_geo_xml_strg_3dap_r4(), lib_vtk_io::vtk_geo_xml_strg_3dap_r8(), lib_vtk_io::vtk_geo_xml_unst_pack_r4(), lib_vtk_io::vtk_geo_xml_unst_pack_r8(), lib_vtk_io::vtk_geo_xml_unst_r4(), lib_vtk_io::vtk_geo_xml_unst_r8(), lib_vtk_io::vtk_ini(), lib_vtk_io::vtk_ini_xml(), lib_vtk_io::vtk_var_scal_i4(), lib_vtk_io::vtk_var_scal_r4(), lib_vtk_io::vtk_var_scal_r8(), lib_vtk_io::vtk_var_text_r4(), lib_vtk_io::vtk_var_text_r8(), lib_vtk_io::vtk_var_vect_i4(), lib_vtk_io::vtk_var_vect_r4(), lib_vtk_io::vtk_var_vect_r8(), lib_vtk_io::vtk_var_xml_list_1da_i1(), lib_vtk_io::vtk_var_xml_list_1da_i2(), lib_vtk_io::vtk_var_xml_list_1da_i4(), lib_vtk_io::vtk_var_xml_list_1da_i8(), lib_vtk_io::vtk_var_xml_list_1da_r4(), lib_vtk_io::vtk_var_xml_list_1da_r8(), lib_vtk_io::vtk_var_xml_list_3da_i1(), lib_vtk_io::vtk_var_xml_list_3da_i2(), lib_vtk_io::vtk_var_xml_list_3da_i4(), lib_vtk_io::vtk_var_xml_list_3da_i8(), lib_vtk_io::vtk_var_xml_list_3da_r4(), lib_vtk_io::vtk_var_xml_list_3da_r8(), lib_vtk_io::vtk_var_xml_scal_1da_i1(), lib_vtk_io::vtk_var_xml_scal_1da_i2(), lib_vtk_io::vtk_var_xml_scal_1da_i4(), lib_vtk_io::vtk_var_xml_scal_1da_i8(), lib_vtk_io::vtk_var_xml_scal_1da_r4(), lib_vtk_io::vtk_var_xml_scal_1da_r8(), lib_vtk_io::vtk_var_xml_scal_3da_i1(), lib_vtk_io::vtk_var_xml_scal_3da_i2(), lib_vtk_io::vtk_var_xml_scal_3da_i4(), lib_vtk_io::vtk_var_xml_scal_3da_i8(), lib_vtk_io::vtk_var_xml_scal_3da_r4(), lib_vtk_io::vtk_var_xml_scal_3da_r8(), lib_vtk_io::vtk_var_xml_vect_1da_i1(), lib_vtk_io::vtk_var_xml_vect_1da_i2(), lib_vtk_io::vtk_var_xml_vect_1da_i4(), lib_vtk_io::vtk_var_xml_vect_1da_i8(), lib_vtk_io::vtk_var_xml_vect_1da_r4(), lib_vtk_io::vtk_var_xml_vect_1da_r8(), lib_vtk_io::vtk_var_xml_vect_3da_i1(), lib_vtk_io::vtk_var_xml_vect_3da_i2(), lib_vtk_io::vtk_var_xml_vect_3da_i4(), lib_vtk_io::vtk_var_xml_vect_3da_i8(), lib_vtk_io::vtk_var_xml_vect_3da_r4(), and lib_vtk_io::vtk_var_xml_vect_3da_r8().
integer(i4p), parameter lib_vtk_io::ascii = 0 private
Ascii-output-format parameter identifier.
Definition at line 445 of file Lib_VTK_IO.f90.
Referenced by data_type_amrblock::load_basemesh_dims(), data_type_sblock::load_bmesh(), data_type_sblock::load_bmesh_dims(), data_type_sblock::save_bmesh(), lib_vtk_io::vtk_con(), lib_vtk_io::vtk_con_xml(), lib_vtk_io::vtk_dat(), lib_vtk_io::vtk_dat_xml(), lib_vtk_io::vtk_end_xml(), lib_vtk_io::vtk_fld_xml_i1(), lib_vtk_io::vtk_fld_xml_i2(), lib_vtk_io::vtk_fld_xml_i4(), lib_vtk_io::vtk_fld_xml_i8(), lib_vtk_io::vtk_fld_xml_oc(), lib_vtk_io::vtk_fld_xml_r4(), lib_vtk_io::vtk_fld_xml_r8(), lib_vtk_io::vtk_geo_rect_r4(), lib_vtk_io::vtk_geo_rect_r8(), lib_vtk_io::vtk_geo_strg_1da_r4(), lib_vtk_io::vtk_geo_strg_1da_r8(), lib_vtk_io::vtk_geo_strg_1dap_r4(), lib_vtk_io::vtk_geo_strg_1dap_r8(), lib_vtk_io::vtk_geo_strg_3da_r4(), lib_vtk_io::vtk_geo_strg_3da_r8(), lib_vtk_io::vtk_geo_strg_3dap_r4(), lib_vtk_io::vtk_geo_strg_3dap_r8(), lib_vtk_io::vtk_geo_strp_r4(), lib_vtk_io::vtk_geo_strp_r8(), lib_vtk_io::vtk_geo_unst_p_r4(), lib_vtk_io::vtk_geo_unst_p_r8(), lib_vtk_io::vtk_geo_unst_r4(), lib_vtk_io::vtk_geo_unst_r8(), lib_vtk_io::vtk_geo_xml_closep(), lib_vtk_io::vtk_geo_xml_rect_r4(), lib_vtk_io::vtk_geo_xml_rect_r8(), lib_vtk_io::vtk_geo_xml_strg_1da_r4(), lib_vtk_io::vtk_geo_xml_strg_1da_r8(), lib_vtk_io::vtk_geo_xml_strg_1dap_r4(), lib_vtk_io::vtk_geo_xml_strg_1dap_r8(), lib_vtk_io::vtk_geo_xml_strg_3da_r4(), lib_vtk_io::vtk_geo_xml_strg_3da_r8(), lib_vtk_io::vtk_geo_xml_strg_3dap_r4(), lib_vtk_io::vtk_geo_xml_strg_3dap_r8(), lib_vtk_io::vtk_geo_xml_unst_pack_r4(), lib_vtk_io::vtk_geo_xml_unst_pack_r8(), lib_vtk_io::vtk_geo_xml_unst_r4(), lib_vtk_io::vtk_geo_xml_unst_r8(), lib_vtk_io::vtk_ini(), lib_vtk_io::vtk_ini_xml(), lib_vtk_io::vtk_var_scal_i4(), lib_vtk_io::vtk_var_scal_r4(), lib_vtk_io::vtk_var_scal_r8(), lib_vtk_io::vtk_var_text_r4(), lib_vtk_io::vtk_var_text_r8(), lib_vtk_io::vtk_var_vect_i4(), lib_vtk_io::vtk_var_vect_r4(), lib_vtk_io::vtk_var_vect_r8(), lib_vtk_io::vtk_var_xml_list_1da_i1(), lib_vtk_io::vtk_var_xml_list_1da_i2(), lib_vtk_io::vtk_var_xml_list_1da_i4(), lib_vtk_io::vtk_var_xml_list_1da_i8(), lib_vtk_io::vtk_var_xml_list_1da_r4(), lib_vtk_io::vtk_var_xml_list_1da_r8(), lib_vtk_io::vtk_var_xml_list_3da_i1(), lib_vtk_io::vtk_var_xml_list_3da_i2(), lib_vtk_io::vtk_var_xml_list_3da_i4(), lib_vtk_io::vtk_var_xml_list_3da_i8(), lib_vtk_io::vtk_var_xml_list_3da_r4(), lib_vtk_io::vtk_var_xml_list_3da_r8(), lib_vtk_io::vtk_var_xml_scal_1da_i1(), lib_vtk_io::vtk_var_xml_scal_1da_i2(), lib_vtk_io::vtk_var_xml_scal_1da_i4(), lib_vtk_io::vtk_var_xml_scal_1da_i8(), lib_vtk_io::vtk_var_xml_scal_1da_r4(), lib_vtk_io::vtk_var_xml_scal_1da_r8(), lib_vtk_io::vtk_var_xml_scal_3da_i1(), lib_vtk_io::vtk_var_xml_scal_3da_i2(), lib_vtk_io::vtk_var_xml_scal_3da_i4(), lib_vtk_io::vtk_var_xml_scal_3da_i8(), lib_vtk_io::vtk_var_xml_scal_3da_r4(), lib_vtk_io::vtk_var_xml_scal_3da_r8(), lib_vtk_io::vtk_var_xml_vect_1da_i1(), lib_vtk_io::vtk_var_xml_vect_1da_i2(), lib_vtk_io::vtk_var_xml_vect_1da_i4(), lib_vtk_io::vtk_var_xml_vect_1da_i8(), lib_vtk_io::vtk_var_xml_vect_1da_r4(), lib_vtk_io::vtk_var_xml_vect_1da_r8(), lib_vtk_io::vtk_var_xml_vect_3da_i1(), lib_vtk_io::vtk_var_xml_vect_3da_i2(), lib_vtk_io::vtk_var_xml_vect_3da_i4(), lib_vtk_io::vtk_var_xml_vect_3da_i8(), lib_vtk_io::vtk_var_xml_vect_3da_r4(), and lib_vtk_io::vtk_var_xml_vect_3da_r8().
integer(i4p), parameter lib_vtk_io::binary = 1 private
Base64-output-format parameter identifier.
Definition at line 446 of file Lib_VTK_IO.f90.
Referenced by data_type_global::load_gfluid_ns(), off_init(), pog(), lib_vtk_io::vtk_con_xml(), lib_vtk_io::vtk_dat_xml(), lib_vtk_io::vtk_end_xml(), lib_vtk_io::vtk_fld_xml_i1(), lib_vtk_io::vtk_fld_xml_i2(), lib_vtk_io::vtk_fld_xml_i4(), lib_vtk_io::vtk_fld_xml_i8(), lib_vtk_io::vtk_fld_xml_oc(), lib_vtk_io::vtk_fld_xml_r4(), lib_vtk_io::vtk_fld_xml_r8(), lib_vtk_io::vtk_geo_xml_closep(), lib_vtk_io::vtk_geo_xml_rect_r4(), lib_vtk_io::vtk_geo_xml_rect_r8(), lib_vtk_io::vtk_geo_xml_strg_1da_r4(), lib_vtk_io::vtk_geo_xml_strg_1da_r8(), lib_vtk_io::vtk_geo_xml_strg_1dap_r4(), lib_vtk_io::vtk_geo_xml_strg_1dap_r8(), lib_vtk_io::vtk_geo_xml_strg_3da_r4(), lib_vtk_io::vtk_geo_xml_strg_3da_r8(), lib_vtk_io::vtk_geo_xml_strg_3dap_r4(), lib_vtk_io::vtk_geo_xml_strg_3dap_r8(), lib_vtk_io::vtk_geo_xml_unst_pack_r4(), lib_vtk_io::vtk_geo_xml_unst_pack_r8(), lib_vtk_io::vtk_geo_xml_unst_r4(), lib_vtk_io::vtk_geo_xml_unst_r8(), lib_vtk_io::vtk_ini_xml(), lib_vtk_io::vtk_var_xml_list_1da_i1(), lib_vtk_io::vtk_var_xml_list_1da_i2(), lib_vtk_io::vtk_var_xml_list_1da_i4(), lib_vtk_io::vtk_var_xml_list_1da_i8(), lib_vtk_io::vtk_var_xml_list_1da_r4(), lib_vtk_io::vtk_var_xml_list_1da_r8(), lib_vtk_io::vtk_var_xml_list_3da_i1(), lib_vtk_io::vtk_var_xml_list_3da_i2(), lib_vtk_io::vtk_var_xml_list_3da_i4(), lib_vtk_io::vtk_var_xml_list_3da_i8(), lib_vtk_io::vtk_var_xml_list_3da_r4(), lib_vtk_io::vtk_var_xml_list_3da_r8(), lib_vtk_io::vtk_var_xml_scal_1da_i1(), lib_vtk_io::vtk_var_xml_scal_1da_i2(), lib_vtk_io::vtk_var_xml_scal_1da_i4(), lib_vtk_io::vtk_var_xml_scal_1da_i8(), lib_vtk_io::vtk_var_xml_scal_1da_r4(), lib_vtk_io::vtk_var_xml_scal_1da_r8(), lib_vtk_io::vtk_var_xml_scal_3da_i1(), lib_vtk_io::vtk_var_xml_scal_3da_i2(), lib_vtk_io::vtk_var_xml_scal_3da_i4(), lib_vtk_io::vtk_var_xml_scal_3da_i8(), lib_vtk_io::vtk_var_xml_scal_3da_r4(), lib_vtk_io::vtk_var_xml_scal_3da_r8(), lib_vtk_io::vtk_var_xml_vect_1da_i1(), lib_vtk_io::vtk_var_xml_vect_1da_i2(), lib_vtk_io::vtk_var_xml_vect_1da_i4(), lib_vtk_io::vtk_var_xml_vect_1da_i8(), lib_vtk_io::vtk_var_xml_vect_1da_r4(), lib_vtk_io::vtk_var_xml_vect_1da_r8(), lib_vtk_io::vtk_var_xml_vect_3da_i1(), lib_vtk_io::vtk_var_xml_vect_3da_i2(), lib_vtk_io::vtk_var_xml_vect_3da_i4(), lib_vtk_io::vtk_var_xml_vect_3da_i8(), lib_vtk_io::vtk_var_xml_vect_3da_r4(), and lib_vtk_io::vtk_var_xml_vect_3da_r8().
integer(i4p), parameter lib_vtk_io::raw = 2 private
Raw-appended-binary-output-format parameter identifier.
Definition at line 447 of file Lib_VTK_IO.f90.
Referenced by lib_vtk_io::byte_update(), lib_vtk_io::vtk_con(), lib_vtk_io::vtk_con_xml(), lib_vtk_io::vtk_dat(), lib_vtk_io::vtk_dat_xml(), lib_vtk_io::vtk_end_xml(), lib_vtk_io::vtk_fld_xml_i1(), lib_vtk_io::vtk_fld_xml_i2(), lib_vtk_io::vtk_fld_xml_i4(), lib_vtk_io::vtk_fld_xml_i8(), lib_vtk_io::vtk_fld_xml_oc(), lib_vtk_io::vtk_fld_xml_r4(), lib_vtk_io::vtk_fld_xml_r8(), lib_vtk_io::vtk_geo_rect_r4(), lib_vtk_io::vtk_geo_rect_r8(), lib_vtk_io::vtk_geo_strg_1da_r4(), lib_vtk_io::vtk_geo_strg_1da_r8(), lib_vtk_io::vtk_geo_strg_1dap_r4(), lib_vtk_io::vtk_geo_strg_1dap_r8(), lib_vtk_io::vtk_geo_strg_3da_r4(), lib_vtk_io::vtk_geo_strg_3da_r8(), lib_vtk_io::vtk_geo_strg_3dap_r4(), lib_vtk_io::vtk_geo_strg_3dap_r8(), lib_vtk_io::vtk_geo_strp_r4(), lib_vtk_io::vtk_geo_strp_r8(), lib_vtk_io::vtk_geo_unst_p_r4(), lib_vtk_io::vtk_geo_unst_p_r8(), lib_vtk_io::vtk_geo_unst_r4(), lib_vtk_io::vtk_geo_unst_r8(), lib_vtk_io::vtk_geo_xml_closep(), lib_vtk_io::vtk_geo_xml_rect_r4(), lib_vtk_io::vtk_geo_xml_rect_r8(), lib_vtk_io::vtk_geo_xml_strg_1da_r4(), lib_vtk_io::vtk_geo_xml_strg_1da_r8(), lib_vtk_io::vtk_geo_xml_strg_1dap_r4(), lib_vtk_io::vtk_geo_xml_strg_1dap_r8(), lib_vtk_io::vtk_geo_xml_strg_3da_r4(), lib_vtk_io::vtk_geo_xml_strg_3da_r8(), lib_vtk_io::vtk_geo_xml_strg_3dap_r4(), lib_vtk_io::vtk_geo_xml_strg_3dap_r8(), lib_vtk_io::vtk_geo_xml_unst_pack_r4(), lib_vtk_io::vtk_geo_xml_unst_pack_r8(), lib_vtk_io::vtk_geo_xml_unst_r4(), lib_vtk_io::vtk_geo_xml_unst_r8(), lib_vtk_io::vtk_ini(), lib_vtk_io::vtk_ini_xml(), lib_vtk_io::vtk_var_scal_i4(), lib_vtk_io::vtk_var_scal_r4(), lib_vtk_io::vtk_var_scal_r8(), lib_vtk_io::vtk_var_text_r4(), lib_vtk_io::vtk_var_text_r8(), lib_vtk_io::vtk_var_vect_i4(), lib_vtk_io::vtk_var_vect_r4(), lib_vtk_io::vtk_var_vect_r8(), lib_vtk_io::vtk_var_xml_list_1da_i1(), lib_vtk_io::vtk_var_xml_list_1da_i2(), lib_vtk_io::vtk_var_xml_list_1da_i4(), lib_vtk_io::vtk_var_xml_list_1da_i8(), lib_vtk_io::vtk_var_xml_list_1da_r4(), lib_vtk_io::vtk_var_xml_list_1da_r8(), lib_vtk_io::vtk_var_xml_list_3da_i1(), lib_vtk_io::vtk_var_xml_list_3da_i2(), lib_vtk_io::vtk_var_xml_list_3da_i4(), lib_vtk_io::vtk_var_xml_list_3da_i8(), lib_vtk_io::vtk_var_xml_list_3da_r4(), lib_vtk_io::vtk_var_xml_list_3da_r8(), lib_vtk_io::vtk_var_xml_scal_1da_i1(), lib_vtk_io::vtk_var_xml_scal_1da_i2(), lib_vtk_io::vtk_var_xml_scal_1da_i4(), lib_vtk_io::vtk_var_xml_scal_1da_i8(), lib_vtk_io::vtk_var_xml_scal_1da_r4(), lib_vtk_io::vtk_var_xml_scal_1da_r8(), lib_vtk_io::vtk_var_xml_scal_3da_i1(), lib_vtk_io::vtk_var_xml_scal_3da_i2(), lib_vtk_io::vtk_var_xml_scal_3da_i4(), lib_vtk_io::vtk_var_xml_scal_3da_i8(), lib_vtk_io::vtk_var_xml_scal_3da_r4(), lib_vtk_io::vtk_var_xml_scal_3da_r8(), lib_vtk_io::vtk_var_xml_vect_1da_i1(), lib_vtk_io::vtk_var_xml_vect_1da_i2(), lib_vtk_io::vtk_var_xml_vect_1da_i4(), lib_vtk_io::vtk_var_xml_vect_1da_i8(), lib_vtk_io::vtk_var_xml_vect_1da_r4(), lib_vtk_io::vtk_var_xml_vect_1da_r8(), lib_vtk_io::vtk_var_xml_vect_3da_i1(), lib_vtk_io::vtk_var_xml_vect_3da_i2(), lib_vtk_io::vtk_var_xml_vect_3da_i4(), lib_vtk_io::vtk_var_xml_vect_3da_i8(), lib_vtk_io::vtk_var_xml_vect_3da_r4(), and lib_vtk_io::vtk_var_xml_vect_3da_r8().
integer(i4p), parameter lib_vtk_io::bin_app = 3 private
Base64-appended-output-format parameter identifier.
Definition at line 448 of file Lib_VTK_IO.f90.
Referenced by lib_vtk_io::vtk_con_xml(), lib_vtk_io::vtk_dat_xml(), lib_vtk_io::vtk_end_xml(), lib_vtk_io::vtk_fld_xml_i1(), lib_vtk_io::vtk_fld_xml_i2(), lib_vtk_io::vtk_fld_xml_i4(), lib_vtk_io::vtk_fld_xml_i8(), lib_vtk_io::vtk_fld_xml_oc(), lib_vtk_io::vtk_fld_xml_r4(), lib_vtk_io::vtk_fld_xml_r8(), lib_vtk_io::vtk_geo_xml_closep(), lib_vtk_io::vtk_geo_xml_rect_r4(), lib_vtk_io::vtk_geo_xml_rect_r8(), lib_vtk_io::vtk_geo_xml_strg_1da_r4(), lib_vtk_io::vtk_geo_xml_strg_1da_r8(), lib_vtk_io::vtk_geo_xml_strg_1dap_r4(), lib_vtk_io::vtk_geo_xml_strg_1dap_r8(), lib_vtk_io::vtk_geo_xml_strg_3da_r4(), lib_vtk_io::vtk_geo_xml_strg_3da_r8(), lib_vtk_io::vtk_geo_xml_strg_3dap_r4(), lib_vtk_io::vtk_geo_xml_strg_3dap_r8(), lib_vtk_io::vtk_geo_xml_unst_pack_r4(), lib_vtk_io::vtk_geo_xml_unst_pack_r8(), lib_vtk_io::vtk_geo_xml_unst_r4(), lib_vtk_io::vtk_geo_xml_unst_r8(), lib_vtk_io::vtk_ini_xml(), lib_vtk_io::vtk_var_xml_list_1da_i1(), lib_vtk_io::vtk_var_xml_list_1da_i2(), lib_vtk_io::vtk_var_xml_list_1da_i4(), lib_vtk_io::vtk_var_xml_list_1da_i8(), lib_vtk_io::vtk_var_xml_list_1da_r4(), lib_vtk_io::vtk_var_xml_list_1da_r8(), lib_vtk_io::vtk_var_xml_list_3da_i1(), lib_vtk_io::vtk_var_xml_list_3da_i2(), lib_vtk_io::vtk_var_xml_list_3da_i4(), lib_vtk_io::vtk_var_xml_list_3da_i8(), lib_vtk_io::vtk_var_xml_list_3da_r4(), lib_vtk_io::vtk_var_xml_list_3da_r8(), lib_vtk_io::vtk_var_xml_scal_1da_i1(), lib_vtk_io::vtk_var_xml_scal_1da_i2(), lib_vtk_io::vtk_var_xml_scal_1da_i4(), lib_vtk_io::vtk_var_xml_scal_1da_i8(), lib_vtk_io::vtk_var_xml_scal_1da_r4(), lib_vtk_io::vtk_var_xml_scal_1da_r8(), lib_vtk_io::vtk_var_xml_scal_3da_i1(), lib_vtk_io::vtk_var_xml_scal_3da_i2(), lib_vtk_io::vtk_var_xml_scal_3da_i4(), lib_vtk_io::vtk_var_xml_scal_3da_i8(), lib_vtk_io::vtk_var_xml_scal_3da_r4(), lib_vtk_io::vtk_var_xml_scal_3da_r8(), lib_vtk_io::vtk_var_xml_vect_1da_i1(), lib_vtk_io::vtk_var_xml_vect_1da_i2(), lib_vtk_io::vtk_var_xml_vect_1da_i4(), lib_vtk_io::vtk_var_xml_vect_1da_i8(), lib_vtk_io::vtk_var_xml_vect_1da_r4(), lib_vtk_io::vtk_var_xml_vect_1da_r8(), lib_vtk_io::vtk_var_xml_vect_3da_i1(), lib_vtk_io::vtk_var_xml_vect_3da_i2(), lib_vtk_io::vtk_var_xml_vect_3da_i4(), lib_vtk_io::vtk_var_xml_vect_3da_i8(), lib_vtk_io::vtk_var_xml_vect_3da_r4(), and lib_vtk_io::vtk_var_xml_vect_3da_r8().
type(type_vtk_file), dimension(:), allocatable lib_vtk_io::vtk private
Global data of VTK files [1:Nvtk].
Definition at line 465 of file Lib_VTK_IO.f90.
integer(i4p) lib_vtk_io::nvtk = 0_I4P private
Number of (concurrent) VTK files.
Definition at line 466 of file Lib_VTK_IO.f90.
integer(i4p) lib_vtk_io::f = 0_I4P private
Current VTK file index.
Definition at line 467 of file Lib_VTK_IO.f90.
Referenced by lib_fluidynamic::boundary_conditions(), lib_fluxes_diffusive::fluxes_diffusive(), load_blocks(), load_icemcfd(), load_option_file(), lib_weno::noweno_central(), preconstruct_n(), lib_vtk_io::pvtk_dat_xml(), lib_vtk_io::pvtk_end_xml(), lib_vtk_io::pvtk_geo_xml(), lib_vtk_io::pvtk_ini_xml(), lib_vtk_io::pvtk_var_xml(), lib_fluidynamic::residuals(), lib_fluidynamic::rk_stages_sum(), rp(), lib_fluidynamic::set_bc(), set_ext_l(), set_in1(), lib_vtk_io::vtk_con(), lib_vtk_io::vtk_con_xml(), lib_vtk_io::vtk_dat(), lib_vtk_io::vtk_dat_xml(), lib_vtk_io::vtk_end(), lib_vtk_io::vtk_end_xml(), lib_vtk_io::vtk_fld_xml_i1(), lib_vtk_io::vtk_fld_xml_i2(), lib_vtk_io::vtk_fld_xml_i4(), lib_vtk_io::vtk_fld_xml_i8(), lib_vtk_io::vtk_fld_xml_oc(), lib_vtk_io::vtk_fld_xml_r4(), lib_vtk_io::vtk_fld_xml_r8(), lib_vtk_io::vtk_geo_rect_r4(), lib_vtk_io::vtk_geo_rect_r8(), lib_vtk_io::vtk_geo_strg_1da_r4(), lib_vtk_io::vtk_geo_strg_1da_r8(), lib_vtk_io::vtk_geo_strg_1dap_r4(), lib_vtk_io::vtk_geo_strg_1dap_r8(), lib_vtk_io::vtk_geo_strg_3da_r4(), lib_vtk_io::vtk_geo_strg_3da_r8(), lib_vtk_io::vtk_geo_strg_3dap_r4(), lib_vtk_io::vtk_geo_strg_3dap_r8(), lib_vtk_io::vtk_geo_strp_r4(), lib_vtk_io::vtk_geo_strp_r8(), lib_vtk_io::vtk_geo_unst_p_r4(), lib_vtk_io::vtk_geo_unst_p_r8(), lib_vtk_io::vtk_geo_unst_r4(), lib_vtk_io::vtk_geo_unst_r8(), lib_vtk_io::vtk_geo_xml_closep(), lib_vtk_io::vtk_geo_xml_rect_r4(), lib_vtk_io::vtk_geo_xml_rect_r8(), lib_vtk_io::vtk_geo_xml_strg_1da_r4(), lib_vtk_io::vtk_geo_xml_strg_1da_r8(), lib_vtk_io::vtk_geo_xml_strg_1dap_r4(), lib_vtk_io::vtk_geo_xml_strg_1dap_r8(), lib_vtk_io::vtk_geo_xml_strg_3da_r4(), lib_vtk_io::vtk_geo_xml_strg_3da_r8(), lib_vtk_io::vtk_geo_xml_strg_3dap_r4(), lib_vtk_io::vtk_geo_xml_strg_3dap_r8(), lib_vtk_io::vtk_geo_xml_unst_pack_r4(), lib_vtk_io::vtk_geo_xml_unst_pack_r8(), lib_vtk_io::vtk_geo_xml_unst_r4(), lib_vtk_io::vtk_geo_xml_unst_r8(), lib_vtk_io::vtk_ini(), lib_vtk_io::vtk_ini_xml(), lib_vtk_io::vtk_var_scal_i4(), lib_vtk_io::vtk_var_scal_r4(), lib_vtk_io::vtk_var_scal_r8(), lib_vtk_io::vtk_var_text_r4(), lib_vtk_io::vtk_var_text_r8(), lib_vtk_io::vtk_var_vect_i4(), lib_vtk_io::vtk_var_vect_r4(), lib_vtk_io::vtk_var_vect_r8(), lib_vtk_io::vtk_var_xml_list_1da_i1(), lib_vtk_io::vtk_var_xml_list_1da_i2(), lib_vtk_io::vtk_var_xml_list_1da_i4(), lib_vtk_io::vtk_var_xml_list_1da_i8(), lib_vtk_io::vtk_var_xml_list_1da_r4(), lib_vtk_io::vtk_var_xml_list_1da_r8(), lib_vtk_io::vtk_var_xml_list_3da_i1(), lib_vtk_io::vtk_var_xml_list_3da_i2(), lib_vtk_io::vtk_var_xml_list_3da_i4(), lib_vtk_io::vtk_var_xml_list_3da_i8(), lib_vtk_io::vtk_var_xml_list_3da_r4(), lib_vtk_io::vtk_var_xml_list_3da_r8(), lib_vtk_io::vtk_var_xml_scal_1da_i1(), lib_vtk_io::vtk_var_xml_scal_1da_i2(), lib_vtk_io::vtk_var_xml_scal_1da_i4(), lib_vtk_io::vtk_var_xml_scal_1da_i8(), lib_vtk_io::vtk_var_xml_scal_1da_r4(), lib_vtk_io::vtk_var_xml_scal_1da_r8(), lib_vtk_io::vtk_var_xml_scal_3da_i1(), lib_vtk_io::vtk_var_xml_scal_3da_i2(), lib_vtk_io::vtk_var_xml_scal_3da_i4(), lib_vtk_io::vtk_var_xml_scal_3da_i8(), lib_vtk_io::vtk_var_xml_scal_3da_r4(), lib_vtk_io::vtk_var_xml_scal_3da_r8(), lib_vtk_io::vtk_var_xml_vect_1da_i1(), lib_vtk_io::vtk_var_xml_vect_1da_i2(), lib_vtk_io::vtk_var_xml_vect_1da_i4(), lib_vtk_io::vtk_var_xml_vect_1da_i8(), lib_vtk_io::vtk_var_xml_vect_1da_r4(), lib_vtk_io::vtk_var_xml_vect_1da_r8(), lib_vtk_io::vtk_var_xml_vect_3da_i1(), lib_vtk_io::vtk_var_xml_vect_3da_i2(), lib_vtk_io::vtk_var_xml_vect_3da_i4(), lib_vtk_io::vtk_var_xml_vect_3da_i8(), lib_vtk_io::vtk_var_xml_vect_3da_r4(), lib_vtk_io::vtk_var_xml_vect_3da_r8(), lib_vtk_io::vtm_wrf_xml(), lib_weno::weno_convolution(), lib_weno::weno_polynomials(), and lib_weno::weno_weights().
type(type_vtm_file) lib_vtk_io::vtm private
Global data of VTM files.
Definition at line 474 of file Lib_VTK_IO.f90.