OFF: Data_Type_Vector
Data_Type_Vector
Private Procedures
elemental subroutine data_type_vector::set (vec, x, y, z)
Subroutine for setting components of Type_Vector variable.
integer(i_p) function data_type_vector::pprint (vec, myrank, unit)
Function for printing in a pretty ascii format the components of type Type_Vector.
elemental subroutine data_type_vector::normalize_self (vec)
Subroutine for normalizing a vector.
elemental function data_type_vector::sq_norm_self (vec)
Function for computing the square of the norm of a vector.
elemental function data_type_vector::norml2_self (vec)
Function for computing the norm L2 of a vector.
elemental subroutine data_type_vector::assign_scalr16p (vec, scal)
elemental subroutine data_type_vector::assign_scalr8p (vec, scal)
elemental subroutine data_type_vector::assign_scalr4p (vec, scal)
elemental subroutine data_type_vector::assign_scali8p (vec, scal)
elemental subroutine data_type_vector::assign_scali4p (vec, scal)
elemental subroutine data_type_vector::assign_scali2p (vec, scal)
elemental subroutine data_type_vector::assign_scali1p (vec, scal)
elemental function data_type_vector::vec_mul_vec (vec1, vec2)
elemental function data_type_vector::scalr16p_mul_vec (scal, vec)
elemental function data_type_vector::vec_mul_scalr16p (vec, scal)
elemental function data_type_vector::scalr8p_mul_vec (scal, vec)
elemental function data_type_vector::vec_mul_scalr8p (vec, scal)
elemental function data_type_vector::scalr4p_mul_vec (scal, vec)
elemental function data_type_vector::vec_mul_scalr4p (vec, scal)
elemental function data_type_vector::scali8p_mul_vec (scal, vec)
elemental function data_type_vector::vec_mul_scali8p (vec, scal)
elemental function data_type_vector::scali4p_mul_vec (scal, vec)
elemental function data_type_vector::vec_mul_scali4p (vec, scal)
elemental function data_type_vector::scali2p_mul_vec (scal, vec)
elemental function data_type_vector::vec_mul_scali2p (vec, scal)
elemental function data_type_vector::scali1p_mul_vec (scal, vec)
elemental function data_type_vector::vec_mul_scali1p (vec, scal)
elemental function data_type_vector::vec_div_vec (vec1, vec2)
elemental function data_type_vector::vec_div_scalr16p (vec, scal)
elemental function data_type_vector::vec_div_scalr8p (vec, scal)
elemental function data_type_vector::vec_div_scalr4p (vec, scal)
elemental function data_type_vector::vec_div_scali8p (vec, scal)
elemental function data_type_vector::vec_div_scali4p (vec, scal)
elemental function data_type_vector::vec_div_scali2p (vec, scal)
elemental function data_type_vector::vec_div_scali1p (vec, scal)
elemental function data_type_vector::positive_vec (vec)
elemental function data_type_vector::vec_sum_vec (vec1, vec2)
elemental function data_type_vector::scalr16p_sum_vec (scal, vec)
elemental function data_type_vector::vec_sum_scalr16p (vec, scal)
elemental function data_type_vector::scalr8p_sum_vec (scal, vec)
elemental function data_type_vector::vec_sum_scalr8p (vec, scal)
elemental function data_type_vector::scalr4p_sum_vec (scal, vec)
elemental function data_type_vector::vec_sum_scalr4p (vec, scal)
elemental function data_type_vector::scali8p_sum_vec (scal, vec)
elemental function data_type_vector::vec_sum_scali8p (vec, scal)
elemental function data_type_vector::scali4p_sum_vec (scal, vec)
elemental function data_type_vector::vec_sum_scali4p (vec, scal)
elemental function data_type_vector::scali2p_sum_vec (scal, vec)
elemental function data_type_vector::vec_sum_scali2p (vec, scal)
elemental function data_type_vector::scali1p_sum_vec (scal, vec)
elemental function data_type_vector::vec_sum_scali1p (vec, scal)
elemental function data_type_vector::negative_vec (vec)
elemental function data_type_vector::vec_sub_vec (vec1, vec2)
elemental function data_type_vector::scalr16p_sub_vec (scal, vec)
elemental function data_type_vector::vec_sub_scalr16p (vec, scal)
elemental function data_type_vector::scalr8p_sub_vec (scal, vec)
elemental function data_type_vector::vec_sub_scalr8p (vec, scal)
elemental function data_type_vector::scalr4p_sub_vec (scal, vec)
elemental function data_type_vector::vec_sub_scalr4p (vec, scal)
elemental function data_type_vector::scali8p_sub_vec (scal, vec)
elemental function data_type_vector::vec_sub_scali8p (vec, scal)
elemental function data_type_vector::scali4p_sub_vec (scal, vec)
elemental function data_type_vector::vec_sub_scali4p (vec, scal)
elemental function data_type_vector::scali2p_sub_vec (scal, vec)
elemental function data_type_vector::vec_sub_scali2p (vec, scal)
elemental function data_type_vector::scali1p_sub_vec (scal, vec)
elemental function data_type_vector::vec_sub_scali1p (vec, scal)
elemental function data_type_vector::vec_not_eq_vec (vec1, vec2)
elemental function data_type_vector::r16p_not_eq_vec (scal, vec)
elemental function data_type_vector::vec_not_eq_r16p (vec, scal)
elemental function data_type_vector::r8p_not_eq_vec (scal, vec)
elemental function data_type_vector::vec_not_eq_r8p (vec, scal)
elemental function data_type_vector::r4p_not_eq_vec (scal, vec)
elemental function data_type_vector::vec_not_eq_r4p (vec, scal)
elemental function data_type_vector::i8p_not_eq_vec (scal, vec)
elemental function data_type_vector::vec_not_eq_i8p (vec, scal)
elemental function data_type_vector::i4p_not_eq_vec (scal, vec)
elemental function data_type_vector::vec_not_eq_i4p (vec, scal)
elemental function data_type_vector::i2p_not_eq_vec (scal, vec)
elemental function data_type_vector::vec_not_eq_i2p (vec, scal)
elemental function data_type_vector::i1p_not_eq_vec (scal, vec)
elemental function data_type_vector::vec_not_eq_i1p (vec, scal)
elemental function data_type_vector::vec_low_vec (vec1, vec2)
elemental function data_type_vector::r16p_low_vec (scal, vec)
elemental function data_type_vector::vec_low_r16p (vec, scal)
elemental function data_type_vector::r8p_low_vec (scal, vec)
elemental function data_type_vector::vec_low_r8p (vec, scal)
elemental function data_type_vector::r4p_low_vec (scal, vec)
elemental function data_type_vector::vec_low_r4p (vec, scal)
elemental function data_type_vector::i8p_low_vec (scal, vec)
elemental function data_type_vector::vec_low_i8p (vec, scal)
elemental function data_type_vector::i4p_low_vec (scal, vec)
elemental function data_type_vector::vec_low_i4p (vec, scal)
elemental function data_type_vector::i2p_low_vec (scal, vec)
elemental function data_type_vector::vec_low_i2p (vec, scal)
elemental function data_type_vector::i1p_low_vec (scal, vec)
elemental function data_type_vector::vec_low_i1p (vec, scal)
elemental function data_type_vector::vec_low_eq_vec (vec1, vec2)
elemental function data_type_vector::r16p_low_eq_vec (scal, vec)
elemental function data_type_vector::vec_low_eq_r16p (vec, scal)
elemental function data_type_vector::r8p_low_eq_vec (scal, vec)
elemental function data_type_vector::vec_low_eq_r8p (vec, scal)
elemental function data_type_vector::r4p_low_eq_vec (scal, vec)
elemental function data_type_vector::vec_low_eq_r4p (vec, scal)
elemental function data_type_vector::i8p_low_eq_vec (scal, vec)
elemental function data_type_vector::vec_low_eq_i8p (vec, scal)
elemental function data_type_vector::i4p_low_eq_vec (scal, vec)
elemental function data_type_vector::vec_low_eq_i4p (vec, scal)
elemental function data_type_vector::i2p_low_eq_vec (scal, vec)
elemental function data_type_vector::vec_low_eq_i2p (vec, scal)
elemental function data_type_vector::i1p_low_eq_vec (scal, vec)
elemental function data_type_vector::vec_low_eq_i1p (vec, scal)
elemental function data_type_vector::vec_eq_vec (vec1, vec2)
elemental function data_type_vector::r16p_eq_vec (scal, vec)
elemental function data_type_vector::vec_eq_r16p (vec, scal)
elemental function data_type_vector::r8p_eq_vec (scal, vec)
elemental function data_type_vector::vec_eq_r8p (vec, scal)
elemental function data_type_vector::r4p_eq_vec (scal, vec)
elemental function data_type_vector::vec_eq_r4p (vec, scal)
elemental function data_type_vector::i8p_eq_vec (scal, vec)
elemental function data_type_vector::vec_eq_i8p (vec, scal)
elemental function data_type_vector::i4p_eq_vec (scal, vec)
elemental function data_type_vector::vec_eq_i4p (vec, scal)
elemental function data_type_vector::i2p_eq_vec (scal, vec)
elemental function data_type_vector::vec_eq_i2p (vec, scal)
elemental function data_type_vector::i1p_eq_vec (scal, vec)
elemental function data_type_vector::vec_eq_i1p (vec, scal)
elemental function data_type_vector::vec_great_eq_vec (vec1, vec2)
elemental function data_type_vector::r16p_great_eq_vec (scal, vec)
elemental function data_type_vector::vec_great_eq_r16p (vec, scal)
elemental function data_type_vector::r8p_great_eq_vec (scal, vec)
elemental function data_type_vector::vec_great_eq_r8p (vec, scal)
elemental function data_type_vector::r4p_great_eq_vec (scal, vec)
elemental function data_type_vector::vec_great_eq_r4p (vec, scal)
elemental function data_type_vector::i8p_great_eq_vec (scal, vec)
elemental function data_type_vector::vec_great_eq_i8p (vec, scal)
elemental function data_type_vector::i4p_great_eq_vec (scal, vec)
elemental function data_type_vector::vec_great_eq_i4p (vec, scal)
elemental function data_type_vector::i2p_great_eq_vec (scal, vec)
elemental function data_type_vector::vec_great_eq_i2p (vec, scal)
elemental function data_type_vector::i1p_great_eq_vec (scal, vec)
elemental function data_type_vector::vec_great_eq_i1p (vec, scal)
elemental function data_type_vector::vec_great_vec (vec1, vec2)
elemental function data_type_vector::r16p_great_vec (scal, vec)
elemental function data_type_vector::vec_great_r16p (vec, scal)
elemental function data_type_vector::r8p_great_vec (scal, vec)
elemental function data_type_vector::vec_great_r8p (vec, scal)
elemental function data_type_vector::r4p_great_vec (scal, vec)
elemental function data_type_vector::vec_great_r4p (vec, scal)
elemental function data_type_vector::i8p_great_vec (scal, vec)
elemental function data_type_vector::vec_great_i8p (vec, scal)
elemental function data_type_vector::i4p_great_vec (scal, vec)
elemental function data_type_vector::vec_great_i4p (vec, scal)
elemental function data_type_vector::i2p_great_vec (scal, vec)
elemental function data_type_vector::vec_great_i2p (vec, scal)
elemental function data_type_vector::i1p_great_vec (scal, vec)
elemental function data_type_vector::vec_great_i1p (vec, scal)
elemental function data_type_vector::crossproduct (vec1, vec2)
elemental function data_type_vector::dotproduct (vec1, vec2)
elemental function data_type_vector::parallel (vec1, vec2)
elemental function data_type_vector::orthogonal (vec1, vec2)
Detailed Description
Function/Subroutine Documentation
elemental subroutine data_type_vector::set (class(type_vector), intent(inout) vec, real(r8p), intent(in), optional x, real(r8p), intent(in), optional y, real(r8p), intent(in), optional z) private
Subroutine for setting components of Type_Vector variable.
Parameters
[in,out] vec Vector.
[in] x Cartesian component in x direction.
[in] y Cartesian component in y direction.
[in] z Cartesian component in z direction.
Definition at line 621 of file Data_Type_Vector.f90.
integer(i_p) function data_type_vector::pprint (class(type_vector), intent(in) vec, integer(i_p), intent(in), optional myrank, integer(i_p), intent(in) unit) private
Function for printing in a pretty ascii format the components of type Type_Vector.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in] vec Vector.
[in] myrank Actual rank process.
[in] unit Logic unit.
Definition at line 640 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::normalize_self (class(type_vector), intent(inout) vec) private
Subroutine for normalizing a vector.
The normalization is made by means of norm L2. If the norm L2 of the vector is less than the parameter smallR8P the normalization value is set to normL2(vec)+smallR8P.
Parameters
[in,out] vec Vector to be normalized.
Definition at line 662 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2(), and ir_precision::smallr8p.
elemental function data_type_vector::sq_norm_self (class(type_vector), intent(in) vec) private
Function for computing the square of the norm of a vector.
The square norm if defined as .
Returns
sq square norm
Parameters
[in] vec Vector.
Definition at line 684 of file Data_Type_Vector.f90.
elemental function data_type_vector::norml2_self (class(type_vector), intent(in) vec) private
Function for computing the norm L2 of a vector.
The norm L2 if defined as .
Returns
norm norm L2
Parameters
[in] vec Vector.
Definition at line 700 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scalr16p (type(type_vector), intent(inout) vec, real(r16p), intent(in) scal) private
Definition at line 714 of file Data_Type_Vector.f90.
Referenced by data_type_conservative::type_conservative::pprint(), and data_type_primitive::type_primitive::pprint().
elemental subroutine data_type_vector::assign_scalr8p (type(type_vector), intent(inout) vec, real(r8p), intent(in) scal) private
Definition at line 733 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scalr4p (type(type_vector), intent(inout) vec, real(r4p), intent(in) scal) private
Definition at line 752 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scali8p (type(type_vector), intent(inout) vec, integer(i8p), intent(in) scal) private
Definition at line 771 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scali4p (type(type_vector), intent(inout) vec, integer(i4p), intent(in) scal) private
Definition at line 790 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scali2p (type(type_vector), intent(inout) vec, integer(i2p), intent(in) scal) private
Definition at line 809 of file Data_Type_Vector.f90.
elemental subroutine data_type_vector::assign_scali1p (type(type_vector), intent(inout) vec, integer(i1p), intent(in) scal) private
Definition at line 828 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_mul_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 848 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr16p_mul_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 868 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_mul_scalr16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 888 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr8p_mul_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 908 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_mul_scalr8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 928 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr4p_mul_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 948 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_mul_scalr4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 968 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali8p_mul_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 988 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_mul_scali8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 1008 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali4p_mul_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1028 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_mul_scali4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 1048 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali2p_mul_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1068 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_mul_scali2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 1088 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali1p_mul_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1108 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_mul_scali1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 1128 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_div_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 1149 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_div_scalr16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 1169 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_div_scalr8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 1189 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_div_scalr4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 1209 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_div_scali8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 1229 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_div_scali4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 1249 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_div_scali2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 1269 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_div_scali1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 1289 of file Data_Type_Vector.f90.
elemental function data_type_vector::positive_vec (type(type_vector), intent(in) vec) private
Definition at line 1310 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sum_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 1329 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr16p_sum_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1349 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sum_scalr16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 1369 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr8p_sum_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1389 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sum_scalr8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 1409 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr4p_sum_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1429 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sum_scalr4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 1449 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali8p_sum_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1469 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sum_scali8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 1489 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali4p_sum_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1509 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sum_scali4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 1529 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali2p_sum_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1549 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sum_scali2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 1569 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali1p_sum_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1589 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sum_scali1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 1609 of file Data_Type_Vector.f90.
elemental function data_type_vector::negative_vec (type(type_vector), intent(in) vec) private
Definition at line 1630 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sub_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 1649 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr16p_sub_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1669 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sub_scalr16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 1689 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr8p_sub_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1709 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sub_scalr8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 1729 of file Data_Type_Vector.f90.
elemental function data_type_vector::scalr4p_sub_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1749 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sub_scalr4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 1769 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali8p_sub_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1789 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sub_scali8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 1809 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali4p_sub_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1829 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sub_scali4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 1849 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali2p_sub_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1869 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sub_scali2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 1889 of file Data_Type_Vector.f90.
elemental function data_type_vector::scali1p_sub_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1909 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_sub_scali1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 1929 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_not_eq_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 1951 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::normalize(), and data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r16p_not_eq_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 1976 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_not_eq_r16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 1994 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r8p_not_eq_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2012 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_not_eq_r8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 2030 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r4p_not_eq_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2048 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_not_eq_r4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 2066 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i8p_not_eq_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2084 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_not_eq_i8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 2102 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i4p_not_eq_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2120 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_not_eq_i4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 2138 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i2p_not_eq_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2156 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_not_eq_i2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 2174 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i1p_not_eq_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2192 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_not_eq_i1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 2210 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::vec_low_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 2229 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r16p_low_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2247 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_r16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 2265 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r8p_low_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2283 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_r8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 2301 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r4p_low_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2319 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_r4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 2337 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i8p_low_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2355 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_i8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 2373 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i4p_low_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2391 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_i4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 2409 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i2p_low_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2427 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_i2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 2445 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i1p_low_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2463 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_i1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 2481 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::vec_low_eq_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 2500 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r16p_low_eq_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2518 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_eq_r16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 2536 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r8p_low_eq_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2554 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_eq_r8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 2572 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r4p_low_eq_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2590 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_eq_r4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 2608 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i8p_low_eq_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2626 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_eq_i8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 2644 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i4p_low_eq_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2662 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_eq_i4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 2680 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i2p_low_eq_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2698 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_eq_i2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 2716 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i1p_low_eq_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2734 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_low_eq_i1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 2752 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::vec_eq_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 2771 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::normalize(), and data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r16p_eq_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2796 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_eq_r16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 2814 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r8p_eq_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2832 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_eq_r8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 2850 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r4p_eq_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2868 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_eq_r4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 2886 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i8p_eq_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2904 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_eq_i8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 2922 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i4p_eq_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2940 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_eq_i4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 2958 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i2p_eq_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 2976 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_eq_i2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 2994 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i1p_eq_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3012 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_eq_i1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 3030 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::vec_great_eq_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 3049 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r16p_great_eq_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3067 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_eq_r16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 3085 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r8p_great_eq_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3103 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_eq_r8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 3121 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r4p_great_eq_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3139 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_eq_r4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 3157 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i8p_great_eq_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3175 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_eq_i8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 3193 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i4p_great_eq_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3211 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_eq_i4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 3229 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i2p_great_eq_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3247 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_eq_i2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 3265 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i1p_great_eq_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3283 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_eq_i1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 3301 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::vec_great_vec (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 3320 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r16p_great_vec (real(r16p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3338 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_r16p (type(type_vector), intent(in) vec, real(r16p), intent(in) scal) private
Definition at line 3356 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r8p_great_vec (real(r8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3374 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_r8p (type(type_vector), intent(in) vec, real(r8p), intent(in) scal) private
Definition at line 3392 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::r4p_great_vec (real(r4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3410 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_r4p (type(type_vector), intent(in) vec, real(r4p), intent(in) scal) private
Definition at line 3428 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i8p_great_vec (integer(i8p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3446 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_i8p (type(type_vector), intent(in) vec, integer(i8p), intent(in) scal) private
Definition at line 3464 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i4p_great_vec (integer(i4p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3482 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_i4p (type(type_vector), intent(in) vec, integer(i4p), intent(in) scal) private
Definition at line 3500 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i2p_great_vec (integer(i2p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3518 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_i2p (type(type_vector), intent(in) vec, integer(i2p), intent(in) scal) private
Definition at line 3536 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::i1p_great_vec (integer(i1p), intent(in) scal, type(type_vector), intent(in) vec) private
Definition at line 3554 of file Data_Type_Vector.f90.
elemental function data_type_vector::vec_great_i1p (type(type_vector), intent(in) vec, integer(i1p), intent(in) scal) private
Definition at line 3572 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2().
elemental function data_type_vector::crossproduct (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 3591 of file Data_Type_Vector.f90.
elemental function data_type_vector::dotproduct (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 3616 of file Data_Type_Vector.f90.
elemental function data_type_vector::parallel (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 3639 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::normalize().
elemental function data_type_vector::orthogonal (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 3657 of file Data_Type_Vector.f90.