OFF: Data_Type_Time
Data_Type_Time
Interfaces
Data Types
interface data_type_time::operator(/=)
Not-equal-to boolean operator (/=) overloading.
interface data_type_time::operator(<)
Lower-than boolean operator (<) overloading.
interface data_type_time::operator(<=)
Lower-equal-than boolean operator (<=) overloading.
interface data_type_time::operator(==)
Equal-to boolean operator (==) overloading.
interface data_type_time::operator(>=)
Higher-equal-than boolean operator (>=) overloading.
interface data_type_time::operator(>)
Higher-than boolean operator (>) overloading.
Detailed Description
Data Type Documentation
interface data_type_time::operator(/=)
Not-equal-to boolean operator (/=) overloading.
Definition at line 74 of file Data_Type_Time.f90.
Private Member Functions
elemental function not_eq (time1, time2)
Member Function/Subroutine Documentation
elemental function data_type_time::operator(/=)::not_eq (type(type_time), intent(in) time1, type(type_time), intent(in) time2) private
Definition at line 123 of file Data_Type_Time.f90.
Referenced by data_type_time::type_time::sec2time().
interface data_type_time::operator(<)
Lower-than boolean operator (<) overloading.
Definition at line 79 of file Data_Type_Time.f90.
Private Member Functions
elemental function low (time1, time2)
Member Function/Subroutine Documentation
elemental function data_type_time::operator(<)::low (type(type_time), intent(in) time1, type(type_time), intent(in) time2) private
Definition at line 144 of file Data_Type_Time.f90.
Referenced by data_type_time::type_time::sec2time().
interface data_type_time::operator(<=)
Lower-equal-than boolean operator (<=) overloading.
Definition at line 84 of file Data_Type_Time.f90.
Private Member Functions
elemental function low_eq (time1, time2)
Member Function/Subroutine Documentation
elemental function data_type_time::operator(<=)::low_eq (type(type_time), intent(in) time1, type(type_time), intent(in) time2) private
Definition at line 184 of file Data_Type_Time.f90.
Referenced by data_type_time::type_time::sec2time().
interface data_type_time::operator(==)
Equal-to boolean operator (==) overloading.
Definition at line 89 of file Data_Type_Time.f90.
Private Member Functions
elemental function eq (time1, time2)
Member Function/Subroutine Documentation
elemental function data_type_time::operator(==)::eq (type(type_time), intent(in) time1, type(type_time), intent(in) time2) private
Definition at line 212 of file Data_Type_Time.f90.
Referenced by data_type_time::type_time::sec2time().
interface data_type_time::operator(>=)
Higher-equal-than boolean operator (>=) overloading.
Definition at line 94 of file Data_Type_Time.f90.
Private Member Functions
elemental function great_eq (time1, time2)
Member Function/Subroutine Documentation
elemental function data_type_time::operator(>=)::great_eq (type(type_time), intent(in) time1, type(type_time), intent(in) time2) private
Definition at line 233 of file Data_Type_Time.f90.
Referenced by data_type_time::type_time::sec2time().
interface data_type_time::operator(>)
Higher-than boolean operator (>) overloading.
Definition at line 99 of file Data_Type_Time.f90.
Private Member Functions
elemental function great (time1, time2)
Member Function/Subroutine Documentation
elemental function data_type_time::operator(>)::great (type(type_time), intent(in) time1, type(type_time), intent(in) time2) private
Definition at line 273 of file Data_Type_Time.f90.
Referenced by data_type_time::type_time::sec2time().