OFF: Lib_IO_Misc
Lib_IO_Misc
Global Variables and Parameters
Variables
type(type_os), public lib_io_misc::os
OS definition (see definition).
Detailed Description
Variable Documentation
type(type_os), public lib_io_misc::os
OS definition (see definition).
Definition at line 56 of file Lib_IO_Misc.f90.
Referenced by lib_io_misc::basedir(), lib_io_misc::basename(), lib_io_misc::copy_file(), load_off_option_file(), load_option_file(), lib_io_misc::make_dir(), parsing_command_line(), lib_io_misc::remove_file(), and lib_io_misc::string_os_sep().