OFF: Lib_Math.f90 File Reference
Lib_Math.f90 File Reference
Data Types
module lib_math
This module contains mathematical procedures.
interface lib_math::isort
Subroutine for computing prime factors of input integer number.
interface lib_math::qsort
Subroutine for performing QuickSort with ascending order.
interface lib_math::spline3
Function for computing cubic spline interpolation of an array of values.
interface lib_math::average
Example of usage:
interface lib_math::digit
Digit overloading.
interface lib_math::div2
Div2 overloading.
interface lib_math::interpolate1
Linear interpolate overloading.
interface lib_math::interpolate2
Bi-linear interpolate overloading.
interface lib_math::interpolate3
Tri-linear interpolate overloading.
interface lib_math::degree
Degree overloading.
interface lib_math::radiant
Radiant overloading.
interface lib_math::delta1_2o
delta1_2o overloading
interface lib_math::delta2_2o
delta2_2o overloading
interface lib_math::abs_grad
abs_grad overloading
interface lib_math::laplacian
laplacian overloading
Functions/Subroutines
recursive subroutine subsor (array, n1, nn)
Sorts array from n1 to nn (QuickSort algorithm).
recursive subroutine subsor (array, n1, nn)
Sorts array from n1 to nn (QuickSort algorithm).
recursive subroutine subsor (array, n1, nn)
Sorts array from n1 to nn (QuickSort algorithm).
recursive subroutine subsor (array, n1, nn)
Sorts array from n1 to nn (QuickSort algorithm).
recursive subroutine subsor (array, n1, nn)
Sorts array from n1 to nn (QuickSort algorithm).
recursive subroutine subsor (array, n1, nn)
Sorts array from n1 to nn (QuickSort algorithm).
recursive subroutine subsor (array, n1, nn)
Sorts array from n1 to nn (QuickSort algorithm).
pure function compute_cd2 (N)
pure function cspline (xint)
pure function cspline (xint)
pure function cspline (xint)
Function/Subroutine Documentation
recursive subroutine qsort_r16::subsor (real(r16p), dimension(:), intent(inout) array, integer(i4p), intent(in) n1, integer(i4p), intent(in) nn) private
Sorts array from n1 to nn (QuickSort algorithm).
Parameters
[in,out] array Array to be sorted.
[in] n1 Initial index of sorting.
[in] nn Final index of sorting.
Definition at line 577 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array().
Referenced by lib_math::qsort_i1(), lib_math::qsort_i2(), lib_math::qsort_i4(), lib_math::qsort_i8(), lib_math::qsort_r16(), lib_math::qsort_r4(), lib_math::qsort_r8(), and subsor().
recursive subroutine qsort_r8::subsor (real(r8p), dimension(:), intent(inout) array, integer(i4p), intent(in) n1, integer(i4p), intent(in) nn) private
Sorts array from n1 to nn (QuickSort algorithm).
Parameters
[in,out] array Array to be sorted.
[in] n1 Initial index of sorting.
[in] nn Final index of sorting.
Definition at line 650 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), and subsor().
recursive subroutine qsort_r4::subsor (real(r4p), dimension(:), intent(inout) array, integer(i4p), intent(in) n1, integer(i4p), intent(in) nn) private
Sorts array from n1 to nn (QuickSort algorithm).
Parameters
[in,out] array Array to be sorted.
[in] n1 Initial index of sorting.
[in] nn Final index of sorting.
Definition at line 723 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), and subsor().
recursive subroutine qsort_i8::subsor (integer(i8p), dimension(:), intent(inout) array, integer(i4p), intent(in) n1, integer(i4p), intent(in) nn) private
Sorts array from n1 to nn (QuickSort algorithm).
Parameters
[in,out] array Array to be sorted.
[in] n1 Initial index of sorting.
[in] nn Final index of sorting.
Definition at line 796 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), and subsor().
recursive subroutine qsort_i4::subsor (integer(i4p), dimension(:), intent(inout) array, integer(i4p), intent(in) n1, integer(i4p), intent(in) nn) private
Sorts array from n1 to nn (QuickSort algorithm).
Parameters
[in,out] array Array to be sorted.
[in] n1 Initial index of sorting.
[in] nn Final index of sorting.
Definition at line 869 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), and subsor().
recursive subroutine qsort_i2::subsor (integer(i2p), dimension(:), intent(inout) array, integer(i4p), intent(in) n1, integer(i4p), intent(in) nn) private
Sorts array from n1 to nn (QuickSort algorithm).
Parameters
[in,out] array Array to be sorted.
[in] n1 Initial index of sorting.
[in] nn Final index of sorting.
Definition at line 942 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), and subsor().
recursive subroutine qsort_i1::subsor (integer(i1p), dimension(:), intent(inout) array, integer(i4p), intent(in) n1, integer(i4p), intent(in) nn) private
Sorts array from n1 to nn (QuickSort algorithm).
Parameters
[in,out] array Array to be sorted.
[in] n1 Initial index of sorting.
[in] nn Final index of sorting.
Definition at line 1015 of file Lib_Math.f90.
References data_type_sl_list::type_sl_link::array(), and subsor().
pure function compute_cd2 (integer(i4p), intent(in) N) private
Parameters
[in] n Number of points.
Definition at line 1097 of file Lib_Math.f90.
References lib_thermodynamic_laws_ideal::p().
Referenced by lib_math::spline3_r16(), lib_math::spline3_r4(), and lib_math::spline3_r8().
pure function spline3_r16::cspline (real(r16p), intent(in) xint) private
Parameters
[in] xint Independent variable abscissa of interpolating point.
Definition at line 1139 of file Lib_Math.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::h(), and lib_morton::mask.
Referenced by lib_math::spline3_r16(), lib_math::spline3_r4(), and lib_math::spline3_r8().
pure function spline3_r8::cspline (real(r8p), intent(in) xint) private
Parameters
[in] xint Independent variable abscissa of interpolating point.
Definition at line 1229 of file Lib_Math.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::h(), and lib_morton::mask.
pure function spline3_r4::cspline (real(r4p), intent(in) xint) private
Parameters
[in] xint Independent variable abscissa of interpolating point.
Definition at line 1319 of file Lib_Math.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::h(), and lib_morton::mask.