OFF: Lib_Parallel.f90 File Reference
Lib_Parallel.f90 File Reference
Data Types
module lib_parallel
This module contains the definition of procedures for send/receive data among processes for parallel (MPI) operations.
Functions/Subroutines
subroutine scan_proc (NcR, proc, global, block, reqsmap, recvmap)
subroutine scan_block (NcR, block, proc, b, c, reqsmap, recvmap)
Function/Subroutine Documentation
subroutine compute_recv_maps::scan_proc (integer(i_p), intent(in) NcR, integer(i_p), intent(in) proc, type(type_global), intent(in) global, type(type_sblock), dimension(1:global%nb), intent(in) block, integer(i_p), dimension(1:4,1:ncr), intent(out) reqsmap, integer(i_p), dimension(1:4,1:ncr), intent(out) recvmap) private
Definition at line 295 of file Lib_Parallel.f90.
References scan_block().
Referenced by lib_parallel::compute_recv_maps().
subroutine compute_recv_maps::scan_block (integer(i_p), intent(in) NcR, type(type_sblock), intent(in) block, integer(i_p), intent(in) proc, integer(i_p), intent(in) b, integer(i_p), intent(inout) c, integer(i_p), dimension(1:4,1:ncr), intent(out) reqsmap, integer(i_p), dimension(1:4,1:ncr), intent(out) recvmap) private
Definition at line 327 of file Lib_Parallel.f90.
References data_type_bc::bc_adj, and lib_parallel::procmap.
Referenced by scan_proc().