OFF: Lib_Math
Lib_Math
Global Variables and Parameters
real(r16p), parameter, public lib_math::pi_r16 = 2._R16P*asin(1._R16P)
with R16P precision.
real(r8p), parameter, public lib_math::pi_r8 = 2._R8P* asin(1._R8P)
with R8P precision.
real(r4p), parameter, public lib_math::pi_r4 = 2._R4P* asin(1._R4P)
with R4P precision.
real(r_p), parameter, public lib_math::pi = 2._R_P* asin(1._R_P)
with R_P precision.
Detailed Description
Variable Documentation
real(r16p), parameter, public lib_math::pi_r16 = 2._R16P*asin(1._R16P)
with R16P precision.
Definition at line 68 of file Lib_Math.f90.
Referenced by lib_math::degree_scalar_r16(), lib_math::degree_vectorial1d_r16(), lib_math::degree_vectorial2d_r16(), lib_math::degree_vectorial3d_r16(), lib_math::radiant_scalar_r16(), lib_math::radiant_vectorial1d_r16(), lib_math::radiant_vectorial2d_r16(), and lib_math::radiant_vectorial3d_r16().
real(r8p), parameter, public lib_math::pi_r8 = 2._R8P* asin(1._R8P)
with R8P precision.
Definition at line 69 of file Lib_Math.f90.
Referenced by lib_math::degree_scalar_r8(), lib_math::degree_vectorial1d_r8(), lib_math::degree_vectorial2d_r8(), lib_math::degree_vectorial3d_r8(), lib_math::radiant_scalar_r8(), lib_math::radiant_vectorial1d_r8(), lib_math::radiant_vectorial2d_r8(), and lib_math::radiant_vectorial3d_r8().
real(r4p), parameter, public lib_math::pi_r4 = 2._R4P* asin(1._R4P)
with R4P precision.
Definition at line 70 of file Lib_Math.f90.
Referenced by lib_math::degree_scalar_r4(), lib_math::degree_vectorial1d_r4(), lib_math::degree_vectorial2d_r4(), lib_math::degree_vectorial3d_r4(), lib_math::radiant_scalar_r4(), lib_math::radiant_vectorial1d_r4(), lib_math::radiant_vectorial2d_r4(), and lib_math::radiant_vectorial3d_r4().
real(r_p), parameter, public lib_math::pi = 2._R_P* asin(1._R_P)
with R_P precision.
Definition at line 71 of file Lib_Math.f90.