OFF: IBM.f90 File Reference
IBM.f90 File Reference
Data Types
type type_blocks
Derived type containing blocks informations.
Functions/Subroutines
program ibm
IBM, Initial and Boundary conditions, Mesh generator for OFF (Open Finite volume Fluid dynamics code).
subroutine print_usage ()
subroutine icg_init (global)
integer(i_p) function load_option_file (filename)
integer(i_p) function load_blocks (filename)
integer(i_p) function load_icemcfd (Nf, filenames)
Data Type Documentation
type type_blocks
Derived type containing blocks informations.
Definition at line 41 of file IBM.f90.
Class Members
integer(i1p), dimension(1:6) gc Ghost cells.
integer(i_p) ni Number of cells in i direction.
integer(i_p) nj Number of cells in j direction.
integer(i_p) nk Number of cells in k direction.
real(r_p) xmin Minimum value of x abscissa.
real(r_p) ymin Minimum value of y abscissa.
real(r_p) zmin Minimum value of z abscissa.
real(r_p) xmax Maximum value of x abscissa.
real(r_p) ymax Maximum value of y abscissa.
real(r_p) zmax Maximum value of z abscissa.
type(type_bc), dimension(1:6) bc Block faces boundary conditions.
type(type_primitive) p Blocks primitive variables.
Function/Subroutine Documentation
subroutine ibm::print_usage ()
Definition at line 194 of file IBM.f90.
Referenced by icg_init(), and parsing_command_line().
subroutine ibm::icg_init (type(type_global), intent(out) global)
Definition at line 213 of file IBM.f90.
References load_option_file(), print_usage(), and lib_io_misc::string_os_sep().
integer(i_p) function ibm::load_option_file (character(*), intent(in) filename)
Definition at line 263 of file IBM.f90.
References lib_vtk_io::f, lib_io_misc::file_not_found(), lib_io_misc::get_unit(), lib_io_misc::make_dir(), lib_io_misc::os, lib_io_misc::string_os_sep(), and lib_io_misc::upper_case().
Referenced by icg_init().
integer(i_p) function ibm::load_blocks (character(*), intent(in) filename)
Definition at line 319 of file IBM.f90.
References data_type_bc::bc_adj, data_type_bc::bc_in1, data_type_bc::bc_in2, lib_vtk_io::f, lib_io_misc::file_not_found(), lib_io_misc::get_unit(), data_type_bc::write_bc(), data_type_primitive::write_primitive(), and data_type_vector::write_vector().
integer(i_p) function ibm::load_icemcfd (integer(i_p), intent(in) Nf, character(*), dimension(1:nf), intent(in) filenames)
Definition at line 682 of file IBM.f90.
References data_type_bc::bc_adj, data_type_bc::bc_in1, data_type_bc::bc_in2, data_type_bc::bc_list, data_type_bc::bc_list_str, lib_vtk_io::f, ir_precision::fi_p, lib_io_misc::file_not_found(), lib_io_misc::get_unit(), data_type_bc::nbc, data_type_bc::write_bc(), data_type_primitive::write_primitive(), and data_type_vector::write_vector().