OFF: Data_Type_Tensor
Data_Type_Tensor
Interfaces
Data Types
interface data_type_tensor::sq_norm
Square norm function sq_norm overloading.
interface data_type_tensor::norml2
L2 norm function normL2 overloading.
interface data_type_tensor::normalize
Normalize function normalize overloading.
interface data_type_tensor::transpose
Transpose function transpose overloading.
interface data_type_tensor::assignment(=)
Assignment operator (=) overloading.
interface data_type_tensor::operator(*)
Multiplication operator (*) overloading.
interface data_type_tensor::operator(/)
Division operator (/) overloading.
interface data_type_tensor::operator(+)
Sum operator (+) overloading.
interface data_type_tensor::operator(-)
Subtraction operator (-) overloading.
interface data_type_tensor::operator(.ddot.)
Double dot product operator (.ddot.) definition.
interface data_type_tensor::operator(.dot.)
Dot product operator (.dot.) definition.
interface data_type_tensor::operator(.diad.)
Diadic product operator (.diad.) definition.
Detailed Description
Data Type Documentation
interface data_type_tensor::sq_norm
Square norm function sq_norm overloading.
The function sq_norm defined for Type_Vector is overloaded for handling also Type_Tensor.
Definition at line 101 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function sq_norm_ten (ten)
Function for computing the square of the norm of a tensor.
Member Function/Subroutine Documentation
elemental function data_type_tensor::sq_norm::sq_norm_ten (class(type_tensor), intent(in) ten) private
Function for computing the square of the norm of a tensor.
The square norm if defined as .
Returns
sq square norm
Definition at line 501 of file Data_Type_Tensor.f90.
Referenced by off().
interface data_type_tensor::norml2
L2 norm function normL2 overloading.
The function normL2 defined for Type_Vector is overloaded for handling also Type_Tensor.
Definition at line 107 of file Data_Type_Tensor.f90.
Private Member Functions
norml2
elemental function norml2_ten (ten)
Function for computing the norm L2 of a tensor.
Constructor & Destructor Documentation
data_type_tensor::norml2::norml2 () private
Member Function/Subroutine Documentation
elemental function data_type_tensor::norml2::norml2_ten (class(type_tensor), intent(in) ten) private
Function for computing the norm L2 of a tensor.
The norm L2 if defined as .
Returns
norm norm L2
Definition at line 517 of file Data_Type_Tensor.f90.
Referenced by data_type_tensor::normalize_self(), and data_type_tensor::normalize_ten().
interface data_type_tensor::normalize
Normalize function normalize overloading.
The function normalize defined for Type_Vector is overloaded for handling also Type_Tensor.
Definition at line 113 of file Data_Type_Tensor.f90.
Private Member Functions
normalize
elemental function normalize_ten (ten)
Function for normalizing a tensor.
Constructor & Destructor Documentation
data_type_tensor::normalize::normalize () private
Member Function/Subroutine Documentation
elemental function data_type_tensor::normalize::normalize_ten (type(type_tensor), intent(in) ten) private
Function for normalizing a tensor.
The normalization is made by means of norm L2. If the norm L2 of the tensor is less than the parameter smallR8P the normalization value is set to normL2(ten)+smallR8P.
Returns
norm normalized tensor
Definition at line 556 of file Data_Type_Tensor.f90.
interface data_type_tensor::transpose
Transpose function transpose overloading.
The built in function transpose defined for rank 2 arrays is overloaded for handling also Type_Tensor.
Definition at line 119 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function transpose_ten (ten)
Function for transposing a tensor.
Member Function/Subroutine Documentation
elemental function data_type_tensor::transpose::transpose_ten (type(type_tensor), intent(in) ten) private
Function for transposing a tensor.
The transpositions is done as following:
      |x%x x%y x%z|           |x%x y%x z%x|
ten = |y%x y%y y%z| => tran = |x%y y%y z%y|
      |z%x z%y z%z|           |x%z y%z z%z|
Parameters
[in] ten Tensor to be transposed.
Definition at line 616 of file Data_Type_Tensor.f90.
interface data_type_tensor::assignment(=)
Assignment operator (=) overloading.
Definition at line 124 of file Data_Type_Tensor.f90.
Private Member Functions
elemental subroutine assign_vec (ten, vec)
elemental subroutine assign_scalr8p (ten, scal)
elemental subroutine assign_scalr4p (ten, scal)
elemental subroutine assign_scali8p (ten, scal)
elemental subroutine assign_scali4p (ten, scal)
elemental subroutine assign_scali2p (ten, scal)
elemental subroutine assign_scali1p (ten, scal)
Member Function/Subroutine Documentation
elemental subroutine data_type_tensor::assignment(=)::assign_vec (type(type_tensor), intent(inout) ten, type(type_vector), intent(in) vec) private
Definition at line 742 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assignment(=)::assign_scalr8p (type(type_tensor), intent(inout) ten, real(r8p), intent(in) scal) private
Definition at line 763 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assignment(=)::assign_scalr4p (type(type_tensor), intent(inout) ten, real(r4p), intent(in) scal) private
Definition at line 782 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assignment(=)::assign_scali8p (type(type_tensor), intent(inout) ten, integer(i8p), intent(in) scal) private
Definition at line 801 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assignment(=)::assign_scali4p (type(type_tensor), intent(inout) ten, integer(i4p), intent(in) scal) private
Definition at line 820 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assignment(=)::assign_scali2p (type(type_tensor), intent(inout) ten, integer(i2p), intent(in) scal) private
Definition at line 839 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assignment(=)::assign_scali1p (type(type_tensor), intent(inout) ten, integer(i1p), intent(in) scal) private
Definition at line 858 of file Data_Type_Tensor.f90.
interface data_type_tensor::operator(*)
Multiplication operator (*) overloading.
Note
The admissible multiplications are:
Type_Tensor * Type_Tensor: each component of first tensor variable (ten1) is multiplied for the corresponding component of the second one (ten2), i.e.
scalar number (real or integer of any kinds defined in IR_Precision module) * Type_Tensor: each component of Type_Tensor is multiplied for the scalar, i.e.
Type_Tensor * scalar number (real or integer of any kinds defined in IR_Precision module): each component of Type_Tensor is multiplied for the scalar, i.e.
Definition at line 154 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function ten_mul_ten (ten1, ten2)
elemental function scalr8p_mul_ten (scal, ten)
elemental function scalr4p_mul_ten (scal, ten)
elemental function scali8p_mul_ten (scal, ten)
elemental function scali4p_mul_ten (scal, ten)
elemental function scali2p_mul_ten (scal, ten)
elemental function scali1p_mul_ten (scal, ten)
elemental function ten_mul_scalr8p (ten, scal)
elemental function ten_mul_scalr4p (ten, scal)
elemental function ten_mul_scali8p (ten, scal)
elemental function ten_mul_scali4p (ten, scal)
elemental function ten_mul_scali2p (ten, scal)
elemental function ten_mul_scali1p (ten, scal)
Member Function/Subroutine Documentation
elemental function data_type_tensor::operator(*)::ten_mul_ten (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 878 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::scalr8p_mul_ten (real(r8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 900 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::scalr4p_mul_ten (real(r4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 940 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::scali8p_mul_ten (integer(i8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 980 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::scali4p_mul_ten (integer(i4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1020 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::scali2p_mul_ten (integer(i2p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1060 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::scali1p_mul_ten (integer(i1p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1100 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::ten_mul_scalr8p (type(type_tensor), intent(in) ten, real(r8p), intent(in) scal) private
Definition at line 920 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::ten_mul_scalr4p (type(type_tensor), intent(in) ten, real(r4p), intent(in) scal) private
Definition at line 960 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::ten_mul_scali8p (type(type_tensor), intent(in) ten, integer(i8p), intent(in) scal) private
Definition at line 1000 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::ten_mul_scali4p (type(type_tensor), intent(in) ten, integer(i4p), intent(in) scal) private
Definition at line 1040 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::ten_mul_scali2p (type(type_tensor), intent(in) ten, integer(i2p), intent(in) scal) private
Definition at line 1080 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(*)::ten_mul_scali1p (type(type_tensor), intent(in) ten, integer(i1p), intent(in) scal) private
Definition at line 1120 of file Data_Type_Tensor.f90.
interface data_type_tensor::operator(/)
Division operator (/) overloading.
Note
The admissible divisions are:
Type_Tensor / Type_Tensor: each component of first tensor variable (ten1) is divided for the corresponding component of the second one (ten2), i.e.
Type_Tensor / scalar number (real or integer of any kinds defined in IR_Precision module): each component of Type_Tensor is divided for the scalar, i.e.
Definition at line 188 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function ten_div_ten (ten1, ten2)
elemental function ten_div_scalr8p (ten, scal)
elemental function ten_div_scalr4p (ten, scal)
elemental function ten_div_scali8p (ten, scal)
elemental function ten_div_scali4p (ten, scal)
elemental function ten_div_scali2p (ten, scal)
elemental function ten_div_scali1p (ten, scal)
Member Function/Subroutine Documentation
elemental function data_type_tensor::operator(/)::ten_div_ten (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 1141 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(/)::ten_div_scalr8p (type(type_tensor), intent(in) ten, real(r8p), intent(in) scal) private
Definition at line 1163 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(/)::ten_div_scalr4p (type(type_tensor), intent(in) ten, real(r4p), intent(in) scal) private
Definition at line 1183 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(/)::ten_div_scali8p (type(type_tensor), intent(in) ten, integer(i8p), intent(in) scal) private
Definition at line 1203 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(/)::ten_div_scali4p (type(type_tensor), intent(in) ten, integer(i4p), intent(in) scal) private
Definition at line 1223 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(/)::ten_div_scali2p (type(type_tensor), intent(in) ten, integer(i2p), intent(in) scal) private
Definition at line 1243 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(/)::ten_div_scali1p (type(type_tensor), intent(in) ten, integer(i1p), intent(in) scal) private
Definition at line 1263 of file Data_Type_Tensor.f90.
interface data_type_tensor::operator(+)
Sum operator (+) overloading.
Note
The admissible summations are:
Type_Tensor + Type_Tensor: each component of first tensor variable (ten1) is summed with the corresponding component of the second one (ten2), i.e.
scalar number (real or integer of any kinds defined in IR_Precision module) + Type_Tensor: each component of Type_Tensor is summed with the scalar, i.e.
Type_Tensor + scalar number (real or integer of any kinds defined in IR_Precision module): each component of Type_Tensor is summed with the scalar, i.e.
Definition at line 218 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function positive_ten (ten)
elemental function ten_sum_ten (ten1, ten2)
elemental function scalr8p_sum_ten (scal, ten)
elemental function scalr4p_sum_ten (scal, ten)
elemental function scali8p_sum_ten (scal, ten)
elemental function scali4p_sum_ten (scal, ten)
elemental function scali2p_sum_ten (scal, ten)
elemental function scali1p_sum_ten (scal, ten)
elemental function ten_sum_scalr8p (ten, scal)
elemental function ten_sum_scalr4p (ten, scal)
elemental function ten_sum_scali8p (ten, scal)
elemental function ten_sum_scali4p (ten, scal)
elemental function ten_sum_scali2p (ten, scal)
elemental function ten_sum_scali1p (ten, scal)
Member Function/Subroutine Documentation
elemental function data_type_tensor::operator(+)::positive_ten (type(type_tensor), intent(in) ten) private
Definition at line 1284 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::ten_sum_ten (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 1303 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::scalr8p_sum_ten (real(r8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1325 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::scalr4p_sum_ten (real(r4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1365 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::scali8p_sum_ten (integer(i8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1405 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::scali4p_sum_ten (integer(i4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1445 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::scali2p_sum_ten (integer(i2p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1485 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::scali1p_sum_ten (integer(i1p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1525 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::ten_sum_scalr8p (type(type_tensor), intent(in) ten, real(r8p), intent(in) scal) private
Definition at line 1345 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::ten_sum_scalr4p (type(type_tensor), intent(in) ten, real(r4p), intent(in) scal) private
Definition at line 1385 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::ten_sum_scali8p (type(type_tensor), intent(in) ten, integer(i8p), intent(in) scal) private
Definition at line 1425 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::ten_sum_scali4p (type(type_tensor), intent(in) ten, integer(i4p), intent(in) scal) private
Definition at line 1465 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::ten_sum_scali2p (type(type_tensor), intent(in) ten, integer(i2p), intent(in) scal) private
Definition at line 1505 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(+)::ten_sum_scali1p (type(type_tensor), intent(in) ten, integer(i1p), intent(in) scal) private
Definition at line 1545 of file Data_Type_Tensor.f90.
interface data_type_tensor::operator(-)
Subtraction operator (-) overloading.
Note
The admissible subtractions are:
Type_Tensor - Type_Tensor: each component of first tensor variable (ten1) is subtracted with the corresponding component of the second one (ten2), i.e.
scalar number (real or integer of any kinds defined in IR_Precision module) - Type_Tensor: each component of Type_Tensor is subtracted with the scalar, i.e.
Type_Tensor - scalar number (real or integer of any kinds defined in IR_Precision module): each component of Type_Tensor is subtracted with the scalar, i.e.
Definition at line 258 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function negative_ten (ten)
elemental function ten_sub_ten (ten1, ten2)
elemental function scalr8p_sub_ten (scal, ten)
elemental function scalr4p_sub_ten (scal, ten)
elemental function scali8p_sub_ten (scal, ten)
elemental function scali4p_sub_ten (scal, ten)
elemental function scali2p_sub_ten (scal, ten)
elemental function scali1p_sub_ten (scal, ten)
elemental function ten_sub_scalr8p (ten, scal)
elemental function ten_sub_scalr4p (ten, scal)
elemental function ten_sub_scali8p (ten, scal)
elemental function ten_sub_scali4p (ten, scal)
elemental function ten_sub_scali2p (ten, scal)
elemental function ten_sub_scali1p (ten, scal)
Member Function/Subroutine Documentation
elemental function data_type_tensor::operator(-)::negative_ten (type(type_tensor), intent(in) ten) private
Definition at line 1566 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::ten_sub_ten (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 1585 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::scalr8p_sub_ten (real(r8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1607 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::scalr4p_sub_ten (real(r4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1647 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::scali8p_sub_ten (integer(i8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1687 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::scali4p_sub_ten (integer(i4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1727 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::scali2p_sub_ten (integer(i2p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1767 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::scali1p_sub_ten (integer(i1p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1807 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::ten_sub_scalr8p (type(type_tensor), intent(in) ten, real(r8p), intent(in) scal) private
Definition at line 1627 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::ten_sub_scalr4p (type(type_tensor), intent(in) ten, real(r4p), intent(in) scal) private
Definition at line 1667 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::ten_sub_scali8p (type(type_tensor), intent(in) ten, integer(i8p), intent(in) scal) private
Definition at line 1707 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::ten_sub_scali4p (type(type_tensor), intent(in) ten, integer(i4p), intent(in) scal) private
Definition at line 1747 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::ten_sub_scali2p (type(type_tensor), intent(in) ten, integer(i2p), intent(in) scal) private
Definition at line 1787 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::operator(-)::ten_sub_scali1p (type(type_tensor), intent(in) ten, integer(i1p), intent(in) scal) private
Definition at line 1827 of file Data_Type_Tensor.f90.
interface data_type_tensor::operator(.ddot.)
Double dot product operator (.ddot.) definition.
Definition at line 282 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function ddotproduct (ten1, ten2)
Member Function/Subroutine Documentation
elemental function data_type_tensor::operator(.ddot.)::ddotproduct (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 1885 of file Data_Type_Tensor.f90.
interface data_type_tensor::operator(.dot.)
Dot product operator (.dot.) definition.
Definition at line 287 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function ten_dot_vec (ten, vec)
elemental function vec_dot_ten (vec, ten)
Member Function/Subroutine Documentation
elemental function data_type_tensor::operator(.dot.)::ten_dot_vec (type(type_tensor), intent(in) ten, type(type_vector), intent(in) vec) private
Definition at line 1848 of file Data_Type_Tensor.f90.
Referenced by data_type_tensor::transpose_self().
elemental function data_type_tensor::operator(.dot.)::vec_dot_ten (type(type_vector), intent(in) vec, type(type_tensor), intent(in) ten) private
Definition at line 1866 of file Data_Type_Tensor.f90.
interface data_type_tensor::operator(.diad.)
Diadic product operator (.diad.) definition.
Definition at line 292 of file Data_Type_Tensor.f90.
Private Member Functions
elemental function diadicproduct (vec1, vec2)
Member Function/Subroutine Documentation
elemental function data_type_tensor::operator(.diad.)::diadicproduct (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 1904 of file Data_Type_Tensor.f90.