OFF: POG.f90 File Reference
POG.f90 File Reference
Functions/Subroutines
program pog
POG, Post-processor Output Generator for OFF (Open Finite volume Fluid dynamics code).
subroutine print_usage ()
subroutine parsing_command_line ()
Function/Subroutine Documentation
subroutine pog::print_usage ()
Definition at line 98 of file POG.f90.
subroutine pog::parsing_command_line ()
Definition at line 150 of file POG.f90.
References data_type_time::get_date_string(), lib_io_misc::os, lib_postprocessing::pp_format, print_usage(), lib_io_misc::string_os_sep(), and lib_io_misc::upper_case().
Referenced by pog().