OFF: Lib_Runge_Kutta
Lib_Runge_Kutta
Public Procedures
subroutine, public lib_runge_kutta::rk_init (S)
Subroutine for initializing Runge-Kutta coefficients.
pure function, public lib_runge_kutta::rk_stage (s1, Dt, Un, KS)
Function for computing Runge-Kutta stage.
pure subroutine, public lib_runge_kutta::rk_time_integ (Dt, KS, R, Unp1)
Subroutine for computing Runge-Kutta one time step integration .
Detailed Description
Function/Subroutine Documentation
subroutine, public lib_runge_kutta::rk_init (integer(i1p), intent(in) S)
Subroutine for initializing Runge-Kutta coefficients.
Note
Currently 5 different schemes are available whose coefficients are (see definition in Runge-Kutta library):
1 stage: Forward Euler, one stage, order
2 stages: Strong Stability Preserving, two stages, order
3 stages: Strong Stability Preserving, three stages, order
4 stages: four stages, order
5 stages: Strong Stability Preserving, five stages, order
Parameters
[in] s Number of stages used.
Definition at line 106 of file Lib_Runge_Kutta.f90.
References lib_runge_kutta::c1, lib_runge_kutta::c2, and lib_runge_kutta::c3.
Referenced by off(), and off_init().
pure function, public lib_runge_kutta::rk_stage (integer(i1p), intent(in) s1, real(r_p), intent(in) Dt, real(r_p), intent(in) Un, real(r_p), dimension(1:), intent(in) KS)
Function for computing Runge-Kutta stage.
Note
For avoid the creation of temporary arrays (improving the efficiency) the array KS is declared as assumed-shape with only the lower bound defined. Its extention is [1:s1-1].
Parameters
[in] s1 Current Runge-Kutta stage number.
[in] dt Current time step.
[in] un Current integrating variable.
[in] ks Previous Runge-Kutta stages [1:s1-1].
Definition at line 180 of file Lib_Runge_Kutta.f90.
References lib_runge_kutta::c2.
Referenced by lib_fluidynamic::rk_time_integration().
pure subroutine, public lib_runge_kutta::rk_time_integ (real(r_p), intent(in) Dt, real(r_p), dimension(1:), intent(in) KS, real(r_p), intent(out), optional R, real(r_p), intent(inout) Unp1)
Subroutine for computing Runge-Kutta one time step integration .
Note
For avoid the creation of temporary arrays (improving the efficiency) the array KS is declared as assumed-shape with only the lower bound defined. Its extention is [1:rk_ord].
Parameters
[in] dt Current time step.
[in] ks Runge-Kutta stages.
[out] r Residual of integration.
[in,out] unp1 Time-integrated variable.
Definition at line 199 of file Lib_Runge_Kutta.f90.
References lib_runge_kutta::c1, and lib_thermodynamic_laws_ideal::r().
Referenced by lib_fluidynamic::solve_grl().