OFF: Data_Type_Time
Data_Type_Time
Public Procedures
character(20) function, public data_type_time::get_date_string ()
Function for getting actual date and returning it into a string.
elemental function, public data_type_time::seconds_to_time (seconds)
Function for converting seconds to Type_Time (days,hours,minutes,seconds) format.
real(r8p) function, public data_type_time::crono (start, instant1, instant0)
A simple stop/watch function.
Detailed Description
Function/Subroutine Documentation
character(20) function, public data_type_time::get_date_string ()
Function for getting actual date and returning it into a string.
Returns
Date_String character(20) variable.
Definition at line 318 of file Data_Type_Time.f90.
Referenced by ibm(), off_init(), and parsing_command_line().
elemental function, public data_type_time::seconds_to_time (real(r8p), intent(in) seconds)
Function for converting seconds to Type_Time (days,hours,minutes,seconds) format.
Returns
Time type(Type_Time) variable.
Parameters
[in] seconds Number of seconds.
Definition at line 345 of file Data_Type_Time.f90.
Referenced by lib_fluidynamic::solve_grl().
real(r8p) function, public data_type_time::crono (logical, intent(in), optional start, real(r8p), intent(in), optional instant1, logical, intent(in), optional instant0)
A simple stop/watch function.
Returns
seconds real(R8P) variable.
Parameters
[in] start Flag for starting time measurament.
[in] instant1 Seconds from instant1 (external supplied, different from instant0).
[in] instant0 Seconds from instant0.
Definition at line 363 of file Data_Type_Time.f90.
References lib_profiling::instant0.
Referenced by off_init(), and lib_fluidynamic::solve_grl().