#!MC 1120
# Created by Tecplot 360 build 11.3.29.563
$!VarSet |MFBD| = './'
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!OPENLAYOUT  "MYLAY.lay"
$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP EXPORTREGION = ALLFRAMES
$!EXPORTSETUP IMAGEWIDTH = 1024
$!EXPORTSETUP USESUPERSAMPLEANTIALIASING = YES
$!EXPORTSETUP EXPORTFNAME = 'MYLAY.png'
$!EXPORT
  EXPORTREGION = ALLFRAMES
$!RemoveVar |MFBD|
