OFF: Lib_VTK_IO
Lib_VTK_IO
Private Procedures
integer function lib_vtk_io::get_unit (Free_Unit)
Function for getting a free logic unit.
elemental character(len=len(string))
function lib_vtk_io::upper_case (string)
Function for converting lower case characters of a string to upper case ones.
elemental subroutine lib_vtk_io::byte_update (vtk, N_Byte)
Subroutine for updating N_Byte and ioffset pointer.
pure subroutine lib_vtk_io::vtk_update (act, cf, Nvtk, vtk)
Subroutine for updating (adding and removing elements into) vtk array.
pure function lib_vtk_io::tochar (string)
Function for converting array of 1 character to a string of characters.
integer(i4p) function lib_vtk_io::vtk_fld_xml_oc (fld_action, cf)
Function for open/close field data tag.
integer(i4p) function lib_vtk_io::vtk_fld_xml_r8 (fld, fname, cf)
Function for saving field data (global auxiliary data, e.g.
integer(i4p) function lib_vtk_io::vtk_fld_xml_r4 (fld, fname, cf)
Function for saving field data (global auxiliary data, e.g.
integer(i4p) function lib_vtk_io::vtk_fld_xml_i8 (fld, fname, cf)
Function for saving field data (global auxiliary data, e.g.
integer(i4p) function lib_vtk_io::vtk_fld_xml_i4 (fld, fname, cf)
Function for saving field data (global auxiliary data, e.g.
integer(i4p) function lib_vtk_io::vtk_fld_xml_i2 (fld, fname, cf)
Function for saving field data (global auxiliary data, e.g.
integer(i4p) function lib_vtk_io::vtk_fld_xml_i1 (fld, fname, cf)
Function for saving field data (global auxiliary data, e.g.
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_1da_r8 (nx1, nx2, ny1, ny2, nz1, nz2, NN, X, Y, Z, cf)
Function for saving mesh with StructuredGrid topology (R8P, 1D Arrays).
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_3da_r8 (nx1, nx2, ny1, ny2, nz1, nz2, NN, X, Y, Z, cf)
Function for saving mesh with StructuredGrid topology (R8P, 3D Arrays).
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_1dap_r8 (nx1, nx2, ny1, ny2, nz1, nz2, NN, XYZ, cf)
Function for saving mesh with StructuredGrid topology (R8P, 1D Arrays, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_3dap_r8 (nx1, nx2, ny1, ny2, nz1, nz2, NN, XYZ, cf)
Function for saving mesh with StructuredGrid topology (R8P, 3D Arrays, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_1da_r4 (nx1, nx2, ny1, ny2, nz1, nz2, NN, X, Y, Z, cf)
Function for saving mesh with StructuredGrid topology (R4P, 1D Arrays).
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_3da_r4 (nx1, nx2, ny1, ny2, nz1, nz2, NN, X, Y, Z, cf)
Function for saving mesh with StructuredGrid topology (R4P, 3D Arrays).
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_1dap_r4 (nx1, nx2, ny1, ny2, nz1, nz2, NN, XYZ, cf)
Function for saving mesh with StructuredGrid topology (R4P, 1D Arrays, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_3dap_r4 (nx1, nx2, ny1, ny2, nz1, nz2, NN, XYZ, cf)
Function for saving mesh with StructuredGrid topology (R4P, 3D Arrays, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_xml_rect_r8 (nx1, nx2, ny1, ny2, nz1, nz2, X, Y, Z, cf)
Function for saving mesh with RectilinearGrid topology (R8P).
integer(i4p) function lib_vtk_io::vtk_geo_xml_rect_r4 (nx1, nx2, ny1, ny2, nz1, nz2, X, Y, Z, cf)
Function for saving mesh with RectilinearGrid topology (R4P).
integer(i4p) function lib_vtk_io::vtk_geo_xml_unst_r8 (NN, NC, X, Y, Z, cf)
Function for saving mesh with UnstructuredGrid topology (R8P).
integer(i4p) function lib_vtk_io::vtk_geo_xml_unst_pack_r8 (NN, NC, XYZ, cf)
Function for saving mesh with UnstructuredGrid topology (R8P, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_xml_unst_r4 (NN, NC, X, Y, Z, cf)
Function for saving mesh with UnstructuredGrid topology (R4P).
integer(i4p) function lib_vtk_io::vtk_geo_xml_unst_pack_r4 (NN, NC, XYZ, cf)
Function for saving mesh with UnstructuredGrid topology (R4P, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_xml_closep (cf)
Function for closing mesh block data.
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_r8 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (R8P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_r8 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (R8P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_r4 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (R4P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_r4 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (R4P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_i8 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I8P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_i8 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I8P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_i4 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I4P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_i4 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I4P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_i2 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I2P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_i2 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I2P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_i1 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I1P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_i1 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I1P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_r8 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (R8P, 1D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_r8 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (R8P, 3D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_r4 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (R4P, 1D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_r4 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (R4P, 3D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_i8 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I8P, 1D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_i8 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I8P, 3D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_i4 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I4P, 1D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_i4 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I4P, 3D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_i2 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I2P, 1D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_i2 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I2P, 3D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_i1 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I1P, 1D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_i1 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I1P, 3D arrays).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_r8 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (R8P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_r8 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (R8P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_r4 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (R4P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_r4 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (R4P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_i8 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (I8P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_i8 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (I8P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_i4 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (I4P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_i4 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (I4P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_i2 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (I2P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_i2 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (I2P, 3D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_i1 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (I1P, 1D array).
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_i1 (NC_NN, N_COL, varname, var, cf)
Function for saving field of list variable (I1P, 3D array).
integer(i4p) function lib_vtk_io::vtk_geo_strp_r8 (Nx, Ny, Nz, X0, Y0, Z0, Dx, Dy, Dz, cf)
Function for saving mesh with STRUCTURED_POINTS topology (R8P).
integer(i4p) function lib_vtk_io::vtk_geo_strp_r4 (Nx, Ny, Nz, X0, Y0, Z0, Dx, Dy, Dz, cf)
Function for saving mesh with STRUCTURED_POINTS topology (R4P).
integer(i4p) function lib_vtk_io::vtk_geo_strg_1da_r8 (Nx, Ny, Nz, NN, X, Y, Z, cf)
Function for saving mesh with STRUCTURED_GRID topology (R8P, 1D arrays).
integer(i4p) function lib_vtk_io::vtk_geo_strg_1dap_r8 (Nx, Ny, Nz, NN, XYZ, cf)
Function for saving mesh with STRUCTURED_GRID topology (R8P, 1D arrays, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_strg_3da_r8 (Nx, Ny, Nz, NN, X, Y, Z, cf)
Function for saving mesh with STRUCTURED_GRID topology (R8P, 3D arrays).
integer(i4p) function lib_vtk_io::vtk_geo_strg_3dap_r8 (Nx, Ny, Nz, NN, XYZ, cf)
Function for saving mesh with STRUCTURED_GRID topology (R8P, 3D arrays, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_strg_1da_r4 (Nx, Ny, Nz, NN, X, Y, Z, cf)
Function for saving mesh with STRUCTURED_GRID topology (R4P, 1D arrays).
integer(i4p) function lib_vtk_io::vtk_geo_strg_1dap_r4 (Nx, Ny, Nz, NN, XYZ, cf)
Function for saving mesh with STRUCTURED_GRID topology (R4P, 1D arrays, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_strg_3da_r4 (Nx, Ny, Nz, NN, X, Y, Z, cf)
Function for saving mesh with STRUCTURED_GRID topology (R4P, 3D arrays).
integer(i4p) function lib_vtk_io::vtk_geo_strg_3dap_r4 (Nx, Ny, Nz, NN, XYZ, cf)
Function for saving mesh with STRUCTURED_GRID topology (R4P, 3D arrays, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_rect_r8 (Nx, Ny, Nz, X, Y, Z, cf)
Function for saving mesh with RECTILINEAR_GRID topology (R8P).
integer(i4p) function lib_vtk_io::vtk_geo_rect_r4 (Nx, Ny, Nz, X, Y, Z, cf)
Function for saving mesh with RECTILINEAR_GRID topology (R4P).
integer(i4p) function lib_vtk_io::vtk_geo_unst_r8 (NN, X, Y, Z, cf)
Function for saving mesh with UNSTRUCTURED_GRID topology (R8P).
integer(i4p) function lib_vtk_io::vtk_geo_unst_p_r8 (NN, XYZ, cf)
Function for saving mesh with UNSTRUCTURED_GRID topology (R8P, packed API).
integer(i4p) function lib_vtk_io::vtk_geo_unst_r4 (NN, X, Y, Z, cf)
Function for saving mesh with UNSTRUCTURED_GRID topology (R4P).
integer(i4p) function lib_vtk_io::vtk_geo_unst_p_r4 (NN, XYZ, cf)
Function for saving mesh with UNSTRUCTURED_GRID topology (R4P, packed API).
integer(i4p) function lib_vtk_io::vtk_var_scal_r8 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (R8P).
integer(i4p) function lib_vtk_io::vtk_var_scal_r4 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (R4P).
integer(i4p) function lib_vtk_io::vtk_var_scal_i4 (NC_NN, varname, var, cf)
Function for saving field of scalar variable (I4P).
integer(i4p) function lib_vtk_io::vtk_var_vect_r8 (vec_type, NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (R8P).
integer(i4p) function lib_vtk_io::vtk_var_vect_r4 (vec_type, NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (R4P).
integer(i4p) function lib_vtk_io::vtk_var_vect_i4 (NC_NN, varname, varX, varY, varZ, cf)
Function for saving field of vectorial variable (I4P).
integer(i4p) function lib_vtk_io::vtk_var_text_r8 (NC_NN, dimm, varname, textCoo, cf)
Function for saving texture variable (R8P).
integer(i4p) function lib_vtk_io::vtk_var_text_r4 (NC_NN, dimm, varname, textCoo, cf)
Function for saving texture variable (R4P).
Detailed Description
Function/Subroutine Documentation
integer function lib_vtk_io::get_unit (integer, intent(out), optional Free_Unit) private
Function for getting a free logic unit.
The users of Lib_VTK_IO does not know which is the logical unit: Lib_VTK_IO uses this information without boring the users. The logical unit used is safe-free: if the program calling Lib_VTK_IO has others logical units used Lib_VTK_IO will never use these units, but will choice one that is free.
Returns
Free_Unit
Parameters
[out] free_unit Free logic unit.
Definition at line 485 of file Lib_VTK_IO.f90.
References lib_io_misc::get_unit().
integer(i4p) function lib_vtk_io::vtk_fld_xml_oc (character(*), intent(in) fld_action, integer(i4p), intent(in), optional cf) private
Function for open/close field data tag.
Returns
E_IO: integer(I4P) error flag
Parameters
[in] fld_action Field data tag action: OPEN or CLOSE tag.
[in] cf Current file index (for concurrent files IO).
Definition at line 772 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, lib_vtk_io::end_rec, lib_vtk_io::f, lib_vtk_io::raw, and lib_io_misc::upper_case().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_r8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r8p), dimension(1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (R8P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 2434 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_strp_r8 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, real(r8p), intent(in) X0, real(r8p), intent(in) Y0, real(r8p), intent(in) Z0, real(r8p), intent(in) Dx, real(r8p), intent(in) Dy, real(r8p), intent(in) Dz, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_POINTS topology (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] x0 X coordinate of origin.
[in] y0 Y coordinate of origin.
[in] z0 Z coordinate of origin.
[in] dx Space step in x direction.
[in] dy Space step in y direction.
[in] dz Space step in z direction.
[in] cf Current file index (for concurrent files IO).
Definition at line 4922 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_var_scal_r8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r8p), dimension(1:nc_nn), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of nodes or cells.
[in] varname Variable name.
[in] var Variable to be saved.
[in] cf Current file index (for concurrent files IO).
Definition at line 5720 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fr8p, and lib_vtk_io::raw.
elemental character(len=len(string)) function lib_vtk_io::upper_case (character(len=*), intent(in) string) private
Function for converting lower case characters of a string to upper case ones.
Lib_VTK_IO uses this function in order to achieve case-insensitive: all character variables used within Lib_VTK_IO functions are pre-processed by Uppper_Case function before these variables are used. So the users can call Lib_VTK_IO functions without pay attention of the case of the keywords passed to the functions: calling the function VTK_INI with the string E_IO = VTK_INI('Ascii',...) is equivalent to E_IO = VTK_INI('ASCII',...).
Returns
Upper_Case
Parameters
[in] string String to be converted.
Definition at line 519 of file Lib_VTK_IO.f90.
References lib_io_misc::upper_case().
elemental subroutine lib_vtk_io::byte_update (class(type_vtk_file), intent(inout) vtk, integer(i4p), intent(in) N_Byte) private
Subroutine for updating N_Byte and ioffset pointer.
Parameters
[in,out] vtk Global data of VTK file.
[in] n_byte Number of bytes saved.
Definition at line 540 of file Lib_VTK_IO.f90.
References ir_precision::byi4p, ir_precision::byi8p, and lib_vtk_io::raw.
pure subroutine lib_vtk_io::vtk_update (character(*), intent(in) act, integer(i4p), intent(inout) cf, integer(i4p), intent(inout) Nvtk, type(type_vtk_file), dimension(:), intent(inout), allocatable vtk) private
Subroutine for updating (adding and removing elements into) vtk array.
Parameters
[in] act Action: 'ADD' one more element, 'REMOVE' current element file.
[in,out] cf Current file index (for concurrent files IO).
[in,out] nvtk Number of (concurrent) VTK files.
[in,out] vtk VTK files data.
Definition at line 571 of file Lib_VTK_IO.f90.
References lib_io_misc::upper_case().
Referenced by lib_vtk_io::pvtk_end_xml(), lib_vtk_io::pvtk_ini_xml(), lib_vtk_io::vtk_end(), lib_vtk_io::vtk_end_xml(), lib_vtk_io::vtk_ini(), and lib_vtk_io::vtk_ini_xml().
pure function lib_vtk_io::tochar (character(1), dimension(1:), intent(in) string) private
Function for converting array of 1 character to a string of characters.
It is used for writing the stream of base64 encoded data.
Parameters
[in] string Array of 1 character.
Definition at line 625 of file Lib_VTK_IO.f90.
Referenced by lib_vtk_io::vtk_con_xml(), lib_vtk_io::vtk_end_xml(), lib_vtk_io::vtk_fld_xml_i1(), lib_vtk_io::vtk_fld_xml_i2(), lib_vtk_io::vtk_fld_xml_i4(), lib_vtk_io::vtk_fld_xml_i8(), lib_vtk_io::vtk_fld_xml_r4(), lib_vtk_io::vtk_fld_xml_r8(), lib_vtk_io::vtk_geo_xml_rect_r4(), lib_vtk_io::vtk_geo_xml_rect_r8(), lib_vtk_io::vtk_geo_xml_strg_1da_r4(), lib_vtk_io::vtk_geo_xml_strg_1da_r8(), lib_vtk_io::vtk_geo_xml_strg_1dap_r4(), lib_vtk_io::vtk_geo_xml_strg_1dap_r8(), lib_vtk_io::vtk_geo_xml_strg_3da_r4(), lib_vtk_io::vtk_geo_xml_strg_3da_r8(), lib_vtk_io::vtk_geo_xml_strg_3dap_r4(), lib_vtk_io::vtk_geo_xml_strg_3dap_r8(), lib_vtk_io::vtk_geo_xml_unst_pack_r4(), lib_vtk_io::vtk_geo_xml_unst_pack_r8(), lib_vtk_io::vtk_geo_xml_unst_r4(), lib_vtk_io::vtk_geo_xml_unst_r8(), lib_vtk_io::vtk_var_xml_list_1da_i1(), lib_vtk_io::vtk_var_xml_list_1da_i2(), lib_vtk_io::vtk_var_xml_list_1da_i4(), lib_vtk_io::vtk_var_xml_list_1da_i8(), lib_vtk_io::vtk_var_xml_list_1da_r4(), lib_vtk_io::vtk_var_xml_list_1da_r8(), lib_vtk_io::vtk_var_xml_list_3da_i1(), lib_vtk_io::vtk_var_xml_list_3da_i2(), lib_vtk_io::vtk_var_xml_list_3da_i4(), lib_vtk_io::vtk_var_xml_list_3da_i8(), lib_vtk_io::vtk_var_xml_list_3da_r4(), lib_vtk_io::vtk_var_xml_list_3da_r8(), lib_vtk_io::vtk_var_xml_scal_1da_i1(), lib_vtk_io::vtk_var_xml_scal_1da_i2(), lib_vtk_io::vtk_var_xml_scal_1da_i4(), lib_vtk_io::vtk_var_xml_scal_1da_i8(), lib_vtk_io::vtk_var_xml_scal_1da_r4(), lib_vtk_io::vtk_var_xml_scal_1da_r8(), lib_vtk_io::vtk_var_xml_scal_3da_i1(), lib_vtk_io::vtk_var_xml_scal_3da_i2(), lib_vtk_io::vtk_var_xml_scal_3da_i4(), lib_vtk_io::vtk_var_xml_scal_3da_i8(), lib_vtk_io::vtk_var_xml_scal_3da_r4(), lib_vtk_io::vtk_var_xml_scal_3da_r8(), lib_vtk_io::vtk_var_xml_vect_1da_i1(), lib_vtk_io::vtk_var_xml_vect_1da_i2(), lib_vtk_io::vtk_var_xml_vect_1da_i4(), lib_vtk_io::vtk_var_xml_vect_1da_i8(), lib_vtk_io::vtk_var_xml_vect_1da_r4(), lib_vtk_io::vtk_var_xml_vect_1da_r8(), lib_vtk_io::vtk_var_xml_vect_3da_i1(), lib_vtk_io::vtk_var_xml_vect_3da_i2(), lib_vtk_io::vtk_var_xml_vect_3da_i4(), lib_vtk_io::vtk_var_xml_vect_3da_i8(), lib_vtk_io::vtk_var_xml_vect_3da_r4(), and lib_vtk_io::vtk_var_xml_vect_3da_r8().
integer(i4p) function lib_vtk_io::vtk_fld_xml_r8 (real(r8p), intent(in) fld, character(*), intent(in) fname, integer(i4p), intent(in), optional cf) private
Function for saving field data (global auxiliary data, e.g.
time, step number, data set name...) (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] fld Field data value.
[in] fname Field data name.
[in] cf Current file index (for concurrent files IO).
Definition at line 809 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_fld_xml_r4 (real(r4p), intent(in) fld, character(*), intent(in) fname, integer(i4p), intent(in), optional cf) private
Function for saving field data (global auxiliary data, e.g.
time, step number, data set name...) (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] fld Field data value.
[in] fname Field data name.
[in] cf Current file index (for concurrent files IO).
Definition at line 854 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_fld_xml_i8 (integer(i8p), intent(in) fld, character(*), intent(in) fname, integer(i4p), intent(in), optional cf) private
Function for saving field data (global auxiliary data, e.g.
time, step number, data set name...) (I8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] fld Field data value.
[in] fname Field data name.
[in] cf Current file index (for concurrent files IO).
Definition at line 899 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_fld_xml_i4 (integer(i4p), intent(in) fld, character(*), intent(in) fname, integer(i4p), intent(in), optional cf) private
Function for saving field data (global auxiliary data, e.g.
time, step number, data set name...) (I4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] fld Field data value.
[in] fname Field data name.
[in] cf Current file index (for concurrent files IO).
Definition at line 944 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_fld_xml_i2 (integer(i2p), intent(in) fld, character(*), intent(in) fname, integer(i4p), intent(in), optional cf) private
Function for saving field data (global auxiliary data, e.g.
time, step number, data set name...) (I2P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] fld Field data value.
[in] fname Field data name.
[in] cf Current file index (for concurrent files IO).
Definition at line 989 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi2p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_fld_xml_i1 (integer(i1p), intent(in) fld, character(*), intent(in) fname, integer(i4p), intent(in), optional cf) private
Function for saving field data (global auxiliary data, e.g.
time, step number, data set name...) (I1P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] fld Field data value.
[in] fname Field data name.
[in] cf Current file index (for concurrent files IO).
Definition at line 1034 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_1da_r8 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, integer(i4p), intent(in) NN, real(r8p), dimension(1:), intent(in) X, real(r8p), dimension(1:), intent(in) Y, real(r8p), dimension(1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with StructuredGrid topology (R8P, 1D Arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] nn Number of all nodes.
[in] x X coordinates [1:NN].
[in] y Y coordinates [1:NN].
[in] z Z coordinates [1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 1079 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_3da_r8 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, integer(i4p), intent(in) NN, real(r8p), dimension(nx1:,ny1:,nz1:), intent(in) X, real(r8p), dimension(nx1:,ny1:,nz1:), intent(in) Y, real(r8p), dimension(nx1:,ny1:,nz1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with StructuredGrid topology (R8P, 3D Arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] nn Number of all nodes.
[in] x X coordinates [nx1:nx2,ny1:ny2,nz1:nz2].
[in] y Y coordinates [nx1:nx2,ny1:ny2,nz1:nz2].
[in] z Z coordinates [nx1:nx2,ny1:ny2,nz1:nz2].
[in] cf Current file index (for concurrent files IO).
Definition at line 1155 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_1dap_r8 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, integer(i4p), intent(in) NN, real(r8p), dimension(1:,1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with StructuredGrid topology (R8P, 1D Arrays, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] nn Number of all nodes.
[in] xyz X, Y, Z coordinates (packed API) [1:3,1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 1237 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_3dap_r8 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, integer(i4p), intent(in) NN, real(r8p), dimension(1:,nx1:,ny1:,nz1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with StructuredGrid topology (R8P, 3D Arrays, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] nn Number of all nodes.
[in] xyz X, Y, Z coordinates (packed API).
[in] cf Current file index (for concurrent files IO).
Definition at line 1312 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_1da_r4 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, integer(i4p), intent(in) NN, real(r4p), dimension(1:), intent(in) X, real(r4p), dimension(1:), intent(in) Y, real(r4p), dimension(1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with StructuredGrid topology (R4P, 1D Arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] nn Number of all nodes.
[in] x X coordinates [1:NN].
[in] y Y coordinates [1:NN].
[in] z Z coordinates [1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 1391 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_3da_r4 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, integer(i4p), intent(in) NN, real(r4p), dimension(nx1:,ny1:,nz1:), intent(in) X, real(r4p), dimension(nx1:,ny1:,nz1:), intent(in) Y, real(r4p), dimension(nx1:,ny1:,nz1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with StructuredGrid topology (R4P, 3D Arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] nn Number of all nodes.
[in] x X coordinates [nx1:nx2,ny1:ny2,nz1:nz2].
[in] y Y coordinates [nx1:nx2,ny1:ny2,nz1:nz2].
[in] z Z coordinates [nx1:nx2,ny1:ny2,nz1:nz2].
[in] cf Current file index (for concurrent files IO).
Definition at line 1467 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_1dap_r4 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, integer(i4p), intent(in) NN, real(r4p), dimension(1:,1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with StructuredGrid topology (R4P, 1D Arrays, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] nn Number of all nodes.
[in] xyz X, Y, Z coordinates (packed API) [1:3,1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 1549 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_strg_3dap_r4 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, integer(i4p), intent(in) NN, real(r4p), dimension(1:,nx1:,ny1:,nz1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with StructuredGrid topology (R4P, 3D Arrays, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] nn Number of all nodes.
[in] xyz X, Y, Z coordinates (packed API) [1:3,nx1:nx2,ny1:ny2,nz1:nz2].
[in] cf Current file index (for concurrent files IO).
Definition at line 1624 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_rect_r8 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, real(r8p), dimension(nx1:nx2), intent(in) X, real(r8p), dimension(ny1:ny2), intent(in) Y, real(r8p), dimension(nz1:nz2), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with RectilinearGrid topology (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] x X coordinates.
[in] y Y coordinates.
[in] z Z coordinates.
[in] cf Current file index (for concurrent files IO).
Definition at line 1703 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fr8p, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_rect_r4 (integer(i4p), intent(in) nx1, integer(i4p), intent(in) nx2, integer(i4p), intent(in) ny1, integer(i4p), intent(in) ny2, integer(i4p), intent(in) nz1, integer(i4p), intent(in) nz2, real(r4p), dimension(nx1:nx2), intent(in) X, real(r4p), dimension(ny1:ny2), intent(in) Y, real(r4p), dimension(nz1:nz2), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with RectilinearGrid topology (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] x X coordinates.
[in] y Y coordinates.
[in] z Z coordinates.
[in] cf Current file index (for concurrent files IO).
Definition at line 1806 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fr4p, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_unst_r8 (integer(i4p), intent(in) NN, integer(i4p), intent(in) NC, real(r8p), dimension(1:nn), intent(in) X, real(r8p), dimension(1:nn), intent(in) Y, real(r8p), dimension(1:nn), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with UnstructuredGrid topology (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nn Number of nodes.
[in] nc Number of cells.
[in] x X coordinates.
[in] y Y coordinates.
[in] z Z coordinates.
[in] cf Current file index (for concurrent files IO).
Definition at line 1909 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_unst_pack_r8 (integer(i4p), intent(in) NN, integer(i4p), intent(in) NC, real(r8p), dimension(1:3,1:nn), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with UnstructuredGrid topology (R8P, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nn Number of nodes.
[in] nc Number of cells.
[in] xyz X, Y, Z coordinates (packed API).
[in] cf Current file index (for concurrent files IO).
Definition at line 1979 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_unst_r4 (integer(i4p), intent(in) NN, integer(i4p), intent(in) NC, real(r4p), dimension(1:nn), intent(in) X, real(r4p), dimension(1:nn), intent(in) Y, real(r4p), dimension(1:nn), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with UnstructuredGrid topology (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nn Number of nodes.
[in] nc Number of cells.
[in] x X coordinates.
[in] y Y coordinates.
[in] z Z coordinates.
[in] cf Current file index (for concurrent files IO).
Definition at line 2048 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_unst_pack_r4 (integer(i4p), intent(in) NN, integer(i4p), intent(in) NC, real(r4p), dimension(1:3,1:nn), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with UnstructuredGrid topology (R4P, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nn Number of nodes.
[in] nc Number of cells.
[in] xyz X, Y, Z coordinates (packed API).
[in] cf Current file index (for concurrent files IO).
Definition at line 2118 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_xml_closep (integer(i4p), intent(in), optional cf) private
Function for closing mesh block data.
Returns
E_IO: integer(I4P) error flag
Parameters
[in] cf Current file index (for concurrent files IO).
Definition at line 2187 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_r8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r8p), dimension(1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (R8P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 2484 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_r4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r4p), dimension(1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (R4P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 2535 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_r4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r4p), dimension(1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (R4P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 2585 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_i8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i8p), dimension(1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I8P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 2636 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_i8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i8p), dimension(1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I8P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 2686 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_i4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i4p), dimension(1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I4P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 2737 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_i4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i4p), dimension(1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I4P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 2788 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_i2 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i2p), dimension(1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I2P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 2840 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi2p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_i2 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i2p), dimension(1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I2P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 2890 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi2p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_1da_i1 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i1p), dimension(1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I1P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 2941 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_scal_3da_i1 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i1p), dimension(1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I1P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved [1:Nx,1:ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 2990 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_r8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r8p), dimension(1:), intent(in) varX, real(r8p), dimension(1:), intent(in) varY, real(r8p), dimension(1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (R8P, 1D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:NC_NN].
[in] vary Y component [1:NC_NN].
[in] varz Z component [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3040 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_r8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r8p), dimension(1:,1:,1:), intent(in) varX, real(r8p), dimension(1:,1:,1:), intent(in) varY, real(r8p), dimension(1:,1:,1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (R8P, 3D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:Nx,1:Ny,1:Nz].
[in] vary Y component [1:Nx,1:Ny,1:Nz].
[in] varz Z component [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 3099 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_r4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r4p), dimension(1:), intent(in) varX, real(r4p), dimension(1:), intent(in) varY, real(r4p), dimension(1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (R4P, 1D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:NC_NN].
[in] vary Y component [1:NC_NN].
[in] varz Z component [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3161 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_r4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r4p), dimension(1:,1:,1:), intent(in) varX, real(r4p), dimension(1:,1:,1:), intent(in) varY, real(r4p), dimension(1:,1:,1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (R4P, 3D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:Nx,1:Ny,1:Nz].
[in] vary Y component [1:Nx,1:Ny,1:Nz].
[in] varz Z component [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 3220 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_i8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i8p), dimension(1:), intent(in) varX, integer(i8p), dimension(1:), intent(in) varY, integer(i8p), dimension(1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I8P, 1D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:NC_NN].
[in] vary Y component [1:NC_NN].
[in] varz Z component [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3282 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_i8 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i8p), dimension(1:,1:,1:), intent(in) varX, integer(i8p), dimension(1:,1:,1:), intent(in) varY, integer(i8p), dimension(1:,1:,1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I8P, 3D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:Nx,1:Ny,1:Nz].
[in] vary Y component [1:Nx,1:Ny,1:Nz].
[in] varz Z component [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 3341 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_i4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i4p), dimension(1:), intent(in) varX, integer(i4p), dimension(1:), intent(in) varY, integer(i4p), dimension(1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I4P, 1D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:NC_NN].
[in] vary Y component [1:NC_NN].
[in] varz Z component [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3403 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_i4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i4p), dimension(1:,1:,1:), intent(in) varX, integer(i4p), dimension(1:,1:,1:), intent(in) varY, integer(i4p), dimension(1:,1:,1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I4P, 3D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:Nx,1:Ny,1:Nz].
[in] vary Y component [1:Nx,1:Ny,1:Nz].
[in] varz Z component [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 3463 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_i2 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i2p), dimension(1:), intent(in) varX, integer(i2p), dimension(1:), intent(in) varY, integer(i2p), dimension(1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I2P, 1D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:NC_NN].
[in] vary Y component [1:NC_NN].
[in] varz Z component [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3526 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi2p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_i2 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i2p), dimension(1:,1:,1:), intent(in) varX, integer(i2p), dimension(1:,1:,1:), intent(in) varY, integer(i2p), dimension(1:,1:,1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I2P, 3D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:Nx,1:Ny,1:Nz].
[in] vary Y component [1:Nx,1:Ny,1:Nz].
[in] varz Z component [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 3585 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi2p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_1da_i1 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i1p), dimension(1:), intent(in) varX, integer(i1p), dimension(1:), intent(in) varY, integer(i1p), dimension(1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I1P, 1D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:NC_NN].
[in] vary Y component [1:NC_NN].
[in] varz Z component [1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3647 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_vect_3da_i1 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i1p), dimension(1:,1:,1:), intent(in) varX, integer(i1p), dimension(1:,1:,1:), intent(in) varY, integer(i1p), dimension(1:,1:,1:), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I1P, 3D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] varname Variable name.
[in] varx X component [1:Nx,1:Ny,1:Nz].
[in] vary Y component [1:Nx,1:Ny,1:Nz].
[in] varz Z component [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 3706 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_r8 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, real(r8p), dimension(1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (R8P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3768 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_r8 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, real(r8p), dimension(1:,1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (R8P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 3822 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_r4 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, real(r4p), dimension(1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (R4P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3876 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_r4 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, real(r4p), dimension(1:,1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (R4P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 3930 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byr4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_i8 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, integer(i8p), dimension(1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (I8P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 3984 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_i8 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, integer(i8p), dimension(1:,1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (I8P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 4038 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi8p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_i4 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, integer(i4p), dimension(1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (I4P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 4092 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_i4 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, integer(i4p), dimension(1:,1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (I4P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 4147 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi4p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_i2 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, integer(i2p), dimension(1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (I2P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 4202 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi2p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_i2 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, integer(i2p), dimension(1:,1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (I2P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 4256 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, ir_precision::byi2p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_1da_i1 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, integer(i1p), dimension(1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (I1P, 1D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:NC_NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 4310 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_var_xml_list_3da_i1 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) N_COL, character(*), intent(in) varname, integer(i1p), dimension(1:,1:,1:,1:), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of list variable (I1P, 3D array).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of cells or nodes.
[in] n_col Number of columns.
[in] varname Variable name.
[in] var Components [1:N_COL,1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 4364 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::bin_app, lib_vtk_io::binary, ir_precision::byi1p, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::i4p, lib_vtk_io::raw, and lib_vtk_io::tochar().
integer(i4p) function lib_vtk_io::vtk_geo_strp_r4 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, real(r4p), intent(in) X0, real(r4p), intent(in) Y0, real(r4p), intent(in) Z0, real(r4p), intent(in) Dx, real(r4p), intent(in) Dy, real(r4p), intent(in) Dz, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_POINTS topology (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] x0 X coordinate of origin.
[in] y0 Y coordinate of origin.
[in] z0 Z coordinate of origin.
[in] dx Space step in x direction.
[in] dy Space step in y direction.
[in] dz Space step in z direction.
[in] cf Current file index (for concurrent files IO).
Definition at line 4961 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_strg_1da_r8 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, integer(i4p), intent(in) NN, real(r8p), dimension(1:), intent(in) X, real(r8p), dimension(1:), intent(in) Y, real(r8p), dimension(1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_GRID topology (R8P, 1D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] nn Number of all nodes.
[in] x X coordinates [1:NN].
[in] y Y coordinates [1:NN].
[in] z Z coordinates [1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 5000 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_strg_1dap_r8 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, integer(i4p), intent(in) NN, real(r8p), dimension(1:,1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_GRID topology (R8P, 1D arrays, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] nn Number of all nodes.
[in] xyz X, Y and Z coordinates [1:3,1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 5041 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_strg_3da_r8 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, integer(i4p), intent(in) NN, real(r8p), dimension(1:,1:,1:), intent(in) X, real(r8p), dimension(1:,1:,1:), intent(in) Y, real(r8p), dimension(1:,1:,1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_GRID topology (R8P, 3D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] nn Number of all nodes.
[in] x X coordinates [1:Nx,1:Ny,1:Nz].
[in] y Y coordinates [1:Nx,1:Ny,1:Nz].
[in] z Z coordinates [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 5080 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_strg_3dap_r8 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, integer(i4p), intent(in) NN, real(r8p), dimension(1:,1:,1:,1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_GRID topology (R8P, 3D arrays, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] nn Number of all nodes.
[in] xyz X, Y and Z coordinates [1:3,1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 5125 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_strg_1da_r4 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, integer(i4p), intent(in) NN, real(r4p), dimension(1:), intent(in) X, real(r4p), dimension(1:), intent(in) Y, real(r4p), dimension(1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_GRID topology (R4P, 1D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] nn Number of all nodes.
[in] x X coordinates [1:NN].
[in] y Y coordinates [1:NN].
[in] z Z coordinates [1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 5168 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_strg_1dap_r4 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, integer(i4p), intent(in) NN, real(r4p), dimension(1:,1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_GRID topology (R4P, 1D arrays, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] nn Number of all nodes.
[in] xyz X, Y and Z coordinates [1:3,1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 5209 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_strg_3da_r4 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, integer(i4p), intent(in) NN, real(r4p), dimension(1:,1:,1:), intent(in) X, real(r4p), dimension(1:,1:,1:), intent(in) Y, real(r4p), dimension(1:,1:,1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_GRID topology (R4P, 3D arrays).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] nn Number of all nodes.
[in] x X coordinates [1:Nx,1:Ny,1:Nz].
[in] y Y coordinates [1:Nx,1:Ny,1:Nz].
[in] z Z coordinates [1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 5248 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_strg_3dap_r4 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, integer(i4p), intent(in) NN, real(r4p), dimension(1:,1:,1:,1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with STRUCTURED_GRID topology (R4P, 3D arrays, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] nn Number of all nodes.
[in] xyz X, Y and Z coordinates [1:3,1:Nx,1:Ny,1:Nz].
[in] cf Current file index (for concurrent files IO).
Definition at line 5293 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_rect_r8 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, real(r8p), dimension(1:nx), intent(in) X, real(r8p), dimension(1:ny), intent(in) Y, real(r8p), dimension(1:nz), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with RECTILINEAR_GRID topology (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] x X coordinates.
[in] y Y coordinates.
[in] z Z coordinates.
[in] cf Current file index (for concurrent files IO).
Definition at line 5336 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_rect_r4 (integer(i4p), intent(in) Nx, integer(i4p), intent(in) Ny, integer(i4p), intent(in) Nz, real(r4p), dimension(1:nx), intent(in) X, real(r4p), dimension(1:ny), intent(in) Y, real(r4p), dimension(1:nz), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with RECTILINEAR_GRID topology (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nx Number of nodes in x direction.
[in] ny Number of nodes in y direction.
[in] nz Number of nodes in z direction.
[in] x X coordinates.
[in] y Y coordinates.
[in] z Z coordinates.
[in] cf Current file index (for concurrent files IO).
Definition at line 5390 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_unst_r8 (integer(i4p), intent(in) NN, real(r8p), dimension(1:), intent(in) X, real(r8p), dimension(1:), intent(in) Y, real(r8p), dimension(1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with UNSTRUCTURED_GRID topology (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nn Number of nodes.
[in] x X coordinates of all nodes [1:NN].
[in] y Y coordinates of all nodes [1:NN].
[in] z Z coordinates of all nodes [1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 5444 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_unst_p_r8 (integer(i4p), intent(in) NN, real(r8p), dimension(1:,1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with UNSTRUCTURED_GRID topology (R8P, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nn Number of nodes.
[in] xyz X, Y and Z coordinates of all nodes [1:3,1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 5480 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_unst_r4 (integer(i4p), intent(in) NN, real(r4p), dimension(1:), intent(in) X, real(r4p), dimension(1:), intent(in) Y, real(r4p), dimension(1:), intent(in) Z, integer(i4p), intent(in), optional cf) private
Function for saving mesh with UNSTRUCTURED_GRID topology (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nn number of nodes.
[in] x X coordinates of all nodes [1:NN].
[in] y Y coordinates of all nodes [1:NN].
[in] z Z coordinates of all nodes [1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 5514 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_geo_unst_p_r4 (integer(i4p), intent(in) NN, real(r4p), dimension(1:,1:), intent(in) XYZ, integer(i4p), intent(in), optional cf) private
Function for saving mesh with UNSTRUCTURED_GRID topology (R4P, packed API).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nn number of nodes.
[in] xyz X, Y and Z coordinates of all nodes [1:3,1:NN].
[in] cf Current file index (for concurrent files IO).
Definition at line 5550 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_var_scal_r4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r4p), dimension(1:nc_nn), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of nodes or cells.
[in] varname Variable name.
[in] var Variable to be saved.
[in] cf Current file index (for concurrent files IO).
Definition at line 5754 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fr4p, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_var_scal_i4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i4p), dimension(1:nc_nn), intent(in) var, integer(i4p), intent(in), optional cf) private
Function for saving field of scalar variable (I4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of nodes or cells.
[in] varname Variable name.
[in] var Variable to be saved.
[in] cf Current file index (for concurrent files IO).
Definition at line 5788 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fi4p, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_var_vect_r8 (character(*), intent(in) vec_type, integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r8p), dimension(1:nc_nn), intent(in) varX, real(r8p), dimension(1:nc_nn), intent(in) varY, real(r8p), dimension(1:nc_nn), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] vec_type Vector type: vect = generic vector , norm = normal vector.
[in] nc_nn Number of nodes or cells.
[in] varname Variable name.
[in] varx X component of vector.
[in] vary Y component of vector.
[in] varz Z component of vector.
[in] cf Current file index (for concurrent files IO).
Definition at line 5822 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fr8p, lib_vtk_io::raw, and lib_io_misc::upper_case().
integer(i4p) function lib_vtk_io::vtk_var_vect_r4 (character(*), intent(in) vec_type, integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, real(r4p), dimension(1:nc_nn), intent(in) varX, real(r4p), dimension(1:nc_nn), intent(in) varY, real(r4p), dimension(1:nc_nn), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] vec_type Vector type: vect = generic vector , norm = normal vector.
[in] nc_nn Number of nodes or cells.
[in] varname Variable name.
[in] varx X component of vector.
[in] vary Y component of vector.
[in] varz Z component of vector.
[in] cf Current file index (for concurrent files IO).
Definition at line 5868 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fr4p, lib_vtk_io::raw, and lib_io_misc::upper_case().
integer(i4p) function lib_vtk_io::vtk_var_vect_i4 (integer(i4p), intent(in) NC_NN, character(*), intent(in) varname, integer(i4p), dimension(1:nc_nn), intent(in) varX, integer(i4p), dimension(1:nc_nn), intent(in) varY, integer(i4p), dimension(1:nc_nn), intent(in) varZ, integer(i4p), intent(in), optional cf) private
Function for saving field of vectorial variable (I4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of nodes or cells.
[in] varname Variable name.
[in] varx X component of vector.
[in] vary Y component of vector.
[in] varz Z component of vector.
[in] cf Current file index (for concurrent files IO).
Definition at line 5914 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fi4p, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_var_text_r8 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) dimm, character(*), intent(in) varname, real(r8p), dimension(1:nc_nn,1:dimm), intent(in) textCoo, integer(i4p), intent(in), optional cf) private
Function for saving texture variable (R8P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of nodes or cells.
[in] dimm Texture dimensions.
[in] varname Variable name.
[in] textcoo Texture.
[in] cf Current file index (for concurrent files IO).
Definition at line 5949 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fi4p, ir_precision::fr4p, and lib_vtk_io::raw.
integer(i4p) function lib_vtk_io::vtk_var_text_r4 (integer(i4p), intent(in) NC_NN, integer(i4p), intent(in) dimm, character(*), intent(in) varname, real(r4p), dimension(1:nc_nn,1:dimm), intent(in) textCoo, integer(i4p), intent(in), optional cf) private
Function for saving texture variable (R4P).
Returns
E_IO: integer(I4P) error flag
Parameters
[in] nc_nn Number of nodes or cells.
[in] dimm Texture dimensions.
[in] varname Variable name.
[in] textcoo Texture.
[in] cf Current file index (for concurrent files IO).
Definition at line 5987 of file Lib_VTK_IO.f90.
References lib_vtk_io::ascii, lib_vtk_io::end_rec, lib_vtk_io::f, ir_precision::fi4p, ir_precision::fr4p, and lib_vtk_io::raw.