OFF: Lib_Riemann
Lib_Riemann
Private Procedures
elemental subroutine lib_riemann::fluxes (p, r, u, g, F_r, F_u, F_E)
elemental subroutine lib_riemann::rarefaction (sgn, g, delta, eta, u0, p0, a0, ux, rx, px, ax, s0, sx)
elemental subroutine lib_riemann::shock (sgn, g, gm1, gp1, u0, p0, a0, ux, rx, px, ax, ss)
elemental subroutine lib_riemann::wavesspeed14u (u1, a1, g1, u4, a4, g4, u23, S1, S4)
elemental subroutine lib_riemann::wavesspeed14up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, S1, S4)
elemental subroutine lib_riemann::wavesspeed1234u (u1, a1, g1, u4, a4, g4, u23, S1, S2, S3, S4)
elemental subroutine lib_riemann::wavesspeed1234up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, S1, S2, S3, S4)
elemental subroutine lib_riemann::interstates23u (p1, u1, a1, g1, gm1_1, gp1_1, delta1, eta1, p4, u4, a4, g4, gm1_4, gp1_4, delta4, eta4, u23, r2, p2, a2, r3, p3, a3, S1, S2, S3, S4)
elemental subroutine lib_riemann::interstates23up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
subroutine lib_riemann::sampling_fluxes (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, p23, r2, r3, S, S1, S2, S3, S4, F_r, F_u, F_E)
elemental subroutine lib_riemann::sampling_fluxes_old (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, p23, r2, r3, S, S1, S2, S3, S4, F_r, F_u, F_E)
elemental subroutine lib_riemann::sampling_fluxes_vacuum (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, S1, S2, S3, S4, F_r, F_u, F_E)
elemental function lib_riemann::vanleer_limiter (Sm1, Sp1)
elemental function lib_riemann::vanalbada_limiter (Sm1, Sp1)
elemental function lib_riemann::harten_limiter (Sm1, Sp1)
elemental subroutine lib_riemann::pvl_u23 (p1, r1, u1, a1, p4, r4, u4, a4, u23)
elemental subroutine lib_riemann::pvl_p23 (p1, r1, u1, a1, p4, r4, u4, a4, p23)
elemental subroutine lib_riemann::pvl_up23 (p1, r1, u1, a1, p4, r4, u4, a4, u23, p23)
elemental subroutine lib_riemann::pvl_wavesspeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine lib_riemann::pvl_wavesspeed1234 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S2, S3, S4)
elemental subroutine lib_riemann::pvl_states (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine lib_riemann::cvl_u23 (p1, r1, u1, a1, p4, r4, u4, a4, u23)
elemental subroutine lib_riemann::cvl_up23 (p1, r1, u1, a1, p4, r4, u4, a4, u23, p23)
elemental subroutine lib_riemann::cvl_wavesspeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine lib_riemann::cvl_states (p1, r1, u1, g1, p4, r4, u4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine lib_riemann::tr_u23 (p1, u1, a1, g1, p4, u4, a4, g4, u23)
elemental subroutine lib_riemann::tr_up23 (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23)
elemental subroutine lib_riemann::tr_wavesspeed14 (p1, u1, a1, g1, p4, u4, a4, g4, S, S1, S4)
elemental subroutine lib_riemann::tr_states (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine lib_riemann::ts_up23 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23)
elemental subroutine lib_riemann::ts_wavesspeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine lib_riemann::ts_states (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine lib_riemann::roe_up23 (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, u23, p23)
elemental subroutine lib_riemann::roe_wavesspeed14 (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, S, S1, S4)
elemental subroutine lib_riemann::roe_ua (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, u_roe, a_roe)
elemental subroutine lib_riemann::roe_state (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, r_roe, u_roe, a_roe, H_roe)
elemental subroutine lib_riemann::bclc_wavesspeed14 (p1, r1, u1, a1, g1, cp1, cv1, p4, r4, u4, a4, g4, cp4, cv4, S, S1, S4)
elemental subroutine lib_riemann::z_wavesspeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
Detailed Description
Function/Subroutine Documentation
elemental subroutine lib_riemann::fluxes (real(r_p), intent(in) p, real(r_p), intent(in) r, real(r_p), intent(in) u, real(r_p), intent(in) g, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E) private
Definition at line 68 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::h(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::riem_solver_aprs(), lib_riemann::riem_solver_exact_u(), lib_riemann::riem_solver_pvl(), lib_riemann::riem_solver_roe(), lib_riemann::sampling_fluxes(), lib_riemann::sampling_fluxes_old(), and lib_riemann::sampling_fluxes_vacuum().
elemental subroutine lib_riemann::pvl_u23 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(out) u23) private
Definition at line 934 of file Lib_Riemann.f90.
Referenced by lib_riemann::pvl_wavesspeed1234(), and lib_riemann::pvl_wavesspeed14().
elemental subroutine lib_riemann::rarefaction (real(r_p), intent(in) sgn, real(r_p), intent(in) g, real(r_p), intent(in) delta, real(r_p), intent(in) eta, real(r_p), intent(in) u0, real(r_p), intent(in) p0, real(r_p), intent(in) a0, real(r_p), intent(in) ux, real(r_p), intent(out) rx, real(r_p), intent(out) px, real(r_p), intent(out) ax, real(r_p), intent(out) s0, real(r_p), intent(out) sx) private
Definition at line 92 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::interstates23u(), and lib_riemann::riem_solver_alfr().
elemental subroutine lib_riemann::shock (real(r_p), intent(in) sgn, real(r_p), intent(in) g, real(r_p), intent(in) gm1, real(r_p), intent(in) gp1, real(r_p), intent(in) u0, real(r_p), intent(in) p0, real(r_p), intent(in) a0, real(r_p), intent(in) ux, real(r_p), intent(out) rx, real(r_p), intent(out) px, real(r_p), intent(out) ax, real(r_p), intent(out) ss) private
Definition at line 121 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::interstates23u().
elemental subroutine lib_riemann::wavesspeed14u (real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) u23, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 154 of file Lib_Riemann.f90.
Referenced by lib_riemann::cvl_states(), lib_riemann::pvl_wavesspeed14(), and lib_riemann::tr_states().
elemental subroutine lib_riemann::wavesspeed14up (real(r_p), intent(in) p1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) u23, real(r_p), intent(in) p23, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 196 of file Lib_Riemann.f90.
Referenced by lib_riemann::cvl_states(), lib_riemann::pvl_wavesspeed1234(), lib_riemann::riem_solver_laxfriedrichs(), lib_riemann::roe_ua(), lib_riemann::tr_states(), and lib_riemann::ts_states().
elemental subroutine lib_riemann::wavesspeed1234u (real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) u23, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 238 of file Lib_Riemann.f90.
Referenced by lib_riemann::pvl_wavesspeed1234().
elemental subroutine lib_riemann::wavesspeed1234up (real(r_p), intent(in) p1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) u23, real(r_p), intent(in) p23, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 284 of file Lib_Riemann.f90.
Referenced by lib_riemann::pvl_states().
elemental subroutine lib_riemann::interstates23u (real(r_p), intent(in) p1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) gm1_1, real(r_p), intent(in) gp1_1, real(r_p), intent(in) delta1, real(r_p), intent(in) eta1, real(r_p), intent(in) p4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) gm1_4, real(r_p), intent(in) gp1_4, real(r_p), intent(in) delta4, real(r_p), intent(in) eta4, real(r_p), intent(in) u23, real(r_p), intent(out) r2, real(r_p), intent(out) p2, real(r_p), intent(out) a2, real(r_p), intent(out) r3, real(r_p), intent(out) p3, real(r_p), intent(out) a3, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 330 of file Lib_Riemann.f90.
References lib_riemann::rarefaction(), lib_riemann::shock(), and ir_precision::zero.
Referenced by lib_riemann::riem_solver_exact_u().
elemental subroutine lib_riemann::interstates23up (real(r_p), intent(in) p1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) u23, real(r_p), intent(in) p23, real(r_p), intent(out) r2, real(r_p), intent(out) r3, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 456 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::cvl_u23(), and lib_riemann::tr_u23().
subroutine lib_riemann::sampling_fluxes (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) delta1, real(r_p), intent(in) eta1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) delta4, real(r_p), intent(in) eta4, real(r_p), intent(in) p23, real(r_p), intent(in) r2, real(r_p), intent(in) r3, real(r_p), intent(in) S, real(r_p), intent(in) S1, real(r_p), intent(in) S2, real(r_p), intent(in) S3, real(r_p), intent(in) S4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E) private
Definition at line 521 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_riemann::fluxes(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::riem_solver_alfr(), lib_riemann::riem_solver_exact_u(), lib_riemann::riem_solver_tr(), and lib_riemann::riem_solver_ts().
elemental subroutine lib_riemann::sampling_fluxes_old (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) delta1, real(r_p), intent(in) eta1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) delta4, real(r_p), intent(in) eta4, real(r_p), intent(in) p23, real(r_p), intent(in) r2, real(r_p), intent(in) r3, real(r_p), intent(in) S, real(r_p), intent(in) S1, real(r_p), intent(in) S2, real(r_p), intent(in) S3, real(r_p), intent(in) S4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E) private
Definition at line 582 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_riemann::fluxes(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
elemental subroutine lib_riemann::sampling_fluxes_vacuum (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) delta1, real(r_p), intent(in) eta1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) delta4, real(r_p), intent(in) eta4, real(r_p), intent(in) S1, real(r_p), intent(in) S2, real(r_p), intent(in) S3, real(r_p), intent(in) S4, real(r_p), intent(out) F_r, real(r_p), intent(out) F_u, real(r_p), intent(out) F_E) private
Definition at line 668 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_riemann::fluxes(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::riem_solver_hllc().
elemental function lib_riemann::vanleer_limiter (real(r_p), intent(in) Sm1, real(r_p), intent(in) Sp1) private
Definition at line 726 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::r(), and ir_precision::zero.
Referenced by lib_riemann::chk_smooth_limiter().
elemental function lib_riemann::vanalbada_limiter (real(r_p), intent(in) Sm1, real(r_p), intent(in) Sp1) private
Definition at line 749 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::r(), and ir_precision::zero.
Referenced by lib_riemann::chk_smooth_limiter().
elemental function lib_riemann::harten_limiter (real(r_p), intent(in) Sm1, real(r_p), intent(in) Sp1) private
Definition at line 772 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::r(), and ir_precision::zero.
Referenced by lib_riemann::chk_smooth_limiter().
elemental subroutine lib_riemann::pvl_p23 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(out) p23) private
Definition at line 958 of file Lib_Riemann.f90.
Referenced by lib_riemann::ts_wavesspeed14().
elemental subroutine lib_riemann::pvl_up23 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(out) u23, real(r_p), intent(out) p23) private
Definition at line 982 of file Lib_Riemann.f90.
Referenced by lib_riemann::chk_smooth_z(), lib_riemann::cvl_u23(), lib_riemann::pvl_states(), lib_riemann::pvl_wavesspeed14(), lib_riemann::riem_solver_aprs(), and lib_riemann::z_wavesspeed14().
elemental subroutine lib_riemann::pvl_wavesspeed14 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) S, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 1010 of file Lib_Riemann.f90.
References lib_riemann::pvl_u23(), lib_riemann::pvl_up23(), and lib_riemann::wavesspeed14u().
Referenced by lib_riemann::riem_solver_laxfriedrichs(), and lib_riemann::riem_solver_roe().
elemental subroutine lib_riemann::pvl_wavesspeed1234 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) S, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 1054 of file Lib_Riemann.f90.
References lib_riemann::pvl_u23(), lib_riemann::wavesspeed1234u(), and lib_riemann::wavesspeed14up().
Referenced by lib_riemann::riem_solver_roe().
elemental subroutine lib_riemann::pvl_states (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) u23, real(r_p), intent(out) p23, real(r_p), intent(out) r2, real(r_p), intent(out) r3, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 1096 of file Lib_Riemann.f90.
References lib_riemann::pvl_up23(), and lib_riemann::wavesspeed1234up().
Referenced by lib_riemann::riem_solver_aprs(), and lib_riemann::riem_solver_tr().
elemental subroutine lib_riemann::cvl_u23 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(out) u23) private
Definition at line 1132 of file Lib_Riemann.f90.
References lib_riemann::interstates23up(), and lib_riemann::pvl_up23().
Referenced by lib_riemann::cvl_states().
elemental subroutine lib_riemann::cvl_up23 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(out) u23, real(r_p), intent(out) p23) private
Definition at line 1160 of file Lib_Riemann.f90.
References lib_runge_kutta::c1.
Referenced by lib_riemann::cvl_states(), and lib_riemann::tr_u23().
elemental subroutine lib_riemann::cvl_wavesspeed14 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) S, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 1193 of file Lib_Riemann.f90.
References lib_runge_kutta::c1.
Referenced by lib_riemann::riem_solver_hllc().
elemental subroutine lib_riemann::cvl_states (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(out) u23, real(r_p), intent(out) p23, real(r_p), intent(out) r2, real(r_p), intent(out) r3, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 1237 of file Lib_Riemann.f90.
References lib_riemann::cvl_u23(), lib_riemann::cvl_up23(), lib_riemann::wavesspeed14u(), and lib_riemann::wavesspeed14up().
elemental subroutine lib_riemann::tr_u23 (real(r_p), intent(in) p1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) u23) private
Definition at line 1275 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_riemann::cvl_up23(), lib_riemann::interstates23up(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::chk_smooth_z(), and lib_riemann::tr_states().
elemental subroutine lib_riemann::tr_up23 (real(r_p), intent(in) p1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) u23, real(r_p), intent(out) p23) private
Definition at line 1309 of file Lib_Riemann.f90.
Referenced by lib_riemann::tr_states(), and lib_riemann::z_wavesspeed14().
elemental subroutine lib_riemann::tr_wavesspeed14 (real(r_p), intent(in) p1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) S, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 1345 of file Lib_Riemann.f90.
Referenced by lib_riemann::riem_solver_roe().
elemental subroutine lib_riemann::tr_states (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) u23, real(r_p), intent(out) p23, real(r_p), intent(out) r2, real(r_p), intent(out) r3, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 1387 of file Lib_Riemann.f90.
References lib_riemann::tr_u23(), lib_riemann::tr_up23(), lib_riemann::wavesspeed14u(), and lib_riemann::wavesspeed14up().
Referenced by lib_riemann::riem_solver_aprs(), and lib_riemann::riem_solver_ts().
elemental subroutine lib_riemann::ts_up23 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) u23, real(r_p), intent(out) p23) private
Definition at line 1430 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::chk_smooth_z(), lib_riemann::riem_solver_laxfriedrichs(), and lib_riemann::ts_states().
elemental subroutine lib_riemann::ts_wavesspeed14 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) S, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 1463 of file Lib_Riemann.f90.
References lib_riemann::pvl_p23().
elemental subroutine lib_riemann::ts_states (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) u23, real(r_p), intent(out) p23, real(r_p), intent(out) r2, real(r_p), intent(out) r3, real(r_p), intent(out) S1, real(r_p), intent(out) S2, real(r_p), intent(out) S3, real(r_p), intent(out) S4) private
Definition at line 1495 of file Lib_Riemann.f90.
References lib_riemann::ts_up23(), and lib_riemann::wavesspeed14up().
Referenced by lib_riemann::riem_solver_aprs(), and lib_riemann::riem_solver_ts().
elemental subroutine lib_riemann::roe_up23 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) cp1, real(r_p), intent(in) cv1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(in) cp4, real(r_p), intent(in) cv4, real(r_p), intent(out) u23, real(r_p), intent(out) p23) private
Definition at line 1543 of file Lib_Riemann.f90.
Referenced by lib_riemann::roe_ua().
elemental subroutine lib_riemann::roe_wavesspeed14 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) cp1, real(r_p), intent(in) cv1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(in) cp4, real(r_p), intent(in) cv4, real(r_p), intent(out) S, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 1586 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::h(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
elemental subroutine lib_riemann::roe_ua (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) cp1, real(r_p), intent(in) cv1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(in) cp4, real(r_p), intent(in) cv4, real(r_p), intent(out) u_roe, real(r_p), intent(out) a_roe) private
Definition at line 1625 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), lib_riemann::roe_up23(), and lib_riemann::wavesspeed14up().
Referenced by lib_riemann::chk_smooth_liu(), and lib_riemann::z_wavesspeed14().
elemental subroutine lib_riemann::roe_state (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) g1, real(r_p), intent(in) cp1, real(r_p), intent(in) cv1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) g4, real(r_p), intent(in) cp4, real(r_p), intent(in) cv4, real(r_p), intent(out) r_roe, real(r_p), intent(out) u_roe, real(r_p), intent(out) a_roe, real(r_p), intent(out) H_roe) private
Definition at line 1664 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::h(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::riem_solver_exact_u(), and lib_riemann::riem_solver_roe().
elemental subroutine lib_riemann::bclc_wavesspeed14 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) cp1, real(r_p), intent(in) cv1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(in) cp4, real(r_p), intent(in) cv4, real(r_p), intent(out) S, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 1707 of file Lib_Riemann.f90.
References lib_thermodynamic_laws_ideal::h(), lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::riem_solver_hllc().
elemental subroutine lib_riemann::z_wavesspeed14 (real(r_p), intent(in) p1, real(r_p), intent(in) r1, real(r_p), intent(in) u1, real(r_p), intent(in) a1, real(r_p), intent(in) g1, real(r_p), intent(in) p4, real(r_p), intent(in) r4, real(r_p), intent(in) u4, real(r_p), intent(in) a4, real(r_p), intent(in) g4, real(r_p), intent(out) S, real(r_p), intent(out) S1, real(r_p), intent(out) S4) private
Definition at line 1747 of file Lib_Riemann.f90.
References lib_riemann::pvl_up23(), lib_riemann::roe_ua(), and lib_riemann::tr_up23().
Referenced by lib_riemann::riem_solver_laxfriedrichs(), and lib_riemann::riem_solver_roe().