OFF: Data_Type_Primitive
Data_Type_Primitive
Public Procedures
integer(i_p) function, public data_type_primitive::write_primitive (scalar, array1D, array2D, array3D, format, unit)
Function for writing Type_Primitive data.
integer(i_p) function, public data_type_primitive::read_primitive (scalar, array1D, array2D, array3D, format, unit)
Function for reading Type_Primitive data.
Detailed Description
Function/Subroutine Documentation
integer(i_p) function, public data_type_primitive::write_primitive (type(type_primitive), intent(in), optional scalar, type(type_primitive), dimension(:), intent(in), optional array1D, type(type_primitive), dimension(:,:), intent(in), optional array2D, type(type_primitive), dimension(:,:,:), intent(in), optional array3D, character(*), intent(in), optional format, integer(i4p), intent(in) unit)
Function for writing Type_Primitive data.
The vector data could be scalar, one, two and three dimensional array. The format could be ascii or binary.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in] scalar Scalar primitive data.
[in] array1d One dimensional array primitive data.
[in] array2d Two dimensional array primitive data.
[in] array3d Three dimensional array primitive data.
[in] format Format specifier.
[in] unit Logic unit.
Definition at line 258 of file Data_Type_Primitive.f90.
References data_type_vector::write_vector().
Referenced by load_blocks(), load_icemcfd(), off(), and data_type_sblock::save_bfluid().
integer(i_p) function, public data_type_primitive::read_primitive (type(type_primitive), intent(inout), optional scalar, type(type_primitive), dimension(:), intent(inout), optional array1D, type(type_primitive), dimension(:,:), intent(inout), optional array2D, type(type_primitive), dimension(:,:,:), intent(inout), optional array3D, character(*), intent(in), optional format, integer(i4p), intent(in) unit)
Function for reading Type_Primitive data.
The vector data could be scalar, one, two and three dimensional array. The format could be ascii or binary.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in,out] scalar Scalar primitive data.
[in,out] array1d One dimensional array primitive data.
[in,out] array2d Two dimensional array primitive data.
[in,out] array3d Three dimensional array primitive data.
[in] format Format specifier.
[in] unit Logic unit.
Definition at line 397 of file Data_Type_Primitive.f90.
References data_type_vector::read_vector().
Referenced by data_type_sblock::load_bfluid(), and data_type_global::load_gbc_in1().