OFF: Lib_Parallel
Lib_Parallel
Private Procedures
subroutine lib_parallel::alloc_sr (global)
subroutine lib_parallel::compute_ncr (block)
subroutine lib_parallel::compute_bbs (global)
subroutine lib_parallel::alloc_sendrecv (global)
subroutine lib_parallel::compute_recv_maps (block)
subroutine lib_parallel::ncrsendrecv (global)
subroutine lib_parallel::mapsendrecv (global)
Detailed Description
Function/Subroutine Documentation
subroutine lib_parallel::alloc_sr (type(type_global), intent(in) global) private
Definition at line 95 of file Lib_Parallel.f90.
References lib_parallel::nproc.
Referenced by lib_parallel::init_sendrecv().
subroutine lib_parallel::compute_ncr (type(type_sblock), dimension(1:,1:), intent(in) block) private
Definition at line 114 of file Lib_Parallel.f90.
References data_type_bc::bc_adj, lib_parallel::nproc, and lib_parallel::procmap.
Referenced by lib_parallel::init_sendrecv().
subroutine lib_parallel::compute_bbs (type(type_global), intent(in) global) private
Definition at line 216 of file Lib_Parallel.f90.
References lib_parallel::nproc.
Referenced by lib_parallel::init_sendrecv().
subroutine lib_parallel::alloc_sendrecv (type(type_global), intent(in) global) private
Definition at line 245 of file Lib_Parallel.f90.
Referenced by lib_parallel::init_sendrecv().
subroutine lib_parallel::compute_recv_maps (type(type_sblock), dimension(1:,1:), intent(in) block) private
Definition at line 265 of file Lib_Parallel.f90.
References lib_parallel::nproc, and scan_proc().
Referenced by lib_parallel::init_sendrecv().
subroutine lib_parallel::ncrsendrecv (type(type_global), intent(in) global) private
Definition at line 439 of file Lib_Parallel.f90.
References lib_parallel::nproc.
Referenced by lib_parallel::init_sendrecv().
subroutine lib_parallel::mapsendrecv (type(type_global), intent(in) global) private
Definition at line 467 of file Lib_Parallel.f90.
References lib_parallel::nproc.
Referenced by lib_parallel::init_sendrecv().