OFF: Data_Type_SL_List
Data_Type_SL_List
Private Procedures
recursive subroutine data_type_sl_list::free_link (l)
Recursive subroutine for freeing (destroying) the list links.
integer(i4p) function data_type_sl_list::leng_link (l)
Function for computing the length of the list links.
logical function data_type_sl_list::homo_link (l)
Function for checking if the list is homogeneous.
type(type_sl_link) function,
pointer data_type_sl_list::link (l, n)
Function for returning the n-th link pointer of the list.
subroutine data_type_sl_list::del_link (l, n)
Subroutine for deleting n-th link of the list.
subroutine data_type_sl_list::delh_link (l)
Subroutine for deleting head link of the list.
subroutine data_type_sl_list::delt_link (l)
Subroutine for deleting tail link of the list.
subroutine data_type_sl_list::get_link_r8 (l, n, d)
Subroutine for getting data from the n-th link of list (R8P).
subroutine data_type_sl_list::get_link_r4 (l, n, d)
Subroutine for getting data from the n-th link of list (R4P).
subroutine data_type_sl_list::get_link_i8 (l, n, d)
Subroutine for getting data from the n-th link of list (I8P).
subroutine data_type_sl_list::get_link_i4 (l, n, d)
Subroutine for getting data from the n-th link of list (I4P).
subroutine data_type_sl_list::get_link_i2 (l, n, d)
Subroutine for getting data from the n-th link of list (I2P).
subroutine data_type_sl_list::get_link_i1 (l, n, d)
Subroutine for getting data from the n-th link of list (I1P).
subroutine data_type_sl_list::get_link_ch (l, n, d)
Subroutine for getting data from the n-th link of list (character).
subroutine data_type_sl_list::get_link_log (l, n, d)
Subroutine for getting data from the n-th link of list (logical).
subroutine data_type_sl_list::geth_link_r8 (l, d)
Subroutine for getting a link data from the list head (R8P).
subroutine data_type_sl_list::geth_link_r4 (l, d)
Subroutine for getting a link data from the list head (R4P).
subroutine data_type_sl_list::geth_link_i8 (l, d)
Subroutine for getting a link data from the list head (I8P).
subroutine data_type_sl_list::geth_link_i4 (l, d)
Subroutine for getting a link data from the list head (I4P).
subroutine data_type_sl_list::geth_link_i2 (l, d)
Subroutine for getting a link data from the list head (I2P).
subroutine data_type_sl_list::geth_link_i1 (l, d)
Subroutine for getting a link data from the list head (I1P).
subroutine data_type_sl_list::geth_link_ch (l, d)
Subroutine for getting a link data from the list head (character).
subroutine data_type_sl_list::geth_link_log (l, d)
Subroutine for getting a link data from the list head (logical).
recursive subroutine data_type_sl_list::gett_link_r8 (l, d)
Subroutine for getting a link data from the list tail (R8P).
recursive subroutine data_type_sl_list::gett_link_r4 (l, d)
Subroutine for getting a link data from the list tail (R4P).
recursive subroutine data_type_sl_list::gett_link_i8 (l, d)
Subroutine for getting a link data from the list tail (I8P).
recursive subroutine data_type_sl_list::gett_link_i4 (l, d)
Subroutine for getting a link data from the list tail (I4P).
recursive subroutine data_type_sl_list::gett_link_i2 (l, d)
Subroutine for getting a link data from the list tail (I2P).
recursive subroutine data_type_sl_list::gett_link_i1 (l, d)
Subroutine for getting a link data from the list tail (I1P).
recursive subroutine data_type_sl_list::gett_link_ch (l, d)
Subroutine for getting a link data from the list tail (character).
recursive subroutine data_type_sl_list::gett_link_log (l, d)
Subroutine for getting a link data from the list tail (logical).
subroutine data_type_sl_list::put_link_r8 (l, n, d)
Subroutine for inserting a link into the n-th link of list (R8P).
subroutine data_type_sl_list::put_link_r4 (l, n, d)
Subroutine for inserting a link into the n-th link of list (R4P).
subroutine data_type_sl_list::put_link_i8 (l, n, d)
Subroutine for inserting a link into the n-th link of list (I8P).
subroutine data_type_sl_list::put_link_i4 (l, n, d)
Subroutine for inserting a link into the n-th link of list (I4P).
subroutine data_type_sl_list::put_link_i2 (l, n, d)
Subroutine for inserting a link into the n-th link of list (I2P).
subroutine data_type_sl_list::put_link_i1 (l, n, d)
Subroutine for inserting a link into the n-th link of list (I1P).
subroutine data_type_sl_list::put_link_ch (l, n, d)
Subroutine for inserting a link into the n-th link of list (character).
subroutine data_type_sl_list::put_link_log (l, n, d)
Subroutine for inserting a link into the n-th link of list (logical).
subroutine data_type_sl_list::puth_link_r8 (l, d)
Subroutine for inserting a link data into the list head (R8P).
subroutine data_type_sl_list::puth_link_r4 (l, d)
Subroutine for inserting a link data into the list head (R4P).
subroutine data_type_sl_list::puth_link_i8 (l, d)
Subroutine for inserting a link data into the list head (I8P).
subroutine data_type_sl_list::puth_link_i4 (l, d)
Subroutine for inserting a link data into the list head (I4P).
subroutine data_type_sl_list::puth_link_i2 (l, d)
Subroutine for inserting a link data into the list head (I2P).
subroutine data_type_sl_list::puth_link_i1 (l, d)
Subroutine for inserting a link data into the list head (I1P).
subroutine data_type_sl_list::puth_link_ch (l, d)
Subroutine for inserting a link data into the list head (character).
subroutine data_type_sl_list::puth_link_log (l, d)
Subroutine for inserting a link data into the list head (logical).
recursive subroutine data_type_sl_list::putt_link_r8 (l, d)
Recursive subroutine for inserting a link data into the list tail (R8P).
recursive subroutine data_type_sl_list::putt_link_r4 (l, d)
Recursive subroutine for inserting a link data into the list tail (R4P).
recursive subroutine data_type_sl_list::putt_link_i8 (l, d)
Recursive subroutine for inserting a link data into the list tail (I18).
recursive subroutine data_type_sl_list::putt_link_i4 (l, d)
Recursive subroutine for inserting a link data into the list tail (I4P).
recursive subroutine data_type_sl_list::putt_link_i2 (l, d)
Recursive subroutine for inserting a link data into the list tail (I2P).
recursive subroutine data_type_sl_list::putt_link_i1 (l, d)
Recursive subroutine for inserting a link data into the list tail (I1P).
recursive subroutine data_type_sl_list::putt_link_ch (l, d)
Recursive subroutine for inserting a link data into the list tail (character).
recursive subroutine data_type_sl_list::putt_link_log (l, d)
Recursive subroutine for inserting a link data into the list tail (logical).
subroutine data_type_sl_list::array_link_r8 (l, a)
Subroutine for converting list to array (R8P).
subroutine data_type_sl_list::array_link_r4 (l, a)
Subroutine for converting list to array (R4P).
subroutine data_type_sl_list::array_link_i8 (l, a)
Subroutine for converting list to array (I8P).
subroutine data_type_sl_list::array_link_i4 (l, a)
Subroutine for converting list to array (I4P).
subroutine data_type_sl_list::array_link_i2 (l, a)
Subroutine for converting list to array (I2P).
subroutine data_type_sl_list::array_link_i1 (l, a)
Subroutine for converting list to array (I1P).
subroutine data_type_sl_list::array_link_ch (l, Nc, a)
Subroutine for converting list to array (character).
subroutine data_type_sl_list::array_link_log (l, a)
Subroutine for converting list to array (logical).
subroutine data_type_sl_list::free_list (l)
Subroutine for freeing (destroying) the list.
integer(i4p) function data_type_sl_list::leng_list (l)
Function for computing the length of the list.
logical function data_type_sl_list::homo_list (l)
Recursive subroutine for checking if the list is homogeneous.
subroutine data_type_sl_list::del_list (l, n)
Subroutine for deleting n-th link of the list.
subroutine data_type_sl_list::delh_list (l)
Subroutine for deleting head link of the list.
subroutine data_type_sl_list::delt_list (l)
Subroutine for deleting tail link of the list.
subroutine data_type_sl_list::get_list_r8 (l, n, d)
Subroutine for getting data from the n-th link of list (R8P).
subroutine data_type_sl_list::get_list_r4 (l, n, d)
Subroutine for getting data from the n-th link of list (R4P).
subroutine data_type_sl_list::get_list_i8 (l, n, d)
Subroutine for getting data from the n-th link of list (I8P).
subroutine data_type_sl_list::get_list_i4 (l, n, d)
Subroutine for getting data from the n-th link of list (I4P).
subroutine data_type_sl_list::get_list_i2 (l, n, d)
Subroutine for getting data from the n-th link of list (I2P).
subroutine data_type_sl_list::get_list_i1 (l, n, d)
Subroutine for getting data from the n-th link of list (I1P).
subroutine data_type_sl_list::get_list_ch (l, n, d)
Subroutine for getting data from the n-th link of list (character).
subroutine data_type_sl_list::get_list_log (l, n, d)
Subroutine for getting data from the n-th link of list (logical).
subroutine data_type_sl_list::geth_list_r8 (l, d)
Subroutine for getting a link data from the list head (R8P).
subroutine data_type_sl_list::geth_list_r4 (l, d)
Subroutine for getting a link data from the list head (R4P).
subroutine data_type_sl_list::geth_list_i8 (l, d)
Subroutine for getting a link data from the list head (I8P).
subroutine data_type_sl_list::geth_list_i4 (l, d)
Subroutine for getting a link data from the list head (I4P).
subroutine data_type_sl_list::geth_list_i2 (l, d)
Subroutine for getting a link data from the list head (I2P).
subroutine data_type_sl_list::geth_list_i1 (l, d)
Subroutine for getting a link data from the list head (I1P).
subroutine data_type_sl_list::geth_list_ch (l, d)
Subroutine for getting a link data from the list head (character).
subroutine data_type_sl_list::geth_list_log (l, d)
Subroutine for getting a link data from the list head (logical).
subroutine data_type_sl_list::gett_list_r8 (l, d)
Subroutine for getting a link data from the list tail (R8P).
subroutine data_type_sl_list::gett_list_r4 (l, d)
Subroutine for getting a link data from the list tail (R4P).
subroutine data_type_sl_list::gett_list_i8 (l, d)
Subroutine for getting a link data from the list tail (I8P).
subroutine data_type_sl_list::gett_list_i4 (l, d)
Subroutine for getting a link data from the list tail (I4P).
subroutine data_type_sl_list::gett_list_i2 (l, d)
Subroutine for getting a link data from the list tail (I2P).
subroutine data_type_sl_list::gett_list_i1 (l, d)
Subroutine for getting a link data from the list tail (I1P).
subroutine data_type_sl_list::gett_list_ch (l, d)
Subroutine for getting a link data from the list tail (character).
subroutine data_type_sl_list::gett_list_log (l, d)
Subroutine for getting a link data from the list tail (logical).
subroutine data_type_sl_list::put_list_r8 (l, n, d)
Subroutine for inserting a link into the n-th link of list (R8P).
subroutine data_type_sl_list::put_list_r4 (l, n, d)
Subroutine for inserting a link into the n-th link of list (R4P).
subroutine data_type_sl_list::put_list_i8 (l, n, d)
Subroutine for inserting a link into the n-th link of list (I8P).
subroutine data_type_sl_list::put_list_i4 (l, n, d)
Subroutine for inserting a link into the n-th link of list (I4P).
subroutine data_type_sl_list::put_list_i2 (l, n, d)
Subroutine for inserting a link into the n-th link of list (I2P).
subroutine data_type_sl_list::put_list_i1 (l, n, d)
Subroutine for inserting a link into the n-th link of list (I1P).
subroutine data_type_sl_list::put_list_ch (l, n, d)
Subroutine for inserting a link into the n-th link of list (character).
subroutine data_type_sl_list::put_list_log (l, n, d)
Subroutine for inserting a link into the n-th link of list (logical).
subroutine data_type_sl_list::puth_list_r8 (l, d)
Subroutine for inserting a link data into the list head (R8P).
subroutine data_type_sl_list::puth_list_r4 (l, d)
Subroutine for inserting a link data into the list head (R4P).
subroutine data_type_sl_list::puth_list_i8 (l, d)
Subroutine for inserting a link data into the list head (I8P).
subroutine data_type_sl_list::puth_list_i4 (l, d)
Subroutine for inserting a link data into the list head (I4P).
subroutine data_type_sl_list::puth_list_i2 (l, d)
Subroutine for inserting a link data into the list head (I2P).
subroutine data_type_sl_list::puth_list_i1 (l, d)
Subroutine for inserting a link data into the list head (I1P).
subroutine data_type_sl_list::puth_list_ch (l, d)
Subroutine for inserting a link data into the list head (character).
subroutine data_type_sl_list::puth_list_log (l, d)
Subroutine for inserting a link data into the list head (logical).
subroutine data_type_sl_list::putt_list_r8 (l, d)
Subroutine for inserting a link data into the list tail (R8P).
subroutine data_type_sl_list::putt_list_r4 (l, d)
Subroutine for inserting a link data into the list tail (R4P).
subroutine data_type_sl_list::putt_list_i8 (l, d)
Subroutine for inserting a link data into the list tail (I8P).
subroutine data_type_sl_list::putt_list_i4 (l, d)
Subroutine for inserting a link data into the list tail (I4P).
subroutine data_type_sl_list::putt_list_i2 (l, d)
Subroutine for inserting a link data into the list tail (I2P).
subroutine data_type_sl_list::putt_list_i1 (l, d)
Subroutine for inserting a link data into the list tail (I1P).
subroutine data_type_sl_list::putt_list_ch (l, d)
Subroutine for inserting a link data into the list tail (character).
subroutine data_type_sl_list::putt_list_log (l, d)
Subroutine for inserting a link data into the list tail (logical).
subroutine data_type_sl_list::array_list_r8 (l, a)
Subroutine for converting list to array (R8P).
subroutine data_type_sl_list::array_list_r4 (l, a)
Subroutine for converting list to array (R4P).
subroutine data_type_sl_list::array_list_i8 (l, a)
Subroutine for converting list to array (I8P).
subroutine data_type_sl_list::array_list_i4 (l, a)
Subroutine for converting list to array (I4P).
subroutine data_type_sl_list::array_list_i2 (l, a)
Subroutine for converting list to array (I2P).
subroutine data_type_sl_list::array_list_i1 (l, a)
Subroutine for converting list to array (I1P).
subroutine data_type_sl_list::array_list_ch (l, Nc, a)
Subroutine for converting list to array (character).
subroutine data_type_sl_list::array_list_log (l, a)
Subroutine for converting list to array (logical).
Detailed Description
Function/Subroutine Documentation
recursive subroutine data_type_sl_list::free_link (class(type_sl_link), intent(inout) l) private
Recursive subroutine for freeing (destroying) the list links.
Parameters
[in,out] l List.
Definition at line 382 of file Data_Type_SL_List.f90.
integer(i4p) function data_type_sl_list::leng_link (class(type_sl_link), intent(in) l) private
Function for computing the length of the list links.
Parameters
[in] l List.
Definition at line 401 of file Data_Type_SL_List.f90.
logical function data_type_sl_list::homo_link (class(type_sl_link), intent(in) l) private
Function for checking if the list is homogeneous.
Parameters
[in] l List.
Definition at line 428 of file Data_Type_SL_List.f90.
type(type_sl_link) function, pointer data_type_sl_list::link (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n) private
Function for returning the n-th link pointer of the list.
Note
If n<1 then the first link of the list is returned, whereas if n> list's length the last link is returned.
Parameters
[in] l List.
[in] n Element of the list to be found.
Definition at line 451 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::del_link (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n) private
Subroutine for deleting n-th link of the list.
Parameters
[in,out] l List.
[in] n Element of the list to be deleted.
Definition at line 476 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::e().
Referenced by data_type_sl_list::type_sl_link::free().
subroutine data_type_sl_list::delh_link (class(type_sl_link), intent(inout) l) private
Subroutine for deleting head link of the list.
Parameters
[in,out] l List.
Definition at line 518 of file Data_Type_SL_List.f90.
Referenced by data_type_sl_list::type_sl_link::leng().
subroutine data_type_sl_list::delt_link (class(type_sl_link), intent(inout), target l) private
Subroutine for deleting tail link of the list.
Parameters
[in,out] l List.
Definition at line 544 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::p().
Referenced by data_type_sl_list::type_sl_link::homogeneous().
subroutine data_type_sl_list::get_link_r8 (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n, real(r8p), intent(out) d) private
Subroutine for getting data from the n-th link of list (R8P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 580 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link(), and ir_precision::minr16p.
subroutine data_type_sl_list::get_link_r4 (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n, real(r4p), intent(out) d) private
Subroutine for getting data from the n-th link of list (R4P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 600 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link(), and ir_precision::minr8p.
subroutine data_type_sl_list::get_link_i8 (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n, integer(i8p), intent(out) d) private
Subroutine for getting data from the n-th link of list (I8P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 620 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link(), and ir_precision::minr4p.
subroutine data_type_sl_list::get_link_i4 (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n, integer(i4p), intent(out) d) private
Subroutine for getting data from the n-th link of list (I4P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 640 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link(), and ir_precision::mini8p.
subroutine data_type_sl_list::get_link_i2 (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n, integer(i2p), intent(out) d) private
Subroutine for getting data from the n-th link of list (I2P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 660 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link(), and ir_precision::mini4p.
subroutine data_type_sl_list::get_link_i1 (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n, integer(i1p), intent(out) d) private
Subroutine for getting data from the n-th link of list (I1P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 680 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link(), and ir_precision::mini2p.
subroutine data_type_sl_list::get_link_ch (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n, character(*), intent(out) d) private
Subroutine for getting data from the n-th link of list (character).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 700 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link(), and ir_precision::mini1p.
subroutine data_type_sl_list::get_link_log (class(type_sl_link), intent(in), target l, integer(i4p), intent(in) n, logical, intent(out) d) private
Subroutine for getting data from the n-th link of list (logical).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 721 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link().
subroutine data_type_sl_list::geth_link_r8 (class(type_sl_link), intent(in) l, real(r8p), intent(out) d) private
Subroutine for getting a link data from the list head (R8P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 742 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::link().
subroutine data_type_sl_list::geth_link_r4 (class(type_sl_link), intent(in) l, real(r4p), intent(out) d) private
Subroutine for getting a link data from the list head (R4P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 758 of file Data_Type_SL_List.f90.
References ir_precision::minr16p.
subroutine data_type_sl_list::geth_link_i8 (class(type_sl_link), intent(in) l, integer(i8p), intent(out) d) private
Subroutine for getting a link data from the list head (I8P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 774 of file Data_Type_SL_List.f90.
References ir_precision::minr8p.
subroutine data_type_sl_list::geth_link_i4 (class(type_sl_link), intent(in) l, integer(i4p), intent(out) d) private
Subroutine for getting a link data from the list head (I4P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 790 of file Data_Type_SL_List.f90.
References ir_precision::minr4p.
subroutine data_type_sl_list::geth_link_i2 (class(type_sl_link), intent(in) l, integer(i2p), intent(out) d) private
Subroutine for getting a link data from the list head (I2P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 806 of file Data_Type_SL_List.f90.
References ir_precision::mini8p.
subroutine data_type_sl_list::geth_link_i1 (class(type_sl_link), intent(in) l, integer(i1p), intent(out) d) private
Subroutine for getting a link data from the list head (I1P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 822 of file Data_Type_SL_List.f90.
References ir_precision::mini4p.
subroutine data_type_sl_list::geth_link_ch (class(type_sl_link), intent(in) l, character(*), intent(out) d) private
Subroutine for getting a link data from the list head (character).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 838 of file Data_Type_SL_List.f90.
References ir_precision::mini2p.
subroutine data_type_sl_list::geth_link_log (class(type_sl_link), intent(in) l, logical, intent(out) d) private
Subroutine for getting a link data from the list head (logical).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 855 of file Data_Type_SL_List.f90.
References ir_precision::mini1p.
recursive subroutine data_type_sl_list::gett_link_r8 (class(type_sl_link), intent(in) l, real(r8p), intent(out) d) private
Subroutine for getting a link data from the list tail (R8P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 873 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::gett_link_r4 (class(type_sl_link), intent(in) l, real(r4p), intent(out) d) private
Subroutine for getting a link data from the list tail (R4P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 893 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::gett_link_i8 (class(type_sl_link), intent(in) l, integer(i8p), intent(out) d) private
Subroutine for getting a link data from the list tail (I8P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 913 of file Data_Type_SL_List.f90.
References ir_precision::minr16p.
recursive subroutine data_type_sl_list::gett_link_i4 (class(type_sl_link), intent(in) l, integer(i4p), intent(out) d) private
Subroutine for getting a link data from the list tail (I4P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 933 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::gett_link_r8(), and ir_precision::minr8p.
recursive subroutine data_type_sl_list::gett_link_i2 (class(type_sl_link), intent(in) l, integer(i2p), intent(out) d) private
Subroutine for getting a link data from the list tail (I2P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 953 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::gett_link_r4(), and ir_precision::minr4p.
recursive subroutine data_type_sl_list::gett_link_i1 (class(type_sl_link), intent(in) l, integer(i1p), intent(out) d) private
Subroutine for getting a link data from the list tail (I1P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 973 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::gett_link_i8(), and ir_precision::mini8p.
recursive subroutine data_type_sl_list::gett_link_ch (class(type_sl_link), intent(in) l, character(*), intent(out) d) private
Subroutine for getting a link data from the list tail (character).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 993 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::gett_link_i4(), and ir_precision::mini4p.
recursive subroutine data_type_sl_list::gett_link_log (class(type_sl_link), intent(in) l, logical, intent(out) d) private
Subroutine for getting a link data from the list tail (logical).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 1014 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::gett_link_i2(), ir_precision::mini1p, and ir_precision::mini2p.
subroutine data_type_sl_list::put_link_r8 (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n, real(r8p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (R8P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 1036 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::gett_link_ch(), and data_type_sl_list::type_sl_link::gett_link_i1().
subroutine data_type_sl_list::put_link_r4 (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n, real(r4p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (R4P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 1061 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::gett_link_log(), and lp().
subroutine data_type_sl_list::put_link_i8 (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n, integer(i8p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (I8P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 1086 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::put_link_i4 (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n, integer(i4p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (I4P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 1111 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::put_link_i2 (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n, integer(i2p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (I2P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 1136 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::put_link_i1 (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n, integer(i1p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (I1P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 1161 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::put_link_ch (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n, character(*), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (character).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 1186 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::put_link_log (class(type_sl_link), intent(inout), target l, integer(i4p), intent(in) n, logical, intent(in) d) private
Subroutine for inserting a link into the n-th link of list (logical).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 1211 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_link_r8 (class(type_sl_link), intent(inout) l, real(r8p), intent(in) d) private
Subroutine for inserting a link data into the list head (R8P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1237 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_link_r4 (class(type_sl_link), intent(inout) l, real(r4p), intent(in) d) private
Subroutine for inserting a link data into the list head (R4P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1260 of file Data_Type_SL_List.f90.
References lp().
subroutine data_type_sl_list::puth_link_i8 (class(type_sl_link), intent(inout) l, integer(i8p), intent(in) d) private
Subroutine for inserting a link data into the list head (I8P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1283 of file Data_Type_SL_List.f90.
References lp().
subroutine data_type_sl_list::puth_link_i4 (class(type_sl_link), intent(inout) l, integer(i4p), intent(in) d) private
Subroutine for inserting a link data into the list head (I4P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1306 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_link_i2 (class(type_sl_link), intent(inout) l, integer(i2p), intent(in) d) private
Subroutine for inserting a link data into the list head (I2P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1329 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_link_i1 (class(type_sl_link), intent(inout) l, integer(i1p), intent(in) d) private
Subroutine for inserting a link data into the list head (I1P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1352 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_link_ch (class(type_sl_link), intent(inout) l, character(*), intent(in) d) private
Subroutine for inserting a link data into the list head (character).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1375 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_link_log (class(type_sl_link), intent(inout) l, logical, intent(in) d) private
Subroutine for inserting a link data into the list head (logical).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1399 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::putt_link_r8 (class(type_sl_link), intent(inout) l, real(r8p), intent(in) d) private
Recursive subroutine for inserting a link data into the list tail (R8P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1424 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::putt_link_r4 (class(type_sl_link), intent(inout) l, real(r4p), intent(in) d) private
Recursive subroutine for inserting a link data into the list tail (R4P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1442 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::putt_link_i8 (class(type_sl_link), intent(inout) l, integer(i8p), intent(in) d) private
Recursive subroutine for inserting a link data into the list tail (I18).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1460 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::putt_link_i4 (class(type_sl_link), intent(inout) l, integer(i4p), intent(in) d) private
Recursive subroutine for inserting a link data into the list tail (I4P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1478 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::putt_link_i2 (class(type_sl_link), intent(inout) l, integer(i2p), intent(in) d) private
Recursive subroutine for inserting a link data into the list tail (I2P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1496 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::putt_link_i1 (class(type_sl_link), intent(inout) l, integer(i1p), intent(in) d) private
Recursive subroutine for inserting a link data into the list tail (I1P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1514 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::putt_link_ch (class(type_sl_link), intent(inout) l, character(*), intent(in) d) private
Recursive subroutine for inserting a link data into the list tail (character).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1532 of file Data_Type_SL_List.f90.
recursive subroutine data_type_sl_list::putt_link_log (class(type_sl_link), intent(inout) l, logical, intent(in) d) private
Recursive subroutine for inserting a link data into the list tail (logical).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 1550 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::putt_link_r4(), and data_type_sl_list::type_sl_link::putt_link_r8().
subroutine data_type_sl_list::array_link_r8 (class(type_sl_link), intent(in) l, real(r8p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (R8P).
Definition at line 1570 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::putt_link_i8().
subroutine data_type_sl_list::array_link_r4 (class(type_sl_link), intent(in) l, real(r4p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (R4P).
Definition at line 1605 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::putt_link_i2(), and data_type_sl_list::type_sl_link::putt_link_i4().
subroutine data_type_sl_list::array_link_i8 (class(type_sl_link), intent(in) l, integer(i8p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (I8P).
Definition at line 1640 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::putt_link_ch(), and data_type_sl_list::type_sl_link::putt_link_i1().
subroutine data_type_sl_list::array_link_i4 (class(type_sl_link), intent(in) l, integer(i4p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (I4P).
Definition at line 1675 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::e(), and data_type_sl_list::type_sl_link::putt_link_log().
subroutine data_type_sl_list::array_link_i2 (class(type_sl_link), intent(in) l, integer(i2p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (I2P).
Definition at line 1710 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::array_link_i1 (class(type_sl_link), intent(in) l, integer(i1p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (I1P).
Definition at line 1745 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::array_link_ch (class(type_sl_link), intent(in) l, integer(i4p), intent(in) Nc, character(nc), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (character).
Definition at line 1780 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::array_link_log (class(type_sl_link), intent(in) l, logical, dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (logical).
Definition at line 1817 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::free_list (class(type_sl_list), intent(inout) l) private
Subroutine for freeing (destroying) the list.
Parameters
[in,out] l List.
Definition at line 1852 of file Data_Type_SL_List.f90.
integer(i4p) function data_type_sl_list::leng_list (class(type_sl_list), intent(in) l) private
Function for computing the length of the list.
Definition at line 1871 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
logical function data_type_sl_list::homo_list (class(type_sl_list), intent(in) l) private
Recursive subroutine for checking if the list is homogeneous.
Parameters
[in] l List.
Definition at line 1886 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::del_list (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n) private
Subroutine for deleting n-th link of the list.
Parameters
[in,out] l List.
[in] n Element of the list to be deleted.
Definition at line 1901 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::delh_list (class(type_sl_list), intent(inout) l) private
Subroutine for deleting head link of the list.
Parameters
[in,out] l List.
Definition at line 1918 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
Referenced by data_type_sl_list::type_sl_list::free().
subroutine data_type_sl_list::delt_list (class(type_sl_list), intent(inout) l) private
Subroutine for deleting tail link of the list.
Parameters
[in,out] l List.
Definition at line 1934 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
Referenced by data_type_sl_list::type_sl_list::leng().
subroutine data_type_sl_list::get_list_r8 (class(type_sl_list), intent(in) l, integer(i4p), intent(in) n, real(r8p), intent(out) d) private
Subroutine for getting data from the n-th link of list (R8P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 1954 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::get_list_r4 (class(type_sl_list), intent(in) l, integer(i4p), intent(in) n, real(r4p), intent(out) d) private
Subroutine for getting data from the n-th link of list (R4P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 1972 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::get_list_i8 (class(type_sl_list), intent(in) l, integer(i4p), intent(in) n, integer(i8p), intent(out) d) private
Subroutine for getting data from the n-th link of list (I8P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 1990 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::e().
subroutine data_type_sl_list::get_list_i4 (class(type_sl_list), intent(in) l, integer(i4p), intent(in) n, integer(i4p), intent(out) d) private
Subroutine for getting data from the n-th link of list (I4P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 2008 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::get_list_i2 (class(type_sl_list), intent(in) l, integer(i4p), intent(in) n, integer(i2p), intent(out) d) private
Subroutine for getting data from the n-th link of list (I2P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 2026 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::get_list_i1 (class(type_sl_list), intent(in) l, integer(i4p), intent(in) n, integer(i1p), intent(out) d) private
Subroutine for getting data from the n-th link of list (I1P).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 2044 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::get_list_ch (class(type_sl_list), intent(in) l, integer(i4p), intent(in) n, character(*), intent(out) d) private
Subroutine for getting data from the n-th link of list (character).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 2062 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::get_list_log (class(type_sl_list), intent(in) l, integer(i4p), intent(in) n, logical, intent(out) d) private
Subroutine for getting data from the n-th link of list (logical).
Note
If n<1 then the first link data is returned, whereas if n> list's length the last data is returned.
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[in] n Element of the list to be found.
[out] d Link data.
Definition at line 2080 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::geth_list_r8 (class(type_sl_list), intent(in) l, real(r8p), intent(out) d) private
Subroutine for getting a link data from the list head (R8P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2099 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::geth_list_r4 (class(type_sl_list), intent(in) l, real(r4p), intent(out) d) private
Subroutine for getting a link data from the list head (R4P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2115 of file Data_Type_SL_List.f90.
References ir_precision::minr16p.
subroutine data_type_sl_list::geth_list_i8 (class(type_sl_list), intent(in) l, integer(i8p), intent(out) d) private
Subroutine for getting a link data from the list head (I8P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2131 of file Data_Type_SL_List.f90.
References ir_precision::minr8p.
subroutine data_type_sl_list::geth_list_i4 (class(type_sl_list), intent(in) l, integer(i4p), intent(out) d) private
Subroutine for getting a link data from the list head (I4P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2147 of file Data_Type_SL_List.f90.
References ir_precision::minr4p.
subroutine data_type_sl_list::geth_list_i2 (class(type_sl_list), intent(in) l, integer(i2p), intent(out) d) private
Subroutine for getting a link data from the list head (I2P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2163 of file Data_Type_SL_List.f90.
References ir_precision::mini8p.
subroutine data_type_sl_list::geth_list_i1 (class(type_sl_list), intent(in) l, integer(i1p), intent(out) d) private
Subroutine for getting a link data from the list head (I1P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2179 of file Data_Type_SL_List.f90.
References ir_precision::mini2p, and ir_precision::mini4p.
subroutine data_type_sl_list::geth_list_ch (class(type_sl_list), intent(in) l, character(*), intent(out) d) private
Subroutine for getting a link data from the list head (character).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2195 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::geth_list_log (class(type_sl_list), intent(in) l, logical, intent(out) d) private
Subroutine for getting a link data from the list head (logical).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2211 of file Data_Type_SL_List.f90.
References ir_precision::mini1p.
subroutine data_type_sl_list::gett_list_r8 (class(type_sl_list), intent(in) l, real(r8p), intent(out) d) private
Subroutine for getting a link data from the list tail (R8P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2229 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::gett_list_r4 (class(type_sl_list), intent(in) l, real(r4p), intent(out) d) private
Subroutine for getting a link data from the list tail (R4P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2245 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::gett_list_i8 (class(type_sl_list), intent(in) l, integer(i8p), intent(out) d) private
Subroutine for getting a link data from the list tail (I8P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2261 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::gett_list_i4 (class(type_sl_list), intent(in) l, integer(i4p), intent(out) d) private
Subroutine for getting a link data from the list tail (I4P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2277 of file Data_Type_SL_List.f90.
References ir_precision::minr16p.
subroutine data_type_sl_list::gett_list_i2 (class(type_sl_list), intent(in) l, integer(i2p), intent(out) d) private
Subroutine for getting a link data from the list tail (I2P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2293 of file Data_Type_SL_List.f90.
References ir_precision::minr8p.
subroutine data_type_sl_list::gett_list_i1 (class(type_sl_list), intent(in) l, integer(i1p), intent(out) d) private
Subroutine for getting a link data from the list tail (I1P).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2309 of file Data_Type_SL_List.f90.
References ir_precision::minr4p.
subroutine data_type_sl_list::gett_list_ch (class(type_sl_list), intent(in) l, character(*), intent(out) d) private
Subroutine for getting a link data from the list tail (character).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2325 of file Data_Type_SL_List.f90.
References ir_precision::mini8p.
subroutine data_type_sl_list::gett_list_log (class(type_sl_list), intent(in) l, logical, intent(out) d) private
Subroutine for getting a link data from the list tail (logical).
Note
If data is not present the minimum representable value is returned (for error checking).
Parameters
[in] l List.
[out] d Link data.
Definition at line 2341 of file Data_Type_SL_List.f90.
References ir_precision::mini2p, and ir_precision::mini4p.
subroutine data_type_sl_list::put_list_r8 (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n, real(r8p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (R8P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Link data.
Definition at line 2359 of file Data_Type_SL_List.f90.
References ir_precision::mini1p.
subroutine data_type_sl_list::put_list_r4 (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n, real(r4p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (R4P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Link data.
Definition at line 2377 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::put_list_i8 (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n, integer(i8p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (I8P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Link data.
Definition at line 2395 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::put_list_i4 (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n, integer(i4p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (I4P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Link data.
Definition at line 2413 of file Data_Type_SL_List.f90.
References ir_precision::minr16p, and ir_precision::minr8p.
subroutine data_type_sl_list::put_list_i2 (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n, integer(i2p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (I2P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Link data.
Definition at line 2431 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::put_list_i1 (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n, integer(i1p), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (I1P).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Link data.
Definition at line 2449 of file Data_Type_SL_List.f90.
References ir_precision::minr4p.
subroutine data_type_sl_list::put_list_ch (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n, character(*), intent(in) d) private
Subroutine for inserting a link into the n-th link of list (character).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Data of the current link.
Definition at line 2467 of file Data_Type_SL_List.f90.
References ir_precision::mini8p.
subroutine data_type_sl_list::put_list_log (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) n, logical, intent(in) d) private
Subroutine for inserting a link into the n-th link of list (logical).
Note
If n<1 then the data is inserted at first link , whereas if n> list's length the data is inserted at last.
Parameters
[in,out] l List.
[in] n Element of the list to be inserted.
[in] d Link data.
Definition at line 2485 of file Data_Type_SL_List.f90.
References ir_precision::mini4p.
subroutine data_type_sl_list::puth_list_r8 (class(type_sl_list), intent(inout) l, real(r8p), intent(in) d) private
Subroutine for inserting a link data into the list head (R8P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2504 of file Data_Type_SL_List.f90.
References ir_precision::mini2p.
subroutine data_type_sl_list::puth_list_r4 (class(type_sl_list), intent(inout) l, real(r4p), intent(in) d) private
Subroutine for inserting a link data into the list head (R4P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2520 of file Data_Type_SL_List.f90.
References ir_precision::mini1p.
subroutine data_type_sl_list::puth_list_i8 (class(type_sl_list), intent(inout) l, integer(i8p), intent(in) d) private
Subroutine for inserting a link data into the list head (I8P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2536 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_list_i4 (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) d) private
Subroutine for inserting a link data into the list head (I4P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2552 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_list_i2 (class(type_sl_list), intent(inout) l, integer(i2p), intent(in) d) private
Subroutine for inserting a link data into the list head (I2P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2568 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_list_i1 (class(type_sl_list), intent(inout) l, integer(i1p), intent(in) d) private
Subroutine for inserting a link data into the list head (I1P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2584 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_list_ch (class(type_sl_list), intent(inout) l, character(*), intent(in) d) private
Subroutine for inserting a link data into the list head (character).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2600 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::puth_list_log (class(type_sl_list), intent(inout) l, logical, intent(in) d) private
Subroutine for inserting a link data into the list head (logical).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2616 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::putt_list_r8 (class(type_sl_list), intent(inout) l, real(r8p), intent(in) d) private
Subroutine for inserting a link data into the list tail (R8P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2634 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::putt_list_r4 (class(type_sl_list), intent(inout) l, real(r4p), intent(in) d) private
Subroutine for inserting a link data into the list tail (R4P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2650 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::putt_list_i8 (class(type_sl_list), intent(inout) l, integer(i8p), intent(in) d) private
Subroutine for inserting a link data into the list tail (I8P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2666 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::putt_list_i4 (class(type_sl_list), intent(inout) l, integer(i4p), intent(in) d) private
Subroutine for inserting a link data into the list tail (I4P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2682 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::putt_list_i2 (class(type_sl_list), intent(inout) l, integer(i2p), intent(in) d) private
Subroutine for inserting a link data into the list tail (I2P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2698 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::putt_list_i1 (class(type_sl_list), intent(inout) l, integer(i1p), intent(in) d) private
Subroutine for inserting a link data into the list tail (I1P).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2714 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::putt_list_ch (class(type_sl_list), intent(inout) l, character(*), intent(in) d) private
Subroutine for inserting a link data into the list tail (character).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2730 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::putt_list_log (class(type_sl_list), intent(inout) l, logical, intent(in) d) private
Subroutine for inserting a link data into the list tail (logical).
Parameters
[in,out] l List.
[in] d Data of the current link.
Definition at line 2746 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::array_list_r8 (class(type_sl_list), intent(in) l, real(r8p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (R8P).
Definition at line 2764 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::array_list_r4 (class(type_sl_list), intent(in) l, real(r4p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (R4P).
Definition at line 2780 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::array_list_i8 (class(type_sl_list), intent(in) l, integer(i8p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (I8P).
Definition at line 2796 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::array_list_i4 (class(type_sl_list), intent(in) l, integer(i4p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (I4P).
Definition at line 2812 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::array_list_i2 (class(type_sl_list), intent(in) l, integer(i2p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (I2P).
Definition at line 2828 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::array_list_i1 (class(type_sl_list), intent(in) l, integer(i1p), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (I1P).
Definition at line 2844 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::array_list_ch (class(type_sl_list), intent(in) l, integer(i4p), intent(in) Nc, character(nc), dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (character).
Definition at line 2860 of file Data_Type_SL_List.f90.
subroutine data_type_sl_list::array_list_log (class(type_sl_list), intent(in) l, logical, dimension(:), intent(out), allocatable a) private
Subroutine for converting list to array (logical).
Definition at line 2877 of file Data_Type_SL_List.f90.
References lib_thermodynamic_laws_ideal::a().