OFF: Lib_Fluidynamic
Lib_Fluidynamic
Public Procedures
Functions/Subroutines
pure subroutine, public lib_fluidynamic::prim2cons (prim, cons)
Subroutine for converting primitive variables to conservative variables.
pure subroutine, public lib_fluidynamic::cons2prim (cp0, cv0, cons, prim)
Subroutine for converting conservative variables to primitive variables.
subroutine, public lib_fluidynamic::primitive2conservative (block)
Subroutine for converting primitive variables to conservative variables of all cells of a block.
subroutine, public lib_fluidynamic::conservative2primitive (block)
Subroutine for converting conservative variables to primitive variables of all cells of a block.
subroutine, public lib_fluidynamic::boundary_conditions (l, block)
Subroutine for imposing the boundary conditions of blocks of grid level "l" updating the ghost cells.
subroutine, public lib_fluidynamic::solve_grl (l, block)
Subroutine for solving (performing one time step integration) the conservation equations for grid level "l".
Detailed Description
Function/Subroutine Documentation
pure subroutine, public lib_fluidynamic::prim2cons (type(type_primitive), intent(in) prim, type(type_conservative), intent(inout) cons)
Subroutine for converting primitive variables to conservative variables.
The conversion laws are:
Partial densities
Momentum
Energy
Parameters
[in] prim Primitive variables (see Type_Primitive definition).
[in,out] cons Conservative variables (see Type_Conservative definition).
Definition at line 73 of file Lib_Fluidynamic.f90.
Referenced by lib_fluidynamic::primitive2conservative().
pure subroutine, public lib_fluidynamic::cons2prim (real(r_p), dimension(:), intent(in) cp0, real(r_p), dimension(:), intent(in) cv0, type(type_conservative), intent(in) cons, type(type_primitive), intent(inout) prim)
Subroutine for converting conservative variables to primitive variables.
The conversion laws are:
Partial densities
Density
Specific heats ratio
Velocity
Pressure
where Ns is the number of initial species and are the initial specific heats.
Parameters
[in] cp0 Specific heat at constant p of initial species.
[in] cv0 Specific heat at constant v of initial species.
[in] cons Conservative variables (see Type_Conservative definition).
[in,out] prim Primitive variables (see Type_Primitive definition).
Definition at line 101 of file Lib_Fluidynamic.f90.
References data_type_tensor::type_tensor::sq_norm().
Referenced by lib_fluidynamic::conservative2primitive(), and lib_fluidynamic::rk_time_integration().
subroutine, public lib_fluidynamic::primitive2conservative (type(type_sblock), intent(inout) block)
Subroutine for converting primitive variables to conservative variables of all cells of a block.
Note
Only the inner cells of the block are converted.
Parameters
[in,out] block Block-level data (see Type_SBlock definition).
Definition at line 129 of file Lib_Fluidynamic.f90.
References lib_fluidynamic::prim2cons().
Referenced by off(), and off_init().
subroutine, public lib_fluidynamic::conservative2primitive (type(type_sblock), intent(inout) block)
Subroutine for converting conservative variables to primitive variables of all cells of a block.
Note
Only the inner cells of the block are converted.
Parameters
[in,out] block Block-level data (see Type_SBlock definition).
Definition at line 156 of file Lib_Fluidynamic.f90.
References lib_fluidynamic::cons2prim().
Referenced by lib_multigrid::correct(), off(), lib_multigrid::restrict(), and lib_fluidynamic::solve_grl().
subroutine, public lib_fluidynamic::boundary_conditions (integer(i_p), intent(in) l, type(type_sblock), dimension(1:), intent(inout) block)
Subroutine for imposing the boundary conditions of blocks of grid level "l" updating the ghost cells.
Note
Considering the ghost cell and the inner one (being the other bound) the available boundary conditions are:
REF: reflective boundary condition ;
EXT: extrapolation boundary condition ;
PER: periodic boundary condition ;
ADJ: adjacent (cell) boundary condition where "a" is the adjacent cell (b,i,j,k indexes must be specified);
IN1: supersonic inflow steady boundary condition .
where are the primitive variables.
Parameters
[in] l Current grid level.
[in,out] block Block-level data.
Definition at line 767 of file Lib_Fluidynamic.f90.
References lib_parallel::blockmap, lib_vtk_io::f, lib_parallel::psendrecv(), and lib_fluidynamic::set_bc().
Referenced by lib_multigrid::correct(), off(), lib_multigrid::restrict(), and lib_fluidynamic::solve_grl().
subroutine, public lib_fluidynamic::solve_grl (integer(i_p), intent(in) l, type(type_sblock), dimension(1:), intent(inout) block)
Subroutine for solving (performing one time step integration) the conservation equations for grid level "l".
Parameters
[in] l Current grid level.
[in,out] block Block-level data(see Type_SBlock definition).
Definition at line 951 of file Lib_Fluidynamic.f90.
References lib_io_misc::basename(), lib_parallel::blockmap, lib_fluidynamic::boundary_conditions(), lib_fluidynamic::compute_time(), lib_fluidynamic::conservative2primitive(), data_type_time::crono(), lib_profiling::instant0, lib_thermodynamic_laws_ideal::p(), lib_profiling::profile(), lib_thermodynamic_laws_ideal::r(), lib_fluidynamic::residuals(), lib_fluidynamic::rk_stages_sum(), lib_runge_kutta::rk_time_integ(), lib_fluidynamic::rk_time_integration(), and data_type_time::seconds_to_time().
Referenced by off().