OFF: Lib_Math
Lib_Math
Interfaces
Data Types
interface lib_math::isort
Subroutine for computing prime factors of input integer number.
interface lib_math::qsort
Subroutine for performing QuickSort with ascending order.
interface lib_math::spline3
Function for computing cubic spline interpolation of an array of values.
interface lib_math::average
Example of usage:
interface lib_math::digit
Digit overloading.
interface lib_math::div2
Div2 overloading.
interface lib_math::interpolate1
Linear interpolate overloading.
interface lib_math::interpolate2
Bi-linear interpolate overloading.
interface lib_math::interpolate3
Tri-linear interpolate overloading.
interface lib_math::degree
Degree overloading.
interface lib_math::radiant
Radiant overloading.
interface lib_math::delta1_2o
delta1_2o overloading
interface lib_math::delta2_2o
delta2_2o overloading
interface lib_math::abs_grad
abs_grad overloading
interface lib_math::laplacian
laplacian overloading
Detailed Description
Data Type Documentation
interface lib_math::isort
Subroutine for computing prime factors of input integer number.
The results is an array of integers containing the prime factors list. Example of usage:
...
integer(I4P):: n=246
integer(I4P), allocatable:: pf(:)
...
call prime(n=n,p=pf)
The input integer n can have all the kinds defined in IR_Precision module.
Note
The output array containing the factors must allocatable of the same kind of input integer.Subroutine for performing InsertionSort with ascending order. Example of usage:
...
integer(I4P):: a(1:100)
...
call isort(a)
The input array can be integer or real with all the kinds defined in IR_Precision module.
Definition at line 102 of file Lib_Math.f90.
Private Member Functions
pure subroutine isort_r8 (array)
Subroutine for performing InsertionSort with ascending order (R8P).
pure subroutine isort_r4 (array)
Subroutine for performing InsertionSort with ascending order (R4P).
pure subroutine isort_i8 (array)
Subroutine for performing InsertionSort with ascending order (I8P).
pure subroutine isort_i4 (array)
Subroutine for performing InsertionSort with ascending order (I4P).
pure subroutine isort_i2 (array)
Subroutine for performing InsertionSort with ascending order (I2P).
pure subroutine isort_i1 (array)
Subroutine for performing InsertionSort with ascending order (I1P).
Member Function/Subroutine Documentation
pure subroutine lib_math::isort::isort_r8 (real(r8p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (R8P).
Parameters
[in,out] array Array to be sorted.
Definition at line 423 of file Lib_Math.f90.
Referenced by lib_math::qsort_r8().
pure subroutine lib_math::isort::isort_r4 (real(r4p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (R4P).
Parameters
[in,out] array Array to be sorted.
Definition at line 446 of file Lib_Math.f90.
Referenced by lib_math::qsort_r4().
pure subroutine lib_math::isort::isort_i8 (integer(i8p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (I8P).
Parameters
[in,out] array Array to be sorted.
Definition at line 469 of file Lib_Math.f90.
Referenced by lib_math::qsort_i8().
pure subroutine lib_math::isort::isort_i4 (integer(i4p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (I4P).
Parameters
[in,out] array Array to be sorted.
Definition at line 492 of file Lib_Math.f90.
Referenced by lib_math::qsort_i4().
pure subroutine lib_math::isort::isort_i2 (integer(i2p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (I2P).
Parameters
[in,out] array Array to be sorted.
Definition at line 515 of file Lib_Math.f90.
Referenced by lib_math::qsort_i2().
pure subroutine lib_math::isort::isort_i1 (integer(i1p), dimension(1:), intent(inout) array) private
Subroutine for performing InsertionSort with ascending order (I1P).
Parameters
[in,out] array Array to be sorted.
Definition at line 538 of file Lib_Math.f90.
Referenced by lib_math::qsort_i1().
interface lib_math::qsort
Subroutine for performing QuickSort with ascending order.
Example of usage:
...
integer(I4P):: a(1:100)
...
call qsort(a)
The input array can be integer or real with all the kinds defined in IR_Precision module.
Definition at line 118 of file Lib_Math.f90.
Private Member Functions
subroutine qsort_r8 (array)
Subroutine for performing QuickSort with ascending order (R8P).
subroutine qsort_r4 (array)
Subroutine for performing QuickSort with ascending order (R4P).
subroutine qsort_i8 (array)
Subroutine for performing QuickSort with ascending order (I8P).
subroutine qsort_i4 (array)
Subroutine for performing QuickSort with ascending order (I4P).
subroutine qsort_i2 (array)
Subroutine for performing QuickSort with ascending order (I2P).
subroutine qsort_i1 (array)
Subroutine for performing QuickSort with ascending order (I1P).
Member Function/Subroutine Documentation
subroutine lib_math::qsort::qsort_r8 (real(r8p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (R8P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 636 of file Lib_Math.f90.
subroutine lib_math::qsort::qsort_r4 (real(r4p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (R4P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 709 of file Lib_Math.f90.
subroutine lib_math::qsort::qsort_i8 (integer(i8p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (I8P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 782 of file Lib_Math.f90.
subroutine lib_math::qsort::qsort_i4 (integer(i4p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (I4P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 855 of file Lib_Math.f90.
subroutine lib_math::qsort::qsort_i2 (integer(i2p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (I2P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 928 of file Lib_Math.f90.
subroutine lib_math::qsort::qsort_i1 (integer(i1p), dimension(1:), intent(inout) array) private
Subroutine for performing QuickSort with ascending order (I1P).
Note
If the number of array elements is "small" the InsertionSort is directly used.
Parameters
[in,out] array Array to be sorted.
Definition at line 1001 of file Lib_Math.f90.
interface lib_math::spline3
Function for computing cubic spline interpolation of an array of values.
This function is an interface to three different functions: there is one function for each of the three real kinds supported (R16P, R8P and R4P).
Note
the input arrays "x", "v" and "vi" must be ordered with increasing values. Details of implementation can be found in "Numerical recipes: The art of scientific computing", third edition, 2007, ISBN 0521880688.
Definition at line 130 of file Lib_Math.f90.
Private Member Functions
pure function spline3_r8 (bc1, bcn, x, v, xi)
Function for computing cubic spline interpolation of an array of values (R8P).
pure function spline3_r4 (bc1, bcn, x, v, xi)
Function for computing cubic spline interpolation of an array of values (R4P).
Member Function/Subroutine Documentation
pure function lib_math::spline3::spline3_r8 (real(r8p), intent(in), optional bc1, real(r8p), intent(in), optional bcn, real(r8p), dimension(1:), intent(in) x, real(r8p), dimension(1:), intent(in) v, real(r8p), dimension(1:), intent(in) xi) private
Function for computing cubic spline interpolation of an array of values (R8P).
Parameters
[in] bc1 Boundary conditions of second derivative at first node.
[in] bcn Boundary conditions of second derivative at last node.
[in] x Independent variable abscissa of original data.
[in] v Dependent variable (to be interpolated) of original data.
[in] xi Independent variable abscissa of interpolating points.
Definition at line 1164 of file Lib_Math.f90.
pure function lib_math::spline3::spline3_r4 (real(r4p), intent(in), optional bc1, real(r4p), intent(in), optional bcn, real(r4p), dimension(1:), intent(in) x, real(r4p), dimension(1:), intent(in) v, real(r4p), dimension(1:), intent(in) xi) private
Function for computing cubic spline interpolation of an array of values (R4P).
Parameters
[in] bc1 Boundary conditions of second derivative at first node.
[in] bcn Boundary conditions of second derivative at last node.
[in] x Independent variable abscissa of original data.
[in] v Dependent variable (to be interpolated) of original data.
[in] xi Independent variable abscissa of interpolating points.
Definition at line 1254 of file Lib_Math.f90.
interface lib_math::average
Example of usage:
...
real(R4P):: x(1:100),v(1:100),xi(1:200),vi(1:200)
...
vi = spline3(x,v,xi)
The real input arrays can have all the kinds defined in IR_Precision module. Average overloading
Definition at line 147 of file Lib_Math.f90.
Private Member Functions
pure function average_vectorial1d_r8 (x)
pure function average_vectorial2d_r8 (x)
pure function average_vectorial3d_r8 (x)
pure function average_vectorial1d_r4 (x)
pure function average_vectorial2d_r4 (x)
pure function average_vectorial3d_r4 (x)
Member Function/Subroutine Documentation
pure function lib_math::average::average_vectorial1d_r8 (real(r8p), dimension(:), intent(in) x) private
Definition at line 1510 of file Lib_Math.f90.
pure function lib_math::average::average_vectorial2d_r8 (real(r8p), dimension(:,:), intent(in) x) private
Definition at line 1561 of file Lib_Math.f90.
pure function lib_math::average::average_vectorial3d_r8 (real(r8p), dimension(:,:,:), intent(in) x) private
Definition at line 1612 of file Lib_Math.f90.
pure function lib_math::average::average_vectorial1d_r4 (real(r4p), dimension(:), intent(in) x) private
Definition at line 1527 of file Lib_Math.f90.
pure function lib_math::average::average_vectorial2d_r4 (real(r4p), dimension(:,:), intent(in) x) private
Definition at line 1578 of file Lib_Math.f90.
pure function lib_math::average::average_vectorial3d_r4 (real(r4p), dimension(:,:,:), intent(in) x) private
Definition at line 1629 of file Lib_Math.f90.
interface lib_math::digit
Digit overloading.
Definition at line 156 of file Lib_Math.f90.
Private Member Functions
elemental function digit_i8 (n)
elemental function digit_i4 (n)
elemental function digit_i2 (n)
elemental function digit_i1 (n)
Member Function/Subroutine Documentation
elemental function lib_math::digit::digit_i8 (integer(i8p), intent(in) n) private
Definition at line 1647 of file Lib_Math.f90.
elemental function lib_math::digit::digit_i4 (integer(i4p), intent(in) n) private
Definition at line 1666 of file Lib_Math.f90.
elemental function lib_math::digit::digit_i2 (integer(i2p), intent(in) n) private
Definition at line 1685 of file Lib_Math.f90.
elemental function lib_math::digit::digit_i1 (integer(i1p), intent(in) n) private
Definition at line 1704 of file Lib_Math.f90.
interface lib_math::div2
Div2 overloading.
Definition at line 161 of file Lib_Math.f90.
Private Member Functions
elemental function div2_i8 (n)
elemental function div2_i4 (n)
elemental function div2_i2 (n)
elemental function div2_i1 (n)
Member Function/Subroutine Documentation
elemental function lib_math::div2::div2_i8 (integer(i8p), intent(in) n) private
Definition at line 1793 of file Lib_Math.f90.
elemental function lib_math::div2::div2_i4 (integer(i4p), intent(in) n) private
Definition at line 1770 of file Lib_Math.f90.
elemental function lib_math::div2::div2_i2 (integer(i2p), intent(in) n) private
Definition at line 1747 of file Lib_Math.f90.
elemental function lib_math::div2::div2_i1 (integer(i1p), intent(in) n) private
Definition at line 1724 of file Lib_Math.f90.
interface lib_math::interpolate1
Linear interpolate overloading.
Definition at line 166 of file Lib_Math.f90.
Private Member Functions
elemental function interpolate1_r8 (x1, x2, V1, V2, x)
elemental function interpolate1_r4 (x1, x2, V1, V2, x)
Member Function/Subroutine Documentation
elemental function lib_math::interpolate1::interpolate1_r8 (real(r8p), intent(in) x1, real(r8p), intent(in) x2, real(r8p), intent(in) V1, real(r8p), intent(in) V2, real(r8p), intent(in) x) private
Definition at line 1836 of file Lib_Math.f90.
Referenced by lib_math::interpolate2_r8(), and lib_math::interpolate3_r8().
elemental function lib_math::interpolate1::interpolate1_r4 (real(r4p), intent(in) x1, real(r4p), intent(in) x2, real(r4p), intent(in) V1, real(r4p), intent(in) V2, real(r4p), intent(in) x) private
Definition at line 1855 of file Lib_Math.f90.
Referenced by lib_math::interpolate2_r4(), and lib_math::interpolate3_r4().
interface lib_math::interpolate2
Bi-linear interpolate overloading.
Definition at line 174 of file Lib_Math.f90.
Private Member Functions
elemental function interpolate2_r8 (x1, y1, x2, y2, V11, V12, V21, V22, x, y)
elemental function interpolate2_r4 (x1, y1, x2, y2, V11, V12, V21, V22, x, y)
Member Function/Subroutine Documentation
elemental function lib_math::interpolate2::interpolate2_r8 (real(r8p), intent(in) x1, real(r8p), intent(in) y1, real(r8p), intent(in) x2, real(r8p), intent(in) y2, real(r8p), intent(in) V11, real(r8p), intent(in) V12, real(r8p), intent(in) V21, real(r8p), intent(in) V22, real(r8p), intent(in) x, real(r8p), intent(in) y) private
Definition at line 1909 of file Lib_Math.f90.
Referenced by lib_math::interpolate3_r8().
elemental function lib_math::interpolate2::interpolate2_r4 (real(r4p), intent(in) x1, real(r4p), intent(in) y1, real(r4p), intent(in) x2, real(r4p), intent(in) y2, real(r4p), intent(in) V11, real(r4p), intent(in) V12, real(r4p), intent(in) V21, real(r4p), intent(in) V22, real(r4p), intent(in) x, real(r4p), intent(in) y) private
Definition at line 1944 of file Lib_Math.f90.
Referenced by lib_math::interpolate3_r4().
interface lib_math::interpolate3
Tri-linear interpolate overloading.
Definition at line 182 of file Lib_Math.f90.
Private Member Functions
elemental function interpolate3_r8 (x1, y1, z1, x2, y2, z2, V111, V121, V211, V221, V112, V122, V212, V222, x, y, z)
elemental function interpolate3_r4 (x1, y1, z1, x2, y2, z2, V111, V121, V211, V221, V112, V122, V212, V222, x, y, z)
Member Function/Subroutine Documentation
elemental function lib_math::interpolate3::interpolate3_r8 (real(r8p), intent(in) x1, real(r8p), intent(in) y1, real(r8p), intent(in) z1, real(r8p), intent(in) x2, real(r8p), intent(in) y2, real(r8p), intent(in) z2, real(r8p), intent(in) V111, real(r8p), intent(in) V121, real(r8p), intent(in) V211, real(r8p), intent(in) V221, real(r8p), intent(in) V112, real(r8p), intent(in) V122, real(r8p), intent(in) V212, real(r8p), intent(in) V222, real(r8p), intent(in) x, real(r8p), intent(in) y, real(r8p), intent(in) z) private
Definition at line 2023 of file Lib_Math.f90.
elemental function lib_math::interpolate3::interpolate3_r4 (real(r4p), intent(in) x1, real(r4p), intent(in) y1, real(r4p), intent(in) z1, real(r4p), intent(in) x2, real(r4p), intent(in) y2, real(r4p), intent(in) z2, real(r4p), intent(in) V111, real(r4p), intent(in) V121, real(r4p), intent(in) V211, real(r4p), intent(in) V221, real(r4p), intent(in) V112, real(r4p), intent(in) V122, real(r4p), intent(in) V212, real(r4p), intent(in) V222, real(r4p), intent(in) x, real(r4p), intent(in) y, real(r4p), intent(in) z) private
Definition at line 2067 of file Lib_Math.f90.
interface lib_math::degree
Degree overloading.
Definition at line 190 of file Lib_Math.f90.
Private Member Functions
elemental function degree_scalar_r8 (x_rad)
pure function degree_vectorial1d_r8 (x_rad)
pure function degree_vectorial2d_r8 (x_rad)
pure function degree_vectorial3d_r8 (x_rad)
elemental function degree_scalar_r4 (x_rad)
pure function degree_vectorial1d_r4 (x_rad)
pure function degree_vectorial2d_r4 (x_rad)
pure function degree_vectorial3d_r4 (x_rad)
Member Function/Subroutine Documentation
elemental function lib_math::degree::degree_scalar_r8 (real(r8p), intent(in) x_rad) private
Definition at line 2129 of file Lib_Math.f90.
pure function lib_math::degree::degree_vectorial1d_r8 (real(r8p), dimension(:), intent(in) x_rad) private
Definition at line 2180 of file Lib_Math.f90.
pure function lib_math::degree::degree_vectorial2d_r8 (real(r8p), dimension(:,:), intent(in) x_rad) private
Definition at line 2231 of file Lib_Math.f90.
pure function lib_math::degree::degree_vectorial3d_r8 (real(r8p), dimension(:,:,:), intent(in) x_rad) private
Definition at line 2282 of file Lib_Math.f90.
elemental function lib_math::degree::degree_scalar_r4 (real(r4p), intent(in) x_rad) private
Definition at line 2146 of file Lib_Math.f90.
pure function lib_math::degree::degree_vectorial1d_r4 (real(r4p), dimension(:), intent(in) x_rad) private
Definition at line 2197 of file Lib_Math.f90.
pure function lib_math::degree::degree_vectorial2d_r4 (real(r4p), dimension(:,:), intent(in) x_rad) private
Definition at line 2248 of file Lib_Math.f90.
pure function lib_math::degree::degree_vectorial3d_r4 (real(r4p), dimension(:,:,:), intent(in) x_rad) private
Definition at line 2299 of file Lib_Math.f90.
interface lib_math::radiant
Radiant overloading.
Definition at line 199 of file Lib_Math.f90.
Private Member Functions
elemental function radiant_scalar_r8 (x_deg)
pure function radiant_vectorial1d_r8 (x_deg)
pure function radiant_vectorial2d_r8 (x_deg)
pure function radiant_vectorial3d_r8 (x_deg)
elemental function radiant_scalar_r4 (x_deg)
pure function radiant_vectorial1d_r4 (x_deg)
pure function radiant_vectorial2d_r4 (x_deg)
pure function radiant_vectorial3d_r4 (x_deg)
Member Function/Subroutine Documentation
elemental function lib_math::radiant::radiant_scalar_r8 (real(r8p), intent(in) x_deg) private
Definition at line 2334 of file Lib_Math.f90.
pure function lib_math::radiant::radiant_vectorial1d_r8 (real(r8p), dimension(:), intent(in) x_deg) private
Definition at line 2385 of file Lib_Math.f90.
pure function lib_math::radiant::radiant_vectorial2d_r8 (real(r8p), dimension(:,:), intent(in) x_deg) private
Definition at line 2436 of file Lib_Math.f90.
pure function lib_math::radiant::radiant_vectorial3d_r8 (real(r8p), dimension(:,:,:), intent(in) x_deg) private
Definition at line 2487 of file Lib_Math.f90.
elemental function lib_math::radiant::radiant_scalar_r4 (real(r4p), intent(in) x_deg) private
Definition at line 2351 of file Lib_Math.f90.
pure function lib_math::radiant::radiant_vectorial1d_r4 (real(r4p), dimension(:), intent(in) x_deg) private
Definition at line 2402 of file Lib_Math.f90.
pure function lib_math::radiant::radiant_vectorial2d_r4 (real(r4p), dimension(:,:), intent(in) x_deg) private
Definition at line 2453 of file Lib_Math.f90.
pure function lib_math::radiant::radiant_vectorial3d_r4 (real(r4p), dimension(:,:,:), intent(in) x_deg) private
Definition at line 2504 of file Lib_Math.f90.
interface lib_math::delta1_2o
delta1_2o overloading
Definition at line 208 of file Lib_Math.f90.
Private Member Functions
elemental function delta1_2o_r8 (Sp1, Sm1, Ds)
elemental function delta1_2o_r4 (Sp1, Sm1, Ds)
Member Function/Subroutine Documentation
elemental function lib_math::delta1_2o::delta1_2o_r8 (real(r8p), intent(in) Sp1, real(r8p), intent(in) Sm1, real(r8p), intent(in) Ds) private
Definition at line 2541 of file Lib_Math.f90.
Referenced by lib_math::abs_grad_r8().
elemental function lib_math::delta1_2o::delta1_2o_r4 (real(r4p), intent(in) Sp1, real(r4p), intent(in) Sm1, real(r4p), intent(in) Ds) private
Definition at line 2560 of file Lib_Math.f90.
Referenced by lib_math::abs_grad_r4().
interface lib_math::delta2_2o
delta2_2o overloading
Definition at line 216 of file Lib_Math.f90.
Private Member Functions
elemental function delta2_2o_r8 (Sp1, S, Sm1, Ds)
elemental function delta2_2o_r4 (Sp1, S, Sm1, Ds)
Member Function/Subroutine Documentation
elemental function lib_math::delta2_2o::delta2_2o_r8 (real(r8p), intent(in) Sp1, real(r8p), intent(in) S, real(r8p), intent(in) Sm1, real(r8p), intent(in) Ds) private
Definition at line 2600 of file Lib_Math.f90.
Referenced by lib_math::laplacian_r8().
elemental function lib_math::delta2_2o::delta2_2o_r4 (real(r4p), intent(in) Sp1, real(r4p), intent(in) S, real(r4p), intent(in) Sm1, real(r4p), intent(in) Ds) private
Definition at line 2620 of file Lib_Math.f90.
Referenced by lib_math::laplacian_r4().
interface lib_math::abs_grad
abs_grad overloading
Definition at line 224 of file Lib_Math.f90.
Private Member Functions
elemental function abs_grad_r8 (Vip1, Vim1, Di, Vjp1, Vjm1, Dj, Vkp1, Vkm1, Dk)
elemental function abs_grad_r4 (Vip1, Vim1, Di, Vjp1, Vjm1, Dj, Vkp1, Vkm1, Dk)
Member Function/Subroutine Documentation
elemental function lib_math::abs_grad::abs_grad_r8 (real(r8p), intent(in) Vip1, real(r8p), intent(in) Vim1, real(r8p), intent(in) Di, real(r8p), intent(in) Vjp1, real(r8p), intent(in) Vjm1, real(r8p), intent(in) Dj, real(r8p), intent(in) Vkp1, real(r8p), intent(in) Vkm1, real(r8p), intent(in) Dk) private
Definition at line 2669 of file Lib_Math.f90.
elemental function lib_math::abs_grad::abs_grad_r4 (real(r4p), intent(in) Vip1, real(r4p), intent(in) Vim1, real(r4p), intent(in) Di, real(r4p), intent(in) Vjp1, real(r4p), intent(in) Vjm1, real(r4p), intent(in) Dj, real(r4p), intent(in) Vkp1, real(r4p), intent(in) Vkm1, real(r4p), intent(in) Dk) private
Definition at line 2697 of file Lib_Math.f90.
interface lib_math::laplacian
laplacian overloading
Definition at line 232 of file Lib_Math.f90.
Private Member Functions
elemental function laplacian_r8 (Vip1, Vi, Vim1, Di, Vjp1, Vj, Vjm1, Dj, Vkp1, Vk, Vkm1, Dk)
elemental function laplacian_r4 (Vip1, Vi, Vim1, Di, Vjp1, Vj, Vjm1, Dj, Vkp1, Vk, Vkm1, Dk)
Member Function/Subroutine Documentation
elemental function lib_math::laplacian::laplacian_r8 (real(r8p), intent(in) Vip1, real(r8p), intent(in) Vi, real(r8p), intent(in) Vim1, real(r8p), intent(in) Di, real(r8p), intent(in) Vjp1, real(r8p), intent(in) Vj, real(r8p), intent(in) Vjm1, real(r8p), intent(in) Dj, real(r8p), intent(in) Vkp1, real(r8p), intent(in) Vk, real(r8p), intent(in) Vkm1, real(r8p), intent(in) Dk) private
Definition at line 2757 of file Lib_Math.f90.
elemental function lib_math::laplacian::laplacian_r4 (real(r4p), intent(in) Vip1, real(r4p), intent(in) Vi, real(r4p), intent(in) Vim1, real(r4p), intent(in) Di, real(r4p), intent(in) Vjp1, real(r4p), intent(in) Vj, real(r4p), intent(in) Vjm1, real(r4p), intent(in) Dj, real(r4p), intent(in) Vkp1, real(r4p), intent(in) Vk, real(r4p), intent(in) Vkm1, real(r4p), intent(in) Dk) private
Definition at line 2788 of file Lib_Math.f90.