OFF: Data_Type_AMRBlock
Data_Type_AMRBlock
Public Procedures
elemental function, public data_type_amrblock::level (ID)
Function for computing the level correspoinding to the passed ID.
elemental function, public data_type_amrblock::firstid (level)
Function for computing the first ID of the passed level.
elemental function, public data_type_amrblock::lastid (level)
Function for computing the last ID of the passed level.
pure function, public data_type_amrblock::siblings (ID)
Function for computing the IDs of siblings of a given ID.
elemental function, public data_type_amrblock::child (pID)
Function for computing the ID of child of a given (parent) ID.
elemental function, public data_type_amrblock::directparent (ID)
Function for computing the direct parent ID of a given ID.
elemental function, public data_type_amrblock::parentatlevel (ID, l)
Function for computing the parent ID of a given ID at a given level.
pure function, public data_type_amrblock::directchildren (ID)
Function for computing the direct children IDs of a given ID.
Detailed Description
Function/Subroutine Documentation
elemental function, public data_type_amrblock::level (integer(i8p), intent(in) ID)
Function for computing the level correspoinding to the passed ID.
Parameters
[in] id Input ID.
Definition at line 194 of file Data_Type_AMRBlock.f90.
Referenced by data_type_amrblock::firstid(), data_type_amrblock::lastid(), and data_type_amrblock::parentatlevel().
elemental function, public data_type_amrblock::firstid (integer(i4p), intent(in) level)
Function for computing the first ID of the passed level.
Parameters
[in] level Passed level.
Definition at line 214 of file Data_Type_AMRBlock.f90.
References data_type_amrblock::level().
elemental function, public data_type_amrblock::lastid (integer(i4p), intent(in) level)
Function for computing the last ID of the passed level.
Parameters
[in] level Passed level.
Definition at line 235 of file Data_Type_AMRBlock.f90.
References data_type_amrblock::level().
pure function, public data_type_amrblock::siblings (integer(i8p), intent(in) ID)
Function for computing the IDs of siblings of a given ID.
Parameters
[in] id Input ID.
Definition at line 256 of file Data_Type_AMRBlock.f90.
References ir_precision::i8p.
elemental function, public data_type_amrblock::child (integer(i8p), intent(in) pID)
Function for computing the ID of child of a given (parent) ID.
Parameters
[in] pid Input (parent) ID.
Definition at line 280 of file Data_Type_AMRBlock.f90.
elemental function, public data_type_amrblock::directparent (integer(i8p), intent(in) ID)
Function for computing the direct parent ID of a given ID.
Parameters
[in] id Input ID.
Definition at line 294 of file Data_Type_AMRBlock.f90.
References lib_thermodynamic_laws_ideal::p().
elemental function, public data_type_amrblock::parentatlevel (integer(i8p), intent(in) ID, integer(i4p), intent(in) l)
Function for computing the parent ID of a given ID at a given level.
Parameters
[in] id Input ID.
[in] l Input level.
Definition at line 308 of file Data_Type_AMRBlock.f90.
References data_type_amrblock::level().
pure function, public data_type_amrblock::directchildren (integer(i8p), intent(in) ID)
Function for computing the direct children IDs of a given ID.
Parameters
[in] id Input ID.
Definition at line 327 of file Data_Type_AMRBlock.f90.