OFF: Data_Type_Vector
Data_Type_Vector
Public Procedures
elemental function, public data_type_vector::sq_norm (vec)
Function for computing the square of the norm of a vector.
elemental function, public data_type_vector::norml2 (vec)
Function for computing the norm L2 of a vector.
elemental function, public data_type_vector::normalize (vec)
Function for normalizing a vector.
elemental function, public data_type_vector::face_normal4 (norm, pt1, pt2, pt3, pt4)
Function for calculating the normal of the face defined by 4 points vector pt1, pt2, pt3 and pt4.
elemental function, public data_type_vector::face_normal3 (norm, pt1, pt2, pt3)
Function for calculating the normal of the face defined by the 3 points vector pt1, pt2 and pt3.
integer(i_p) function, public data_type_vector::write_vector (scalar, array1D, array2D, array3D, format, unit)
Function for writing Type_Vector data.
integer(i_p) function, public data_type_vector::read_vector (scalar, array1D, array2D, array3D, format, unit)
Function for reading Type_Vector data.
Detailed Description
Function/Subroutine Documentation
elemental function, public data_type_vector::sq_norm (type(type_vector), intent(in) vec)
Function for computing the square of the norm of a vector.
The square norm if defined as .
Returns
sq square norm
Parameters
[in] vec Vector.
Definition at line 383 of file Data_Type_Vector.f90.
elemental function, public data_type_vector::norml2 (type(type_vector), intent(in) vec)
Function for computing the norm L2 of a vector.
The norm L2 if defined as .
Returns
norm norm L2
Parameters
[in] vec Vector.
Definition at line 399 of file Data_Type_Vector.f90.
elemental function, public data_type_vector::normalize (type(type_vector), intent(in) vec)
Function for normalizing a vector.
The normalization is made by means of norm L2. If the norm L2 of the vector is less than the parameter smallR8P the normalization value is set to normL2(vec)+smallR8P.
Returns
norm normalized vector
Parameters
[in] vec Vector to be normalized.
Definition at line 416 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::norml2(), and ir_precision::smallr8p.
elemental function, public data_type_vector::face_normal4 (character(1), intent(in), optional norm, type(type_vector), intent(in) pt1, type(type_vector), intent(in) pt2, type(type_vector), intent(in) pt3, type(type_vector), intent(in) pt4)
Function for calculating the normal of the face defined by 4 points vector pt1, pt2, pt3 and pt4.
The convention for the points numeration is the following:
1.----------.2
 |          |
 |          |
 |          |
 |          |
4.----------.3
The normal is calculated by the cross product of the diagonal d13 for the diagonal d24: d13 x d24. The normal is normalized if the variable 'norm' is passed (with any value).
Returns
fnormal face normal
Parameters
[in] norm If 'norm' is passed as argument the normal is normalized.
[in] pt1 First face point.
[in] pt2 Second face point.
[in] pt3 Third face point.
[in] pt4 Fourth face point.
Definition at line 449 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::normalize().
Referenced by data_type_sblock::metrics().
elemental function, public data_type_vector::face_normal3 (character(1), intent(in), optional norm, type(type_vector), intent(in) pt1, type(type_vector), intent(in) pt2, type(type_vector), intent(in) pt3)
Function for calculating the normal of the face defined by the 3 points vector pt1, pt2 and pt3.
1.----.2
  \   |
   \  |
    \ |
     \|
      .3
The normal is calculated by the cross product of the side s12 for the side s13: s12 x s13. The normal is normalized if the variable 'norm' is passed (with any value).
Returns
fnormal face normal
Parameters
[in] norm If 'norm' is passed as argument the normal is normalized.
[in] pt1 First face point.
[in] pt2 Second face point.
[in] pt3 Third face point.
Definition at line 486 of file Data_Type_Vector.f90.
References data_type_tensor::type_tensor::normalize().
integer(i_p) function, public data_type_vector::write_vector (type(type_vector), intent(in), optional scalar, type(type_vector), dimension(:), intent(in), optional array1D, type(type_vector), dimension(:,:), intent(in), optional array2D, type(type_vector), dimension(:,:,:), intent(in), optional array3D, character(*), intent(in), optional format, integer(i4p), intent(in) unit)
Function for writing Type_Vector data.
The vector data could be scalar, one, two and three dimensional array. The format could be ascii or binary.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in] scalar Scalar vector data.
[in] array1d One dimensional array vector data.
[in] array2d Two dimensional array vector data.
[in] array3d Three dimensional array vector data.
[in] format Format specifier.
[in] unit Logic unit.
Definition at line 512 of file Data_Type_Vector.f90.
Referenced by load_blocks(), load_icemcfd(), data_type_sblock::save_bmesh(), data_type_conservative::write_conservative(), and data_type_primitive::write_primitive().
integer(i_p) function, public data_type_vector::read_vector (type(type_vector), intent(inout), optional scalar, type(type_vector), dimension(:), intent(inout), optional array1D, type(type_vector), dimension(:,:), intent(inout), optional array2D, type(type_vector), dimension(:,:,:), intent(inout), optional array3D, character(*), intent(in), optional format, integer(i4p), intent(in) unit)
Function for reading Type_Vector data.
The vector data could be scalar, one, two and three dimensional array. The format could be ascii or binary.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in,out] scalar Scalar vector data.
[in,out] array1d One dimensional array vector data.
[in,out] array2d Two dimensional array vector data.
[in,out] array3d Three dimensional array vector data.
[in] format Format specifier.
[in] unit Logic unit.
Definition at line 566 of file Data_Type_Vector.f90.
Referenced by data_type_sblock::load_bmesh(), data_type_conservative::read_conservative(), and data_type_primitive::read_primitive().