OFF: Lib_Thermodynamic_Laws_Ideal
Lib_Thermodynamic_Laws_Ideal
Public Procedures
elemental function, public lib_thermodynamic_laws_ideal::p (r, a, g)
Function for computing the pressure for an ideal calorically perfect gas.
elemental function, public lib_thermodynamic_laws_ideal::r (p, a, g)
Function for computing the density for an ideal calorically perfect gas.
elemental function, public lib_thermodynamic_laws_ideal::a (p, r, g)
Function for computing the speed of sound for an ideal calorically perfect gas.
elemental function, public lib_thermodynamic_laws_ideal::e (p, r, u, g)
Function for computing the total specific energy (per unit of mass) for an ideal calorically perfect gas.
elemental function, public lib_thermodynamic_laws_ideal::h (p, r, u, g)
Function for computing the total specific entalpy (per unit of mass) for an ideal calorically perfect gas.
Detailed Description
Function/Subroutine Documentation
elemental function, public lib_thermodynamic_laws_ideal::p (real(r_p), intent(in) r, real(r_p), intent(in) a, real(r_p), intent(in) g)
Function for computing the pressure for an ideal calorically perfect gas.
Parameters
[in] r Density ().
[in] a Speed of sound.
[in] g Specific heats ratio .
Definition at line 35 of file Lib_Thermodynamic_Laws_Ideal.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_thermodynamic_laws_ideal::a(), lib_riemann::bclc_wavesspeed14(), data_type_hashid::build(), lib_riemann::chk_smooth_liu(), lib_riemann::chk_smooth_z(), compute_cd2(), lib_postprocessing::compute_dimensions(), lib_fluidynamic::compute_time(), lib_multigrid::correct(), data_type_sl_list::delt_link(), data_type_amrblock::directparent(), lib_thermodynamic_laws_ideal::e(), lib_riemann::fluxes(), gnu_blk_data(), lib_thermodynamic_laws_ideal::h(), data_type_amrblock::init_amrblock(), lib_postprocessing::interpolate_primitive(), lib_riemann::interstates23up(), off(), lib_profiling::profile(), lib_thermodynamic_laws_ideal::r(), lib_riemann::rarefaction(), lib_multigrid::restrict(), lib_riemann::riem_solver_alfr(), lib_riemann::riem_solver_aprs(), lib_riemann::riem_solver_exact_u(), lib_riemann::riem_solver_hllc(), lib_riemann::riem_solver_laxfriedrichs(), lib_riemann::riem_solver_pvl(), lib_riemann::riem_solver_roe(), lib_riemann::riem_solver_tr(), lib_riemann::riem_solver_ts(), rk_stages_sum_backend(), lib_fluidynamic::rk_time_integration(), lib_riemann::roe_state(), lib_riemann::roe_ua(), lib_riemann::roe_wavesspeed14(), lib_riemann::sampling_fluxes(), lib_riemann::sampling_fluxes_old(), lib_riemann::sampling_fluxes_vacuum(), lib_riemann::shock(), lib_fluidynamic::solve_grl(), lib_math::spline3_r4(), lib_math::spline3_r8(), tec_blk_data(), tec_dat(), lib_riemann::tr_u23(), lib_riemann::ts_up23(), vtk_blk_data(), lib_postprocessing::vtk_output(), lib_weno::weno_convolution(), and lib_weno::weno_weights().
elemental function, public lib_thermodynamic_laws_ideal::r (real(r_p), intent(in) p, real(r_p), intent(in) a, real(r_p), intent(in) g)
Function for computing the density for an ideal calorically perfect gas.
Parameters
[in] p Pressure.
[in] a Speed of sound.
[in] g Specific heats ratio .
Definition at line 51 of file Lib_Thermodynamic_Laws_Ideal.f90.
References lib_thermodynamic_laws_ideal::a(), and lib_thermodynamic_laws_ideal::p().
Referenced by lib_thermodynamic_laws_ideal::a(), lib_riemann::bclc_wavesspeed14(), lib_riemann::chk_smooth_liu(), lib_riemann::chk_smooth_z(), lib_fluidynamic::compute_time(), lib_thermodynamic_laws_ideal::e(), lib_riemann::fluxes(), gnu_blk_data(), lib_postprocessing::gnu_output(), lib_thermodynamic_laws_ideal::h(), lib_riemann::harten_limiter(), lib_riemann::interstates23up(), data_type_global::load_gfluid_0species(), lib_thermodynamic_laws_ideal::p(), lib_riemann::rarefaction(), lib_multigrid::restrict(), lib_riemann::riem_solver_alfr(), lib_riemann::riem_solver_aprs(), lib_riemann::riem_solver_exact_u(), lib_riemann::riem_solver_hllc(), lib_riemann::riem_solver_laxfriedrichs(), lib_riemann::riem_solver_pvl(), lib_riemann::riem_solver_roe(), lib_riemann::riem_solver_tr(), lib_riemann::riem_solver_ts(), lib_runge_kutta::rk_time_integ(), rk_time_integration_backend(), lib_riemann::roe_state(), lib_riemann::roe_ua(), lib_riemann::roe_wavesspeed14(), rp(), lib_riemann::sampling_fluxes(), lib_riemann::sampling_fluxes_old(), lib_riemann::sampling_fluxes_vacuum(), lib_riemann::shock(), lib_fluidynamic::solve_grl(), te_estimation(), tec_blk_data(), tec_dat(), lib_riemann::tr_u23(), lib_riemann::ts_up23(), lib_riemann::vanalbada_limiter(), lib_riemann::vanleer_limiter(), vtk_blk_data(), and lib_postprocessing::vtk_output().
elemental function, public lib_thermodynamic_laws_ideal::a (real(r_p), intent(in) p, real(r_p), intent(in) r, real(r_p), intent(in) g)
Function for computing the speed of sound for an ideal calorically perfect gas.
Parameters
[in] p Pressure.
[in] r Density ().
[in] g Specific heats ratio .
Definition at line 67 of file Lib_Thermodynamic_Laws_Ideal.f90.
References lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by data_type_sl_list::array_link_ch(), data_type_sl_list::array_link_i1(), data_type_sl_list::array_link_i2(), data_type_sl_list::array_link_i4(), data_type_sl_list::array_link_log(), data_type_sl_list::array_list_log(), lib_riemann::chk_smooth_liu(), lib_riemann::chk_smooth_z(), lib_fluidynamic::compute_time(), cspline(), data_type_sl_list::del_list(), data_type_sl_list::delh_list(), data_type_sl_list::delt_list(), data_type_sl_list::get_list_i8(), data_type_sl_list::get_list_r4(), data_type_sl_list::get_list_r8(), lib_riemann::interstates23up(), data_type_sl_list::leng_list(), lib_thermodynamic_laws_ideal::p(), lib_thermodynamic_laws_ideal::r(), lib_riemann::rarefaction(), lib_riemann::riem_solver_alfr(), lib_riemann::riem_solver_aprs(), lib_riemann::riem_solver_exact_u(), lib_riemann::riem_solver_hllc(), lib_riemann::riem_solver_laxfriedrichs(), lib_riemann::riem_solver_pvl(), lib_riemann::riem_solver_roe(), lib_riemann::riem_solver_tr(), lib_riemann::riem_solver_ts(), lib_riemann::roe_ua(), rp(), lib_riemann::sampling_fluxes(), lib_riemann::sampling_fluxes_old(), lib_riemann::sampling_fluxes_vacuum(), lib_riemann::shock(), lib_riemann::tr_u23(), lib_riemann::ts_up23(), lib_weno::weno_convolution(), and lib_weno::weno_weights().
elemental function, public lib_thermodynamic_laws_ideal::e (real(r_p), intent(in) p, real(r_p), intent(in) r, real(r_p), intent(in) u, real(r_p), intent(in) g)
Function for computing the total specific energy (per unit of mass) for an ideal calorically perfect gas.
Note
This law is defined as:
Parameters
[in] p Pressure.
[in] r Density ().
[in] u Module of velocity vector.
[in] g Specific heats ratio .
Definition at line 85 of file Lib_Thermodynamic_Laws_Ideal.f90.
References lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by data_type_sl_list::array_link_ch(), data_type_sl_list::array_link_i1(), data_type_sl_list::array_link_i2(), data_type_sl_list::array_link_i4(), data_type_sl_list::array_link_log(), data_type_sl_list::del_link(), data_type_sl_list::del_list(), data_type_sl_list::delh_list(), data_type_sl_list::delt_list(), lib_base64::encode_bits(), data_type_sl_list::get_list_i8(), data_type_sl_list::get_list_r4(), data_type_sl_list::get_list_r8(), data_type_sl_list::leng_list(), data_type_sl_list::link(), lib_riemann::riem_solver_pvl(), lib_riemann::riem_solver_roe(), and rp().
elemental function, public lib_thermodynamic_laws_ideal::h (real(r_p), intent(in) p, real(r_p), intent(in) r, real(r_p), intent(in) u, real(r_p), intent(in) g)
Function for computing the total specific entalpy (per unit of mass) for an ideal calorically perfect gas.
Note
This law is defined as:
Parameters
[in] p Pressure.
[in] r Density ().
[in] u Module of velocity vector.
[in] g Specific heats ratio .
Definition at line 104 of file Lib_Thermodynamic_Laws_Ideal.f90.
References lib_thermodynamic_laws_ideal::p(), and lib_thermodynamic_laws_ideal::r().
Referenced by lib_riemann::bclc_wavesspeed14(), cspline(), lib_riemann::fluxes(), lib_riemann::roe_state(), and lib_riemann::roe_wavesspeed14().