OFF: Data_Type_SL_List
Data_Type_SL_List
Derived Types
Data Types
type data_type_sl_list::type_sl_link
Derived type containing link data of a single linked list.
type data_type_sl_list::type_sl_list
Derived type containing single linked list.
Detailed Description
Data Type Documentation
type data_type_sl_list::type_sl_link
Derived type containing link data of a single linked list.
Definition at line 55 of file Data_Type_SL_List.f90.
Private Member Functions
procedure, non_overridable free => free_link
procedure, non_overridable leng => leng_link
procedure, non_overridable homogeneous => homo_link
procedure, non_overridable link
procedure, non_overridable del => del_link
procedure, non_overridable delh => delh_link
procedure, non_overridable delt => delt_link
generic get =>get_link_R8, get_link_R4,get_link_I8, get_link_I4, get_link_I2, get_link_I1, get_link_ch, get_link_log
generic geth =>
non_overridable geth_link_r8
non_overridable geth_link_r4
non_overridable geth_link_i8
non_overridable geth_link_i4
non_overridable geth_link_i2
non_overridable geth_link_i1
non_overridable geth_link_ch
non_overridable geth_link_log
generic gett =>
non_overridable gett_link_r8
non_overridable gett_link_r4
non_overridable gett_link_i8
non_overridable gett_link_i4
non_overridable gett_link_i2
non_overridable gett_link_i1
non_overridable gett_link_ch
non_overridable gett_link_log
generic put =>
non_overridable put_link_r8
non_overridable put_link_r4
non_overridable put_link_i8
non_overridable put_link_i4
non_overridable put_link_i2
non_overridable put_link_i1
non_overridable put_link_ch
non_overridable put_link_log
generic puth =>
non_overridable puth_link_r8
non_overridable puth_link_r4
non_overridable puth_link_i8
non_overridable puth_link_i4
non_overridable puth_link_i2
non_overridable puth_link_i1
non_overridable puth_link_ch
non_overridable puth_link_log
generic putt =>
non_overridable putt_link_r8
non_overridable putt_link_r4
non_overridable putt_link_i8
non_overridable putt_link_i4
non_overridable putt_link_i2
non_overridable putt_link_i1
non_overridable putt_link_ch
non_overridable putt_link_log
generic array =>
non_overridable array_link_r8
non_overridable array_link_r4
non_overridable array_link_i8
non_overridable array_link_i4
non_overridable array_link_i2
non_overridable array_link_i1
non_overridable array_link_ch
non_overridable array_link_log
procedure, non_overridable get_link_r8
procedure, non_overridable get_link_r4
procedure, non_overridable get_link_i8
procedure, non_overridable get_link_i4
procedure, non_overridable get_link_i2
procedure, non_overridable get_link_i1
procedure, non_overridable get_link_ch
procedure, non_overridable get_link_log
procedure, non_overridable geth_link_r8
procedure, non_overridable geth_link_r4
procedure, non_overridable geth_link_i8
procedure, non_overridable geth_link_i4
procedure, non_overridable geth_link_i2
procedure, non_overridable geth_link_i1
procedure, non_overridable geth_link_ch
procedure, non_overridable geth_link_log
procedure, non_overridable gett_link_r8
procedure, non_overridable gett_link_r4
procedure, non_overridable gett_link_i8
procedure, non_overridable gett_link_i4
procedure, non_overridable gett_link_i2
procedure, non_overridable gett_link_i1
procedure, non_overridable gett_link_ch
procedure, non_overridable gett_link_log
procedure, non_overridable put_link_r8
procedure, non_overridable put_link_r4
procedure, non_overridable put_link_i8
procedure, non_overridable put_link_i4
procedure, non_overridable put_link_i2
procedure, non_overridable put_link_i1
procedure, non_overridable put_link_ch
procedure, non_overridable put_link_log
procedure, non_overridable puth_link_r8
procedure, non_overridable puth_link_r4
procedure, non_overridable puth_link_i8
procedure, non_overridable puth_link_i4
procedure, non_overridable puth_link_i2
procedure, non_overridable puth_link_i1
procedure, non_overridable puth_link_ch
procedure, non_overridable puth_link_log
procedure, non_overridable putt_link_r8
procedure, non_overridable putt_link_r4
procedure, non_overridable putt_link_i8
procedure, non_overridable putt_link_i4
procedure, non_overridable putt_link_i2
procedure, non_overridable putt_link_i1
procedure, non_overridable putt_link_ch
procedure, non_overridable putt_link_log
procedure, non_overridable array_link_r8
procedure, non_overridable array_link_r4
procedure, non_overridable array_link_i8
procedure, non_overridable array_link_i4
procedure, non_overridable array_link_i2
procedure, non_overridable array_link_i1
procedure, non_overridable array_link_ch
procedure, non_overridable array_link_log
Private Attributes
integer(i1p) tp =tp_NULL
Type of data.
integer(i1p), dimension(:), pointer d
Link data.
type(type_sl_link), pointer n => null()
Pointer to the next link of the list.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_sl_list::type_sl_link::free () private
Definition at line 61 of file Data_Type_SL_List.f90.
References data_type_sl_list::del_link().
procedure, non_overridable data_type_sl_list::type_sl_link::leng () private
Definition at line 62 of file Data_Type_SL_List.f90.
References delh(), and data_type_sl_list::delh_link().
Referenced by data_type_hashtcell::init_hasht(), data_type_hashtnode::init_hasht(), and data_type_hashtface::init_hasht().
procedure, non_overridable data_type_sl_list::type_sl_link::homogeneous () private
Definition at line 63 of file Data_Type_SL_List.f90.
References delt(), and data_type_sl_list::delt_link().
procedure, non_overridable data_type_sl_list::type_sl_link::link () private
Definition at line 64 of file Data_Type_SL_List.f90.
References data_type_hashtcell::type_sll::get().
Referenced by data_type_sl_list::get_link_ch(), data_type_sl_list::get_link_i1(), data_type_sl_list::get_link_i2(), data_type_sl_list::get_link_i4(), data_type_sl_list::get_link_i8(), data_type_sl_list::get_link_log(), data_type_sl_list::get_link_r4(), data_type_sl_list::get_link_r8(), and data_type_sl_list::geth_link_r8().
procedure, non_overridable data_type_sl_list::type_sl_link::del () private
Definition at line 65 of file Data_Type_SL_List.f90.
References get_link_r4(), and get_link_r8().
procedure, non_overridable data_type_sl_list::type_sl_link::delh () private
Definition at line 66 of file Data_Type_SL_List.f90.
References get_link_ch(), get_link_i1(), get_link_i2(), get_link_i4(), get_link_i8(), and get_link_log().
Referenced by data_type_sl_list::type_sl_list::free(), and leng().
procedure, non_overridable data_type_sl_list::type_sl_link::delt () private
Definition at line 67 of file Data_Type_SL_List.f90.
References geth().
Referenced by homogeneous(), and data_type_sl_list::type_sl_list::leng().
generic data_type_sl_list::type_sl_link::get () private
Definition at line 68 of file Data_Type_SL_List.f90.
generic data_type_sl_list::type_sl_link::geth () private
Definition at line 71 of file Data_Type_SL_List.f90.
References geth_link_ch(), geth_link_i1(), geth_link_i2(), geth_link_i4(), geth_link_i8(), geth_link_log(), geth_link_r4(), geth_link_r8(), and gett().
Referenced by delt(), and data_type_sl_list::type_sl_list::get().
non_overridable data_type_sl_list::type_sl_link::geth_link_r8 () private
Definition at line 75 of file Data_Type_SL_List.f90.
Referenced by get_link_log(), and geth().
non_overridable data_type_sl_list::type_sl_link::geth_link_r4 () private
Definition at line 75 of file Data_Type_SL_List.f90.
Referenced by get_link_log(), and geth().
non_overridable data_type_sl_list::type_sl_link::geth_link_i8 () private
Definition at line 75 of file Data_Type_SL_List.f90.
Referenced by get_link_log(), and geth().
non_overridable data_type_sl_list::type_sl_link::geth_link_i4 () private
Definition at line 75 of file Data_Type_SL_List.f90.
Referenced by get_link_log(), and geth().
non_overridable data_type_sl_list::type_sl_link::geth_link_i2 () private
Definition at line 75 of file Data_Type_SL_List.f90.
Referenced by geth(), and geth_link_r8().
non_overridable data_type_sl_list::type_sl_link::geth_link_i1 () private
Definition at line 75 of file Data_Type_SL_List.f90.
Referenced by geth(), and geth_link_r4().
non_overridable data_type_sl_list::type_sl_link::geth_link_ch () private
Definition at line 75 of file Data_Type_SL_List.f90.
Referenced by geth(), and geth_link_i8().
non_overridable data_type_sl_list::type_sl_link::geth_link_log () private
Definition at line 75 of file Data_Type_SL_List.f90.
Referenced by geth(), and geth_link_i4().
generic data_type_sl_list::type_sl_link::gett () private
Definition at line 77 of file Data_Type_SL_List.f90.
References gett_link_ch(), gett_link_i1(), gett_link_i2(), gett_link_i4(), gett_link_i8(), gett_link_log(), gett_link_r4(), gett_link_r8(), and data_type_hashtcell::type_sll::put().
Referenced by geth(), and data_type_sl_list::type_sl_list::geth().
non_overridable data_type_sl_list::type_sl_link::gett_link_r8 () private
Definition at line 81 of file Data_Type_SL_List.f90.
Referenced by geth_link_log(), gett(), and data_type_sl_list::gett_link_i4().
non_overridable data_type_sl_list::type_sl_link::gett_link_r4 () private
Definition at line 81 of file Data_Type_SL_List.f90.
Referenced by geth_link_log(), gett(), and data_type_sl_list::gett_link_i2().
non_overridable data_type_sl_list::type_sl_link::gett_link_i8 () private
Definition at line 81 of file Data_Type_SL_List.f90.
Referenced by geth_link_log(), gett(), and data_type_sl_list::gett_link_i1().
non_overridable data_type_sl_list::type_sl_link::gett_link_i4 () private
Definition at line 81 of file Data_Type_SL_List.f90.
Referenced by geth_link_log(), gett(), and data_type_sl_list::gett_link_ch().
non_overridable data_type_sl_list::type_sl_link::gett_link_i2 () private
Definition at line 81 of file Data_Type_SL_List.f90.
Referenced by gett(), data_type_sl_list::gett_link_log(), and gett_link_r8().
non_overridable data_type_sl_list::type_sl_link::gett_link_i1 () private
Definition at line 81 of file Data_Type_SL_List.f90.
Referenced by gett(), gett_link_r4(), and data_type_sl_list::put_link_r8().
non_overridable data_type_sl_list::type_sl_link::gett_link_ch () private
Definition at line 81 of file Data_Type_SL_List.f90.
Referenced by gett(), gett_link_i8(), and data_type_sl_list::put_link_r8().
non_overridable data_type_sl_list::type_sl_link::gett_link_log () private
Definition at line 81 of file Data_Type_SL_List.f90.
Referenced by gett(), gett_link_i4(), and data_type_sl_list::put_link_r4().
generic data_type_sl_list::type_sl_link::put () private
Definition at line 83 of file Data_Type_SL_List.f90.
References put_link_ch(), put_link_i1(), put_link_i2(), put_link_i4(), put_link_i8(), put_link_log(), put_link_r4(), put_link_r8(), and puth().
non_overridable data_type_sl_list::type_sl_link::put_link_r8 () private
Definition at line 87 of file Data_Type_SL_List.f90.
Referenced by gett_link_log(), and put().
non_overridable data_type_sl_list::type_sl_link::put_link_r4 () private
Definition at line 87 of file Data_Type_SL_List.f90.
Referenced by gett_link_log(), and put().
non_overridable data_type_sl_list::type_sl_link::put_link_i8 () private
Definition at line 87 of file Data_Type_SL_List.f90.
Referenced by gett_link_log(), and put().
non_overridable data_type_sl_list::type_sl_link::put_link_i4 () private
Definition at line 87 of file Data_Type_SL_List.f90.
Referenced by gett_link_log(), and put().
non_overridable data_type_sl_list::type_sl_link::put_link_i2 () private
Definition at line 87 of file Data_Type_SL_List.f90.
Referenced by put(), and put_link_r8().
non_overridable data_type_sl_list::type_sl_link::put_link_i1 () private
Definition at line 87 of file Data_Type_SL_List.f90.
Referenced by put(), and put_link_r4().
non_overridable data_type_sl_list::type_sl_link::put_link_ch () private
Definition at line 87 of file Data_Type_SL_List.f90.
Referenced by put(), and put_link_i8().
non_overridable data_type_sl_list::type_sl_link::put_link_log () private
Definition at line 87 of file Data_Type_SL_List.f90.
Referenced by put(), and put_link_i4().
generic data_type_sl_list::type_sl_link::puth () private
Definition at line 89 of file Data_Type_SL_List.f90.
References puth_link_ch(), puth_link_i1(), puth_link_i2(), puth_link_i4(), puth_link_i8(), puth_link_log(), puth_link_r4(), puth_link_r8(), and putt().
Referenced by put(), and data_type_sl_list::type_sl_list::put().
non_overridable data_type_sl_list::type_sl_link::puth_link_r8 () private
Definition at line 93 of file Data_Type_SL_List.f90.
Referenced by put_link_log(), and puth().
non_overridable data_type_sl_list::type_sl_link::puth_link_r4 () private
Definition at line 93 of file Data_Type_SL_List.f90.
Referenced by put_link_log(), and puth().
non_overridable data_type_sl_list::type_sl_link::puth_link_i8 () private
Definition at line 93 of file Data_Type_SL_List.f90.
Referenced by put_link_log(), and puth().
non_overridable data_type_sl_list::type_sl_link::puth_link_i4 () private
Definition at line 93 of file Data_Type_SL_List.f90.
Referenced by put_link_log(), and puth().
non_overridable data_type_sl_list::type_sl_link::puth_link_i2 () private
Definition at line 93 of file Data_Type_SL_List.f90.
Referenced by puth(), and puth_link_r8().
non_overridable data_type_sl_list::type_sl_link::puth_link_i1 () private
Definition at line 93 of file Data_Type_SL_List.f90.
Referenced by puth(), and puth_link_r4().
non_overridable data_type_sl_list::type_sl_link::puth_link_ch () private
Definition at line 93 of file Data_Type_SL_List.f90.
Referenced by puth(), and puth_link_i8().
non_overridable data_type_sl_list::type_sl_link::puth_link_log () private
Definition at line 93 of file Data_Type_SL_List.f90.
Referenced by puth(), and puth_link_i4().
generic data_type_sl_list::type_sl_link::putt () private
Definition at line 95 of file Data_Type_SL_List.f90.
References array(), putt_link_ch(), putt_link_i1(), putt_link_i2(), putt_link_i4(), putt_link_i8(), putt_link_log(), putt_link_r4(), and putt_link_r8().
Referenced by puth(), and data_type_sl_list::type_sl_list::puth().
non_overridable data_type_sl_list::type_sl_link::putt_link_r8 () private
Definition at line 99 of file Data_Type_SL_List.f90.
Referenced by puth_link_log(), putt(), and data_type_sl_list::putt_link_log().
non_overridable data_type_sl_list::type_sl_link::putt_link_r4 () private
Definition at line 99 of file Data_Type_SL_List.f90.
Referenced by puth_link_log(), putt(), and data_type_sl_list::putt_link_log().
non_overridable data_type_sl_list::type_sl_link::putt_link_i8 () private
Definition at line 99 of file Data_Type_SL_List.f90.
Referenced by data_type_sl_list::array_link_r8(), puth_link_log(), and putt().
non_overridable data_type_sl_list::type_sl_link::putt_link_i4 () private
Definition at line 99 of file Data_Type_SL_List.f90.
Referenced by data_type_sl_list::array_link_r4(), puth_link_log(), and putt().
non_overridable data_type_sl_list::type_sl_link::putt_link_i2 () private
Definition at line 99 of file Data_Type_SL_List.f90.
Referenced by data_type_sl_list::array_link_r4(), putt(), and putt_link_r8().
non_overridable data_type_sl_list::type_sl_link::putt_link_i1 () private
Definition at line 99 of file Data_Type_SL_List.f90.
Referenced by data_type_sl_list::array_link_i8(), putt(), and putt_link_r4().
non_overridable data_type_sl_list::type_sl_link::putt_link_ch () private
Definition at line 99 of file Data_Type_SL_List.f90.
Referenced by data_type_sl_list::array_link_i8(), putt(), and putt_link_i8().
non_overridable data_type_sl_list::type_sl_link::putt_link_log () private
Definition at line 99 of file Data_Type_SL_List.f90.
Referenced by data_type_sl_list::array_link_i4(), putt(), and putt_link_i4().
generic data_type_sl_list::type_sl_link::array () private
Definition at line 101 of file Data_Type_SL_List.f90.
References array_link_ch(), array_link_i1(), array_link_i2(), array_link_i4(), array_link_i8(), array_link_log(), array_link_r4(), and array_link_r8().
Referenced by data_type_conservative::array2cons(), data_type_conservative::array2consf(), data_type_primitive::array2prim(), data_type_conservative::cons2array(), lib_math::isort_i1(), lib_math::isort_i2(), lib_math::isort_i4(), lib_math::isort_i8(), lib_math::isort_r16(), lib_math::isort_r4(), lib_math::isort_r8(), data_type_primitive::prim2array(), lib_parallel::psendrecv(), putt(), data_type_sl_list::type_sl_list::putt(), lib_math::qsort_i1(), lib_math::qsort_i2(), lib_math::qsort_i4(), lib_math::qsort_i8(), lib_math::qsort_r16(), lib_math::qsort_r4(), lib_math::qsort_r8(), set_in1(), and subsor().
non_overridable data_type_sl_list::type_sl_link::array_link_r8 () private
Definition at line 105 of file Data_Type_SL_List.f90.
References get_link_i4(), get_link_i8(), get_link_r4(), and get_link_r8().
Referenced by array(), and putt_link_log().
non_overridable data_type_sl_list::type_sl_link::array_link_r4 () private
Definition at line 105 of file Data_Type_SL_List.f90.
Referenced by array(), and putt_link_log().
non_overridable data_type_sl_list::type_sl_link::array_link_i8 () private
Definition at line 105 of file Data_Type_SL_List.f90.
Referenced by array(), and putt_link_log().
non_overridable data_type_sl_list::type_sl_link::array_link_i4 () private
Definition at line 105 of file Data_Type_SL_List.f90.
Referenced by array(), and putt_link_log().
non_overridable data_type_sl_list::type_sl_link::array_link_i2 () private
Definition at line 105 of file Data_Type_SL_List.f90.
Referenced by array(), and array_link_r8().
non_overridable data_type_sl_list::type_sl_link::array_link_i1 () private
Definition at line 105 of file Data_Type_SL_List.f90.
Referenced by array(), and array_link_r4().
non_overridable data_type_sl_list::type_sl_link::array_link_ch () private
Definition at line 105 of file Data_Type_SL_List.f90.
Referenced by array(), and array_link_i8().
non_overridable data_type_sl_list::type_sl_link::array_link_log () private
Definition at line 105 of file Data_Type_SL_List.f90.
Referenced by array(), and array_link_i4().
procedure, non_overridable data_type_sl_list::type_sl_link::get_link_r8 () private
Definition at line 110 of file Data_Type_SL_List.f90.
References get_link_i2().
Referenced by array_link_r8(), and del().
procedure, non_overridable data_type_sl_list::type_sl_link::get_link_r4 () private
Definition at line 111 of file Data_Type_SL_List.f90.
References get_link_i1().
Referenced by array_link_r8(), and del().
procedure, non_overridable data_type_sl_list::type_sl_link::get_link_i8 () private
Definition at line 112 of file Data_Type_SL_List.f90.
References get_link_ch().
Referenced by array_link_r8(), and delh().
procedure, non_overridable data_type_sl_list::type_sl_link::get_link_i4 () private
Definition at line 113 of file Data_Type_SL_List.f90.
References get_link_log().
Referenced by array_link_r8(), and delh().
procedure, non_overridable data_type_sl_list::type_sl_link::get_link_i2 () private
Definition at line 114 of file Data_Type_SL_List.f90.
Referenced by delh(), and get_link_r8().
procedure, non_overridable data_type_sl_list::type_sl_link::get_link_i1 () private
Definition at line 115 of file Data_Type_SL_List.f90.
Referenced by delh(), and get_link_r4().
procedure, non_overridable data_type_sl_list::type_sl_link::get_link_ch () private
Definition at line 116 of file Data_Type_SL_List.f90.
Referenced by delh(), and get_link_i8().
procedure, non_overridable data_type_sl_list::type_sl_link::get_link_log () private
Definition at line 117 of file Data_Type_SL_List.f90.
References geth_link_i4(), geth_link_i8(), geth_link_r4(), and geth_link_r8().
Referenced by delh(), and get_link_i4().
procedure, non_overridable data_type_sl_list::type_sl_link::geth_link_r8 () private
Definition at line 121 of file Data_Type_SL_List.f90.
References geth_link_i2().
procedure, non_overridable data_type_sl_list::type_sl_link::geth_link_r4 () private
Definition at line 122 of file Data_Type_SL_List.f90.
References geth_link_i1().
procedure, non_overridable data_type_sl_list::type_sl_link::geth_link_i8 () private
Definition at line 123 of file Data_Type_SL_List.f90.
References geth_link_ch().
procedure, non_overridable data_type_sl_list::type_sl_link::geth_link_i4 () private
Definition at line 124 of file Data_Type_SL_List.f90.
References geth_link_log().
procedure, non_overridable data_type_sl_list::type_sl_link::geth_link_i2 () private
Definition at line 125 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::geth_link_i1 () private
Definition at line 126 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::geth_link_ch () private
Definition at line 127 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::geth_link_log () private
Definition at line 128 of file Data_Type_SL_List.f90.
References gett_link_i4(), gett_link_i8(), gett_link_r4(), and gett_link_r8().
procedure, non_overridable data_type_sl_list::type_sl_link::gett_link_r8 () private
Definition at line 132 of file Data_Type_SL_List.f90.
References gett_link_i2().
procedure, non_overridable data_type_sl_list::type_sl_link::gett_link_r4 () private
Definition at line 133 of file Data_Type_SL_List.f90.
References gett_link_i1().
procedure, non_overridable data_type_sl_list::type_sl_link::gett_link_i8 () private
Definition at line 134 of file Data_Type_SL_List.f90.
References gett_link_ch().
procedure, non_overridable data_type_sl_list::type_sl_link::gett_link_i4 () private
Definition at line 135 of file Data_Type_SL_List.f90.
References gett_link_log().
procedure, non_overridable data_type_sl_list::type_sl_link::gett_link_i2 () private
Definition at line 136 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::gett_link_i1 () private
Definition at line 137 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::gett_link_ch () private
Definition at line 138 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::gett_link_log () private
Definition at line 139 of file Data_Type_SL_List.f90.
References put_link_i4(), put_link_i8(), put_link_r4(), and put_link_r8().
procedure, non_overridable data_type_sl_list::type_sl_link::put_link_r8 () private
Definition at line 143 of file Data_Type_SL_List.f90.
References put_link_i2().
procedure, non_overridable data_type_sl_list::type_sl_link::put_link_r4 () private
Definition at line 144 of file Data_Type_SL_List.f90.
References put_link_i1().
procedure, non_overridable data_type_sl_list::type_sl_link::put_link_i8 () private
Definition at line 145 of file Data_Type_SL_List.f90.
References put_link_ch().
procedure, non_overridable data_type_sl_list::type_sl_link::put_link_i4 () private
Definition at line 146 of file Data_Type_SL_List.f90.
References put_link_log().
procedure, non_overridable data_type_sl_list::type_sl_link::put_link_i2 () private
Definition at line 147 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::put_link_i1 () private
Definition at line 148 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::put_link_ch () private
Definition at line 149 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::put_link_log () private
Definition at line 150 of file Data_Type_SL_List.f90.
References puth_link_i4(), puth_link_i8(), puth_link_r4(), and puth_link_r8().
procedure, non_overridable data_type_sl_list::type_sl_link::puth_link_r8 () private
Definition at line 154 of file Data_Type_SL_List.f90.
References puth_link_i2().
procedure, non_overridable data_type_sl_list::type_sl_link::puth_link_r4 () private
Definition at line 155 of file Data_Type_SL_List.f90.
References puth_link_i1().
procedure, non_overridable data_type_sl_list::type_sl_link::puth_link_i8 () private
Definition at line 156 of file Data_Type_SL_List.f90.
References puth_link_ch().
procedure, non_overridable data_type_sl_list::type_sl_link::puth_link_i4 () private
Definition at line 157 of file Data_Type_SL_List.f90.
References puth_link_log().
procedure, non_overridable data_type_sl_list::type_sl_link::puth_link_i2 () private
Definition at line 158 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::puth_link_i1 () private
Definition at line 159 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::puth_link_ch () private
Definition at line 160 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::puth_link_log () private
Definition at line 161 of file Data_Type_SL_List.f90.
References putt_link_i4(), putt_link_i8(), putt_link_r4(), and putt_link_r8().
procedure, non_overridable data_type_sl_list::type_sl_link::putt_link_r8 () private
Definition at line 165 of file Data_Type_SL_List.f90.
References putt_link_i2().
procedure, non_overridable data_type_sl_list::type_sl_link::putt_link_r4 () private
Definition at line 166 of file Data_Type_SL_List.f90.
References putt_link_i1().
procedure, non_overridable data_type_sl_list::type_sl_link::putt_link_i8 () private
Definition at line 167 of file Data_Type_SL_List.f90.
References putt_link_ch().
procedure, non_overridable data_type_sl_list::type_sl_link::putt_link_i4 () private
Definition at line 168 of file Data_Type_SL_List.f90.
References putt_link_log().
procedure, non_overridable data_type_sl_list::type_sl_link::putt_link_i2 () private
Definition at line 169 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::putt_link_i1 () private
Definition at line 170 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::putt_link_ch () private
Definition at line 171 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::putt_link_log () private
Definition at line 172 of file Data_Type_SL_List.f90.
References array_link_i4(), array_link_i8(), array_link_r4(), and array_link_r8().
procedure, non_overridable data_type_sl_list::type_sl_link::array_link_r8 () private
Definition at line 176 of file Data_Type_SL_List.f90.
References array_link_i2().
procedure, non_overridable data_type_sl_list::type_sl_link::array_link_r4 () private
Definition at line 177 of file Data_Type_SL_List.f90.
References array_link_i1().
procedure, non_overridable data_type_sl_list::type_sl_link::array_link_i8 () private
Definition at line 178 of file Data_Type_SL_List.f90.
References array_link_ch().
procedure, non_overridable data_type_sl_list::type_sl_link::array_link_i4 () private
Definition at line 179 of file Data_Type_SL_List.f90.
References array_link_log().
procedure, non_overridable data_type_sl_list::type_sl_link::array_link_i2 () private
Definition at line 180 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::array_link_i1 () private
Definition at line 181 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::array_link_ch () private
Definition at line 182 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_link::array_link_log () private
Definition at line 183 of file Data_Type_SL_List.f90.
Member Data Documentation
integer(i1p) data_type_sl_list::type_sl_link::tp =tp_NULL private
Type of data.
Definition at line 57 of file Data_Type_SL_List.f90.
integer(i1p), dimension(:), pointer data_type_sl_list::type_sl_link::d private
Link data.
Definition at line 58 of file Data_Type_SL_List.f90.
type(type_sl_link), pointer data_type_sl_list::type_sl_link::n => null() private
Pointer to the next link of the list.
Definition at line 59 of file Data_Type_SL_List.f90.
type data_type_sl_list::type_sl_list
Derived type containing single linked list.
Type_SL_List is a generic Single Linked List. The term generic means that the data stored in each node (link) of the list is generic: at present, the stored data can be integer (of any kinds defined in IR_Precision module), real (of any kinds defined in IR_Precision module), characters (of any length) and logical. In order to insert and retrieve data from the list nodes (and in general for list manipulation) the type bound methods must be used, because the data is not directly accessible. This is due to the internal representation of the data. In order to allow generic data, the intrinsic transfer function is used to encode all user data into the internal integer(I1P) array representation. As a consequence, if the node is directed accessed the user can obtain unpredictable results due to the encoded internal representation. The provide methods for list handling are the following:
...
type(type_sl_list):: list
...
insert data into list head:
call list%puth(d=#user_data)
insert data into list tail:
call list%putt(d=#user_data)
retrieve data from list at some node "n":
call list%get(n=n,d=#user_data)
retrieve data from list head:
call list%geth(d=#user_data)
retrieve data from list tail:
call list%gett(d=#user_data)
deleting list head link:
call list%delh
deleting list tail link:
call list%delt
freeing (destroying) list:
call list%free
converting list to array:
call list%array(a=#user_array)
Note
For the character data, the methods get and array need a supplementary arguments, namely Nc being the length of the character variable (array element for array method).
Array method converts the list into an array thus the list must have homogeneous data. Even if the list can have nodes with different data type the conversion to a standard array can be completed successfully only if all data nodes are of the same kind (e.g. all real or all integer or all character etc...).
Definition at line 241 of file Data_Type_SL_List.f90.
Public Member Functions
procedure, non_overridable free => free_list
procedure, non_overridable leng => leng_list
procedure, non_overridable homogeneous => homo_list
procedure, non_overridable del => del_list
procedure, non_overridable delh => delh_list
procedure, non_overridable delt => delt_list
generic get =>
non_overridable get_list_r8
non_overridable get_list_r4
non_overridable get_list_i8
non_overridable get_list_i4
non_overridable get_list_i2
non_overridable get_list_i1
non_overridable get_list_ch
non_overridable get_list_log
generic geth =>
non_overridable geth_list_r8
non_overridable geth_list_r4
non_overridable geth_list_i8
non_overridable geth_list_i4
non_overridable geth_list_i2
non_overridable geth_list_i1
non_overridable geth_list_ch
non_overridable geth_list_log
generic gett =>
non_overridable gett_list_r8
non_overridable gett_list_r4
non_overridable gett_list_i8
non_overridable gett_list_i4
non_overridable gett_list_i2
non_overridable gett_list_i1
non_overridable gett_list_ch
non_overridable gett_list_log
generic put =>
non_overridable put_list_r8
non_overridable put_list_r4
non_overridable put_list_i8
non_overridable put_list_i4
non_overridable put_list_i2
non_overridable put_list_i1
non_overridable put_list_ch
non_overridable put_list_log
generic puth =>
non_overridable puth_list_r8
non_overridable puth_list_r4
non_overridable puth_list_i8
non_overridable puth_list_i4
non_overridable puth_list_i2
non_overridable puth_list_i1
non_overridable puth_list_ch
non_overridable puth_list_log
generic putt =>
non_overridable putt_list_r8
non_overridable putt_list_r4
non_overridable putt_list_i8
non_overridable putt_list_i4
non_overridable putt_list_i2
non_overridable putt_list_i1
non_overridable putt_list_ch
non_overridable putt_list_log
generic array =>
non_overridable array_list_r8
non_overridable array_list_r4
non_overridable array_list_i8
non_overridable array_list_i4
non_overridable array_list_i2
non_overridable array_list_i1
non_overridable array_list_ch
non_overridable array_list_log
procedure, non_overridable get_list_r8
procedure, non_overridable get_list_r4
procedure, non_overridable get_list_i8
procedure, non_overridable get_list_i4
procedure, non_overridable get_list_i2
procedure, non_overridable get_list_i1
procedure, non_overridable get_list_ch
procedure, non_overridable get_list_log
procedure, non_overridable geth_list_r8
procedure, non_overridable geth_list_r4
procedure, non_overridable geth_list_i8
procedure, non_overridable geth_list_i4
procedure, non_overridable geth_list_i2
procedure, non_overridable geth_list_i1
procedure, non_overridable geth_list_ch
procedure, non_overridable geth_list_log
procedure, non_overridable gett_list_r8
procedure, non_overridable gett_list_r4
procedure, non_overridable gett_list_i8
procedure, non_overridable gett_list_i4
procedure, non_overridable gett_list_i2
procedure, non_overridable gett_list_i1
procedure, non_overridable gett_list_ch
procedure, non_overridable gett_list_log
procedure, non_overridable put_list_r8
procedure, non_overridable put_list_r4
procedure, non_overridable put_list_i8
procedure, non_overridable put_list_i4
procedure, non_overridable put_list_i2
procedure, non_overridable put_list_i1
procedure, non_overridable put_list_ch
procedure, non_overridable put_list_log
procedure, non_overridable puth_list_r8
procedure, non_overridable puth_list_r4
procedure, non_overridable puth_list_i8
procedure, non_overridable puth_list_i4
procedure, non_overridable puth_list_i2
procedure, non_overridable puth_list_i1
procedure, non_overridable puth_list_ch
procedure, non_overridable puth_list_log
procedure, non_overridable putt_list_r8
procedure, non_overridable putt_list_r4
procedure, non_overridable putt_list_i8
procedure, non_overridable putt_list_i4
procedure, non_overridable putt_list_i2
procedure, non_overridable putt_list_i1
procedure, non_overridable putt_list_ch
procedure, non_overridable putt_list_log
procedure, non_overridable array_list_r8
procedure, non_overridable array_list_r4
procedure, non_overridable array_list_i8
procedure, non_overridable array_list_i4
procedure, non_overridable array_list_i2
procedure, non_overridable array_list_i1
procedure, non_overridable array_list_ch
procedure, non_overridable array_list_log
Public Attributes
integer(i4p), public l = 0
List length.
logical, public homo = .true.
Flag for checking if the list is homogeneous.
type(type_sl_link), pointer f => null()
Pointer to the first link of the list.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_sl_list::type_sl_list::free ()
Definition at line 247 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::delh(), and data_type_sl_list::delh_list().
procedure, non_overridable data_type_sl_list::type_sl_list::leng ()
Definition at line 248 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::delt(), and data_type_sl_list::delt_list().
procedure, non_overridable data_type_sl_list::type_sl_list::homogeneous ()
Definition at line 249 of file Data_Type_SL_List.f90.
References data_type_hashtcell::type_sll::get().
procedure, non_overridable data_type_sl_list::type_sl_list::del ()
Definition at line 250 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::delh ()
Definition at line 251 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::delt ()
Definition at line 252 of file Data_Type_SL_List.f90.
generic data_type_sl_list::type_sl_list::get ()
Definition at line 253 of file Data_Type_SL_List.f90.
References get_list_ch(), get_list_i1(), get_list_i2(), get_list_i4(), get_list_i8(), get_list_log(), get_list_r4(), get_list_r8(), and data_type_sl_list::type_sl_link::geth().
non_overridable data_type_sl_list::type_sl_list::get_list_r8 ()
Definition at line 257 of file Data_Type_SL_List.f90.
Referenced by array_list_r8(), and get().
non_overridable data_type_sl_list::type_sl_list::get_list_r4 ()
Definition at line 257 of file Data_Type_SL_List.f90.
Referenced by array_list_r8(), and get().
non_overridable data_type_sl_list::type_sl_list::get_list_i8 ()
Definition at line 257 of file Data_Type_SL_List.f90.
Referenced by array_list_r8(), and get().
non_overridable data_type_sl_list::type_sl_list::get_list_i4 ()
Definition at line 257 of file Data_Type_SL_List.f90.
Referenced by array_list_r8(), and get().
non_overridable data_type_sl_list::type_sl_list::get_list_i2 ()
Definition at line 257 of file Data_Type_SL_List.f90.
Referenced by get(), and get_list_r8().
non_overridable data_type_sl_list::type_sl_list::get_list_i1 ()
Definition at line 257 of file Data_Type_SL_List.f90.
Referenced by get(), and get_list_r4().
non_overridable data_type_sl_list::type_sl_list::get_list_ch ()
Definition at line 257 of file Data_Type_SL_List.f90.
Referenced by get(), and get_list_i8().
non_overridable data_type_sl_list::type_sl_list::get_list_log ()
Definition at line 257 of file Data_Type_SL_List.f90.
Referenced by get(), and get_list_i4().
generic data_type_sl_list::type_sl_list::geth ()
Definition at line 259 of file Data_Type_SL_List.f90.
References geth_list_ch(), geth_list_i1(), geth_list_i2(), geth_list_i4(), geth_list_i8(), geth_list_log(), geth_list_r4(), geth_list_r8(), and data_type_sl_list::type_sl_link::gett().
non_overridable data_type_sl_list::type_sl_list::geth_list_r8 ()
Definition at line 263 of file Data_Type_SL_List.f90.
Referenced by get_list_log(), and geth().
non_overridable data_type_sl_list::type_sl_list::geth_list_r4 ()
Definition at line 263 of file Data_Type_SL_List.f90.
Referenced by get_list_log(), and geth().
non_overridable data_type_sl_list::type_sl_list::geth_list_i8 ()
Definition at line 263 of file Data_Type_SL_List.f90.
Referenced by get_list_log(), and geth().
non_overridable data_type_sl_list::type_sl_list::geth_list_i4 ()
Definition at line 263 of file Data_Type_SL_List.f90.
Referenced by get_list_log(), and geth().
non_overridable data_type_sl_list::type_sl_list::geth_list_i2 ()
Definition at line 263 of file Data_Type_SL_List.f90.
Referenced by geth(), and geth_list_r8().
non_overridable data_type_sl_list::type_sl_list::geth_list_i1 ()
Definition at line 263 of file Data_Type_SL_List.f90.
Referenced by geth(), and geth_list_r4().
non_overridable data_type_sl_list::type_sl_list::geth_list_ch ()
Definition at line 263 of file Data_Type_SL_List.f90.
Referenced by geth(), and geth_list_i8().
non_overridable data_type_sl_list::type_sl_list::geth_list_log ()
Definition at line 263 of file Data_Type_SL_List.f90.
Referenced by geth(), and geth_list_i4().
generic data_type_sl_list::type_sl_list::gett ()
Definition at line 265 of file Data_Type_SL_List.f90.
References gett_list_ch(), gett_list_i1(), gett_list_i2(), gett_list_i4(), gett_list_i8(), gett_list_log(), gett_list_r4(), gett_list_r8(), and data_type_hashtcell::type_sll::put().
non_overridable data_type_sl_list::type_sl_list::gett_list_r8 ()
Definition at line 269 of file Data_Type_SL_List.f90.
Referenced by geth_list_log(), and gett().
non_overridable data_type_sl_list::type_sl_list::gett_list_r4 ()
Definition at line 269 of file Data_Type_SL_List.f90.
Referenced by geth_list_log(), and gett().
non_overridable data_type_sl_list::type_sl_list::gett_list_i8 ()
Definition at line 269 of file Data_Type_SL_List.f90.
Referenced by geth_list_log(), and gett().
non_overridable data_type_sl_list::type_sl_list::gett_list_i4 ()
Definition at line 269 of file Data_Type_SL_List.f90.
Referenced by geth_list_log(), and gett().
non_overridable data_type_sl_list::type_sl_list::gett_list_i2 ()
Definition at line 269 of file Data_Type_SL_List.f90.
Referenced by gett(), and gett_list_r8().
non_overridable data_type_sl_list::type_sl_list::gett_list_i1 ()
Definition at line 269 of file Data_Type_SL_List.f90.
Referenced by gett(), and gett_list_r4().
non_overridable data_type_sl_list::type_sl_list::gett_list_ch ()
Definition at line 269 of file Data_Type_SL_List.f90.
Referenced by gett(), and gett_list_i8().
non_overridable data_type_sl_list::type_sl_list::gett_list_log ()
Definition at line 269 of file Data_Type_SL_List.f90.
Referenced by gett(), and gett_list_i4().
generic data_type_sl_list::type_sl_list::put ()
Definition at line 271 of file Data_Type_SL_List.f90.
References put_list_ch(), put_list_i1(), put_list_i2(), put_list_i4(), put_list_i8(), put_list_log(), put_list_r4(), put_list_r8(), and data_type_sl_list::type_sl_link::puth().
non_overridable data_type_sl_list::type_sl_list::put_list_r8 ()
Definition at line 275 of file Data_Type_SL_List.f90.
Referenced by gett_list_log(), and put().
non_overridable data_type_sl_list::type_sl_list::put_list_r4 ()
Definition at line 275 of file Data_Type_SL_List.f90.
Referenced by gett_list_log(), and put().
non_overridable data_type_sl_list::type_sl_list::put_list_i8 ()
Definition at line 275 of file Data_Type_SL_List.f90.
Referenced by gett_list_log(), and put().
non_overridable data_type_sl_list::type_sl_list::put_list_i4 ()
Definition at line 275 of file Data_Type_SL_List.f90.
Referenced by gett_list_log(), and put().
non_overridable data_type_sl_list::type_sl_list::put_list_i2 ()
Definition at line 275 of file Data_Type_SL_List.f90.
Referenced by put(), and put_list_r8().
non_overridable data_type_sl_list::type_sl_list::put_list_i1 ()
Definition at line 275 of file Data_Type_SL_List.f90.
Referenced by put(), and put_list_r4().
non_overridable data_type_sl_list::type_sl_list::put_list_ch ()
Definition at line 275 of file Data_Type_SL_List.f90.
Referenced by put(), and put_list_i8().
non_overridable data_type_sl_list::type_sl_list::put_list_log ()
Definition at line 275 of file Data_Type_SL_List.f90.
Referenced by put(), and put_list_i4().
generic data_type_sl_list::type_sl_list::puth ()
Definition at line 277 of file Data_Type_SL_List.f90.
References puth_list_ch(), puth_list_i1(), puth_list_i2(), puth_list_i4(), puth_list_i8(), puth_list_log(), puth_list_r4(), puth_list_r8(), and data_type_sl_list::type_sl_link::putt().
non_overridable data_type_sl_list::type_sl_list::puth_list_r8 ()
Definition at line 281 of file Data_Type_SL_List.f90.
Referenced by put_list_log(), and puth().
non_overridable data_type_sl_list::type_sl_list::puth_list_r4 ()
Definition at line 281 of file Data_Type_SL_List.f90.
Referenced by put_list_log(), and puth().
non_overridable data_type_sl_list::type_sl_list::puth_list_i8 ()
Definition at line 281 of file Data_Type_SL_List.f90.
Referenced by put_list_log(), and puth().
non_overridable data_type_sl_list::type_sl_list::puth_list_i4 ()
Definition at line 281 of file Data_Type_SL_List.f90.
Referenced by put_list_log(), and puth().
non_overridable data_type_sl_list::type_sl_list::puth_list_i2 ()
Definition at line 281 of file Data_Type_SL_List.f90.
Referenced by puth(), and puth_list_r8().
non_overridable data_type_sl_list::type_sl_list::puth_list_i1 ()
Definition at line 281 of file Data_Type_SL_List.f90.
Referenced by puth(), and puth_list_r4().
non_overridable data_type_sl_list::type_sl_list::puth_list_ch ()
Definition at line 281 of file Data_Type_SL_List.f90.
Referenced by puth(), and puth_list_i8().
non_overridable data_type_sl_list::type_sl_list::puth_list_log ()
Definition at line 281 of file Data_Type_SL_List.f90.
Referenced by puth(), and puth_list_i4().
generic data_type_sl_list::type_sl_list::putt ()
Definition at line 283 of file Data_Type_SL_List.f90.
References data_type_sl_list::type_sl_link::array(), putt_list_ch(), putt_list_i1(), putt_list_i2(), putt_list_i4(), putt_list_i8(), putt_list_log(), putt_list_r4(), and putt_list_r8().
non_overridable data_type_sl_list::type_sl_list::putt_list_r8 ()
Definition at line 287 of file Data_Type_SL_List.f90.
Referenced by puth_list_log(), and putt().
non_overridable data_type_sl_list::type_sl_list::putt_list_r4 ()
Definition at line 287 of file Data_Type_SL_List.f90.
Referenced by puth_list_log(), and putt().
non_overridable data_type_sl_list::type_sl_list::putt_list_i8 ()
Definition at line 287 of file Data_Type_SL_List.f90.
Referenced by puth_list_log(), and putt().
non_overridable data_type_sl_list::type_sl_list::putt_list_i4 ()
Definition at line 287 of file Data_Type_SL_List.f90.
Referenced by puth_list_log(), and putt().
non_overridable data_type_sl_list::type_sl_list::putt_list_i2 ()
Definition at line 287 of file Data_Type_SL_List.f90.
Referenced by putt(), and putt_list_r8().
non_overridable data_type_sl_list::type_sl_list::putt_list_i1 ()
Definition at line 287 of file Data_Type_SL_List.f90.
Referenced by putt(), and putt_list_r4().
non_overridable data_type_sl_list::type_sl_list::putt_list_ch ()
Definition at line 287 of file Data_Type_SL_List.f90.
Referenced by putt(), and putt_list_i8().
non_overridable data_type_sl_list::type_sl_list::putt_list_log ()
Definition at line 287 of file Data_Type_SL_List.f90.
Referenced by putt(), and putt_list_i4().
generic data_type_sl_list::type_sl_list::array ()
Definition at line 289 of file Data_Type_SL_List.f90.
References array_list_ch(), array_list_i1(), array_list_i2(), array_list_i4(), array_list_i8(), array_list_log(), array_list_r4(), and array_list_r8().
non_overridable data_type_sl_list::type_sl_list::array_list_r8 ()
Definition at line 293 of file Data_Type_SL_List.f90.
References get_list_i4(), get_list_i8(), get_list_r4(), and get_list_r8().
Referenced by array(), and putt_list_log().
non_overridable data_type_sl_list::type_sl_list::array_list_r4 ()
Definition at line 293 of file Data_Type_SL_List.f90.
Referenced by array(), and putt_list_log().
non_overridable data_type_sl_list::type_sl_list::array_list_i8 ()
Definition at line 293 of file Data_Type_SL_List.f90.
Referenced by array(), and putt_list_log().
non_overridable data_type_sl_list::type_sl_list::array_list_i4 ()
Definition at line 293 of file Data_Type_SL_List.f90.
Referenced by array(), and putt_list_log().
non_overridable data_type_sl_list::type_sl_list::array_list_i2 ()
Definition at line 293 of file Data_Type_SL_List.f90.
Referenced by array(), and array_list_r8().
non_overridable data_type_sl_list::type_sl_list::array_list_i1 ()
Definition at line 293 of file Data_Type_SL_List.f90.
Referenced by array(), and array_list_r4().
non_overridable data_type_sl_list::type_sl_list::array_list_ch ()
Definition at line 293 of file Data_Type_SL_List.f90.
Referenced by array(), and array_list_i8().
non_overridable data_type_sl_list::type_sl_list::array_list_log ()
Definition at line 293 of file Data_Type_SL_List.f90.
Referenced by array(), and array_list_i4().
procedure, non_overridable data_type_sl_list::type_sl_list::get_list_r8 ()
Definition at line 298 of file Data_Type_SL_List.f90.
References get_list_i2().
procedure, non_overridable data_type_sl_list::type_sl_list::get_list_r4 ()
Definition at line 299 of file Data_Type_SL_List.f90.
References get_list_i1().
procedure, non_overridable data_type_sl_list::type_sl_list::get_list_i8 ()
Definition at line 300 of file Data_Type_SL_List.f90.
References get_list_ch().
procedure, non_overridable data_type_sl_list::type_sl_list::get_list_i4 ()
Definition at line 301 of file Data_Type_SL_List.f90.
References get_list_log().
procedure, non_overridable data_type_sl_list::type_sl_list::get_list_i2 ()
Definition at line 302 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::get_list_i1 ()
Definition at line 303 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::get_list_ch ()
Definition at line 304 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::get_list_log ()
Definition at line 305 of file Data_Type_SL_List.f90.
References geth_list_i4(), geth_list_i8(), geth_list_r4(), and geth_list_r8().
procedure, non_overridable data_type_sl_list::type_sl_list::geth_list_r8 ()
Definition at line 309 of file Data_Type_SL_List.f90.
References geth_list_i2().
procedure, non_overridable data_type_sl_list::type_sl_list::geth_list_r4 ()
Definition at line 310 of file Data_Type_SL_List.f90.
References geth_list_i1().
procedure, non_overridable data_type_sl_list::type_sl_list::geth_list_i8 ()
Definition at line 311 of file Data_Type_SL_List.f90.
References geth_list_ch().
procedure, non_overridable data_type_sl_list::type_sl_list::geth_list_i4 ()
Definition at line 312 of file Data_Type_SL_List.f90.
References geth_list_log().
procedure, non_overridable data_type_sl_list::type_sl_list::geth_list_i2 ()
Definition at line 313 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::geth_list_i1 ()
Definition at line 314 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::geth_list_ch ()
Definition at line 315 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::geth_list_log ()
Definition at line 316 of file Data_Type_SL_List.f90.
References gett_list_i4(), gett_list_i8(), gett_list_r4(), and gett_list_r8().
procedure, non_overridable data_type_sl_list::type_sl_list::gett_list_r8 ()
Definition at line 320 of file Data_Type_SL_List.f90.
References gett_list_i2().
procedure, non_overridable data_type_sl_list::type_sl_list::gett_list_r4 ()
Definition at line 321 of file Data_Type_SL_List.f90.
References gett_list_i1().
procedure, non_overridable data_type_sl_list::type_sl_list::gett_list_i8 ()
Definition at line 322 of file Data_Type_SL_List.f90.
References gett_list_ch().
procedure, non_overridable data_type_sl_list::type_sl_list::gett_list_i4 ()
Definition at line 323 of file Data_Type_SL_List.f90.
References gett_list_log().
procedure, non_overridable data_type_sl_list::type_sl_list::gett_list_i2 ()
Definition at line 324 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::gett_list_i1 ()
Definition at line 325 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::gett_list_ch ()
Definition at line 326 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::gett_list_log ()
Definition at line 327 of file Data_Type_SL_List.f90.
References put_list_i4(), put_list_i8(), put_list_r4(), and put_list_r8().
procedure, non_overridable data_type_sl_list::type_sl_list::put_list_r8 ()
Definition at line 331 of file Data_Type_SL_List.f90.
References put_list_i2().
procedure, non_overridable data_type_sl_list::type_sl_list::put_list_r4 ()
Definition at line 332 of file Data_Type_SL_List.f90.
References put_list_i1().
procedure, non_overridable data_type_sl_list::type_sl_list::put_list_i8 ()
Definition at line 333 of file Data_Type_SL_List.f90.
References put_list_ch().
procedure, non_overridable data_type_sl_list::type_sl_list::put_list_i4 ()
Definition at line 334 of file Data_Type_SL_List.f90.
References put_list_log().
procedure, non_overridable data_type_sl_list::type_sl_list::put_list_i2 ()
Definition at line 335 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::put_list_i1 ()
Definition at line 336 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::put_list_ch ()
Definition at line 337 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::put_list_log ()
Definition at line 338 of file Data_Type_SL_List.f90.
References puth_list_i4(), puth_list_i8(), puth_list_r4(), and puth_list_r8().
procedure, non_overridable data_type_sl_list::type_sl_list::puth_list_r8 ()
Definition at line 342 of file Data_Type_SL_List.f90.
References puth_list_i2().
procedure, non_overridable data_type_sl_list::type_sl_list::puth_list_r4 ()
Definition at line 343 of file Data_Type_SL_List.f90.
References puth_list_i1().
procedure, non_overridable data_type_sl_list::type_sl_list::puth_list_i8 ()
Definition at line 344 of file Data_Type_SL_List.f90.
References puth_list_ch().
procedure, non_overridable data_type_sl_list::type_sl_list::puth_list_i4 ()
Definition at line 345 of file Data_Type_SL_List.f90.
References puth_list_log().
procedure, non_overridable data_type_sl_list::type_sl_list::puth_list_i2 ()
Definition at line 346 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::puth_list_i1 ()
Definition at line 347 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::puth_list_ch ()
Definition at line 348 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::puth_list_log ()
Definition at line 349 of file Data_Type_SL_List.f90.
References putt_list_i4(), putt_list_i8(), putt_list_r4(), and putt_list_r8().
procedure, non_overridable data_type_sl_list::type_sl_list::putt_list_r8 ()
Definition at line 353 of file Data_Type_SL_List.f90.
References putt_list_i2().
procedure, non_overridable data_type_sl_list::type_sl_list::putt_list_r4 ()
Definition at line 354 of file Data_Type_SL_List.f90.
References putt_list_i1().
procedure, non_overridable data_type_sl_list::type_sl_list::putt_list_i8 ()
Definition at line 355 of file Data_Type_SL_List.f90.
References putt_list_ch().
procedure, non_overridable data_type_sl_list::type_sl_list::putt_list_i4 ()
Definition at line 356 of file Data_Type_SL_List.f90.
References putt_list_log().
procedure, non_overridable data_type_sl_list::type_sl_list::putt_list_i2 ()
Definition at line 357 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::putt_list_i1 ()
Definition at line 358 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::putt_list_ch ()
Definition at line 359 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::putt_list_log ()
Definition at line 360 of file Data_Type_SL_List.f90.
References array_list_i4(), array_list_i8(), array_list_r4(), and array_list_r8().
procedure, non_overridable data_type_sl_list::type_sl_list::array_list_r8 ()
Definition at line 364 of file Data_Type_SL_List.f90.
References array_list_i2().
procedure, non_overridable data_type_sl_list::type_sl_list::array_list_r4 ()
Definition at line 365 of file Data_Type_SL_List.f90.
References array_list_i1().
procedure, non_overridable data_type_sl_list::type_sl_list::array_list_i8 ()
Definition at line 366 of file Data_Type_SL_List.f90.
References array_list_ch().
procedure, non_overridable data_type_sl_list::type_sl_list::array_list_i4 ()
Definition at line 367 of file Data_Type_SL_List.f90.
References array_list_log().
procedure, non_overridable data_type_sl_list::type_sl_list::array_list_i2 ()
Definition at line 368 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::array_list_i1 ()
Definition at line 369 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::array_list_ch ()
Definition at line 370 of file Data_Type_SL_List.f90.
procedure, non_overridable data_type_sl_list::type_sl_list::array_list_log ()
Definition at line 371 of file Data_Type_SL_List.f90.
Member Data Documentation
integer(i4p), public data_type_sl_list::type_sl_list::l = 0
List length.
Definition at line 243 of file Data_Type_SL_List.f90.
logical, public data_type_sl_list::type_sl_list::homo = .true.
Flag for checking if the list is homogeneous.
Definition at line 244 of file Data_Type_SL_List.f90.
type(type_sl_link), pointer data_type_sl_list::type_sl_list::f => null()
Pointer to the first link of the list.
Definition at line 245 of file Data_Type_SL_List.f90.