OFF: data_type_global::type_global Type Reference
data_type_global::type_global Type Reference
Derived type containing the global-level data.
integer(i_p) myrank = 0_I_P
Rank of the process which data belongs to.
type(type_file) file
File data.
integer(i_p) nl = 1_I_P
Number of grid levels.
integer(i_p) nb = 0_I_P
Number of blocks.
integer(i_p) nb_tot = 0_I_P
Number of total blocks (sum over each process).
integer(i1p) gco = 1_I1P
Number of ghost cells necessary to achieve the space reconstruction order.
integer(i_p) nin1 = 0_I_P
Number of inflow 1 boundary conditions.
type(type_primitive),
dimension(:), allocatable in1
Inflow 1 boundary conditions primitive variables [1:Nin1].
integer(i8p) n = 0_I8P
Time steps counter.
real(r_p) t = 0._R_P
Time.
integer(i_p) ns = 1_I_P
Number of species.
integer(i_p) np = 7_I_P
Number of primitive variables (Np = Ns + 6).
integer(i_p) nc = 5_I_P
Number of conservative variables (Nc = Ns + 4).
logical inviscid = .true.
Type of simulation: inviscid (Euler's eq.) or viscous (Navier-Stokes eq.).
logical unsteady = .true.
Type of simulation: unsteady or not.
integer(i8p) nmax = 0_I8P
Max number of iterations.
real(r_p) tmax = 0._R_P
Max time, ignored if Nmax>0.
integer(i1p) sp_ord = 1_I1P
Order of space convergence (number of ghost cells).
integer(i1p) rk_ord = 1_I1P
Order of time convergence (number of Runge-Kutta stages).
real(r_p) cfl = 0.3_R_P
Value of stability coefficient.
real(r_p) residual_toll = 0.01_R_P
Tolerance for residuals vanishing evaluation.
logical residual_stop = .false.
Sentinel for stopping steady simulation when residuals vanish.
real(r_p), dimension(:),
allocatable cp0
Initial specific heat cp for each specie [1:Ns].
real(r_p), dimension(:),
allocatable cv0
Initial specific heat cv for each specie [1:Ns].
type(type_adimensional) adim
Non-dimensionalization data.
procedure, non_overridable alloc_bc => alloc_gbc
procedure, non_overridable load_bc_in1 => load_gbc_in1
procedure, non_overridable load_fluid_soption => load_gfluid_soption
procedure, non_overridable load_fluid_ns => load_gfluid_Ns
procedure, non_overridable load_fluid_0species => load_gfluid_0species
procedure, non_overridable alloc_fluid => alloc_gfluid
Detailed Description
Derived type containing the global-level data.
Definition at line 91 of file Data_Type_Global.f90.
Member Function/Subroutine Documentation
procedure, non_overridable data_type_global::type_global::alloc_bc ()
Definition at line 121 of file Data_Type_Global.f90.
References load_fluid_0species(), and data_type_global::load_gfluid_0species().
procedure, non_overridable data_type_global::type_global::load_bc_in1 ()
Definition at line 122 of file Data_Type_Global.f90.
References alloc_fluid(), and data_type_global::alloc_gfluid().
procedure, non_overridable data_type_global::type_global::load_fluid_soption ()
Definition at line 123 of file Data_Type_Global.f90.
procedure, non_overridable data_type_global::type_global::load_fluid_ns ()
Definition at line 124 of file Data_Type_Global.f90.
procedure, non_overridable data_type_global::type_global::load_fluid_0species ()
Definition at line 125 of file Data_Type_Global.f90.
Referenced by alloc_bc().
procedure, non_overridable data_type_global::type_global::alloc_fluid ()
Definition at line 126 of file Data_Type_Global.f90.
References data_type_global::file_name::block_file_name(), data_type_global::file_name::block_flip_file_name(), and data_type_global::file_name::block_step_file_name().
Referenced by load_bc_in1().
Member Data Documentation
integer(i_p) data_type_global::type_global::myrank = 0_I_P
Rank of the process which data belongs to.
Definition at line 92 of file Data_Type_Global.f90.
type(type_file) data_type_global::type_global::file
File data.
Definition at line 93 of file Data_Type_Global.f90.
integer(i_p) data_type_global::type_global::nl = 1_I_P
Number of grid levels.
Definition at line 95 of file Data_Type_Global.f90.
integer(i_p) data_type_global::type_global::nb = 0_I_P
Number of blocks.
Definition at line 96 of file Data_Type_Global.f90.
integer(i_p) data_type_global::type_global::nb_tot = 0_I_P
Number of total blocks (sum over each process).
Definition at line 97 of file Data_Type_Global.f90.
integer(i1p) data_type_global::type_global::gco = 1_I1P
Number of ghost cells necessary to achieve the space reconstruction order.
Definition at line 98 of file Data_Type_Global.f90.
integer(i_p) data_type_global::type_global::nin1 = 0_I_P
Number of inflow 1 boundary conditions.
Definition at line 100 of file Data_Type_Global.f90.
type(type_primitive), dimension(:), allocatable data_type_global::type_global::in1
Inflow 1 boundary conditions primitive variables [1:Nin1].
Definition at line 101 of file Data_Type_Global.f90.
integer(i8p) data_type_global::type_global::n = 0_I8P
Time steps counter.
Definition at line 103 of file Data_Type_Global.f90.
real(r_p) data_type_global::type_global::t = 0._R_P
Time.
Definition at line 104 of file Data_Type_Global.f90.
integer(i_p) data_type_global::type_global::ns = 1_I_P
Number of species.
Definition at line 105 of file Data_Type_Global.f90.
integer(i_p) data_type_global::type_global::np = 7_I_P
Number of primitive variables (Np = Ns + 6).
Definition at line 106 of file Data_Type_Global.f90.
integer(i_p) data_type_global::type_global::nc = 5_I_P
Number of conservative variables (Nc = Ns + 4).
Definition at line 107 of file Data_Type_Global.f90.
logical data_type_global::type_global::inviscid = .true.
Type of simulation: inviscid (Euler's eq.) or viscous (Navier-Stokes eq.).
Definition at line 108 of file Data_Type_Global.f90.
logical data_type_global::type_global::unsteady = .true.
Type of simulation: unsteady or not.
Definition at line 109 of file Data_Type_Global.f90.
integer(i8p) data_type_global::type_global::nmax = 0_I8P
Max number of iterations.
Definition at line 110 of file Data_Type_Global.f90.
real(r_p) data_type_global::type_global::tmax = 0._R_P
Max time, ignored if Nmax>0.
Definition at line 111 of file Data_Type_Global.f90.
integer(i1p) data_type_global::type_global::sp_ord = 1_I1P
Order of space convergence (number of ghost cells).
Definition at line 112 of file Data_Type_Global.f90.
integer(i1p) data_type_global::type_global::rk_ord = 1_I1P
Order of time convergence (number of Runge-Kutta stages).
Definition at line 113 of file Data_Type_Global.f90.
real(r_p) data_type_global::type_global::cfl = 0.3_R_P
Value of stability coefficient.
Definition at line 114 of file Data_Type_Global.f90.
real(r_p) data_type_global::type_global::residual_toll = 0.01_R_P
Tolerance for residuals vanishing evaluation.
Definition at line 115 of file Data_Type_Global.f90.
logical data_type_global::type_global::residual_stop = .false.
Sentinel for stopping steady simulation when residuals vanish.
Definition at line 116 of file Data_Type_Global.f90.
real(r_p), dimension(:), allocatable data_type_global::type_global::cp0
Initial specific heat cp for each specie [1:Ns].
Definition at line 117 of file Data_Type_Global.f90.
real(r_p), dimension(:), allocatable data_type_global::type_global::cv0
Initial specific heat cv for each specie [1:Ns].
Definition at line 118 of file Data_Type_Global.f90.
type(type_adimensional) data_type_global::type_global::adim
Non-dimensionalization data.
Definition at line 119 of file Data_Type_Global.f90.
The documentation for this type was generated from the following file:
Data_Type_Global.f90