OFF: Lib_Fluidynamic
Lib_Fluidynamic
Private Procedures
Functions/Subroutines
pure subroutine p2c_reshape1D (N, P, U)
Subroutine for doing the calculation on 1D-reshaped arrays in order to augment computational efficiency.
pure subroutine c2p_reshape1D (N, U, P)
Subroutine for doing the calculation on 1D-reshaped arrays in order to augment computational efficiency.
subroutine Lib_Fluidynamic::compute_time (global, block, Dtmin)
Function for evaluating the local and global time step value by CFL condition.
subroutine Lib_Fluidynamic::residuals (s1, global, block)
Subroutine for computing the residuals.
pure subroutine Lib_Fluidynamic::rk_stages_sum (s1, global, block)
Subroutine for summing Runge-Kutta stages for updating primitive variables (block%fluid%P).
pure subroutine rk_stg_reshape1D (N, Dt, U, KS, P)
Subroutine for doing the calculation on 1D-reshaped arrays in order to augment computational efficiency.
pure subroutine Lib_Fluidynamic::rk_time_integration (global, block, RU)
Subroutine for computing Runge-Kutta one time step integration.
pure subroutine rk_t_int_reshape1D (N, Dt, KS, U, RU)
Subroutine for doing the calculation on 1D-reshaped arrays in order to augment computational efficiency.
Function/Subroutine Documentation
pure subroutine primitive2conservative::p2c_reshape1D (integer(I8P), intent(in) N, type(Type_Primitive), dimension(1:n), intent(in) P, type(Type_Conservative), dimension(1:n), intent(inout) U) [private]
Subroutine for doing the calculation on 1D-reshaped arrays in order to augment computational efficiency.
The computation of the parent procedure is performed in 1D re-shaped arrays in order to augment the computational efficiency when using OpenMP shared parallel paradigm. As a matter of facts the scalability of OpenMP parallelism is exploited only when the parallelized loop is the largest one. In the case of multi-dimensional arrays the first index is not always the largest one. Therefore the 1D reshaping ensures that the OpenMP parallelism is applied on the largest index because after reshaping there is only one index.
Parameters:
[in] N Number of finite volumes.
[in] P Primitive variables.
[in,out] U Conservative variables.
Definition at line 158 of file Lib_Fluidynamic.f90.
pure subroutine conservative2primitive::c2p_reshape1D (integer(I8P), intent(in) N, type(Type_Conservative), dimension(1:n), intent(in) U, type(Type_Primitive), dimension(1:n), intent(inout) P) [private]
Subroutine for doing the calculation on 1D-reshaped arrays in order to augment computational efficiency.
The computation of the parent procedure is performed in 1D re-shaped arrays in order to augment the computational efficiency when using OpenMP shared parallel paradigm. As a matter of facts the scalability of OpenMP parallelism is exploited only when the parallelized loop is the largest one. In the case of multi-dimensional arrays the first index is not always the largest one. Therefore the 1D reshaping ensures that the OpenMP parallelism is applied on the largest index because after reshaping there is only one index.
Parameters:
[in] N Number of finite volumes.
[in] U Conservative variables.
[in,out] P Primitive variables.
Definition at line 205 of file Lib_Fluidynamic.f90.
subroutine Lib_Fluidynamic::compute_time (type(Type_Global), intent(in) global, integer(I_P), intent(inout) block, real(R_P), intent(out) Dtmin) [private]
Function for evaluating the local and global time step value by CFL condition.
Parameters:
[in] global Global-level data.
[in,out] block Block-level data.
[out] Dtmin Minimum Dt.
Definition at line 230 of file Lib_Fluidynamic.f90.
subroutine Lib_Fluidynamic::residuals (integer(I_P), intent(in) s1, type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block) [private]
Subroutine for computing the residuals.
This the space operator.
Definition at line 358 of file Lib_Fluidynamic.f90.
References fluxes().
pure subroutine Lib_Fluidynamic::rk_stages_sum (integer(I_P), intent(in) s1, type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block) [private]
Subroutine for summing Runge-Kutta stages for updating primitive variables (block%fluid%P).
Parameters:
[in] s1 Current Runge-Kutta stage.
[in] global Global-level data.
[in,out] block Block-level data.
Definition at line 1352 of file Lib_Fluidynamic.f90.
pure subroutine rk_stages_sum::rk_stg_reshape1D (integer(I8P), intent(in) N, real(R_P), dimension(1:n), intent(in) Dt, type(Type_Conservative), dimension(1:n), intent(in) U, type(Type_Conservative), dimension(1:n,1:s1-1), intent(in) KS, type(Type_Primitive), dimension(1:n), intent(inout) P) [private]
Subroutine for doing the calculation on 1D-reshaped arrays in order to augment computational efficiency.
The computation of the parent procedure is performed in 1D re-shaped arrays in order to augment the computational efficiency when using OpenMP shared parallel paradigm. As a matter of facts the scalability of OpenMP parallelism is exploited only when the parallelized loop is the largest one. In the case of multi-dimensional arrays the first index is not always the largest one. Therefore the 1D reshaping ensures that the OpenMP parallelism is applied on the largest index because after reshaping there is only one index.
Parameters:
[in] N Number of finite volumes.
[in] Dt Time steps.
[in] U Current conservative variables.
[in] KS Runge-Kutta stages.
[in,out] P Updated primitive variables.
Definition at line 1376 of file Lib_Fluidynamic.f90.
Referenced by rk_t_int_reshape1D().
pure subroutine Lib_Fluidynamic::rk_time_integration (type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block, real(R_P), dimension(1:global%fluid%nc), intent(out) RU) [private]
Subroutine for computing Runge-Kutta one time step integration.
Parameters:
[in] global Global-level data.
[in,out] block Block-level data.
[out] RU NormL2 of residuals of conservative variables.
Definition at line 1406 of file Lib_Fluidynamic.f90.
pure subroutine rk_time_integration::rk_t_int_reshape1D (integer(I8P), intent(in) N, real(R_P), dimension(1:n), intent(in) Dt, type(Type_Conservative), dimension(1:n,1:global%fluid%rk_ord), intent(in) KS, type(Type_Conservative), dimension(1:n), intent(inout) U, real(R_P), dimension(1:global%fluid%nc), intent(out) RU) [private]
Subroutine for doing the calculation on 1D-reshaped arrays in order to augment computational efficiency.
The computation of the parent procedure is performed in 1D re-shaped arrays in order to augment the computational efficiency when using OpenMP shared parallel paradigm. As a matter of facts the scalability of OpenMP parallelism is exploited only when the parallelized loop is the largest one. In the case of multi-dimensional arrays the first index is not always the largest one. Therefore the 1D reshaping ensures that the OpenMP parallelism is applied on the largest index because after reshaping there is only one index.
Parameters:
[in] N Number of finite volumes.
[in] Dt Time steps.
[in] KS Runge-Kutta stages.
[in,out] U Current conservative variables.
[out] RU NormL2 of residuals of conservative variables.
Definition at line 1430 of file Lib_Fluidynamic.f90.
References rk_stg_reshape1D().