OFF: Lib_Math
Lib_Math
Modules Libraries
Data Types
module lib_math
This module contains mathematical procedures.
Detailed Description
Data Type Documentation
module lib_math
This module contains mathematical procedures.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 38 of file Lib_Math.f90.
Public Member Functions
pure function, public stretchinglside (Ns, s_uniform, stretch)
pure function, public stretchingrside (Ns, s_uniform, stretch)
pure function, public stretching2side (s_sym_in, Ns, s_uniform, Ds_L, Ds_R)
Public Attributes
real(r16p), parameter, public pi_r16 = 2._R16P*asin(1._R16P)
with R16P precision.
real(r8p), parameter, public pi_r8 = 2._R8P* asin(1._R8P)
with R8P precision.
real(r4p), parameter, public pi_r4 = 2._R4P* asin(1._R4P)
with R4P precision.
real(r_p), parameter, public pi = 2._R_P* asin(1._R_P)
with R_P precision.
Private Member Functions
pure function average_vectorial1d_r16 (x)
pure function average_vectorial1d_r8 (x)
pure function average_vectorial1d_r4 (x)
pure function average_vectorial2d_r16 (x)
pure function average_vectorial2d_r8 (x)
pure function average_vectorial2d_r4 (x)
pure function average_vectorial3d_r16 (x)
pure function average_vectorial3d_r8 (x)
pure function average_vectorial3d_r4 (x)
elemental function digit_i8 (n)
elemental function digit_i4 (n)
elemental function digit_i2 (n)
elemental function digit_i1 (n)
elemental function div2_i1 (n)
elemental function div2_i2 (n)
elemental function div2_i4 (n)
elemental function div2_i8 (n)
elemental function interpolate1_r16 (x1, x2, V1, V2, x)
elemental function interpolate1_r8 (x1, x2, V1, V2, x)
elemental function interpolate1_r4 (x1, x2, V1, V2, x)
elemental function interpolate2_r16 (x1, y1, x2, y2, V11, V12, V21, V22, x, y)
elemental function interpolate2_r8 (x1, y1, x2, y2, V11, V12, V21, V22, x, y)
elemental function interpolate2_r4 (x1, y1, x2, y2, V11, V12, V21, V22, x, y)
elemental function interpolate3_r16 (x1, y1, z1, x2, y2, z2, V111, V121, V211, V221, V112, V122, V212, V222, x, y, z)
elemental function interpolate3_r8 (x1, y1, z1, x2, y2, z2, V111, V121, V211, V221, V112, V122, V212, V222, x, y, z)
elemental function interpolate3_r4 (x1, y1, z1, x2, y2, z2, V111, V121, V211, V221, V112, V122, V212, V222, x, y, z)
elemental function degree_scalar_r16 (x_rad)
elemental function degree_scalar_r8 (x_rad)
elemental function degree_scalar_r4 (x_rad)
pure function degree_vectorial1d_r16 (x_rad)
pure function degree_vectorial1d_r8 (x_rad)
pure function degree_vectorial1d_r4 (x_rad)
pure function degree_vectorial2d_r16 (x_rad)
pure function degree_vectorial2d_r8 (x_rad)
pure function degree_vectorial2d_r4 (x_rad)
pure function degree_vectorial3d_r16 (x_rad)
pure function degree_vectorial3d_r8 (x_rad)
pure function degree_vectorial3d_r4 (x_rad)
elemental function radiant_scalar_r16 (x_deg)
elemental function radiant_scalar_r8 (x_deg)
elemental function radiant_scalar_r4 (x_deg)
pure function radiant_vectorial1d_r16 (x_deg)
pure function radiant_vectorial1d_r8 (x_deg)
pure function radiant_vectorial1d_r4 (x_deg)
pure function radiant_vectorial2d_r16 (x_deg)
pure function radiant_vectorial2d_r8 (x_deg)
pure function radiant_vectorial2d_r4 (x_deg)
pure function radiant_vectorial3d_r16 (x_deg)
pure function radiant_vectorial3d_r8 (x_deg)
pure function radiant_vectorial3d_r4 (x_deg)
elemental function delta1_2o_r16 (Sp1, Sm1, Ds)
elemental function delta1_2o_r8 (Sp1, Sm1, Ds)
elemental function delta1_2o_r4 (Sp1, Sm1, Ds)
elemental function delta2_2o_r16 (Sp1, S, Sm1, Ds)
elemental function delta2_2o_r8 (Sp1, S, Sm1, Ds)
elemental function delta2_2o_r4 (Sp1, S, Sm1, Ds)
elemental function abs_grad_r16 (Vip1, Vim1, Di, Vjp1, Vjm1, Dj, Vkp1, Vkm1, Dk)
elemental function abs_grad_r8 (Vip1, Vim1, Di, Vjp1, Vjm1, Dj, Vkp1, Vkm1, Dk)
elemental function abs_grad_r4 (Vip1, Vim1, Di, Vjp1, Vjm1, Dj, Vkp1, Vkm1, Dk)
elemental function laplacian_r16 (Vip1, Vi, Vim1, Di, Vjp1, Vj, Vjm1, Dj, Vkp1, Vk, Vkm1, Dk)
elemental function laplacian_r8 (Vip1, Vi, Vim1, Di, Vjp1, Vj, Vjm1, Dj, Vkp1, Vk, Vkm1, Dk)
elemental function laplacian_r4 (Vip1, Vi, Vim1, Di, Vjp1, Vj, Vjm1, Dj, Vkp1, Vk, Vkm1, Dk)
pure subroutine isort_r16 (array)
Subroutine for computing prime factors of input integer number (I8P).
pure subroutine isort_r8 (array)
Subroutine for performing InsertionSort with ascending order (R8P).
pure subroutine isort_r4 (array)
Subroutine for performing InsertionSort with ascending order (R4P).
pure subroutine isort_i8 (array)
Subroutine for performing InsertionSort with ascending order (I8P).
pure subroutine isort_i4 (array)
Subroutine for performing InsertionSort with ascending order (I4P).
pure subroutine isort_i2 (array)
Subroutine for performing InsertionSort with ascending order (I2P).
pure subroutine isort_i1 (array)
Subroutine for performing InsertionSort with ascending order (I1P).
subroutine qsort_r16 (array)
Subroutine for performing QuickSort with ascending order (R16P).
subroutine qsort_r8 (array)
Subroutine for performing QuickSort with ascending order (R8P).
subroutine qsort_r4 (array)
Subroutine for performing QuickSort with ascending order (R4P).
subroutine qsort_i8 (array)
Subroutine for performing QuickSort with ascending order (I8P).
subroutine qsort_i4 (array)
Subroutine for performing QuickSort with ascending order (I4P).
subroutine qsort_i2 (array)
Subroutine for performing QuickSort with ascending order (I2P).
subroutine qsort_i1 (array)
Subroutine for performing QuickSort with ascending order (I1P).
pure function spline3_r16 (bc1, bcn, x, v, xi)
Function for computing cubic spline interpolation of an array of values (R16P).
pure function spline3_r8 (bc1, bcn, x, v, xi)
Function for computing cubic spline interpolation of an array of values (R8P).
pure function spline3_r4 (bc1, bcn, x, v, xi)
Function for computing cubic spline interpolation of an array of values (R4P).
Member Function/Subroutine Documentation
pure function, public lib_math::stretchinglside (integer(i4p), intent(in) Ns, real(r_p), dimension(1:ns), intent(in) s_uniform, real(r_p), intent(in) stretch)
Definition at line 1345 of file Lib_Math.f90.
pure function, public lib_math::stretchingrside (integer(i4p), intent(in) Ns, real(r_p), dimension(1:ns), intent(in) s_uniform, real(r_p), intent(in) stretch)
Definition at line 1378 of file Lib_Math.f90.
pure function, public lib_math::stretching2side (real(r_p), intent(in), optional s_sym_in, integer(i4p), intent(in) Ns, real(r_p), dimension(1:ns), intent(in) s_uniform, real(r_p), intent(in) Ds_L, real(r_p), intent(in) Ds_R)
Definition at line 1411 of file Lib_Math.f90.
pure function lib_math::average_vectorial1d_r16 (real(r16p), dimension(:), intent(in) x) private
Definition at line 1493 of file Lib_Math.f90.
pure function lib_math::average_vectorial1d_r8 (real(r8p), dimension(:), intent(in) x) private
Definition at line 1510 of file Lib_Math.f90.
pure function lib_math::average_vectorial1d_r4 (real(r4p), dimension(:), intent(in) x) private
Definition at line 1527 of file Lib_Math.f90.
pure function lib_math::average_vectorial2d_r16 (real(r16p), dimension(:,:), intent(in) x) private
Definition at line 1544 of file Lib_Math.f90.
pure function lib_math::average_vectorial2d_r8 (real(r8p), dimension(:,:), intent(in) x) private
Definition at line 1561 of file Lib_Math.f90.
pure function lib_math::average_vectorial2d_r4 (real(r4p), dimension(:,:), intent(in) x) private
Definition at line 1578 of file Lib_Math.f90.
pure function lib_math::average_vectorial3d_r16 (real(r16p), dimension(:,:,:), intent(in) x) private
Definition at line 1595 of file Lib_Math.f90.
pure function lib_math::average_vectorial3d_r8 (real(r8p), dimension(:,:,:), intent(in) x) private
Definition at line 1612 of file Lib_Math.f90.
pure function lib_math::average_vectorial3d_r4 (real(r4p), dimension(:,:,:), intent(in) x) private
Definition at line 1629 of file Lib_Math.f90.
elemental function lib_math::digit_i8 (integer(i8p), intent(in) n) private
Definition at line 1647 of file Lib_Math.f90.
References ir_precision::fi8p.
elemental function lib_math::digit_i4 (integer(i4p), intent(in) n) private
Definition at line 1666 of file Lib_Math.f90.
References ir_precision::fi4p.
elemental function lib_math::digit_i2 (integer(i2p), intent(in) n) private
Definition at line 1685 of file Lib_Math.f90.
References ir_precision::fi2p.
elemental function lib_math::digit_i1 (integer(i1p), intent(in) n) private
Definition at line 1704 of file Lib_Math.f90.
References ir_precision::fi1p.
elemental function lib_math::div2_i1 (integer(i1p), intent(in) n) private
Definition at line 1724 of file Lib_Math.f90.
References ir_precision::i4p.
elemental function lib_math::div2_i2 (integer(i2p), intent(in) n) private
Definition at line 1747 of file Lib_Math.f90.
References ir_precision::i4p.
elemental function lib_math::div2_i4 (integer(i4p), intent(in) n) private
Definition at line 1770 of file Lib_Math.f90.
References ir_precision::i4p.
elemental function lib_math::div2_i8 (integer(i8p), intent(in) n) private
Definition at line 1793 of file Lib_Math.f90.
References ir_precision::i4p.
elemental function lib_math::interpolate1_r16 (real(r16p), intent(in) x1, real(r16p), intent(in) x2, real(r16p), intent(in) V1, real(r16p), intent(in) V2, real(r16p), intent(in) x) private
Definition at line 1817 of file Lib_Math.f90.
Referenced by interpolate2_r16(), and interpolate3_r16().
elemental function lib_math::interpolate1_r8 (real(r8p), intent(in) x1, real(r8p), intent(in) x2, real(r8p), intent(in) V1, real(r8p), intent(in) V2, real(r8p), intent(in) x) private
Definition at line 1836 of file Lib_Math.f90.
elemental function lib_math::interpolate1_r4 (real(r4p), intent(in) x1, real(r4p), intent(in) x2, real(r4p), intent(in) V1, real(r4p), intent(in) V2, real(r4p), intent(in) x) private
Definition at line 1855 of file Lib_Math.f90.
elemental function lib_math::interpolate2_r16 (real(r16p), intent(in) x1, real(r16p), intent(in) y1, real(r16p), intent(in) x2, real(r16p), intent(in) y2, real(r16p), intent(in) V11, real(r16p), intent(in) V12, real(r16p), intent(in) V21, real(r16p), intent(in) V22, real(r16p), intent(in) x, real(r16p), intent(in) y) private
Definition at line 1874 of file Lib_Math.f90.
References interpolate1_r16().
Referenced by interpolate3_r16().
elemental function lib_math::interpolate2_r8 (real(r8p), intent(in) x1, real(r8p), intent(in) y1, real(r8p), intent(in) x2, real(r8p), intent(in) y2, real(r8p), intent(in) V11, real(r8p), intent(in) V12, real(r8p), intent(in) V21, real(r8p), intent(in) V22, real(r8p), intent(in) x, real(r8p), intent(in) y) private
Definition at line 1909 of file Lib_Math.f90.
References lib_math::interpolate1::interpolate1_r8().
elemental function lib_math::interpolate2_r4 (real(r4p), intent(in) x1, real(r4p), intent(in) y1, real(r4p), intent(in) x2, real(r4p), intent(in) y2, real(r4p), intent(in) V11, real(r4p), intent(in) V12, real(r4p), intent(in) V21, real(r4p), intent(in) V22, real(r4p), intent(in) x, real(r4p), intent(in) y) private
Definition at line 1944 of file Lib_Math.f90.
References lib_math::interpolate1::interpolate1_r4().
elemental function lib_math::interpolate3_r16 (real(r16p), intent(in) x1, real(r16p), intent(in) y1, real(r16p), intent(in) z1, real(r16p), intent(in) x2, real(r16p), intent(in) y2, real(r16p), intent(in) z2, real(r16p), intent(in) V111, real(r16p), intent(in) V121, real(r16p), intent(in) V211, real(r16p), intent(in) V221, real(r16p), intent(in) V112, real(r16p), intent(in) V122, real(r16p), intent(in) V212, real(r16p), intent(in) V222, real(r16p), intent(in) x, real(r16p), intent(in) y, real(r16p), intent(in) z) private
Definition at line 1979 of file Lib_Math.f90.
References interpolate1_r16(), and interpolate2_r16().
elemental function lib_math::interpolate3_r8 (real(r8p), intent(in) x1, real(r8p), intent(in) y1, real(r8p), intent(in) z1, real(r8p), intent(in) x2, real(r8p), intent(in) y2, real(r8p), intent(in) z2, real(r8p), intent(in) V111, real(r8p), intent(in) V121, real(r8p), intent(in) V211, real(r8p), intent(in) V221, real(r8p), intent(in) V112, real(r8p), intent(in) V122, real(r8p), intent(in) V212, real(r8p), intent(in) V222, real(r8p), intent(in) x, real(r8p), intent(in) y, real(r8p), intent(in) z) private
Definition at line 2023 of file Lib_Math.f90.
References lib_math::interpolate1::interpolate1_r8(), and lib_math::interpolate2::interpolate2_r8().
elemental function lib_math::interpolate3_r4 (real(r4p), intent(in) x1, real(r4p), intent(in) y1, real(r4p), intent(in) z1, real(r4p), intent(in) x2, real(r4p), intent(in) y2, real(r4p), intent(in) z2, real(r4p), intent(in) V111, real(r4p), intent(in) V121, real(r4p), intent(in) V211, real(r4p), intent(in) V221, real(r4p), intent(in) V112, real(r4p), intent(in) V122, real(r4p), intent(in) V212, real(r4p), intent(in) V222, real(r4p), intent(in) x, real(r4p), intent(in) y, real(r4p), intent(in) z) private
Definition at line 2067 of file Lib_Math.f90.
References lib_math::interpolate1::interpolate1_r4(), and lib_math::interpolate2::interpolate2_r4().
elemental function lib_math::degree_scalar_r16 (real(r16p), intent(in) x_rad) private
Definition at line 2112 of file Lib_Math.f90.
References pi_r16.
elemental function lib_math::degree_scalar_r8 (real(r8p), intent(in) x_rad) private
Definition at line 2129 of file Lib_Math.f90.
References pi_r8.
elemental function lib_math::degree_scalar_r4 (real(r4p), intent(in) x_rad) private
Definition at line 2146 of file Lib_Math.f90.
References pi_r4.
pure function lib_math::degree_vectorial1d_r16 (real(r16p), dimension(:), intent(in) x_rad) private
Definition at line 2163 of file Lib_Math.f90.
References pi_r16.
pure function lib_math::degree_vectorial1d_r8 (real(r8p), dimension(:), intent(in) x_rad) private
Definition at line 2180 of file Lib_Math.f90.
References pi_r8.
pure function lib_math::degree_vectorial1d_r4 (real(r4p), dimension(:), intent(in) x_rad) private
Definition at line 2197 of file Lib_Math.f90.
References pi_r4.
pure function lib_math::degree_vectorial2d_r16 (real(r16p), dimension(:,:), intent(in) x_rad) private
Definition at line 2214 of file Lib_Math.f90.
References pi_r16.
pure function lib_math::degree_vectorial2d_r8 (real(r8p), dimension(:,:), intent(in) x_rad) private
Definition at line 2231 of file Lib_Math.f90.
References pi_r8.
pure function lib_math::degree_vectorial2d_r4 (real(r4p), dimension(:,:), intent(in) x_rad) private
Definition at line 2248 of file Lib_Math.f90.
References pi_r4.
pure function lib_math::degree_vectorial3d_r16 (real(r16p), dimension(:,:,:), intent(in) x_rad) private
Definition at line 2265 of file Lib_Math.f90.
References pi_r16.
pure function lib_math::degree_vectorial3d_r8 (real(r8p), dimension(:,:,:), intent(in) x_rad) private
Definition at line 2282 of file Lib_Math.f90.
References pi_r8.
pure function lib_math::degree_vectorial3d_r4 (real(r4p), dimension(:,:,:), intent(in) x_rad) private
Definition at line 2299 of file Lib_Math.f90.
References pi_r4.
elemental function lib_math::radiant_scalar_r16 (real(r16p), intent(in) x_deg) private
Definition at line 2317 of file Lib_Math.f90.
References pi_r16.
elemental function lib_math::radiant_scalar_r8 (real(r8p), intent(in) x_deg) private
Definition at line 2334 of file Lib_Math.f90.
References pi_r8.
elemental function lib_math::radiant_scalar_r4 (real(r4p), intent(in) x_deg) private
Definition at line 2351 of file Lib_Math.f90.
References pi_r4.
pure function lib_math::radiant_vectorial1d_r16 (real(r16p), dimension(:), intent(in) x_deg) private
Definition at line 2368 of file Lib_Math.f90.
References pi_r16.
pure function lib_math::radiant_vectorial1d_r8 (real(r8p), dimension(:), intent(in) x_deg) private
Definition at line 2385 of file Lib_Math.f90.
References pi_r8.
pure function lib_math::radiant_vectorial1d_r4 (real(r4p), dimension(:), intent(in) x_deg) private
Definition at line 2402 of file Lib_Math.f90.
References pi_r4.
pure function lib_math::radiant_vectorial2d_r16 (real(r16p), dimension(:,:), intent(in) x_deg) private
Definition at line 2419 of file Lib_Math.f90.
References pi_r16.
pure function lib_math::radiant_vectorial2d_r8 (real(r8p), dimension(:,:), intent(in) x_deg) private
Definition at line 2436 of file Lib_Math.f90.
References pi_r8.
pure function lib_math::radiant_vectorial2d_r4 (real(r4p), dimension(:,:), intent(in) x_deg) private
Definition at line 2453 of file Lib_Math.f90.
References pi_r4.
pure function lib_math::radiant_vectorial3d_r16 (real(r16p), dimension(:,:,:), intent(in) x_deg) private
Definition at line 2470 of file Lib_Math.f90.
References pi_r16.
pure function lib_math::radiant_vectorial3d_r8 (real(r8p), dimension(:,:,:), intent(in) x_deg) private
Definition at line 2487 of file Lib_Math.f90.
References pi_r8.
pure function lib_math::radiant_vectorial3d_r4 (real(r4p), dimension(:,:,:), intent(in) x_deg) private
Definition at line 2504 of file Lib_Math.f90.
References pi_r4.
elemental function lib_math::delta1_2o_r16 (real(r16p), intent(in) Sp1, real(r16p), intent(in) Sm1, real(r16p), intent(in) Ds) private
Definition at line 2522 of file Lib_Math.f90.
Referenced by abs_grad_r16().
elemental function lib_math::delta1_2o_r8 (real(r8p), intent(in) Sp1, real(r8p), intent(in) Sm1, real(r8p), intent(in) Ds) private
Definition at line 2541 of file Lib_Math.f90.
elemental function lib_math::delta1_2o_r4 (real(r4p), intent(in) Sp1, real(r4p), intent(in) Sm1, real(r4p), intent(in) Ds) private
Definition at line 2560 of file Lib_Math.f90.
elemental function lib_math::delta2_2o_r16 (real(r16p), intent(in) Sp1, real(r16p), intent(in) S, real(r16p), intent(in) Sm1, real(r16p), intent(in) Ds) private
Definition at line 2580 of file Lib_Math.f90.
Referenced by laplacian_r16().
elemental function lib_math::delta2_2o_r8 (real(r8p), intent(in) Sp1, real(r8p), intent(in) S, real(r8p), intent(in) Sm1, real(r8p), intent(in) Ds) private
Definition at line 2600 of file Lib_Math.f90.
elemental function lib_math::delta2_2o_r4 (real(r4p), intent(in) Sp1, real(r4p), intent(in) S, real(r4p), intent(in) Sm1, real(r4p), intent(in) Ds) private
Definition at line 2620 of file Lib_Math.f90.
elemental function lib_math::abs_grad_r16 (real(r16p), intent(in) Vip1, real(r16p), intent(in) Vim1, real(r16p), intent(in) Di, real(r16p), intent(in) Vjp1, real(r16p), intent(in) Vjm1, real(r16p), intent(in) Dj, real(r16p), intent(in) Vkp1, real(r16p), intent(in) Vkm1, real(r16p), intent(in) Dk) private
Definition at line 2641 of file Lib_Math.f90.
References delta1_2o_r16().
elemental function lib_math::abs_grad_r8 (real(r8p), intent(in) Vip1, real(r8p), intent(in) Vim1, real(r8p), intent(in) Di, real(r8p), intent(in) Vjp1, real(r8p), intent(in) Vjm1, real(r8p), intent(in) Dj, real(r8p), intent(in) Vkp1, real(r8p), intent(in) Vkm1, real(r8p), intent(in) Dk) private
Definition at line 2669 of file Lib_Math.f90.
References lib_math::delta1_2o::delta1_2o_r8().
elemental function lib_math::abs_grad_r4 (real(r4p), intent(in) Vip1, real(r4p), intent(in) Vim1, real(r4p), intent(in) Di, real(r4p), intent(in) Vjp1, real(r4p), intent(in) Vjm1, real(r4p), intent(in) Dj, real(r4p), intent(in) Vkp1, real(r4p), intent(in) Vkm1, real(r4p), intent(in) Dk) private
Definition at line 2697 of file Lib_Math.f90.
References lib_math::delta1_2o::delta1_2o_r4().
elemental function lib_math::laplacian_r16 (real(r16p), intent(in) Vip1, real(r16p), intent(in) Vi, real(r16p), intent(in) Vim1, real(r16p), intent(in) Di, real(r16p), intent(in) Vjp1, real(r16p), intent(in) Vj, real(r16p), intent(in) Vjm1, real(r16p), intent(in) Dj, real(r16p), intent(in) Vkp1, real(r16p), intent(in) Vk, real(r16p), intent(in) Vkm1, real(r16p), intent(in) Dk) private
Definition at line 2726 of file Lib_Math.f90.
References delta2_2o_r16().
elemental function lib_math::laplacian_r8 (real(r8p), intent(in) Vip1, real(r8p), intent(in) Vi, real(r8p), intent(in) Vim1, real(r8p), intent(in) Di, real(r8p), intent(in) Vjp1, real(r8p), intent(in) Vj, real(r8p), intent(in) Vjm1, real(r8p), intent(in) Dj, real(r8p), intent(in) Vkp1, real(r8p), intent(in) Vk, real(r8p), intent(in) Vkm1, real(r8p), intent(in) Dk) private
Definition at line 2757 of file Lib_Math.f90.
References lib_math::delta2_2o::delta2_2o_r8().
elemental function lib_math::laplacian_r4 (real(r4p), intent(in) Vip1, real(r4p), intent(in) Vi, real(r4p), intent(in) Vim1, real(r4p), intent(in) Di, real(r4p), intent(in) Vjp1, real(r4p), intent(in) Vj, real(r4p), intent(in) Vjm1, real(r4p), intent(in) Dj, real(r4p), intent(in) Vkp1, real(r4p), intent(in) Vk, real(r4p), intent(in) Vkm1, real(r4p), intent(in) Dk) private
Definition at line 2788 of file Lib_Math.f90.
References lib_math::delta2_2o::delta2_2o_r4().