OFF: Lib_Fluxes_Convective
Lib_Fluxes_Convective
Private Procedures
Functions/Subroutines
pure subroutine preconstruct_n (gc, N, Ns, cp0, cv0, F, C, PR)
Subroutine for reconstructing primitive variables along direction "NF".
pure function lp (Ns, primitive)
Function for computing left eigenvectors matrix (L) of the Jacobian fluxes matrix in primitive variables form.
pure function rp (Ns, primitive)
Function for computing right eigenvectors matrix (R) of the Jacobian fluxes matrix in primitive variables form.
pure subroutine positivity_preserving_limiter (o, vmean, vr)
Positivity preserving limiter.
Detailed Description
Function/Subroutine Documentation
pure subroutine fluxes_convective::preconstruct_n (integer(i1p), intent(in) gc, integer(i_p), intent(in) N, integer(i_p), intent(in) Ns, real(r_p), dimension(1:ns), intent(in) cp0, real(r_p), dimension(1:ns), intent(in) cv0, type(type_face), dimension (0-gc: n+gc), intent(in) F, type(type_cell), dimension (1-gc: n+gc), intent(in) C, real(r_p), dimension (1:ns+4, 1:2, 0: n+1), intent(out) PR) private
Subroutine for reconstructing primitive variables along direction "NF".
Parameters
[in] gc Number of ghost cells used.
[in] n Number of cells.
[in] ns Number of species.
[in] cp0 Initial specific heat cp.
[in] cv0 Initial specific heat cv.
[in] f Faces data [0-gc:N+gc].
[in] c Cells data [1-gc:N+gc].
[out] pr Reconstructed interface values 1D primitive variables.
Definition at line 167 of file Lib_Fluxes_Convective.f90.
References lib_vtk_io::f, lp(), rp(), and data_type_tensor::type_tensor::sq_norm().
pure function fluxes_convective::lp (integer(i_p), intent(in) Ns, real(r_p), dimension(1:ns+4), intent(in) primitive) private
Function for computing left eigenvectors matrix (L) of the Jacobian fluxes matrix in primitive variables form.
Note
This function consider only the normal direction: where P are the primitive variables and n is the normal direction. R is the matrix of the right eigenvectors, is the diagonal matrix of the eigenvalues and L is the matrix of the left eigenvectors.
Definition at line 263 of file Lib_Fluxes_Convective.f90.
References positivity_preserving_limiter(), and lib_weno::weno().
Referenced by preconstruct_n(), data_type_sl_list::put_link_r4(), data_type_sl_list::puth_link_i8(), and data_type_sl_list::puth_link_r4().
pure function fluxes_convective::rp (integer(i_p), intent(in) Ns, real(r_p), dimension(1:ns+4), intent(in) primitive) private
Function for computing right eigenvectors matrix (R) of the Jacobian fluxes matrix in primitive variables form.
Note
This function consider only the normal direction: where P are the primitive variables and n is the normal direction. R is the matrix of the right eigenvectors, is the diagonal matrix of the eigenvalues and L is the matrix of the left eigenvectors.
Definition at line 296 of file Lib_Fluxes_Convective.f90.
References lib_thermodynamic_laws_ideal::a(), lib_thermodynamic_laws_ideal::e(), lib_vtk_io::f, and lib_thermodynamic_laws_ideal::r().
Referenced by preconstruct_n().
pure subroutine fluxes_convective::positivity_preserving_limiter (integer(i_p), intent(in) o, real(r_p), intent(in) vmean, real(r_p), dimension(1:2), intent(inout) vr) private
Positivity preserving limiter.
Definition at line 326 of file Lib_Fluxes_Convective.f90.
Referenced by lp().