OFF: Lib_Fluxes_Diffusive
Lib_Fluxes_Diffusive
Modules Libraries
Data Types
module lib_fluxes_diffusive
This module contains the definition of procedures for computing diffusive fluxes (parabolic operator).
Detailed Description
Data Type Documentation
module lib_fluxes_diffusive
This module contains the definition of procedures for computing diffusive fluxes (parabolic operator).
This is a library module.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 24 of file Lib_Fluxes_Diffusive.f90.
Public Member Functions
subroutine, public fluxes_diffusive (block, i, j, k, dir, F)
Subroutine for computing interfaces diffusive fluxes (parabolic operator).
Member Function/Subroutine Documentation
subroutine, public lib_fluxes_diffusive::fluxes_diffusive (type(type_sblock), intent(in) block, integer(i_p), intent(in) i, integer(i_p), intent(in) j, integer(i_p), intent(in) k, character(1), intent(in) dir, type(type_conservative), intent(inout) F)
Subroutine for computing interfaces diffusive fluxes (parabolic operator).
Parameters
[in] block Block-level data.
[in] i Interface i indexe.
[in] j Interface j indexe.
[in] k Interface k indexe.
[in] dir Direction of fluxes ('i','j','k').
[in,out] f Diffusive fluxes at the interface.
Definition at line 42 of file Lib_Fluxes_Diffusive.f90.
References lib_vtk_io::f, fv_interface_metrics(), fv_interface_velocity(), and shear_stress().
Referenced by lib_fluidynamic::residuals().