OFF: Data_Type_Global
Data_Type_Global
Interfaces
Data Types
interface data_type_global::file_name
Generic procedure for building file names.
Detailed Description
Data Type Documentation
interface data_type_global::file_name
Generic procedure for building file names.
Three different types of output file name can be build by means of this generic interface:
File name of block-clean data; this type of file name is referred to those files containing block-level data; calling signature is of the type:
fname = file_name(basename,suffix,blk,grl)
File name of block-time_step data; this type of file name is referred to those files containing block-level data that varying with time; calling signature is of the type:
fname = file_name(basename,suffix,blk,grl,n)
File name of block-flip_flop data; this type of file name is referred to those files containing block-level data stored as backup flip/flop file; calling signature is of the type:
fname = file_name(basename,suffix,blk,grl,flip)
Definition at line 144 of file Data_Type_Global.f90.
Private Member Functions
character(len_trim(basename)+4+5+len_trim(suffix))
function block_file_name (basename, suffix, blk, grl)
Function for building block-clean file name.
character(len_trim(basename)+4+5+13+len_trim(suffix))
function block_step_file_name (basename, suffix, blk, grl, n)
Function for building block-time_step file name.
character(len_trim(basename)+3+4+5+len_trim(suffix))
function block_flip_file_name (basename, suffix, blk, grl, flip)
Function for building block-flip_flop file name.
Member Function/Subroutine Documentation
character(len_trim(basename)+4+5+len_trim(suffix)) function data_type_global::file_name::block_file_name (character(*), intent(in) basename, character(*), intent(in) suffix, integer(i_p), intent(in) blk, integer(i_p), intent(in) grl) private
Function for building block-clean file name.
Returns
filename character(len_trim(basename)+4+5+len_trim(suffix)) variable.
Parameters
[in] basename Base name of file name.
[in] suffix Suffix of file name.
[in] blk Block number.
[in] grl Grid refinement level.
Definition at line 153 of file Data_Type_Global.f90.
Referenced by data_type_global::type_global::alloc_fluid().
character(len_trim(basename)+4+5+13+len_trim(suffix)) function data_type_global::file_name::block_step_file_name (character(*), intent(in) basename, character(*), intent(in) suffix, integer(i_p), intent(in) blk, integer(i_p), intent(in) grl, integer(i8p), intent(in) n) private
Function for building block-time_step file name.
Returns
filename character(len_trim(basename)+4+5+13+len_trim(suffix)) variable.
Parameters
[in] basename Base name of file name.
[in] suffix Suffix of file name.
[in] blk Block number.
[in] grl Grid refinement level.
[in] n Time step number.
Definition at line 171 of file Data_Type_Global.f90.
Referenced by data_type_global::type_global::alloc_fluid().
character(len_trim(basename)+3+4+5+len_trim(suffix)) function data_type_global::file_name::block_flip_file_name (character(*), intent(in) basename, character(*), intent(in) suffix, integer(i_p), intent(in) blk, integer(i_p), intent(in) grl, integer(i1p), intent(in) flip) private
Function for building block-flip_flop file name.
Returns
filename character(len_trim(basename)+3+4+5+len_trim(suffix)) variable.
Parameters
[in] basename Base name of file name.
[in] suffix Suffix of file name.
[in] blk Block number.
[in] grl Grid refinement level.
[in] flip Flip-flop number.
Definition at line 190 of file Data_Type_Global.f90.
Referenced by data_type_global::type_global::alloc_fluid().