OFF: Lib_PostProcessing
Lib_PostProcessing
Private Procedures
subroutine lib_postprocessing::interpolate_primitive (block, P)
subroutine lib_postprocessing::compute_dimensions (block, ni1, ni2, nj1, nj2, nk1, nk2, ci1, ci2, cj1, cj2, ck1, ck2)
Detailed Description
Function/Subroutine Documentation
subroutine lib_postprocessing::interpolate_primitive (type(type_sblock), intent(inout) block, type(type_primitive), dimension(0:block%ni,0:block%nj,0:block%nk), intent(inout) P) private
Definition at line 71 of file Lib_PostProcessing.f90.
References lib_thermodynamic_laws_ideal::p().
Referenced by gnu_blk_data(), tec_blk_data(), and vtk_blk_data().
subroutine lib_postprocessing::compute_dimensions (type(type_sblock), intent(in) block, integer(i_p), intent(out) ni1, integer(i_p), intent(out) ni2, integer(i_p), intent(out) nj1, integer(i_p), intent(out) nj2, integer(i_p), intent(out) nk1, integer(i_p), intent(out) nk2, integer(i_p), intent(out) ci1, integer(i_p), intent(out) ci2, integer(i_p), intent(out) cj1, integer(i_p), intent(out) cj2, integer(i_p), intent(out) ck1, integer(i_p), intent(out) ck2) private
Definition at line 110 of file Lib_PostProcessing.f90.
References lib_thermodynamic_laws_ideal::p().
Referenced by gnu_blk_data(), tec_blk_data(), and vtk_blk_data().