OFF: Lib_WENO
Lib_WENO
Public Procedures
subroutine, public lib_weno::weno_init (block, S)
Subroutine for initialization of WENO coefficients.
pure subroutine, public lib_weno::noweno_central (S, V, VR)
Subroutine for computing central difference reconstruction of order instead of WENO one.
pure subroutine, public lib_weno::weno_optimal (S, V, VR)
Subroutine for computing WENO reconstruction with optimal weights (without smoothness indicators computations) of order.
pure subroutine, public lib_weno::weno (S, V, VR)
Subroutine for computing WENO reconstruction of order.
Detailed Description
Function/Subroutine Documentation
subroutine, public lib_weno::weno_init (type(type_sblock), dimension(1:), intent(in) block, integer(i1p), intent(in) S)
Subroutine for initialization of WENO coefficients.
Parameters
[in] block Block-level data.
[in] s Number of stencils used.
Definition at line 61 of file Lib_WENO.f90.
References ir_precision::fi1p, ir_precision::fi_p, ir_precision::fr_p, get_min_sstep(), ir_precision::i_p, ir_precision::maxr_p, lib_weno::weno_a, lib_weno::weno_c, lib_weno::weno_d, and lib_weno::weno_p.
Referenced by off(), and off_init().
pure subroutine, public lib_weno::noweno_central (integer(i1p), intent(in) S, real(r_p), dimension (1:,0:), intent(in) V, real(r_p), dimension(1:), intent(out) VR)
Subroutine for computing central difference reconstruction of order instead of WENO one.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the arrays V and VR are declared as assumed-shape with only the lower bound defined. Their extensions are: V [1:2,0:2*S], VR [1:2].
Parameters
[in] s Number of stencils used.
[in] v Variable to be reconstructed. [1:2,0:2*S].
[out] vr Left and right (1,2) interface value of reconstructed V [1:2 ].
Definition at line 308 of file Lib_WENO.f90.
References lib_vtk_io::f, and lib_weno::weno_c.
pure subroutine, public lib_weno::weno_optimal (integer(i1p), intent(in) S, real(r_p), dimension (1:,1-s:), intent(in) V, real(r_p), dimension(1:), intent(out) VR)
Subroutine for computing WENO reconstruction with optimal weights (without smoothness indicators computations) of order.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the arrays V and VR are declared as assumed-shape with only the lower bound defined. Their extensions are: V [1:2,1-S:-1+S], VR [1:2].
Parameters
[in] s Number of stencils used.
[in] v Variable to be reconstructed [1:2,1-S:-1+S].
[out] vr Left and right (1,2) interface value of reconstructed V [1:2 ].
Definition at line 333 of file Lib_WENO.f90.
References lib_weno::weno_a, lib_weno::weno_convolution(), and lib_weno::weno_polynomials().
pure subroutine, public lib_weno::weno (integer(i1p), intent(in) S, real(r_p), dimension (1:,1_i1p-s:), intent(in) V, real(r_p), dimension(1:), intent(out) VR)
Subroutine for computing WENO reconstruction of order.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the arrays V and VR are declared as assumed-shape with only the lower bound defined. Their extensions are: V [1:2,1-S:-1+S], VR [1:2].
Parameters
[in] s Number of stencils used.
[in] v Variable to be reconstructed [1:2,1-S:-1+S].
[out] vr Left and right (1,2) interface value of reconstructed V [1:2 ].
Definition at line 357 of file Lib_WENO.f90.
References lib_weno::weno_convolution(), lib_weno::weno_polynomials(), and lib_weno::weno_weights().
Referenced by lp().