OFF: Lib_WENO
Lib_WENO
Private Procedures
pure subroutine lib_weno::weno_polynomials (S, V, VP)
Subroutine for computing WENO polynomials.
pure subroutine lib_weno::weno_weights (S, V, w)
Subroutine for computing WENO weights of the polynomial reconstructions.
pure subroutine lib_weno::weno_convolution (S, VP, w, VR)
Function for computing the WENO convolution of the polynomial reconstructions.
recursive pure function lib_weno::udiff (p, v)
Detailed Description
Function/Subroutine Documentation
pure subroutine lib_weno::weno_polynomials (integer(i1p), intent(in) S, real(r_p), dimension (1:,1-s:), intent(in) V, real(r_p), dimension(1:,0:), intent(out) VP) private
Subroutine for computing WENO polynomials.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the arrays V and VP are declared as assumed-shape with only the lower bound defined. Their extensions are: V [1:2,1-S:-1+S], VP [1:2,0:S-1].
Parameters
[in] s Number of stencils used.
[in] v Variable to be reconstructed [1:2,1-S:-1+S].
[out] vp Polynomial reconstructions [1:2, 0:S-1 ].
Definition at line 384 of file Lib_WENO.f90.
References lib_vtk_io::f, and lib_weno::weno_p.
Referenced by lib_weno::weno(), and lib_weno::weno_optimal().
pure subroutine lib_weno::weno_weights (integer(i1p), intent(in) S, real(r_p), dimension (1:,1-s:), intent(in) V, real(r_p), dimension (1:,0:), intent(out) w) private
Subroutine for computing WENO weights of the polynomial reconstructions.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the arrays V and w are declared as assumed-shape with only the lower bound defined. Their extensions are: V [1:2,1-S:-1+S], w [1:2,0:S-1].
Parameters
[in] s Number of stencils used.
[in] v Variable to be reconstructed [1:2,1-S:-1+S].
[out] w Weights of the stencils [1:2, 0:S-1 ].
Definition at line 410 of file Lib_WENO.f90.
References lib_thermodynamic_laws_ideal::a(), lib_vtk_io::f, lib_thermodynamic_laws_ideal::p(), lib_weno::udiff(), lib_weno::weno_a, and lib_weno::weno_d.
Referenced by lib_weno::weno().
pure subroutine lib_weno::weno_convolution (integer(i1p), intent(in) S, real(r_p), dimension(1:,0:), intent(in) VP, real(r_p), dimension (1:,0:), intent(in) w, real(r_p), dimension(1:), intent(out) VR) private
Function for computing the WENO convolution of the polynomial reconstructions.
Note
For avoiding the creation of temporary arrays (improving the efficiency) the arrays VP w and VR are declared as assumed-shape with only the lower bound defined. Their extentions are: VP [1:2,0:S-1], w [1:2,0:S-1], V [1:2].
Parameters
[in] s Number of stencils used.
[in] vp Polynomial reconstructions [1:2,0:S-1].
[in] w Weights of the stencils [1:2,0:S-1].
[out] vr Left and right (1,2) interface value of reconstructed V [1:2 ].
Definition at line 467 of file Lib_WENO.f90.
References lib_thermodynamic_laws_ideal::a(), lib_vtk_io::f, lib_thermodynamic_laws_ideal::p(), lib_weno::udiff(), and lib_weno::weno_a.
Referenced by lib_weno::weno(), and lib_weno::weno_optimal().
recursive pure function lib_weno::udiff (integer(i_p), intent(in) p, real(r_p), dimension(1:p+1), intent(in) v) private
Definition at line 489 of file Lib_WENO.f90.
Referenced by lib_weno::weno_convolution(), and lib_weno::weno_weights().