OFF: Data_Type_BC
Data_Type_BC
Public Procedures
integer(i_p) function, public data_type_bc::write_bc (scalar, array1D, array2D, array3D, format, unit)
Function for writing Type_BC data.
integer(i_p) function, public data_type_bc::read_bc (scalar, array1D, array2D, array3D, format, unit)
Function for reading Type_BC data.
Detailed Description
Function/Subroutine Documentation
integer(i_p) function, public data_type_bc::write_bc (type(type_bc), intent(in), optional scalar, type(type_bc), dimension(:), intent(in), optional array1D, type(type_bc), dimension(:,:), intent(in), optional array2D, type(type_bc), dimension(:,:,:), intent(in), optional array3D, character(*), intent(in), optional format, integer(i4p), intent(in) unit)
Function for writing Type_BC data.
The vector data could be scalar, one, two and three dimensional array. The format could be ascii or binary.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in] scalar Scalar bc data.
[in] array1d One dimensional array bc data.
[in] array2d Two dimensional array bc data.
[in] array3d Three dimensional array bc data.
[in] format Format specifier.
[in] unit Logic unit.
Definition at line 121 of file Data_Type_BC.f90.
Referenced by load_blocks(), load_icemcfd(), and data_type_sblock::save_bbc().
integer(i_p) function, public data_type_bc::read_bc (type(type_bc), intent(inout), optional scalar, type(type_bc), dimension(:), intent(inout), optional array1D, type(type_bc), dimension(:,:), intent(inout), optional array2D, type(type_bc), dimension(:,:,:), intent(inout), optional array3D, character(*), intent(in), optional format, integer(i4p), intent(in) unit)
Function for reading Type_BC data.
The vector data could be scalar, one, two and three dimensional array. The format could be ascii or binary.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in,out] scalar Scalar bc data.
[in,out] array1d One dimensional array bc data.
[in,out] array2d Two dimensional array bc data.
[in,out] array3d Three dimensional array bc data.
[in] format Format specifier.
[in] unit Logic unit.
Definition at line 284 of file Data_Type_BC.f90.
Referenced by data_type_sblock::load_bbc().