OFF: Data_Type_Conservative
Data_Type_Conservative
Public Procedures
integer(i_p) function, public data_type_conservative::write_conservative (scalar, array1D, array2D, array3D, format, unit)
Function for writing Type_Conservative data.
integer(i_p) function, public data_type_conservative::read_conservative (scalar, array1D, array2D, array3D, format, unit)
Function for reading Type_Conservative data.
pure function, public data_type_conservative::array2consf (array)
Function for converting array to derived type Type_Conservative.
Detailed Description
Function/Subroutine Documentation
integer(i_p) function, public data_type_conservative::write_conservative (type(type_conservative), intent(in), optional scalar, type(type_conservative), dimension(:), intent(in), optional array1D, type(type_conservative), dimension(:,:), intent(in), optional array2D, type(type_conservative), dimension(:,:,:), intent(in), optional array3D, character(*), intent(in), optional format, integer(i4p), intent(in) unit)
Function for writing Type_Conservative data.
The vector data could be scalar, one, two and three dimensional array. The format could be ascii or binary.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in] scalar Scalar conservative data.
[in] array1d One dimensional array conservative data.
[in] array2d Two dimensional array conservative data.
[in] array3d Three dimensional array conservative data.
[in] format Format specifier.
[in] unit Logic unit.
Definition at line 245 of file Data_Type_Conservative.f90.
References data_type_vector::write_vector().
integer(i_p) function, public data_type_conservative::read_conservative (type(type_conservative), intent(inout), optional scalar, type(type_conservative), dimension(:), intent(inout), optional array1D, type(type_conservative), dimension(:,:), intent(inout), optional array2D, type(type_conservative), dimension(:,:,:), intent(inout), optional array3D, character(*), intent(in), optional format, integer(i4p), intent(in) unit)
Function for reading Type_Conservative data.
The vector data could be scalar, one, two and three dimensional array. The format could be ascii or binary.
Returns
err integer(I_P) variable for error trapping.
Parameters
[in,out] scalar Scalar conservative data.
[in,out] array1d One dimensional array conservative data.
[in,out] array2d Two dimensional array conservative data.
[in,out] array3d Three dimensional array conservative data.
[in] format Format specifier.
[in] unit Logic unit.
Definition at line 360 of file Data_Type_Conservative.f90.
References data_type_vector::read_vector().
pure function, public data_type_conservative::array2consf (real(r8p), dimension(:), intent(in) array)
Function for converting array to derived type Type_Conservative.
Parameters
[in] array Conservative data in the form of array.
Definition at line 473 of file Data_Type_Conservative.f90.
References data_type_sl_list::type_sl_link::array().