OFF: Lib_Fluxes_Diffusive.f90 File Reference
Lib_Fluxes_Diffusive.f90 File Reference
Data Types
module lib_fluxes_diffusive
This module contains the definition of procedures for computing diffusive fluxes (parabolic operator).
Functions/Subroutines
subroutine fv_interface_metrics (block)
Subroutine for computing the metrics (normals and interfaces area) of finite volume centered at interface i,j,k.
subroutine fv_interface_velocity (block)
Subroutine for computing the velocity vector at interfaces of finite volume centered at interface i,j,k.
real(r_p) function dudi_fv (u, nsi, v)
Function for computing first partial derivative by means of Finite Volumes approach (Green's theorem).
subroutine shear_stress ()
Subroutine for computing the shear stress tensor at center of a finite volume.
Function/Subroutine Documentation
subroutine fluxes_diffusive::fv_interface_metrics (type(type_sblock), intent(in) block) private
Subroutine for computing the metrics (normals and interfaces area) of finite volume centered at interface i,j,k.
Such a 'shifted' finite volume is used in computing partial derivative by means of finite volume approach (using Green's theorem).
Note
The computed metrics is stored as normals to the 6 hexahedron faces of the shifted finite volume. Each normal has module equal to its face area.
Returns
NFS(1:6) Type_Vector array.
Parameters
[in] block Block-level data.
Definition at line 88 of file Lib_Fluxes_Diffusive.f90.
Referenced by lib_fluxes_diffusive::fluxes_diffusive().
subroutine fluxes_diffusive::fv_interface_velocity (type(type_sblock), intent(in) block) private
Subroutine for computing the velocity vector at interfaces of finite volume centered at interface i,j,k.
Returns
vel(1:6) Type_Vector array.
Parameters
[in] block Block-level data.
Definition at line 124 of file Lib_Fluxes_Diffusive.f90.
Referenced by lib_fluxes_diffusive::fluxes_diffusive().
real(r_p) function fluxes_diffusive::dudi_fv (real(r_p), dimension(1:6), intent(in) u, real(r_p), dimension(1:6), intent(in) nsi, real(r_p), intent(in) v) private
Function for computing first partial derivative by means of Finite Volumes approach (Green's theorem).
Using the Green's theorem the first partial derivative of in direction could be written as being the value of finite volume, the outward unit normal of face which area is .
Note
It is assumed that the finite volume is discretized by means of a hexahedron.
Returns
fpd real(R_P) variable.
Parameters
[in] u Values of variable to be differentiated at each of 6 interfaces surrounding finite volume.
[in] nsi Area of 6 interfaces surrounding finite volume multiplied by normals projected along 'i'.
[in] v Value of finite volume.
Definition at line 172 of file Lib_Fluxes_Diffusive.f90.
Referenced by shear_stress().
subroutine fluxes_diffusive::shear_stress () private
Subroutine for computing the shear stress tensor at center of a finite volume.
Definition at line 188 of file Lib_Fluxes_Diffusive.f90.
References dudi_fv().
Referenced by lib_fluxes_diffusive::fluxes_diffusive().