OFF: Data_Type_Tensor
Data_Type_Tensor
Private Procedures
elemental subroutine data_type_tensor::set (ten, x, y, z)
Subroutine for setting components of Type_Tensor variable.
elemental function data_type_tensor::sq_norm_ten (ten)
Function for computing the square of the norm of a tensor.
elemental function data_type_tensor::norml2_ten (ten)
Function for computing the norm L2 of a tensor.
elemental subroutine data_type_tensor::normalize_self (ten)
Subroutine for normalizing a tensor.
elemental function data_type_tensor::normalize_ten (ten)
Function for normalizing a tensor.
elemental subroutine data_type_tensor::transpose_self (ten)
Subroutine for transposing a tensor.
elemental function data_type_tensor::transpose_ten (ten)
Function for transposing a tensor.
elemental subroutine data_type_tensor::invert_self (ten)
Subroutine for computing the inverse of a tensor.
elemental subroutine data_type_tensor::rotox (ten, ang)
Subroutine for computing the rotation tensor along x.
elemental subroutine data_type_tensor::rotoy (ten, ang)
Subroutine for computing the rotation tensor along y.
elemental subroutine data_type_tensor::rotoz (ten, ang)
Subroutine for computing the rotation tensor along z.
elemental subroutine data_type_tensor::rotou (ten, u, ang)
Subroutine for computing the rotation tensor along a generic vector axis.
elemental subroutine data_type_tensor::assign_vec (ten, vec)
elemental subroutine data_type_tensor::assign_scalr8p (ten, scal)
elemental subroutine data_type_tensor::assign_scalr4p (ten, scal)
elemental subroutine data_type_tensor::assign_scali8p (ten, scal)
elemental subroutine data_type_tensor::assign_scali4p (ten, scal)
elemental subroutine data_type_tensor::assign_scali2p (ten, scal)
elemental subroutine data_type_tensor::assign_scali1p (ten, scal)
elemental function data_type_tensor::ten_mul_ten (ten1, ten2)
elemental function data_type_tensor::scalr8p_mul_ten (scal, ten)
elemental function data_type_tensor::ten_mul_scalr8p (ten, scal)
elemental function data_type_tensor::scalr4p_mul_ten (scal, ten)
elemental function data_type_tensor::ten_mul_scalr4p (ten, scal)
elemental function data_type_tensor::scali8p_mul_ten (scal, ten)
elemental function data_type_tensor::ten_mul_scali8p (ten, scal)
elemental function data_type_tensor::scali4p_mul_ten (scal, ten)
elemental function data_type_tensor::ten_mul_scali4p (ten, scal)
elemental function data_type_tensor::scali2p_mul_ten (scal, ten)
elemental function data_type_tensor::ten_mul_scali2p (ten, scal)
elemental function data_type_tensor::scali1p_mul_ten (scal, ten)
elemental function data_type_tensor::ten_mul_scali1p (ten, scal)
elemental function data_type_tensor::ten_div_ten (ten1, ten2)
elemental function data_type_tensor::ten_div_scalr8p (ten, scal)
elemental function data_type_tensor::ten_div_scalr4p (ten, scal)
elemental function data_type_tensor::ten_div_scali8p (ten, scal)
elemental function data_type_tensor::ten_div_scali4p (ten, scal)
elemental function data_type_tensor::ten_div_scali2p (ten, scal)
elemental function data_type_tensor::ten_div_scali1p (ten, scal)
elemental function data_type_tensor::positive_ten (ten)
elemental function data_type_tensor::ten_sum_ten (ten1, ten2)
elemental function data_type_tensor::scalr8p_sum_ten (scal, ten)
elemental function data_type_tensor::ten_sum_scalr8p (ten, scal)
elemental function data_type_tensor::scalr4p_sum_ten (scal, ten)
elemental function data_type_tensor::ten_sum_scalr4p (ten, scal)
elemental function data_type_tensor::scali8p_sum_ten (scal, ten)
elemental function data_type_tensor::ten_sum_scali8p (ten, scal)
elemental function data_type_tensor::scali4p_sum_ten (scal, ten)
elemental function data_type_tensor::ten_sum_scali4p (ten, scal)
elemental function data_type_tensor::scali2p_sum_ten (scal, ten)
elemental function data_type_tensor::ten_sum_scali2p (ten, scal)
elemental function data_type_tensor::scali1p_sum_ten (scal, ten)
elemental function data_type_tensor::ten_sum_scali1p (ten, scal)
elemental function data_type_tensor::negative_ten (ten)
elemental function data_type_tensor::ten_sub_ten (ten1, ten2)
elemental function data_type_tensor::scalr8p_sub_ten (scal, ten)
elemental function data_type_tensor::ten_sub_scalr8p (ten, scal)
elemental function data_type_tensor::scalr4p_sub_ten (scal, ten)
elemental function data_type_tensor::ten_sub_scalr4p (ten, scal)
elemental function data_type_tensor::scali8p_sub_ten (scal, ten)
elemental function data_type_tensor::ten_sub_scali8p (ten, scal)
elemental function data_type_tensor::scali4p_sub_ten (scal, ten)
elemental function data_type_tensor::ten_sub_scali4p (ten, scal)
elemental function data_type_tensor::scali2p_sub_ten (scal, ten)
elemental function data_type_tensor::ten_sub_scali2p (ten, scal)
elemental function data_type_tensor::scali1p_sub_ten (scal, ten)
elemental function data_type_tensor::ten_sub_scali1p (ten, scal)
elemental function data_type_tensor::ten_dot_vec (ten, vec)
elemental function data_type_tensor::vec_dot_ten (vec, ten)
elemental function data_type_tensor::ddotproduct (ten1, ten2)
elemental function data_type_tensor::diadicproduct (vec1, vec2)
Detailed Description
Function/Subroutine Documentation
elemental subroutine data_type_tensor::set (class(type_tensor), intent(inout) ten, type(type_vector), intent(in), optional x, type(type_vector), intent(in), optional y, type(type_vector), intent(in), optional z) private
Subroutine for setting components of Type_Tensor variable.
Parameters
[in,out] ten Tensor.
[in] x Cartesian vector component in x direction.
[in] y Cartesian vector component in y direction.
[in] z Cartesian vector component in z direction.
Definition at line 481 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::sq_norm_ten (class(type_tensor), intent(in) ten) private
Function for computing the square of the norm of a tensor.
The square norm if defined as .
Returns
sq square norm
Definition at line 501 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::norml2_ten (class(type_tensor), intent(in) ten) private
Function for computing the norm L2 of a tensor.
The norm L2 if defined as .
Returns
norm norm L2
Definition at line 517 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::normalize_self (class(type_tensor), intent(inout) ten) private
Subroutine for normalizing a tensor.
The normalization is made by means of norm L2. If the norm L2 of the tensor is less than the parameter smallR8P the normalization value is set to normL2(ten)+smallR8P.
Definition at line 533 of file Data_Type_Tensor.f90.
References data_type_tensor::norml2::norml2_ten(), and ir_precision::smallr8p.
Referenced by data_type_vector::type_vector::set().
elemental function data_type_tensor::normalize_ten (type(type_tensor), intent(in) ten) private
Function for normalizing a tensor.
The normalization is made by means of norm L2. If the norm L2 of the tensor is less than the parameter smallR8P the normalization value is set to normL2(ten)+smallR8P.
Returns
norm normalized tensor
Definition at line 556 of file Data_Type_Tensor.f90.
References data_type_tensor::norml2::norml2_ten(), and ir_precision::smallr8p.
elemental subroutine data_type_tensor::transpose_self (class(type_tensor), intent(inout) ten) private
Subroutine for transposing a tensor.
The transpositions is done as following:
      |x%x x%y x%z|           |x%x y%x z%x|
ten = |y%x y%y y%z| => tran = |x%y y%y z%y|
      |z%x z%y z%z|           |x%z y%z z%z|
Parameters
[in,out] ten Tensor to be transposed.
Definition at line 583 of file Data_Type_Tensor.f90.
References data_type_vector::ex, data_type_vector::ey, data_type_vector::ez, and data_type_tensor::operator(.dot.)::ten_dot_vec().
Referenced by data_type_tensor::type_tensor::set().
elemental function data_type_tensor::transpose_ten (type(type_tensor), intent(in) ten) private
Function for transposing a tensor.
The transpositions is done as following:
      |x%x x%y x%z|           |x%x y%x z%x|
ten = |y%x y%y y%z| => tran = |x%y y%y z%y|
      |z%x z%y z%z|           |x%z y%z z%z|
Parameters
[in] ten Tensor to be transposed.
Definition at line 616 of file Data_Type_Tensor.f90.
References data_type_vector::ex, data_type_vector::ey, and data_type_vector::ez.
elemental subroutine data_type_tensor::invert_self (class(type_tensor), intent(inout) ten) private
Subroutine for computing the inverse of a tensor.
If the tensor is not invertible a null tensor is returned.
Returns
inv type(Type_Tensor) variable
Note
The inverse tensor is computed according the following equation:
where det(T) is the determinant computed by means of the function determinant.
Parameters
[in,out] ten Tensor to be inverted.
Definition at line 640 of file Data_Type_Tensor.f90.
References data_type_tensor::type_tensor::determinant(), data_type_vector::ex, data_type_vector::ey, and data_type_vector::ez.
Referenced by data_type_tensor::type_tensor::norml2().
elemental subroutine data_type_tensor::rotox (class(type_tensor), intent(inout) ten, real(r8p), intent(in) ang) private
Subroutine for computing the rotation tensor along x.
Parameters
[in,out] ten Rotating tensor.
[in] ang Angle (radians) of rotation.
Definition at line 668 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::rotoy (class(type_tensor), intent(inout) ten, real(r8p), intent(in) ang) private
Subroutine for computing the rotation tensor along y.
Parameters
[in,out] ten Rotating tensor.
[in] ang Angle (radians) of rotation.
Definition at line 684 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::rotoz (class(type_tensor), intent(inout) ten, real(r8p), intent(in) ang) private
Subroutine for computing the rotation tensor along z.
Parameters
[in,out] ten Rotating tensor.
[in] ang Angle (radians) of rotation.
Definition at line 700 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::rotou (class(type_tensor), intent(inout) ten, type(type_vector), intent(in) u, real(r8p), intent(in) ang) private
Subroutine for computing the rotation tensor along a generic vector axis.
Parameters
[in,out] ten Rotating tensor.
[in] u Vector axis.
[in] ang Angle (radians) of rotation.
Definition at line 716 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assign_vec (type(type_tensor), intent(inout) ten, type(type_vector), intent(in) vec) private
Definition at line 742 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assign_scalr8p (type(type_tensor), intent(inout) ten, real(r8p), intent(in) scal) private
Definition at line 763 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assign_scalr4p (type(type_tensor), intent(inout) ten, real(r4p), intent(in) scal) private
Definition at line 782 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assign_scali8p (type(type_tensor), intent(inout) ten, integer(i8p), intent(in) scal) private
Definition at line 801 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assign_scali4p (type(type_tensor), intent(inout) ten, integer(i4p), intent(in) scal) private
Definition at line 820 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assign_scali2p (type(type_tensor), intent(inout) ten, integer(i2p), intent(in) scal) private
Definition at line 839 of file Data_Type_Tensor.f90.
elemental subroutine data_type_tensor::assign_scali1p (type(type_tensor), intent(inout) ten, integer(i1p), intent(in) scal) private
Definition at line 858 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_mul_ten (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 878 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scalr8p_mul_ten (real(r8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 900 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_mul_scalr8p (type(type_tensor), intent(in) ten, real(r8p), intent(in) scal) private
Definition at line 920 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scalr4p_mul_ten (real(r4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 940 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_mul_scalr4p (type(type_tensor), intent(in) ten, real(r4p), intent(in) scal) private
Definition at line 960 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali8p_mul_ten (integer(i8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 980 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_mul_scali8p (type(type_tensor), intent(in) ten, integer(i8p), intent(in) scal) private
Definition at line 1000 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali4p_mul_ten (integer(i4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1020 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_mul_scali4p (type(type_tensor), intent(in) ten, integer(i4p), intent(in) scal) private
Definition at line 1040 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali2p_mul_ten (integer(i2p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1060 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_mul_scali2p (type(type_tensor), intent(in) ten, integer(i2p), intent(in) scal) private
Definition at line 1080 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali1p_mul_ten (integer(i1p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1100 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_mul_scali1p (type(type_tensor), intent(in) ten, integer(i1p), intent(in) scal) private
Definition at line 1120 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_div_ten (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 1141 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_div_scalr8p (type(type_tensor), intent(in) ten, real(r8p), intent(in) scal) private
Definition at line 1163 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_div_scalr4p (type(type_tensor), intent(in) ten, real(r4p), intent(in) scal) private
Definition at line 1183 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_div_scali8p (type(type_tensor), intent(in) ten, integer(i8p), intent(in) scal) private
Definition at line 1203 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_div_scali4p (type(type_tensor), intent(in) ten, integer(i4p), intent(in) scal) private
Definition at line 1223 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_div_scali2p (type(type_tensor), intent(in) ten, integer(i2p), intent(in) scal) private
Definition at line 1243 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_div_scali1p (type(type_tensor), intent(in) ten, integer(i1p), intent(in) scal) private
Definition at line 1263 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::positive_ten (type(type_tensor), intent(in) ten) private
Definition at line 1284 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sum_ten (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 1303 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scalr8p_sum_ten (real(r8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1325 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sum_scalr8p (type(type_tensor), intent(in) ten, real(r8p), intent(in) scal) private
Definition at line 1345 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scalr4p_sum_ten (real(r4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1365 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sum_scalr4p (type(type_tensor), intent(in) ten, real(r4p), intent(in) scal) private
Definition at line 1385 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali8p_sum_ten (integer(i8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1405 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sum_scali8p (type(type_tensor), intent(in) ten, integer(i8p), intent(in) scal) private
Definition at line 1425 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali4p_sum_ten (integer(i4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1445 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sum_scali4p (type(type_tensor), intent(in) ten, integer(i4p), intent(in) scal) private
Definition at line 1465 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali2p_sum_ten (integer(i2p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1485 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sum_scali2p (type(type_tensor), intent(in) ten, integer(i2p), intent(in) scal) private
Definition at line 1505 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali1p_sum_ten (integer(i1p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1525 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sum_scali1p (type(type_tensor), intent(in) ten, integer(i1p), intent(in) scal) private
Definition at line 1545 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::negative_ten (type(type_tensor), intent(in) ten) private
Definition at line 1566 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sub_ten (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 1585 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scalr8p_sub_ten (real(r8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1607 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sub_scalr8p (type(type_tensor), intent(in) ten, real(r8p), intent(in) scal) private
Definition at line 1627 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scalr4p_sub_ten (real(r4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1647 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sub_scalr4p (type(type_tensor), intent(in) ten, real(r4p), intent(in) scal) private
Definition at line 1667 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali8p_sub_ten (integer(i8p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1687 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sub_scali8p (type(type_tensor), intent(in) ten, integer(i8p), intent(in) scal) private
Definition at line 1707 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali4p_sub_ten (integer(i4p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1727 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sub_scali4p (type(type_tensor), intent(in) ten, integer(i4p), intent(in) scal) private
Definition at line 1747 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali2p_sub_ten (integer(i2p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1767 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sub_scali2p (type(type_tensor), intent(in) ten, integer(i2p), intent(in) scal) private
Definition at line 1787 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::scali1p_sub_ten (integer(i1p), intent(in) scal, type(type_tensor), intent(in) ten) private
Definition at line 1807 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_sub_scali1p (type(type_tensor), intent(in) ten, integer(i1p), intent(in) scal) private
Definition at line 1827 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ten_dot_vec (type(type_tensor), intent(in) ten, type(type_vector), intent(in) vec) private
Definition at line 1848 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::vec_dot_ten (type(type_vector), intent(in) vec, type(type_tensor), intent(in) ten) private
Definition at line 1866 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::ddotproduct (type(type_tensor), intent(in) ten1, type(type_tensor), intent(in) ten2) private
Definition at line 1885 of file Data_Type_Tensor.f90.
elemental function data_type_tensor::diadicproduct (type(type_vector), intent(in) vec1, type(type_vector), intent(in) vec2) private
Definition at line 1904 of file Data_Type_Tensor.f90.
References data_type_vector::ex, data_type_vector::ey, and data_type_vector::ez.