OFF: Data_Type_BC
Data_Type_BC
Global Variables and Parameters
character(3), parameter, public data_type_bc::bc_nan_str = 'NAN'
Definition of non-assigned boundary condition parameter string.
integer(i1p), parameter, public data_type_bc::bc_nan =-1_I1P
Definition of non-assigned boundary condition parameter id.
character(3), parameter, public data_type_bc::bc_ref_str = 'REF'
Definition of reflective boundary condition parameter string.
integer(i1p), parameter, public data_type_bc::bc_ref = 1_I1P
Definition of reflective boundary condition parameter id.
character(3), parameter, public data_type_bc::bc_ext_str = 'EXT'
Definition of extrapolation boundary condition parameter string.
integer(i1p), parameter, public data_type_bc::bc_ext = 2_I1P
Definition of extrapolation boundary condition parameter id.
character(3), parameter, public data_type_bc::bc_per_str = 'PER'
Definition of periodic boundary condition parameter string.
integer(i1p), parameter, public data_type_bc::bc_per = 3_I1P
Definition of periodic boundary condition parameter id.
character(3), parameter, public data_type_bc::bc_adj_str = 'ADJ'
Definition of adjacent boundary condition parameter string.
integer(i1p), parameter, public data_type_bc::bc_adj = 4_I1P
Definition of adjacent boundary condition parameter id.
character(3), parameter, public data_type_bc::bc_in1_str = 'IN1'
Definition of inflow 1 boundary condition parameter string.
integer(i1p), parameter, public data_type_bc::bc_in1 = 5_I1P
Definition of inflow 1 boundary condition parameter id.
character(3), parameter, public data_type_bc::bc_in2_str = 'IN2'
Definition of inflow 2 boundary condition parameter string.
integer(i1p), parameter, public data_type_bc::bc_in2 = 6_I1P
Definition of inflow 2 boundary condition parameter id.
integer(i1p), parameter, public data_type_bc::nbc = 7_I1P
Number of possible boundary conditions.
character(3), dimension(1:nbc),
parameter, public data_type_bc::bc_list_str = (/ bc_nan_str, bc_ref_str, bc_ext_str, bc_per_str, bc_adj_str, bc_in1_str, bc_in2_str /)
Boundary conditions string list.
integer(i1p), dimension(1:nbc),
parameter, public data_type_bc::bc_list = (/ bc_nan, bc_ref, bc_ext, bc_per, bc_adj, bc_in1, bc_in2 /)
Boundary conditions list.
Detailed Description
Variable Documentation
character(3), parameter, public data_type_bc::bc_nan_str = 'NAN'
Definition of non-assigned boundary condition parameter string.
Definition at line 50 of file Data_Type_BC.f90.
integer(i1p), parameter, public data_type_bc::bc_nan =-1_I1P
Definition of non-assigned boundary condition parameter id.
Definition at line 51 of file Data_Type_BC.f90.
character(3), parameter, public data_type_bc::bc_ref_str = 'REF'
Definition of reflective boundary condition parameter string.
Definition at line 52 of file Data_Type_BC.f90.
integer(i1p), parameter, public data_type_bc::bc_ref = 1_I1P
Definition of reflective boundary condition parameter id.
Definition at line 53 of file Data_Type_BC.f90.
Referenced by data_type_sblock::metrics_correction(), lib_fluidynamic::set_bc(), and set_ext_l().
character(3), parameter, public data_type_bc::bc_ext_str = 'EXT'
Definition of extrapolation boundary condition parameter string.
Definition at line 54 of file Data_Type_BC.f90.
integer(i1p), parameter, public data_type_bc::bc_ext = 2_I1P
Definition of extrapolation boundary condition parameter id.
Definition at line 55 of file Data_Type_BC.f90.
Referenced by data_type_sblock::metrics_correction(), lib_fluidynamic::set_bc(), and set_ext_l().
character(3), parameter, public data_type_bc::bc_per_str = 'PER'
Definition of periodic boundary condition parameter string.
Definition at line 56 of file Data_Type_BC.f90.
integer(i1p), parameter, public data_type_bc::bc_per = 3_I1P
Definition of periodic boundary condition parameter id.
Definition at line 57 of file Data_Type_BC.f90.
Referenced by lib_fluidynamic::set_bc(), and set_ext_l().
character(3), parameter, public data_type_bc::bc_adj_str = 'ADJ'
Definition of adjacent boundary condition parameter string.
Definition at line 58 of file Data_Type_BC.f90.
integer(i1p), parameter, public data_type_bc::bc_adj = 4_I1P
Definition of adjacent boundary condition parameter id.
Definition at line 59 of file Data_Type_BC.f90.
Referenced by lib_parallel::compute_ncr(), load_blocks(), load_icemcfd(), scan_block(), and set_ext_l().
character(3), parameter, public data_type_bc::bc_in1_str = 'IN1'
Definition of inflow 1 boundary condition parameter string.
Definition at line 60 of file Data_Type_BC.f90.
integer(i1p), parameter, public data_type_bc::bc_in1 = 5_I1P
Definition of inflow 1 boundary condition parameter id.
Definition at line 61 of file Data_Type_BC.f90.
Referenced by load_blocks(), load_icemcfd(), data_type_sblock::metrics_correction(), off_init(), and set_ext_l().
character(3), parameter, public data_type_bc::bc_in2_str = 'IN2'
Definition of inflow 2 boundary condition parameter string.
Definition at line 62 of file Data_Type_BC.f90.
integer(i1p), parameter, public data_type_bc::bc_in2 = 6_I1P
Definition of inflow 2 boundary condition parameter id.
Definition at line 63 of file Data_Type_BC.f90.
Referenced by load_blocks(), load_icemcfd(), and data_type_sblock::metrics_correction().
integer(i1p), parameter, public data_type_bc::nbc = 7_I1P
Number of possible boundary conditions.
Definition at line 64 of file Data_Type_BC.f90.
Referenced by load_icemcfd().
character(3), dimension(1:nbc), parameter, public data_type_bc::bc_list_str = (/ bc_nan_str, bc_ref_str, bc_ext_str, bc_per_str, bc_adj_str, bc_in1_str, bc_in2_str /)
Boundary conditions string list.
Definition at line 65 of file Data_Type_BC.f90.
Referenced by load_icemcfd().
integer(i1p), dimension (1:nbc), parameter, public data_type_bc::bc_list = (/ bc_nan, bc_ref, bc_ext, bc_per, bc_adj, bc_in1, bc_in2 /)
Boundary conditions list.
Definition at line 74 of file Data_Type_BC.f90.
Referenced by load_icemcfd().