OFF: Lib_Multigrid Module Reference
Lib_Multigrid Module Reference
The module Lib_Multigrid contains the definition of multigrid functions and subroutines.
Public Member Functions
subroutine, public alloc_multigrid (Nc, bb1, bb2)
subroutine, public restrict (myrank, l, Nb, gco, gc, Ni_f, Nj_f, Nk_f, Ni_c, Nj_c, Nk_c, bb_f, bb_c, bb_Fi_c, bb_Fj_c, bb_Fk_c, Np, Nc, Ns, NFi_c, NFj_c, NFk_c, BCi_c, BCj_c, BCk_c, Nin1, in1, Nin2, bb_in2, in2, Si_c, Sj_c, Sk_c, V_f, V_c, U_f, R_f, t, U_c, UR, TE)
subroutine, public correct (myrank, l, Nb, gco, gc, Ni_f, Nj_f, Nk_f, Ni_c, Nj_c, Nk_c, bb_f, bb_c, bb_Fi_f, bb_Fj_f, bb_Fk_f, Np, Nc, Ns, NFi_f, NFj_f, NFk_f, BCi_f, BCj_f, BCk_f, Nin1, in1, Nin2, bb_in2, in2, Si_f, Sj_f, Sk_f, V_f, UR, U_c, t, U_f, P_f)
Public Attributes
real(R_P), allocatable, public UR
Restriction of conservative variables [1:Nc,bb1:bb2].
real(R_P), allocatable, public TE
Truncation error of conservative variables [1:Nc,bb1:bb2].
Detailed Description
The module Lib_Multigrid contains the definition of multigrid functions and subroutines.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 7 of file Lib_Multigrid.f90.
Member Function/Subroutine Documentation
subroutine, public Lib_Multigrid::alloc_multigrid (integer(I_P), intent(in) Nc, integer(I_P), intent(in) bb1, integer(I_P), intent(in) bb2)
Definition at line 34 of file Lib_Multigrid.f90.
subroutine, public Lib_Multigrid::restrict (integer(I_P), intent(in) myrank, integer(I_P), intent(in) l, integer(I_P), intent(in) Nb, integer(I_P), intent(in) gco, integer(I_P), dimension(1:6,1:nb), intent(in) gc, integer(I_P), dimension(1:nb), intent(in) Ni_f, integer(I_P), dimension(1:nb), intent(in) Nj_f, integer(I_P), dimension(1:nb), intent(in) Nk_f, integer(I_P), dimension(1:nb), intent(in) Ni_c, integer(I_P), dimension(1:nb), intent(in) Nj_c, integer(I_P), dimension(1:nb), intent(in) Nk_c, integer(I_P), dimension (1:2,1:nb), intent(in) bb_f, integer(I_P), dimension (1:2,1:nb), intent(in) bb_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fi_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fj_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fk_c, integer(I_P), intent(in) Np, integer(I_P), intent(in) Nc, integer(I_P), intent(in) Ns, type(Type_Vector), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) NFi_c, type(Type_Vector), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) NFj_c, type(Type_Vector), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) NFk_c, type(Type_BC), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) BCi_c, type(Type_BC), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) BCj_c, type(Type_BC), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) BCk_c, integer(I_P), intent(in) Nin1, real(R_P), dimension(1:np,1:nin1), intent(in) in1, integer(I_P), intent(in) Nin2, integer(I_P), dimension(1:2,1:nin2), intent(in) bb_in2, real(R_P), dimension(1:np+1,bb_in2(1,1):bb_in2(2,nin2)), intent(in) in2, real(R_P), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) Si_c, real(R_P), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) Sj_c, real(R_P), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) Sk_c, real(R_P), dimension (bb_f (1,1):bb_f (2,nb)), intent(in) V_f, real(R_P), dimension (bb_c (1,1):bb_c (2,nb)), intent(in) V_c, real(R_P), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(in) U_f, real(R_P), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(in) R_f, real(R_P), intent(in) t, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) U_c, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) UR, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) TE)
Definition at line 52 of file Lib_Multigrid.f90.
References fine2coarse_R(), fine2coarse_U(), and te_estimation().
subroutine, public Lib_Multigrid::correct (integer(I_P), intent(in) myrank, integer(I_P), intent(in) l, integer(I_P), intent(in) Nb, integer(I_P), intent(in) gco, integer(I_P), dimension(1:6,1:nb), intent(in) gc, integer(I_P), dimension(1:nb), intent(in) Ni_f, integer(I_P), dimension(1:nb), intent(in) Nj_f, integer(I_P), dimension(1:nb), intent(in) Nk_f, integer(I_P), dimension(1:nb), intent(in) Ni_c, integer(I_P), dimension(1:nb), intent(in) Nj_c, integer(I_P), dimension(1:nb), intent(in) Nk_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_f, integer(I_P), dimension(1:2,1:nb), intent(in) bb_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fi_f, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fj_f, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fk_f, integer(I_P), intent(in) Np, integer(I_P), intent(in) Nc, integer(I_P), intent(in) Ns, type(Type_Vector), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) NFi_f, type(Type_Vector), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) NFj_f, type(Type_Vector), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) NFk_f, type(Type_BC), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) BCi_f, type(Type_BC), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) BCj_f, type(Type_BC), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) BCk_f, integer(I_P), intent(in) Nin1, real(R_P), dimension(1:np,1:nin1), intent(in) in1, integer(I_P), intent(in) Nin2, integer(I_P), dimension(1:2,1:nin2), intent(in) bb_in2, real(R_P), dimension(1:np+1,bb_in2(1,1):bb_in2(2,nin2)), intent(in) in2, real(R_P), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) Si_f, real(R_P), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) Sj_f, real(R_P), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) Sk_f, real(R_P), dimension (bb_f (1,1):bb_f (2,nb)), intent(in) V_f, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(in) UR, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(in) U_c, real(R_P), intent(in) t, real(R_P), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(inout) U_f, real(R_P), dimension (1:np,bb_f (1,1):bb_f (2,nb)), intent(out) P_f)
Definition at line 322 of file Lib_Multigrid.f90.
References coarse2fine_U(), get_correction(), and update_fine().
Member Data Documentation
real(R_P), allocatable, public Lib_Multigrid::UR
Restriction of conservative variables [1:Nc,bb1:bb2].
Definition at line 30 of file Lib_Multigrid.f90.
real(R_P), allocatable, public Lib_Multigrid::TE
Truncation error of conservative variables [1:Nc,bb1:bb2].
Definition at line 31 of file Lib_Multigrid.f90.
The documentation for this module was generated from the following file:
Lib_Multigrid.f90