OFF: Data_Type_SBlock
Data_Type_SBlock
Private Procedures
subroutine data_type_sblock::alloc_block (block)
Subroutine for allocating dynamic data of Type_SBlock variables.
subroutine data_type_sblock::free_block (block)
Subroutine for freeing dynamic data of Type_SBlock variables.
integer(i_p) function data_type_sblock::save_bmesh (block, ascii, filename)
Function for saving block mesh file.
integer(i_p) function data_type_sblock::load_bmesh_dims (block, ascii, filename)
Function for loading the mesh data dimensions of block from the mesh file "filename".
integer(i_p) function data_type_sblock::load_bmesh (block, ascii, filename)
Function for loading block mesh file.
integer(i_p) function data_type_sblock::print_info_bmesh (block, blk, grl)
Function for printing to standard output info of block mesh data.
integer(i_p) function data_type_sblock::save_bbc (block, filename)
Function for saving block boundary conditions file.
integer(i_p) function data_type_sblock::load_bbc (block, filename)
Function for loading block boundary conditions file.
integer(i_p) function data_type_sblock::save_bfluid (block, filename)
Function for saving fluid dynamic file.
integer(i_p) function data_type_sblock::load_bfluid (block, filename)
Function for loading fluid dynamic file.
integer(i_p) function data_type_sblock::print_info_bfluid (block, blk, grl)
Function for printing to standard output info of block fluid data.
subroutine data_type_sblock::metrics (block)
Subroutine for computing the metrics of structured block.
subroutine data_type_sblock::metrics_correction (block)
Subroutine for correcting the metrics of natural (and negative volume) boundary conditions cells of structured block.
subroutine data_type_sblock::node2center (block)
Subroutine for computing cell center coordinates from cell nodes ones.
Detailed Description
Function/Subroutine Documentation
subroutine data_type_sblock::alloc_block (class(type_sblock), intent(inout) block)
Subroutine for allocating dynamic data of Type_SBlock variables.
Parameters
[in,out] block Block data.
Definition at line 77 of file Data_Type_SBlock.f90.
subroutine data_type_sblock::free_block (class(type_sblock), intent(inout) block) private
Subroutine for freeing dynamic data of Type_SBlock variables.
Parameters
[in,out] block Block data.
Definition at line 107 of file Data_Type_SBlock.f90.
integer(i_p) function data_type_sblock::save_bmesh (class(type_sblock), intent(in) block, logical, intent(in), optional ascii, character(*), intent(in) filename) private
Function for saving block mesh file.
Returns
err integer(I_P) variable.
Parameters
[in] block Block level data.
[in] ascii Flag for ascii file.
[in] filename Name of file where mesh variables are saved.
Definition at line 125 of file Data_Type_SBlock.f90.
References lib_vtk_io::ascii, ir_precision::fi1p, ir_precision::fi_p, lib_io_misc::get_unit(), and data_type_vector::write_vector().
integer(i_p) function data_type_sblock::load_bmesh_dims (class(type_sblock), intent(inout) block, logical, intent(in), optional ascii, character(*), intent(in) filename) private
Function for loading the mesh data dimensions of block from the mesh file "filename".
Returns
err integer(I_P) variable.
Parameters
[in,out] block Block level data.
[in] ascii Flag for ascii file.
[in] filename Name of file where mesh variables are saved.
Definition at line 157 of file Data_Type_SBlock.f90.
References lib_vtk_io::ascii, lib_io_misc::file_not_found(), and lib_io_misc::get_unit().
integer(i_p) function data_type_sblock::load_bmesh (class(type_sblock), intent(inout) block, logical, intent(in), optional ascii, character(*), intent(in) filename) private
Function for loading block mesh file.
Returns
err integer(I_P) variable.
Parameters
[in,out] block Block level data.
[in] ascii Flag for ascii file.
[in] filename Name of file where mesh variables are saved.
Definition at line 188 of file Data_Type_SBlock.f90.
References lib_vtk_io::ascii, lib_io_misc::file_not_found(), lib_io_misc::get_unit(), and data_type_vector::read_vector().
Referenced by data_type_sblock::type_sblock::alloc().
integer(i_p) function data_type_sblock::print_info_bmesh (class(type_sblock), intent(in) block, integer(i_p), intent(in) blk, integer(i_p), intent(in) grl) private
Function for printing to standard output info of block mesh data.
Returns
err integer(I_P) variable.
Parameters
[in] block Block level data.
[in] blk Actual block number.
[in] grl Actual grid level number.
Definition at line 223 of file Data_Type_SBlock.f90.
Referenced by data_type_sblock::type_sblock::free().
integer(i_p) function data_type_sblock::save_bbc (class(type_sblock), intent(in) block, character(*), intent(in) filename) private
Function for saving block boundary conditions file.
Returns
err integer(I_P) variable.
Parameters
[in] block Block level data.
[in] filename Name of file where mesh variables are saved.
Definition at line 297 of file Data_Type_SBlock.f90.
References lib_io_misc::get_unit(), and data_type_bc::write_bc().
Referenced by data_type_sblock::type_sblock::save_mesh().
integer(i_p) function data_type_sblock::load_bbc (class(type_sblock), intent(inout) block, character(*), intent(in) filename) private
Function for loading block boundary conditions file.
Returns
err integer(I_P) variable.
Parameters
[in,out] block Block level data.
[in] filename Name of file where mesh variables are saved.
Definition at line 318 of file Data_Type_SBlock.f90.
References lib_io_misc::file_not_found(), lib_io_misc::get_unit(), and data_type_bc::read_bc().
Referenced by data_type_sblock::type_sblock::load_mesh_dims().
integer(i_p) function data_type_sblock::save_bfluid (class(type_sblock), intent(in) block, character(*), intent(in) filename) private
Function for saving fluid dynamic file.
Returns
err integer(I_P) variable.
Parameters
[in] block Block level data.
[in] filename Name of file where mesh variables are saved.
Definition at line 342 of file Data_Type_SBlock.f90.
References lib_io_misc::get_unit(), and data_type_primitive::write_primitive().
Referenced by data_type_sblock::type_sblock::load_mesh().
integer(i_p) function data_type_sblock::load_bfluid (class(type_sblock), intent(inout) block, character(*), intent(in) filename) private
Function for loading fluid dynamic file.
Returns
err integer(I_P) variable.
Parameters
[in,out] block Block level data.
[in] filename Name of file where mesh variables are saved.
Definition at line 366 of file Data_Type_SBlock.f90.
References lib_io_misc::file_not_found(), lib_io_misc::get_unit(), and data_type_primitive::read_primitive().
Referenced by data_type_sblock::type_sblock::print_info_mesh().
integer(i_p) function data_type_sblock::print_info_bfluid (class(type_sblock), intent(in) block, integer(i_p), intent(in) blk, integer(i_p), intent(in) grl) private
Function for printing to standard output info of block fluid data.
Returns
err integer(I_P) variable.
Parameters
[in] block Block level data.
[in] blk Actual block number.
[in] grl Actual grid level number.
Definition at line 393 of file Data_Type_SBlock.f90.
Referenced by data_type_sblock::type_sblock::save_bc().
subroutine data_type_sblock::metrics (class(type_sblock), intent(inout) block) private
Subroutine for computing the metrics of structured block.
Parameters
[in,out] block Block-level data.
Definition at line 463 of file Data_Type_SBlock.f90.
References data_type_vector::face_normal4(), data_type_tensor::type_tensor::normalize(), and data_type_tensor::type_tensor::norml2().
subroutine data_type_sblock::metrics_correction (class(type_sblock), intent(inout) block) private
Subroutine for correcting the metrics of natural (and negative volume) boundary conditions cells of structured block.
Parameters
[in,out] block Block-level data.
Definition at line 621 of file Data_Type_SBlock.f90.
References data_type_bc::bc_ext, data_type_bc::bc_in1, data_type_bc::bc_in2, data_type_bc::bc_ref, lib_multigrid::correct(), data_type_tensor::type_tensor::normalize(), and data_type_tensor::type_tensor::norml2().
subroutine data_type_sblock::node2center (class(type_sblock), intent(inout) block) private
Subroutine for computing cell center coordinates from cell nodes ones.
Parameters
[in,out] block Block-level data.
Definition at line 892 of file Data_Type_SBlock.f90.