OFF: OFF
OFF
Private Procedures
subroutine off_init ()
Subroutine for initializing the simulation according to the input options.
integer(i_p) function load_off_option_file (filename, global)
Function for loading global file options.
Detailed Description
Function/Subroutine Documentation
subroutine off::off_init ()
Subroutine for initializing the simulation according to the input options.
Definition at line 227 of file OFF.f90.
References lib_io_misc::basename(), data_type_bc::bc_in1, lib_vtk_io::binary, lib_parallel::blockmap, lib_io_misc::copy_file(), data_type_time::crono(), ir_precision::fi8p, ir_precision::fr_p, data_type_time::get_date_string(), lib_io_misc::get_unit(), lib_parallel::init_sendrecv(), lib_profiling::instant0, ir_precision::ir_print(), load_off_option_file(), lib_io_misc::make_dir(), lib_parallel::nproc, lib_parallel::nthreads, lib_fluidynamic::primitive2conservative(), lib_parallel::procmap_load(), lib_profiling::profile(), lib_runge_kutta::rk_init(), lib_io_misc::string_os_sep(), and lib_weno::weno_init().
Referenced by off().
integer(i_p) function off::load_off_option_file (character(*), intent(in) filename, type(type_global), intent(inout) global)
Function for loading global file options.
Parameters
[in] filename Name of file where option variables are saved.
[in,out] global Global-level data.
Definition at line 562 of file OFF.f90.
References lib_io_misc::file_not_found(), lib_io_misc::get_unit(), lib_io_misc::os, lib_io_misc::string_os_sep(), and lib_io_misc::upper_case().
Referenced by off_init().