OFF: IR_Precision
IR_Precision
Public Procedures
Portable kind-parameters module.
Functions/Subroutines
subroutine, public ir_precision::ir_init ()
Subroutine for initilizing module's variables that are not initialized into the definition specification.
subroutine, public ir_precision::ir_print ()
Subroutine for printing to the standard output the kind definition of reals and integers and the utility variables.
pure function ir_precision::is_little_endian ()
Function for checking if the type of the bit ordering of the running architecture is little endian.
subroutine, public ir_precision::check_endian ()
Subroutine for checking the type of bit ordering (big or little endian) of the running architecture; the result is stored into the "endian" global variable.
Detailed Description
Portable kind-parameters module.
Function/Subroutine Documentation
pure function ir_precision::is_little_endian () private
Function for checking if the type of the bit ordering of the running architecture is little endian.
Definition at line 290 of file IR_Precision.f90.
Referenced by ir_precision::check_endian().
subroutine, public ir_precision::ir_init ()
Subroutine for initilizing module's variables that are not initialized into the definition specification.
Definition at line 1015 of file IR_Precision.f90.
References ir_precision::check_endian(), and ir_precision::ir_initialized.
Referenced by ir_precision::ir_print(), pog(), lib_vtk_io::pvtk_ini_xml(), lib_vtk_io::vtk_ini(), lib_vtk_io::vtk_ini_xml(), and lib_vtk_io::vtm_ini_xml().
subroutine, public ir_precision::ir_print ()
Subroutine for printing to the standard output the kind definition of reals and integers and the utility variables.
Definition at line 1035 of file IR_Precision.f90.
References ir_precision::ir_init().
Referenced by off_init().
subroutine, public ir_precision::check_endian ()
Subroutine for checking the type of bit ordering (big or little endian) of the running architecture; the result is stored into the "endian" global variable.
Returns
endian
Definition at line 307 of file IR_Precision.f90.
References ir_precision::endianb, and ir_precision::is_little_endian().
Referenced by ir_precision::ir_init().