OFF: OFF.f90 File Reference
OFF.f90 File Reference
Functions/Subroutines
program OFF
OFF is an Open source Finite volume Fluid dynamics code.
subroutine off_init ()
Subroutine for initializing the simulation according to the input options.
integer(I_P) function load_option_file (myrank, filename, global)
Function for loading global file options.
Function/Subroutine Documentation
program OFF ()
OFF is an Open source Finite volume Fluid dynamics code.
It is written in in standard (compliant) Fortran 2003 with highly modularity as design target.
The aim of OFF is to solve, numerically, the Navier-Stokes equations of fluid dynamics by means of Finite Volume technique. The main features of OFF code are the following:
Finite Volume, Godunov-like scheme based on Euler conservation Laws written in fully conservative formulation:
the extension to viscous Navier-Stokes equations is under developing;
Underling Riemann Problem solver for convective fluxes:
Approximate Riemann solver based on (local) Lax-Friedrichs (known also as Rusanov) algorithm;
Approximate Riemann solver based on Primitive Variables Linearization algorithm;
Approximate Riemann solver based on Two Rarefactions algorithm;
Approximate Riemann solver based on Two Shocks algorithm;
Approximate Riemann solver based on Adaptive (non iterative) PVL-TR-TS algorithm;
Approximate Riemann solver based on Adaptive (non iterative) LF-TR algorithm;
Approximate Riemann solver based on HLLC algorithm;
Approximate Riemann solver based on Roe linearization.
Exact Riemann solver based on iterative solution of u-function;
Multi-Species fluids models:
Partial Densities species conservation (Standard Thermodynamic Model);
New multi-dimensional conservation models of Favini, B. et al (under developing);
Multi-Phases fluids models:
Fully-coupled Lagrangian particles transport model (under developing);
Space numerical integration models:
order piece-wise constant reconstruction;
order TVD linear-wise reconstruction;
orders WENO non-linear reconstruction;
Time approximation models:
order forward Euler integration;
orders Strong-Stability-Preserving explicit Runge-Kutta integration;
Local pseudo-time convergence acceleration for steady simulations;
Multi-grid time convergence acceleration:
Multi-grid model has been already developed, but it is affected by some not still recognized bugs. Testing and bugs fixing are in progress.
Underling numerical grid models:
3D, general curvilinear, body-fitted, structured multi-blocks mesh;
Adaptive Mesh Refinement, AMR model (under developing);
Blocks overlapping, overset (Chimera) model (to be developed in future);
Computational parallelism ability:
Domain decomposition by means of Message Passing Interface (MPI) paradigm providing the ability to use distributed-memory cluster facilities;
Fine, local parallelism by means of OpenMP paradigm providing the ability to use shared-memory cluster facilities;
Fine, local parallelism by means of GPU programming (e.g. CUDA framework) providing the ability to use GPUs cluster facilities (to be developed in future).
Author:
Stefano Zaghi
Version:
0.0.5
Date:
2012-04-24
Copyright:
GNU Public License version 3.
Bug:
Multi-grid Models:
Multi-grid time convergence acceleration has been developed, but it is affected by some bugs that blow up steady simulations.
Todo:
NavierStokesEq: Extension to viscous Navier-Stokes equations
MultiSpeciesModel: Introducing new multi-dimensional conservation models of Favini, B. et al
MultiPhaseModel: Introducing fully-coupled Lagrangian particles transport model
AMR: Introducing AMR (Adaptive Mesh Refinement) model
Chimera: Introducing blocks overlapping, overset (Chimera) model
GPU: Introducing fine, local parallelism by means of GPU programming (e.g. CUDA framework)
DocImprove: Improve the documentation
DocMakeFile: Create the documentation of makefile
Definition at line 62 of file OFF.f90.
References off_init().
subroutine OFF::off_init ()
Subroutine for initializing the simulation according to the input options.
Definition at line 172 of file OFF.f90.
References load_option_file().
Referenced by OFF().
integer(I_P) function OFF::load_option_file (integer(I_P), intent(in) myrank, character(*), intent(in) filename, type(Type_Global), intent(inout) global)
Function for loading global file options.
Parameters:
[in] myrank Actual rank process.
[in] filename Name of file where option variables are saved.
[in,out] global Global-level data.
Definition at line 464 of file OFF.f90.