OFF: Lib_Profiling
Lib_Profiling
Private Variables and Parameters
integer(i8p) lib_profiling::instant0 = 0_I8P
The Crono starting instant used for profing the code.
integer(i_p) lib_profiling::npp = 0_I_P
Number of parts of the code profiled.
integer(i8p), dimension(:,:),
allocatable lib_profiling::partial
Partial times used for profing the code [1:2,1:Npp].
integer(i_p), dimension(:),
allocatable lib_profiling::unitprofile
Logic units for profiling files [1:Npp].
integer(i_p), dimension(:),
allocatable lib_profiling::tictoc
Counter of files access [1:Npp].
integer(i_p) lib_profiling::pp = 0_I_P
Index of current profiled part of the code.
Detailed Description
Variable Documentation
integer(i8p) lib_profiling::instant0 = 0_I8P private
The Crono starting instant used for profing the code.
Definition at line 42 of file Lib_Profiling.f90.
Referenced by data_type_time::crono(), off_init(), lib_profiling::profile(), and lib_fluidynamic::solve_grl().
integer(i_p) lib_profiling::npp = 0_I_P private
Number of parts of the code profiled.
Definition at line 43 of file Lib_Profiling.f90.
Referenced by lib_profiling::profile().
integer(i8p), dimension(:,:), allocatable lib_profiling::partial private
Partial times used for profing the code [1:2,1:Npp].
Definition at line 45 of file Lib_Profiling.f90.
Referenced by lib_profiling::profile().
integer(i_p), dimension(:), allocatable lib_profiling::unitprofile private
Logic units for profiling files [1:Npp].
Definition at line 46 of file Lib_Profiling.f90.
integer(i_p), dimension(:), allocatable lib_profiling::tictoc private
Counter of files access [1:Npp].
Definition at line 47 of file Lib_Profiling.f90.
integer(i_p) lib_profiling::pp = 0_I_P private
Index of current profiled part of the code.
Definition at line 48 of file Lib_Profiling.f90.