OFF: Modules Libraries
Modules Libraries
List of modules containing libraries of procedures.
Data Types
module Lib_Fluidynamic
This module contains the definition of fluid dynamic procedures.
module Lib_IO_Misc
This module contains miscellanea procedures for input/output and string operations.
module Lib_Math
This module contains mathematical procedures.
module Lib_Mesh
This module contains mesh procedures.
module Lib_Multigrid
This module contains the definition of multigrid procedures.
module Lib_Parallel
This module contains the definition of procedures for send/receive data among processes for parallel (MPI) operations.
module Lib_PostProcessing
This module contains the definition of procedures and variables useful for post-process the OFF data.
module Lib_Riemann
This module contains procedures for computing the solution of a Riemann Problem.
module Lib_Thermodynamic_Laws_Ideal
This module contains the definition of Thermodynamic Laws for ideal calorically perfect gas.
module Lib_VTK_IO
This is a library of functions for Input and Output pure Fortran data in VTK format.
module Lib_WENO
This module contains the definition of procedures for computing WENO reconstruction with a user-defined order.
Detailed Description
List of modules containing libraries of procedures.
Data Type Documentation
module Lib_Fluidynamic
This module contains the definition of fluid dynamic procedures.
This is a library module.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 9 of file Lib_Fluidynamic.f90.
Public Member Functions
subroutine, public primitive2conservative (block)
subroutine, public conservative2primitive (global, block)
subroutine, public residuals (s1, global, block)
subroutine, public boundary_conditions (myrank, l, global, block)
subroutine, public solve_grl (myrank, l, global, block)
subroutine, public rk_init (S)
Private Member Functions
pure subroutine prim2cons (prim, cons)
pure subroutine cons2prim (cp0, cv0, cons, prim)
subroutine compute_time (global, block, Dtmin)
subroutine rk_stages_sum (s1, global, block)
subroutine rk_time_integration (global, block, RU)
Private Attributes
real(R_P), dimension(:),
allocatable rk_c1
c1 coefficients of Runge-Kutta's integration [1:rk_ord]
real(R_P), dimension(:,:),
allocatable rk_c2
c2 coefficients of Runge-Kutta's integration [1:rk_ord,1:rk_ord]
integer(I1P) flip = 0_I_P
Flip-Flop flag for restart solution file.
Member Function/Subroutine Documentation
pure subroutine Lib_Fluidynamic::prim2cons (type(Type_Primitive), intent(in) prim, type(Type_Conservative), intent(inout) cons) [private]
Definition at line 71 of file Lib_Fluidynamic.f90.
pure subroutine Lib_Fluidynamic::cons2prim (real(R_P), dimension(:), intent(in) cp0, real(R_P), dimension(:), intent(in) cv0, type(Type_Conservative), intent(in) cons, type(Type_Primitive), intent(inout) prim) [private]
Definition at line 90 of file Lib_Fluidynamic.f90.
subroutine, public Lib_Fluidynamic::primitive2conservative (type(Type_Block), intent(inout) block)
Definition at line 115 of file Lib_Fluidynamic.f90.
subroutine, public Lib_Fluidynamic::conservative2primitive (type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block)
Definition at line 144 of file Lib_Fluidynamic.f90.
subroutine Lib_Fluidynamic::compute_time (type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block, real(R_P), intent(out) Dtmin) [private]
Definition at line 173 of file Lib_Fluidynamic.f90.
subroutine, public Lib_Fluidynamic::residuals (integer(I_P), intent(in) s1, type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block)
Definition at line 303 of file Lib_Fluidynamic.f90.
References fluxes().
subroutine, public Lib_Fluidynamic::boundary_conditions (integer(I_P), intent(in) myrank, integer(I_P), intent(in) l, type(Type_Global), intent(in) global, type(Type_Block), dimension(1:global%mesh%nb), intent(inout) block)
Definition at line 747 of file Lib_Fluidynamic.f90.
References positivity_preserving_limiter().
subroutine, public Lib_Fluidynamic::solve_grl (integer(I_P), intent(in) myrank, integer(I_P), intent(in) l, type(Type_Global), intent(inout) global, type(Type_Block), dimension(1:global%mesh%nb), intent(inout) block)
Definition at line 1166 of file Lib_Fluidynamic.f90.
subroutine, public Lib_Fluidynamic::rk_init (integer(I1P), intent(in) S)
Definition at line 1337 of file Lib_Fluidynamic.f90.
subroutine Lib_Fluidynamic::rk_stages_sum (integer(I_P), intent(in) s1, type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block) [private]
Definition at line 1406 of file Lib_Fluidynamic.f90.
subroutine Lib_Fluidynamic::rk_time_integration (type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block, real(R_P), dimension(1:global%fluid%nc), intent(out) RU) [private]
Definition at line 1443 of file Lib_Fluidynamic.f90.
Member Data Documentation
real(R_P), dimension(:), allocatable Lib_Fluidynamic::rk_c1 [private]
c1 coefficients of Runge-Kutta's integration [1:rk_ord]
Definition at line 65 of file Lib_Fluidynamic.f90.
real(R_P), dimension(:,:), allocatable Lib_Fluidynamic::rk_c2 [private]
c2 coefficients of Runge-Kutta's integration [1:rk_ord,1:rk_ord]
Definition at line 66 of file Lib_Fluidynamic.f90.
integer(I1P) Lib_Fluidynamic::flip = 0_I_P [private]
Flip-Flop flag for restart solution file.
Definition at line 68 of file Lib_Fluidynamic.f90.
module Lib_IO_Misc
This module contains miscellanea procedures for input/output and string operations.
This is a library module.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 14 of file Lib_IO_Misc.f90.
Public Member Functions
integer function, public Get_Unit ()
The GetUnit function is used for getting a free logic unit.
integer(I4P) function, public make_dir (myrank, directory)
integer(I4P) function, public remove_file (filename)
integer(I4P) function, public copy_file (source_file, target_file)
integer(I4P) function, public lc_file (filename, fileform)
character(len=len(filename))
function, public basedir (filename)
character(len=len(filename))
function, public basename (filename)
character(len=len(string))
function, public Upper_Case (string)
The Upper_Case function converts the lower case characters of a string to upper case one.
character(len=len(string))
function, public Lower_Case (string)
character(len=len(string))
function, public string_OS_sep (string)
subroutine, public File_Not_Found (myrank, filename, cpn)
Public Attributes
type(Type_OS), public OS
OS definition (see definition).
Member Function/Subroutine Documentation
integer function, public Lib_IO_Misc::Get_Unit ()
The GetUnit function is used for getting a free logic unit.
Returns:
Free_Unit
Definition at line 46 of file Lib_IO_Misc.f90.
integer(I4P) function, public Lib_IO_Misc::make_dir (integer(I_P), intent(in), optional myrank, character(*), intent(in) directory)
Definition at line 74 of file Lib_IO_Misc.f90.
integer(I4P) function, public Lib_IO_Misc::remove_file (character(*), intent(in) filename)
Definition at line 110 of file Lib_IO_Misc.f90.
integer(I4P) function, public Lib_IO_Misc::copy_file (character(*), intent(in) source_file, character(*), intent(in) target_file)
Definition at line 139 of file Lib_IO_Misc.f90.
integer(I4P) function, public Lib_IO_Misc::lc_file (character(*), intent(in) filename, character(*), intent(in) fileform)
Definition at line 174 of file Lib_IO_Misc.f90.
character(len=len(filename)) function, public Lib_IO_Misc::basedir (character(len=*), intent(in) filename)
Definition at line 219 of file Lib_IO_Misc.f90.
character(len=len(filename)) function, public Lib_IO_Misc::basename (character(len=*), intent(in) filename)
Definition at line 236 of file Lib_IO_Misc.f90.
character(len=len(string)) function, public Lib_IO_Misc::Upper_Case (character(len=len(string)), intent(in) string)
The Upper_Case function converts the lower case characters of a string to upper case one.
Returns:
Upper_Case
Parameters:
[in] string String to be converted.
Definition at line 255 of file Lib_IO_Misc.f90.
character(len=len(string)) function, public Lib_IO_Misc::Lower_Case (character(len=*), intent(in) string)
Definition at line 275 of file Lib_IO_Misc.f90.
character(len=len(string)) function, public Lib_IO_Misc::string_OS_sep (character(len=*), intent(in) string)
Definition at line 305 of file Lib_IO_Misc.f90.
subroutine, public Lib_IO_Misc::File_Not_Found (integer(I_P), intent(in) myrank, character(*), intent(in) filename, character(*), intent(in) cpn)
Definition at line 341 of file Lib_IO_Misc.f90.
module Lib_Math
This module contains mathematical procedures.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 13 of file Lib_Math.f90.
Public Member Functions
pure function, public stretchinglside (Ns, s_uniform, stretch)
pure function, public stretchingrside (Ns, s_uniform, stretch)
pure function, public stretching2side (s_sym_in, Ns, s_uniform, Ds_L, Ds_R)
Public Attributes
real(R8P), parameter, public pi_R8 = 2._R8P* asin(1._R8P)
with R8P precision.
real(R4P), parameter, public pi_R4 = 2._R4P* asin(1._R4P)
with R4P precision.
real(R_P), parameter, public pi = 2._R_P* asin(1._R_P)
with R_P precision.
Private Member Functions
pure function average_Vectorial1D_R8 (x)
pure function average_Vectorial1D_R4 (x)
pure function average_Vectorial2D_R8 (x)
pure function average_Vectorial2D_R4 (x)
pure function average_Vectorial3D_R8 (x)
pure function average_Vectorial3D_R4 (x)
elemental function digit_I8 (n)
elemental function digit_I4 (n)
elemental function digit_I2 (n)
elemental function digit_I1 (n)
elemental function interpolate1_R8 (x1, x2, V1, V2, x)
elemental function interpolate1_R4 (x1, x2, V1, V2, x)
elemental function interpolate2_R8 (x1, y1, x2, y2, V11, V12, V21, V22, x, y)
elemental function interpolate2_R4 (x1, y1, x2, y2, V11, V12, V21, V22, x, y)
elemental function interpolate3_R8 (x1, y1, z1, x2, y2, z2, V111, V121, V211, V221, V112, V122, V212, V222, x, y, z)
elemental function interpolate3_R4 (x1, y1, z1, x2, y2, z2, V111, V121, V211, V221, V112, V122, V212, V222, x, y, z)
elemental function degree_Scalar_R8 (x_rad)
elemental function degree_Scalar_R4 (x_rad)
pure function degree_Vectorial1D_R8 (x_rad)
pure function degree_Vectorial1D_R4 (x_rad)
pure function degree_Vectorial2D_R8 (x_rad)
pure function degree_Vectorial2D_R4 (x_rad)
pure function degree_Vectorial3D_R8 (x_rad)
pure function degree_Vectorial3D_R4 (x_rad)
elemental function radiant_Scalar_R8 (x_deg)
elemental function radiant_Scalar_R4 (x_deg)
pure function radiant_Vectorial1D_R8 (x_deg)
pure function radiant_Vectorial1D_R4 (x_deg)
pure function radiant_Vectorial2D_R8 (x_deg)
pure function radiant_Vectorial2D_R4 (x_deg)
pure function radiant_Vectorial3D_R8 (x_deg)
pure function radiant_Vectorial3D_R4 (x_deg)
elemental function delta1_2o_R8 (Sp1, Sm1, Ds)
elemental function delta1_2o_R4 (Sp1, Sm1, Ds)
elemental function delta2_2o_R8 (Sp1, S, Sm1, Ds)
elemental function delta2_2o_R4 (Sp1, S, Sm1, Ds)
elemental function abs_grad_R8 (Vip1, Vim1, Di, Vjp1, Vjm1, Dj, Vkp1, Vkm1, Dk)
elemental function abs_grad_R4 (Vip1, Vim1, Di, Vjp1, Vjm1, Dj, Vkp1, Vkm1, Dk)
elemental function laplacian_R8 (Vip1, Vi, Vim1, Di, Vjp1, Vj, Vjm1, Dj, Vkp1, Vk, Vkm1, Dk)
elemental function laplacian_R4 (Vip1, Vi, Vim1, Di, Vjp1, Vj, Vjm1, Dj, Vkp1, Vk, Vkm1, Dk)
Member Function/Subroutine Documentation
pure function, public Lib_Math::stretchinglside (integer(I4P), intent(in) Ns, real(R_P), dimension(1:ns), intent(in) s_uniform, real(R_P), intent(in) stretch)
Definition at line 149 of file Lib_Math.f90.
pure function, public Lib_Math::stretchingrside (integer(I4P), intent(in) Ns, real(R_P), dimension(1:ns), intent(in) s_uniform, real(R_P), intent(in) stretch)
Definition at line 182 of file Lib_Math.f90.
pure function, public Lib_Math::stretching2side (real(R_P), intent(in), optional s_sym_in, integer(I4P), intent(in) Ns, real(R_P), dimension(1:ns), intent(in) s_uniform, real(R_P), intent(in) Ds_L, real(R_P), intent(in) Ds_R)
Definition at line 215 of file Lib_Math.f90.
pure function Lib_Math::average_Vectorial1D_R8 (real(R8P), dimension(:), intent(in) x) [private]
Definition at line 299 of file Lib_Math.f90.
pure function Lib_Math::average_Vectorial1D_R4 (real(R4P), dimension(:), intent(in) x) [private]
Definition at line 316 of file Lib_Math.f90.
pure function Lib_Math::average_Vectorial2D_R8 (real(R8P), dimension(:,:), intent(in) x) [private]
Definition at line 335 of file Lib_Math.f90.
pure function Lib_Math::average_Vectorial2D_R4 (real(R4P), dimension(:,:), intent(in) x) [private]
Definition at line 352 of file Lib_Math.f90.
pure function Lib_Math::average_Vectorial3D_R8 (real(R8P), dimension(:,:,:), intent(in) x) [private]
Definition at line 371 of file Lib_Math.f90.
pure function Lib_Math::average_Vectorial3D_R4 (real(R4P), dimension(:,:,:), intent(in) x) [private]
Definition at line 388 of file Lib_Math.f90.
elemental function Lib_Math::digit_I8 (integer(I8P), intent(in) n) [private]
Definition at line 406 of file Lib_Math.f90.
elemental function Lib_Math::digit_I4 (integer(I4P), intent(in) n) [private]
Definition at line 425 of file Lib_Math.f90.
elemental function Lib_Math::digit_I2 (integer(I2P), intent(in) n) [private]
Definition at line 444 of file Lib_Math.f90.
elemental function Lib_Math::digit_I1 (integer(I1P), intent(in) n) [private]
Definition at line 463 of file Lib_Math.f90.
elemental function Lib_Math::interpolate1_R8 (real(R8P), intent(in) x1, real(R8P), intent(in) x2, real(R8P), intent(in) V1, real(R8P), intent(in) V2, real(R8P), intent(in) x) [private]
Definition at line 485 of file Lib_Math.f90.
elemental function Lib_Math::interpolate1_R4 (real(R4P), intent(in) x1, real(R4P), intent(in) x2, real(R4P), intent(in) V1, real(R4P), intent(in) V2, real(R4P), intent(in) x) [private]
Definition at line 504 of file Lib_Math.f90.
elemental function Lib_Math::interpolate2_R8 (real(R8P), intent(in) x1, real(R8P), intent(in) y1, real(R8P), intent(in) x2, real(R8P), intent(in) y2, real(R8P), intent(in) V11, real(R8P), intent(in) V12, real(R8P), intent(in) V21, real(R8P), intent(in) V22, real(R8P), intent(in) x, real(R8P), intent(in) y) [private]
Definition at line 525 of file Lib_Math.f90.
elemental function Lib_Math::interpolate2_R4 (real(R4P), intent(in) x1, real(R4P), intent(in) y1, real(R4P), intent(in) x2, real(R4P), intent(in) y2, real(R4P), intent(in) V11, real(R4P), intent(in) V12, real(R4P), intent(in) V21, real(R4P), intent(in) V22, real(R4P), intent(in) x, real(R4P), intent(in) y) [private]
Definition at line 560 of file Lib_Math.f90.
elemental function Lib_Math::interpolate3_R8 (real(R8P), intent(in) x1, real(R8P), intent(in) y1, real(R8P), intent(in) z1, real(R8P), intent(in) x2, real(R8P), intent(in) y2, real(R8P), intent(in) z2, real(R8P), intent(in) V111, real(R8P), intent(in) V121, real(R8P), intent(in) V211, real(R8P), intent(in) V221, real(R8P), intent(in) V112, real(R8P), intent(in) V122, real(R8P), intent(in) V212, real(R8P), intent(in) V222, real(R8P), intent(in) x, real(R8P), intent(in) y, real(R8P), intent(in) z) [private]
Definition at line 597 of file Lib_Math.f90.
elemental function Lib_Math::interpolate3_R4 (real(R4P), intent(in) x1, real(R4P), intent(in) y1, real(R4P), intent(in) z1, real(R4P), intent(in) x2, real(R4P), intent(in) y2, real(R4P), intent(in) z2, real(R4P), intent(in) V111, real(R4P), intent(in) V121, real(R4P), intent(in) V211, real(R4P), intent(in) V221, real(R4P), intent(in) V112, real(R4P), intent(in) V122, real(R4P), intent(in) V212, real(R4P), intent(in) V222, real(R4P), intent(in) x, real(R4P), intent(in) y, real(R4P), intent(in) z) [private]
Definition at line 641 of file Lib_Math.f90.
elemental function Lib_Math::degree_Scalar_R8 (real(R8P), intent(in) x_rad) [private]
Definition at line 688 of file Lib_Math.f90.
elemental function Lib_Math::degree_Scalar_R4 (real(R4P), intent(in) x_rad) [private]
Definition at line 705 of file Lib_Math.f90.
pure function Lib_Math::degree_Vectorial1D_R8 (real(R8P), dimension(:), intent(in) x_rad) [private]
Definition at line 724 of file Lib_Math.f90.
pure function Lib_Math::degree_Vectorial1D_R4 (real(R4P), dimension(:), intent(in) x_rad) [private]
Definition at line 741 of file Lib_Math.f90.
pure function Lib_Math::degree_Vectorial2D_R8 (real(R8P), dimension(:,:), intent(in) x_rad) [private]
Definition at line 760 of file Lib_Math.f90.
pure function Lib_Math::degree_Vectorial2D_R4 (real(R4P), dimension(:,:), intent(in) x_rad) [private]
Definition at line 777 of file Lib_Math.f90.
pure function Lib_Math::degree_Vectorial3D_R8 (real(R8P), dimension(:,:,:), intent(in) x_rad) [private]
Definition at line 796 of file Lib_Math.f90.
pure function Lib_Math::degree_Vectorial3D_R4 (real(R4P), dimension(:,:,:), intent(in) x_rad) [private]
Definition at line 813 of file Lib_Math.f90.
elemental function Lib_Math::radiant_Scalar_R8 (real(R8P), intent(in) x_deg) [private]
Definition at line 833 of file Lib_Math.f90.
elemental function Lib_Math::radiant_Scalar_R4 (real(R4P), intent(in) x_deg) [private]
Definition at line 850 of file Lib_Math.f90.
pure function Lib_Math::radiant_Vectorial1D_R8 (real(R8P), dimension(:), intent(in) x_deg) [private]
Definition at line 869 of file Lib_Math.f90.
pure function Lib_Math::radiant_Vectorial1D_R4 (real(R4P), dimension(:), intent(in) x_deg) [private]
Definition at line 886 of file Lib_Math.f90.
pure function Lib_Math::radiant_Vectorial2D_R8 (real(R8P), dimension(:,:), intent(in) x_deg) [private]
Definition at line 905 of file Lib_Math.f90.
pure function Lib_Math::radiant_Vectorial2D_R4 (real(R4P), dimension(:,:), intent(in) x_deg) [private]
Definition at line 922 of file Lib_Math.f90.
pure function Lib_Math::radiant_Vectorial3D_R8 (real(R8P), dimension(:,:,:), intent(in) x_deg) [private]
Definition at line 941 of file Lib_Math.f90.
pure function Lib_Math::radiant_Vectorial3D_R4 (real(R4P), dimension(:,:,:), intent(in) x_deg) [private]
Definition at line 958 of file Lib_Math.f90.
elemental function Lib_Math::delta1_2o_R8 (real(R8P), intent(in) Sp1, real(R8P), intent(in) Sm1, real(R8P), intent(in) Ds) [private]
Definition at line 978 of file Lib_Math.f90.
elemental function Lib_Math::delta1_2o_R4 (real(R4P), intent(in) Sp1, real(R4P), intent(in) Sm1, real(R4P), intent(in) Ds) [private]
Definition at line 997 of file Lib_Math.f90.
elemental function Lib_Math::delta2_2o_R8 (real(R8P), intent(in) Sp1, real(R8P), intent(in) S, real(R8P), intent(in) Sm1, real(R8P), intent(in) Ds) [private]
Definition at line 1019 of file Lib_Math.f90.
elemental function Lib_Math::delta2_2o_R4 (real(R4P), intent(in) Sp1, real(R4P), intent(in) S, real(R4P), intent(in) Sm1, real(R4P), intent(in) Ds) [private]
Definition at line 1039 of file Lib_Math.f90.
elemental function Lib_Math::abs_grad_R8 (real(R8P), intent(in) Vip1, real(R8P), intent(in) Vim1, real(R8P), intent(in) Di, real(R8P), intent(in) Vjp1, real(R8P), intent(in) Vjm1, real(R8P), intent(in) Dj, real(R8P), intent(in) Vkp1, real(R8P), intent(in) Vkm1, real(R8P), intent(in) Dk) [private]
Definition at line 1062 of file Lib_Math.f90.
elemental function Lib_Math::abs_grad_R4 (real(R4P), intent(in) Vip1, real(R4P), intent(in) Vim1, real(R4P), intent(in) Di, real(R4P), intent(in) Vjp1, real(R4P), intent(in) Vjm1, real(R4P), intent(in) Dj, real(R4P), intent(in) Vkp1, real(R4P), intent(in) Vkm1, real(R4P), intent(in) Dk) [private]
Definition at line 1090 of file Lib_Math.f90.
elemental function Lib_Math::laplacian_R8 (real(R8P), intent(in) Vip1, real(R8P), intent(in) Vi, real(R8P), intent(in) Vim1, real(R8P), intent(in) Di, real(R8P), intent(in) Vjp1, real(R8P), intent(in) Vj, real(R8P), intent(in) Vjm1, real(R8P), intent(in) Dj, real(R8P), intent(in) Vkp1, real(R8P), intent(in) Vk, real(R8P), intent(in) Vkm1, real(R8P), intent(in) Dk) [private]
Definition at line 1121 of file Lib_Math.f90.
elemental function Lib_Math::laplacian_R4 (real(R4P), intent(in) Vip1, real(R4P), intent(in) Vi, real(R4P), intent(in) Vim1, real(R4P), intent(in) Di, real(R4P), intent(in) Vjp1, real(R4P), intent(in) Vj, real(R4P), intent(in) Vjm1, real(R4P), intent(in) Dj, real(R4P), intent(in) Vkp1, real(R4P), intent(in) Vk, real(R4P), intent(in) Vkm1, real(R4P), intent(in) Dk) [private]
Definition at line 1152 of file Lib_Math.f90.
module Lib_Mesh
This module contains mesh procedures.
Definition at line 7 of file Lib_Mesh.f90.
Public Member Functions
subroutine, public node2center (block)
Subroutine for computing cell center coordinates from cell nodes ones.
subroutine, public mesh_metrics (block)
Subroutine for computing the metrics of blocks.
subroutine, public mesh_metrics_correction (block)
Subroutine for correcting the metrics of natural (and negative volume) boundary conditions cells.
Member Function/Subroutine Documentation
subroutine, public Lib_Mesh::node2center (type(Type_Block), intent(inout) block)
Subroutine for computing cell center coordinates from cell nodes ones.
Parameters:
[in,out] block Block-level data.
Definition at line 24 of file Lib_Mesh.f90.
subroutine, public Lib_Mesh::mesh_metrics (type(Type_Block), intent(inout) block)
Subroutine for computing the metrics of blocks.
Parameters:
[in,out] block Block-level data.
Definition at line 72 of file Lib_Mesh.f90.
subroutine, public Lib_Mesh::mesh_metrics_correction (integer(I_P), intent(inout) block)
Subroutine for correcting the metrics of natural (and negative volume) boundary conditions cells.
Parameters:
[in,out] block Block-level data.
Definition at line 230 of file Lib_Mesh.f90.
module Lib_Multigrid
This module contains the definition of multigrid procedures.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 8 of file Lib_Multigrid.f90.
Public Member Functions
subroutine, public alloc_multigrid (Nc, bb1, bb2)
subroutine, public restrict (myrank, l, Nb, gco, gc, Ni_f, Nj_f, Nk_f, Ni_c, Nj_c, Nk_c, bb_f, bb_c, bb_Fi_c, bb_Fj_c, bb_Fk_c, Np, Nc, Ns, NFi_c, NFj_c, NFk_c, BCi_c, BCj_c, BCk_c, Nin1, in1, Nin2, bb_in2, in2, Si_c, Sj_c, Sk_c, V_f, V_c, U_f, R_f, t, U_c, UR, TE)
subroutine, public correct (myrank, l, Nb, gco, gc, Ni_f, Nj_f, Nk_f, Ni_c, Nj_c, Nk_c, bb_f, bb_c, bb_Fi_f, bb_Fj_f, bb_Fk_f, Np, Nc, Ns, NFi_f, NFj_f, NFk_f, BCi_f, BCj_f, BCk_f, Nin1, in1, Nin2, bb_in2, in2, Si_f, Sj_f, Sk_f, V_f, UR, U_c, t, U_f, P_f)
Public Attributes
real(R_P), allocatable, public UR
Restriction of conservative variables [1:Nc,bb1:bb2].
real(R_P), allocatable, public TE
Truncation error of conservative variables [1:Nc,bb1:bb2].
Member Function/Subroutine Documentation
subroutine, public Lib_Multigrid::alloc_multigrid (integer(I_P), intent(in) Nc, integer(I_P), intent(in) bb1, integer(I_P), intent(in) bb2)
Definition at line 35 of file Lib_Multigrid.f90.
subroutine, public Lib_Multigrid::restrict (integer(I_P), intent(in) myrank, integer(I_P), intent(in) l, integer(I_P), intent(in) Nb, integer(I_P), intent(in) gco, integer(I_P), dimension(1:6,1:nb), intent(in) gc, integer(I_P), dimension(1:nb), intent(in) Ni_f, integer(I_P), dimension(1:nb), intent(in) Nj_f, integer(I_P), dimension(1:nb), intent(in) Nk_f, integer(I_P), dimension(1:nb), intent(in) Ni_c, integer(I_P), dimension(1:nb), intent(in) Nj_c, integer(I_P), dimension(1:nb), intent(in) Nk_c, integer(I_P), dimension (1:2,1:nb), intent(in) bb_f, integer(I_P), dimension (1:2,1:nb), intent(in) bb_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fi_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fj_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fk_c, integer(I_P), intent(in) Np, integer(I_P), intent(in) Nc, integer(I_P), intent(in) Ns, type(Type_Vector), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) NFi_c, type(Type_Vector), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) NFj_c, type(Type_Vector), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) NFk_c, type(Type_BC), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) BCi_c, type(Type_BC), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) BCj_c, type(Type_BC), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) BCk_c, integer(I_P), intent(in) Nin1, real(R_P), dimension(1:np,1:nin1), intent(in) in1, integer(I_P), intent(in) Nin2, integer(I_P), dimension(1:2,1:nin2), intent(in) bb_in2, real(R_P), dimension(1:np+1,bb_in2(1,1):bb_in2(2,nin2)), intent(in) in2, real(R_P), dimension (bb_fi_c(1,1):bb_fi_c(2,nb)), intent(in) Si_c, real(R_P), dimension (bb_fj_c(1,1):bb_fj_c(2,nb)), intent(in) Sj_c, real(R_P), dimension (bb_fk_c(1,1):bb_fk_c(2,nb)), intent(in) Sk_c, real(R_P), dimension (bb_f (1,1):bb_f (2,nb)), intent(in) V_f, real(R_P), dimension (bb_c (1,1):bb_c (2,nb)), intent(in) V_c, real(R_P), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(in) U_f, real(R_P), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(in) R_f, real(R_P), intent(in) t, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) U_c, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) UR, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(out) TE)
Definition at line 53 of file Lib_Multigrid.f90.
References fine2coarse_R(), fine2coarse_U(), and te_estimation().
subroutine, public Lib_Multigrid::correct (integer(I_P), intent(in) myrank, integer(I_P), intent(in) l, integer(I_P), intent(in) Nb, integer(I_P), intent(in) gco, integer(I_P), dimension(1:6,1:nb), intent(in) gc, integer(I_P), dimension(1:nb), intent(in) Ni_f, integer(I_P), dimension(1:nb), intent(in) Nj_f, integer(I_P), dimension(1:nb), intent(in) Nk_f, integer(I_P), dimension(1:nb), intent(in) Ni_c, integer(I_P), dimension(1:nb), intent(in) Nj_c, integer(I_P), dimension(1:nb), intent(in) Nk_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_f, integer(I_P), dimension(1:2,1:nb), intent(in) bb_c, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fi_f, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fj_f, integer(I_P), dimension(1:2,1:nb), intent(in) bb_Fk_f, integer(I_P), intent(in) Np, integer(I_P), intent(in) Nc, integer(I_P), intent(in) Ns, type(Type_Vector), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) NFi_f, type(Type_Vector), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) NFj_f, type(Type_Vector), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) NFk_f, type(Type_BC), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) BCi_f, type(Type_BC), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) BCj_f, type(Type_BC), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) BCk_f, integer(I_P), intent(in) Nin1, real(R_P), dimension(1:np,1:nin1), intent(in) in1, integer(I_P), intent(in) Nin2, integer(I_P), dimension(1:2,1:nin2), intent(in) bb_in2, real(R_P), dimension(1:np+1,bb_in2(1,1):bb_in2(2,nin2)), intent(in) in2, real(R_P), dimension (bb_fi_f(1,1):bb_fi_f(2,nb)), intent(in) Si_f, real(R_P), dimension (bb_fj_f(1,1):bb_fj_f(2,nb)), intent(in) Sj_f, real(R_P), dimension (bb_fk_f(1,1):bb_fk_f(2,nb)), intent(in) Sk_f, real(R_P), dimension (bb_f (1,1):bb_f (2,nb)), intent(in) V_f, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(in) UR, real(R_P), dimension (1:nc,bb_c (1,1):bb_c (2,nb)), intent(in) U_c, real(R_P), intent(in) t, real(R_P), dimension (1:nc,bb_f (1,1):bb_f (2,nb)), intent(inout) U_f, real(R_P), dimension (1:np,bb_f (1,1):bb_f (2,nb)), intent(out) P_f)
Definition at line 323 of file Lib_Multigrid.f90.
References coarse2fine_U(), get_correction(), and update_fine().
Member Data Documentation
real(R_P), allocatable, public Lib_Multigrid::UR
Restriction of conservative variables [1:Nc,bb1:bb2].
Definition at line 31 of file Lib_Multigrid.f90.
real(R_P), allocatable, public Lib_Multigrid::TE
Truncation error of conservative variables [1:Nc,bb1:bb2].
Definition at line 32 of file Lib_Multigrid.f90.
module Lib_Parallel
This module contains the definition of procedures for send/receive data among processes for parallel (MPI) operations.
It is based on MPI library.
Note:
The communications have a tag-shift (for make them unique) that assumes a maximum number of processes of 10000. Increment this parameter if using more processes than 10000.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 16 of file Lib_Parallel.f90.
Public Member Functions
subroutine, public Init_sendrecv (myrank, global, block)
Subroutine for initializing the send/receive communications data.
subroutine, public Psendrecv (myrank, l, global, block)
Subroutine for performing send/receive of primitive variables of myrank to other processes.
integer(I_P) function, public procmap_load (myrank, filename, global)
Function for loading the processes/blocks map and local/global blocks map.
integer(I_P) function, public procmap_save (filename, global)
Function for saving the processes/blocks map.
Public Attributes
integer(I_P), public Nthreads = 1_I_P
Number of OpenMP threads.
integer(I_P), public Nproc = 1_I_P
Number of processes (for MPI parallelization).
integer(I_P), dimension(:),
allocatable, public procmap
Processes/blocks map [1:Nb_tot].
integer(I_P), dimension(:),
allocatable, public blockmap
Local/global blocks map [1:Nb].
Private Member Functions
subroutine alloc_SR (global)
subroutine compute_NcR (myrank, global, block)
subroutine NcRsendrecv (myrank, global)
subroutine compute_bbS (global)
subroutine alloc_sendrecv (global)
subroutine compute_recv_maps (myrank, global, block)
subroutine mapsendrecv (myrank, global)
integer(I_P) function Printsendrecvmaps (myrank)
Private Attributes
integer(I_P), parameter maxproc = 10000
Maximum number of processes used for communications tag shift.
integer(I_P) gNcR
Global number of receive cells (sum(NcR)).
integer(I_P) gNcS
Global number of send cells (sum(NcS)).
integer(I_P), allocatable NcR
Number of receive cells from each process [ 0:Nproc-1,1:Nl].
integer(I_P), allocatable NcS
Number of send cells for each process [ 0:Nproc-1,1:Nl].
integer(I_P), allocatable bbR
Processes bounds of receive cells [1:2,0:Nproc-1,1:Nl].
integer(I_P), allocatable bbS
Processes bounds of send cells [1:2,0:Nproc-1,1:Nl].
integer(I_P), dimension(:,:),
allocatable recvmap
Receiving cells map of myrank from other processes [1:4,1:gNcR].
integer(I_P), dimension(:,:),
allocatable reqsmap
Querying cells map of myrank for other processes [1:4,1:gNcR].
integer(I_P), dimension(:,:),
allocatable sendmap
Sending cells map from myrank to other processes [1:4,1:gNcS].
real(R_P), allocatable Precv
Receiving buffer of primitive variable of myrank from other processes [1:Np,1:gNcR].
real(R_P), allocatable Psend
Sending buffer of primitive variable of myrank for other processes [1:Np,1:gNcS].
Member Function/Subroutine Documentation
subroutine Lib_Parallel::alloc_SR (type(Type_Global), intent(in) global) [private]
Definition at line 64 of file Lib_Parallel.f90.
subroutine Lib_Parallel::compute_NcR (integer(I_P), intent(in) myrank, type(Type_Global), intent(in) global, type(Type_Block), dimension(1:global%mesh%nb,1:global%mesh%nl), intent(in) block) [private]
Definition at line 83 of file Lib_Parallel.f90.
subroutine Lib_Parallel::NcRsendrecv (integer(I_P), intent(in) myrank, type(Type_Global), intent(in) global) [private]
Definition at line 185 of file Lib_Parallel.f90.
subroutine Lib_Parallel::compute_bbS (type(Type_Global), intent(in) global) [private]
Definition at line 218 of file Lib_Parallel.f90.
subroutine Lib_Parallel::alloc_sendrecv (type(Type_Global), intent(in) global) [private]
Definition at line 247 of file Lib_Parallel.f90.
subroutine Lib_Parallel::compute_recv_maps (integer(I_P), intent(in) myrank, type(Type_Global), intent(in) global, type(Type_Block), dimension(1:global%mesh%nb,1:global%mesh%nl), intent(in) block) [private]
Definition at line 267 of file Lib_Parallel.f90.
References scan_proc().
subroutine Lib_Parallel::mapsendrecv (integer(I_P), intent(in) myrank, type(Type_Global), intent(in) global) [private]
Definition at line 441 of file Lib_Parallel.f90.
subroutine, public Lib_Parallel::Init_sendrecv (integer(I_P), intent(in) myrank, type(Type_Global), intent(in) global, type(Type_Block), dimension(1:global%mesh%nb,1:global%mesh%nl), intent(in) block)
Subroutine for initializing the send/receive communications data.
Parameters:
[in] myrank Actual rank process.
[in] global Global-level data.
[in] block Block-level data.
Definition at line 477 of file Lib_Parallel.f90.
subroutine, public Lib_Parallel::Psendrecv (integer(I_P), intent(in) myrank, integer(I_P), intent(in) l, type(Type_Global), intent(in) global, type(Type_Block), dimension(1:global%mesh%nb), intent(inout) block)
Subroutine for performing send/receive of primitive variables of myrank to other processes.
Parameters:
[in] myrank Actual rank process.
[in] l Grid level.
[in] global Global-level data.
[in,out] block Block-level data.
Definition at line 500 of file Lib_Parallel.f90.
integer(I_P) function Lib_Parallel::Printsendrecvmaps (integer(I_P), intent(in) myrank) [private]
Definition at line 539 of file Lib_Parallel.f90.
integer(I_P) function, public Lib_Parallel::procmap_load (integer(I_P), intent(in) myrank, character(*), intent(in) filename, type(Type_Global), intent(inout) global)
Function for loading the processes/blocks map and local/global blocks map.
Returns:
err integer(I4P) variable.
Parameters:
[in] myrank Actual rank process.
[in] filename File name processes/blocks map.
[in,out] global Global-level data.
Definition at line 570 of file Lib_Parallel.f90.
integer(I_P) function, public Lib_Parallel::procmap_save (character(*), intent(in) filename, type(Type_Global), intent(in) global)
Function for saving the processes/blocks map.
Returns:
err integer(I4P) variable.
Parameters:
[in] filename File name processes/blocks map.
[in] global Global-level data.
Definition at line 622 of file Lib_Parallel.f90.
Member Data Documentation
integer(I_P), parameter Lib_Parallel::maxproc = 10000 [private]
Maximum number of processes used for communications tag shift.
Definition at line 50 of file Lib_Parallel.f90.
integer(I_P) Lib_Parallel::gNcR [private]
Global number of receive cells (sum(NcR)).
Definition at line 51 of file Lib_Parallel.f90.
integer(I_P) Lib_Parallel::gNcS [private]
Global number of send cells (sum(NcS)).
Definition at line 52 of file Lib_Parallel.f90.
integer(I_P), allocatable Lib_Parallel::NcR [private]
Number of receive cells from each process [ 0:Nproc-1,1:Nl].
Definition at line 53 of file Lib_Parallel.f90.
integer(I_P), allocatable Lib_Parallel::NcS [private]
Number of send cells for each process [ 0:Nproc-1,1:Nl].
Definition at line 54 of file Lib_Parallel.f90.
integer(I_P), allocatable Lib_Parallel::bbR [private]
Processes bounds of receive cells [1:2,0:Nproc-1,1:Nl].
Definition at line 55 of file Lib_Parallel.f90.
integer(I_P), allocatable Lib_Parallel::bbS [private]
Processes bounds of send cells [1:2,0:Nproc-1,1:Nl].
Definition at line 56 of file Lib_Parallel.f90.
integer(I_P), dimension(:,:), allocatable Lib_Parallel::recvmap [private]
Receiving cells map of myrank from other processes [1:4,1:gNcR].
Definition at line 57 of file Lib_Parallel.f90.
integer(I_P), dimension(:,:), allocatable Lib_Parallel::reqsmap [private]
Querying cells map of myrank for other processes [1:4,1:gNcR].
Definition at line 58 of file Lib_Parallel.f90.
integer(I_P), dimension(:,:), allocatable Lib_Parallel::sendmap [private]
Sending cells map from myrank to other processes [1:4,1:gNcS].
Definition at line 59 of file Lib_Parallel.f90.
real(R_P), allocatable Lib_Parallel::Precv [private]
Receiving buffer of primitive variable of myrank from other processes [1:Np,1:gNcR].
Definition at line 60 of file Lib_Parallel.f90.
real(R_P), allocatable Lib_Parallel::Psend [private]
Sending buffer of primitive variable of myrank for other processes [1:Np,1:gNcS].
Definition at line 61 of file Lib_Parallel.f90.
module Lib_PostProcessing
This module contains the definition of procedures and variables useful for post-process the OFF data.
Definition at line 12 of file Lib_PostProcessing.f90.
Public Member Functions
integer(I_P) function, public tec_output (meshonly, global, block, filename)
Function for writing OFF block data to Tecplot file.
integer(I_P) function, public vtk_output (meshonly, global, block, filename)
Function for writing OFF block data to VTK file.
Public Attributes
type(Type_PP_Format), public pp_format
Post-processing format options (see definition).
Private Member Functions
subroutine interpolate_primitive (global, block, P)
subroutine compute_dimensions (block, ni1, ni2, nj1, nj2, nk1, nk2, ci1, ci2, cj1, cj2, ck1, ck2)
Member Function/Subroutine Documentation
subroutine Lib_PostProcessing::interpolate_primitive (type(Type_Global), intent(in) global, type(Type_Block), intent(inout) block, type(Type_Primitive), dimension(0:block%mesh%ni, 0:block%mesh%nj, 0:block%mesh%nk), intent(inout) P) [private]
Definition at line 46 of file Lib_PostProcessing.f90.
subroutine Lib_PostProcessing::compute_dimensions (type(Type_Block), intent(in) block, integer(I_P), intent(out) ni1, integer(I_P), intent(out) ni2, integer(I_P), intent(out) nj1, integer(I_P), intent(out) nj2, integer(I_P), intent(out) nk1, integer(I_P), intent(out) nk2, integer(I_P), intent(out) ci1, integer(I_P), intent(out) ci2, integer(I_P), intent(out) cj1, integer(I_P), intent(out) cj2, integer(I_P), intent(out) ck1, integer(I_P), intent(out) ck2) [private]
Definition at line 88 of file Lib_PostProcessing.f90.
integer(I_P) function, public Lib_PostProcessing::tec_output (logical, intent(in) meshonly, type(Type_Global), intent(in) global, type(Type_Block), dimension(1:global%mesh%nb), intent(inout) block, character(*), intent(in) filename)
Function for writing OFF block data to Tecplot file.
Parameters:
[in] meshonly Flag for post-process only mesh.
[in] global Global-level data.
[in,out] block Block-level data.
[in] filename File name of the output file.
Definition at line 133 of file Lib_PostProcessing.f90.
integer(I_P) function, public Lib_PostProcessing::vtk_output (logical, intent(in) meshonly, type(Type_Global), intent(in) global, type(Type_Block), dimension(1:global%mesh%nb), intent(inout) block, character(*), intent(in) filename)
Function for writing OFF block data to VTK file.
Parameters:
[in] meshonly Flag for post-process only mesh.
[in] global Global-level data.
[in,out] block Block-level data.
[in] filename File name of the output file.
Definition at line 413 of file Lib_PostProcessing.f90.
References tec_dat().
module Lib_Riemann
This module contains procedures for computing the solution of a Riemann Problem.
This is a library module.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 9 of file Lib_Riemann.f90.
Public Member Functions
logical function, public chk_smooth_z (p1, r1, u1, g1, p4, r4, u4, g4)
Function for evaluating the smoothness of an interface using a Riemann solver-like algorithm.
logical function, public chk_smooth_limiter (pm1, pp1, rm1, rp1, um1, up1, gm1, gp1)
Function for evaluating the smoothness of a cell using a discontinuity detector based on slope limiter function.
logical function, public chk_smooth_liu (pm1, rm1, um1, gm1, cpm1, cvm1, p1, r1, u1m, u1p, g1, cp1, cv1, pp1, rp1, up1, gp1, cpp1, cvp1)
Function for evaluating the smoothness of a cell using the Liu's entropy conditions.
elemental subroutine, public Riem_Solver_LaxFriedrichs (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on (local) Lax-Friedrichs (known also as Rusanov) algorithm.
subroutine, public Riem_Solver_PVL (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Primitive Variables Linearization algorithm.
subroutine, public Riem_Solver_TR (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Two Rarefactions algorithm.
elemental subroutine, public Riem_Solver_TS (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Two Shocks algorithm.
subroutine, public Riem_Solver_APRS (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Adaptive (non iterative) PVL-TR-TS algorithm.
subroutine, public Riem_Solver_ALFR (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Approximate Riemann solver based on Adaptive (non iterative) LF-TR algorithm.
elemental subroutine, public Riem_Solver_HLLC (p1, r1, u1, g1,
Approximate Riemann solver based on HLLC algorithm.
elemental subroutine, public Riem_Solver_Roe (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, F_r, F_u, F_E)
Approximate Riemann solver based on Roe linearization.
subroutine, public Riem_Solver_Exact_U (p1, r1, u1, g1, p4, r4, u4, g4, F_r, F_u, F_E)
Exact Riemann solver based on iterative solution of u-function.
Private Member Functions
elemental subroutine fluxes (p, r, u, g, F_r, F_u, F_E)
elemental subroutine Rarefaction (sgn, g, delta, eta, u0, p0, a0, ux, rx, px, ax, s0, sx)
elemental subroutine Shock (sgn, g, gm1, gp1, u0, p0, a0, ux, rx, px, ax, ss)
elemental subroutine WavesSpeed14u (u1, a1, g1, u4, a4, g4, u23, S1, S4)
elemental subroutine WavesSpeed14up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, S1, S4)
elemental subroutine WavesSpeed1234u (u1, a1, g1, u4, a4, g4, u23, S1, S2, S3, S4)
elemental subroutine WavesSpeed1234up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, S1, S2, S3, S4)
elemental subroutine InterStates23u (p1, u1, a1, g1, gm1_1, gp1_1, delta1, eta1, p4, u4, a4, g4, gm1_4, gp1_4, delta4, eta4, u23, r2, p2, a2, r3, p3, a3, S1, S2, S3, S4)
elemental subroutine InterStates23up (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
subroutine sampling_fluxes (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, p23, r2, r3, S, S1, S2, S3, S4, F_r, F_u, F_E)
elemental subroutine sampling_fluxes_old (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, p23, r2, r3, S, S1, S2, S3, S4, F_r, F_u, F_E)
elemental subroutine sampling_fluxes_vacuum (p1, r1, u1, a1, g1, delta1, eta1, p4, r4, u4, a4, g4, delta4, eta4, S1, S2, S3, S4, F_r, F_u, F_E)
elemental function VanLeer_limiter (Sm1, Sp1)
elemental function VanAlbada_limiter (Sm1, Sp1)
elemental function Harten_limiter (Sm1, Sp1)
elemental subroutine PVL_u23 (p1, r1, u1, a1, p4, r4, u4, a4, u23)
elemental subroutine PVL_p23 (p1, r1, u1, a1, p4, r4, u4, a4, p23)
elemental subroutine PVL_up23 (p1, r1, u1, a1, p4, r4, u4, a4, u23, p23)
elemental subroutine PVL_WavesSpeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine PVL_WavesSpeed1234 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S2, S3, S4)
elemental subroutine PVL_States (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine CVL_u23 (p1, r1, u1, a1, p4, r4, u4, a4, u23)
elemental subroutine CVL_up23 (p1, r1, u1, a1, p4, r4, u4, a4, u23, p23)
elemental subroutine CVL_WavesSpeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine CVL_States (p1, r1, u1, g1, p4, r4, u4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine TR_u23 (p1, u1, a1, g1, p4, u4, a4, g4, u23)
elemental subroutine TR_up23 (p1, u1, a1, g1, p4, u4, a4, g4, u23, p23)
elemental subroutine TR_WavesSpeed14 (p1, u1, a1, g1, p4, u4, a4, g4, S, S1, S4)
elemental subroutine TR_States (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine TS_up23 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23)
elemental subroutine TS_WavesSpeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
elemental subroutine TS_States (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, u23, p23, r2, r3, S1, S2, S3, S4)
elemental subroutine Roe_up23 (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, u23, p23)
elemental subroutine Roe_WavesSpeed14 (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, S, S1, S4)
elemental subroutine Roe_ua (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, u_roe, a_roe)
elemental subroutine Roe_State (p1, r1, u1, g1, cp1, cv1, p4, r4, u4, g4, cp4, cv4, r_roe, u_roe, a_roe, H_roe)
elemental subroutine BCLC_WavesSpeed14 (p1, r1, u1, a1, g1, cp1, cv1, p4, r4, u4, a4, g4, cp4, cv4, S, S1, S4)
elemental subroutine Z_WavesSpeed14 (p1, r1, u1, a1, g1, p4, r4, u4, a4, g4, S, S1, S4)
Private Attributes
real(R_P), parameter toll = 1.D-10
Member Function/Subroutine Documentation
elemental subroutine Lib_Riemann::fluxes (real(R_P), intent(in) p, real(R_P), intent(in) r, real(R_P), intent(in) u, real(R_P), intent(in) g, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E) [private]
Definition at line 40 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Rarefaction (real(R_P), intent(in) sgn, real(R_P), intent(in) g, real(R_P), intent(in) delta, real(R_P), intent(in) eta, real(R_P), intent(in) u0, real(R_P), intent(in) p0, real(R_P), intent(in) a0, real(R_P), intent(in) ux, real(R_P), intent(out) rx, real(R_P), intent(out) px, real(R_P), intent(out) ax, real(R_P), intent(out) s0, real(R_P), intent(out) sx) [private]
Definition at line 64 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Shock (real(R_P), intent(in) sgn, real(R_P), intent(in) g, real(R_P), intent(in) gm1, real(R_P), intent(in) gp1, real(R_P), intent(in) u0, real(R_P), intent(in) p0, real(R_P), intent(in) a0, real(R_P), intent(in) ux, real(R_P), intent(out) rx, real(R_P), intent(out) px, real(R_P), intent(out) ax, real(R_P), intent(out) ss) [private]
Definition at line 93 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::WavesSpeed14u (real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 126 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::WavesSpeed14up (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(in) p23, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 168 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::WavesSpeed1234u (real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 210 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::WavesSpeed1234up (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(in) p23, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 256 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::InterStates23u (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) gm1_1, real(R_P), intent(in) gp1_1, real(R_P), intent(in) delta1, real(R_P), intent(in) eta1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) gm1_4, real(R_P), intent(in) gp1_4, real(R_P), intent(in) delta4, real(R_P), intent(in) eta4, real(R_P), intent(in) u23, real(R_P), intent(out) r2, real(R_P), intent(out) p2, real(R_P), intent(out) a2, real(R_P), intent(out) r3, real(R_P), intent(out) p3, real(R_P), intent(out) a3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 302 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::InterStates23up (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) u23, real(R_P), intent(in) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 428 of file Lib_Riemann.f90.
subroutine Lib_Riemann::sampling_fluxes (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) delta1, real(R_P), intent(in) eta1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) delta4, real(R_P), intent(in) eta4, real(R_P), intent(in) p23, real(R_P), intent(in) r2, real(R_P), intent(in) r3, real(R_P), intent(in) S, real(R_P), intent(in) S1, real(R_P), intent(in) S2, real(R_P), intent(in) S3, real(R_P), intent(in) S4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E) [private]
Definition at line 493 of file Lib_Riemann.f90.
References fluxes().
elemental subroutine Lib_Riemann::sampling_fluxes_old (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) delta1, real(R_P), intent(in) eta1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) delta4, real(R_P), intent(in) eta4, real(R_P), intent(in) p23, real(R_P), intent(in) r2, real(R_P), intent(in) r3, real(R_P), intent(in) S, real(R_P), intent(in) S1, real(R_P), intent(in) S2, real(R_P), intent(in) S3, real(R_P), intent(in) S4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E) [private]
Definition at line 555 of file Lib_Riemann.f90.
References fluxes().
elemental subroutine Lib_Riemann::sampling_fluxes_vacuum (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) delta1, real(R_P), intent(in) eta1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) delta4, real(R_P), intent(in) eta4, real(R_P), intent(in) S1, real(R_P), intent(in) S2, real(R_P), intent(in) S3, real(R_P), intent(in) S4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E) [private]
Definition at line 641 of file Lib_Riemann.f90.
References fluxes().
elemental function Lib_Riemann::VanLeer_limiter (real(R_P), intent(in) Sm1, real(R_P), intent(in) Sp1) [private]
Definition at line 699 of file Lib_Riemann.f90.
elemental function Lib_Riemann::VanAlbada_limiter (real(R_P), intent(in) Sm1, real(R_P), intent(in) Sp1) [private]
Definition at line 722 of file Lib_Riemann.f90.
elemental function Lib_Riemann::Harten_limiter (real(R_P), intent(in) Sm1, real(R_P), intent(in) Sp1) [private]
Definition at line 745 of file Lib_Riemann.f90.
logical function, public Lib_Riemann::chk_smooth_z (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4)
Function for evaluating the smoothness of an interface using a Riemann solver-like algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
Definition at line 770 of file Lib_Riemann.f90.
logical function, public Lib_Riemann::chk_smooth_limiter (real(R_P), intent(in) pm1, real(R_P), intent(in) pp1, real(R_P), intent(in) rm1, real(R_P), intent(in) rp1, real(R_P), intent(in) um1, real(R_P), intent(in) up1, real(R_P), intent(in) gm1, real(R_P), intent(in) gp1)
Function for evaluating the smoothness of a cell using a discontinuity detector based on slope limiter function.
Parameters:
[in] pm1 Upwind difference of pressure.
[in] pp1 Downwind difference of pressure.
[in] rm1 Upwind difference of density.
[in] rp1 Downwind difference of density.
[in] um1 Upwind difference of speed.
[in] up1 Downwind difference of speed.
[in] gm1 Upwind difference of specific heats ratio.
[in] gp1 Downwind difference of specific heats ratio.
Definition at line 810 of file Lib_Riemann.f90.
logical function, public Lib_Riemann::chk_smooth_liu (real(R_P), intent(in) pm1, real(R_P), intent(in) rm1, real(R_P), intent(in) um1, real(R_P), intent(in) gm1, real(R_P), intent(in) cpm1, real(R_P), intent(in) cvm1, real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1m, real(R_P), intent(in) u1p, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) pp1, real(R_P), intent(in) rp1, real(R_P), intent(in) up1, real(R_P), intent(in) gp1, real(R_P), intent(in) cpp1, real(R_P), intent(in) cvp1)
Function for evaluating the smoothness of a cell using the Liu's entropy conditions.
Parameters:
[in] pm1 Pressure of state i-1.
[in] rm1 Density of state i-1.
[in] um1 Velocity of state i-1.
[in] gm1 Specific heats ratio of state i-1.
[in] cpm1 Specific heats cp of state i-1.
[in] cvm1 Specific heats cv of state i-1.
[in] p1 Pressure of state i.
[in] r1 Density of state i.
[in] u1m Velocity of state i at left interface.
[in] u1p Velocity of state i at left interface.
[in] g1 Specific heats ratio of state i.
[in] cp1 Specific heats cp of state i.
[in] cv1 Specific heats cv of state i.
[in] pp1 Pressure of state i+1.
[in] rp1 Density of state i+1.
[in] up1 Velocity of state i+1.
[in] gp1 Specific heats ratio of state i+1.
[in] cpp1 Specific heats cp of state i+1.
[in] cvp1 Specific heats cv of state i+1.
Definition at line 844 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_u23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) u23) [private]
Definition at line 901 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_p23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) p23) [private]
Definition at line 925 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 949 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 977 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_WavesSpeed1234 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1021 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::PVL_States (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1063 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::CVL_u23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) u23) [private]
Definition at line 1099 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::CVL_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 1127 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::CVL_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1160 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::CVL_States (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1204 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TR_u23 (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23) [private]
Definition at line 1242 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TR_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 1276 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TR_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1312 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TR_States (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1354 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TS_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 1397 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TS_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1430 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::TS_States (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) u23, real(R_P), intent(out) p23, real(R_P), intent(out) r2, real(R_P), intent(out) r3, real(R_P), intent(out) S1, real(R_P), intent(out) S2, real(R_P), intent(out) S3, real(R_P), intent(out) S4) [private]
Definition at line 1462 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Roe_up23 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) u23, real(R_P), intent(out) p23) [private]
Definition at line 1510 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Roe_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1553 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Roe_ua (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) u_roe, real(R_P), intent(out) a_roe) [private]
Definition at line 1592 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Roe_State (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) r_roe, real(R_P), intent(out) u_roe, real(R_P), intent(out) a_roe, real(R_P), intent(out) H_roe) [private]
Definition at line 1631 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::BCLC_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1674 of file Lib_Riemann.f90.
elemental subroutine Lib_Riemann::Z_WavesSpeed14 (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) a1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) a4, real(R_P), intent(in) g4, real(R_P), intent(out) S, real(R_P), intent(out) S1, real(R_P), intent(out) S4) [private]
Definition at line 1714 of file Lib_Riemann.f90.
elemental subroutine, public Lib_Riemann::Riem_Solver_LaxFriedrichs (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on (local) Lax-Friedrichs (known also as Rusanov) algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1759 of file Lib_Riemann.f90.
subroutine, public Lib_Riemann::Riem_Solver_PVL (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Primitive Variables Linearization algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1809 of file Lib_Riemann.f90.
References fluxes().
subroutine, public Lib_Riemann::Riem_Solver_TR (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Two Rarefactions algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1851 of file Lib_Riemann.f90.
elemental subroutine, public Lib_Riemann::Riem_Solver_TS (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Two Shocks algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1893 of file Lib_Riemann.f90.
subroutine, public Lib_Riemann::Riem_Solver_APRS (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Adaptive (non iterative) PVL-TR-TS algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 1941 of file Lib_Riemann.f90.
References fluxes().
subroutine, public Lib_Riemann::Riem_Solver_ALFR (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Adaptive (non iterative) LF-TR algorithm.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 2004 of file Lib_Riemann.f90.
elemental subroutine, public Lib_Riemann::Riem_Solver_HLLC (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1)
Approximate Riemann solver based on HLLC algorithm.
Note:
Five variants are provided: HLLCb, using BCLC estimation of waves speed, HLLCc using CVL algorithm, HLLCp using PVL algorithm, HLLCt using TR algorithm and HLLCz using Z one.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
Definition at line 2091 of file Lib_Riemann.f90.
elemental subroutine, public Lib_Riemann::Riem_Solver_Roe (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) cp1, real(R_P), intent(in) cv1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(in) cp4, real(R_P), intent(in) cv4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Approximate Riemann solver based on Roe linearization.
Note:
The Harten-Hyman entropy fix is used to avoid shock-expansions (entropy violation).
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 Velocity of state 1.
[in] g1 Specific heats ratio of state 1.
[in] cp1 Specific heats cp of state 1.
[in] cv1 Specific heats cv of state 1.
[in] p4 pressure of state 4.
[in] r4 Density of state 4.
[in] u4 Velocity of state 4.
[in] g4 Specific heats ratio of state 4.
[in] cp4 Specific heats cp of state 4.
[in] cv4 Specific heats cv of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 2180 of file Lib_Riemann.f90.
References fluxes().
subroutine, public Lib_Riemann::Riem_Solver_Exact_U (real(R_P), intent(in) p1, real(R_P), intent(in) r1, real(R_P), intent(in) u1, real(R_P), intent(in) g1, real(R_P), intent(in) p4, real(R_P), intent(in) r4, real(R_P), intent(in) u4, real(R_P), intent(in) g4, real(R_P), intent(out) F_r, real(R_P), intent(out) F_u, real(R_P), intent(out) F_E)
Exact Riemann solver based on iterative solution of u-function.
Parameters:
[in] p1 Pressure of state 1.
[in] r1 Density of state 1.
[in] u1 U speed of state 1.
[in] g1 Specific heats ratio of state 1.
[in] p4 Pressure of state 4.
[in] r4 Density of state 4.
[in] u4 U speed of state 4.
[in] g4 Specific heats ratio of state 4.
[out] F_r Flux of mass conservation.
[out] F_u Flux of momentum conservation.
[out] F_E Flux of energy conservation.
Definition at line 2280 of file Lib_Riemann.f90.
References fluxes().
Member Data Documentation
real(R_P), parameter Lib_Riemann::toll = 1.D-10 [private]
Definition at line 36 of file Lib_Riemann.f90.
module Lib_Thermodynamic_Laws_Ideal
This module contains the definition of Thermodynamic Laws for ideal calorically perfect gas.
Definition at line 7 of file Lib_Thermodynamic_Laws_Ideal.f90.
Public Member Functions
elemental function, public p (r, a, g)
Function for computing the pressure for an ideal calorically perfect gas.
elemental function, public r (p, a, g)
Function for computing the density for an ideal calorically perfect gas.
elemental function, public a (p, r, g)
Function for computing the speed of sound for an ideal calorically perfect gas.
elemental function, public E (p, r, u, g)
Function for computing the total specific energy (per unit of mass) for an ideal calorically perfect gas.
elemental function, public H (p, r, u, g)
Function for computing the total specific entalpy (per unit of mass) for an ideal calorically perfect gas.
Member Function/Subroutine Documentation
elemental function, public Lib_Thermodynamic_Laws_Ideal::p (real(R_P), intent(in) r, real(R_P), intent(in) a, real(R_P), intent(in) g)
Function for computing the pressure for an ideal calorically perfect gas.
Parameters:
[in] r Density ().
[in] a Speed of sound.
[in] g Specific heats ratio .
Definition at line 23 of file Lib_Thermodynamic_Laws_Ideal.f90.
elemental function, public Lib_Thermodynamic_Laws_Ideal::r (real(R_P), intent(in) p, real(R_P), intent(in) a, real(R_P), intent(in) g)
Function for computing the density for an ideal calorically perfect gas.
Parameters:
[in] p Pressure.
[in] a Speed of sound.
[in] g Specific heats ratio .
Definition at line 39 of file Lib_Thermodynamic_Laws_Ideal.f90.
elemental function, public Lib_Thermodynamic_Laws_Ideal::a (real(R_P), intent(in) p, real(R_P), intent(in) r, real(R_P), intent(in) g)
Function for computing the speed of sound for an ideal calorically perfect gas.
Parameters:
[in] p Pressure.
[in] r Density ().
[in] g Specific heats ratio .
Definition at line 55 of file Lib_Thermodynamic_Laws_Ideal.f90.
elemental function, public Lib_Thermodynamic_Laws_Ideal::E (real(R_P), intent(in) p, real(R_P), intent(in) r, real(R_P), intent(in) u, real(R_P), intent(in) g)
Function for computing the total specific energy (per unit of mass) for an ideal calorically perfect gas.
Note:
This law is defined as:
Parameters:
[in] p Pressure.
[in] r Density ().
[in] u Module of velocity vector.
[in] g Specific heats ratio .
Definition at line 73 of file Lib_Thermodynamic_Laws_Ideal.f90.
elemental function, public Lib_Thermodynamic_Laws_Ideal::H (real(R_P), intent(in) p, real(R_P), intent(in) r, real(R_P), intent(in) u, real(R_P), intent(in) g)
Function for computing the total specific entalpy (per unit of mass) for an ideal calorically perfect gas.
Note:
This law is defined as:
Parameters:
[in] p Pressure.
[in] r Density ().
[in] u Module of velocity vector.
[in] g Specific heats ratio .
Definition at line 92 of file Lib_Thermodynamic_Laws_Ideal.f90.
module Lib_VTK_IO
This is a library of functions for Input and Output pure Fortran data in VTK format.
It is useful for Paraview visualization tool. Even though there are many wrappers/porting of the VTK source code (C++ code), there is not a Fortran one. This library is not a porting or a wrapper of the VTK code, but it only an exporter/importer of the VTK data format written in pure Fortran language (standard Fortran 2003) that can be used by Fortran coders (yes, there are still a lot of these brave coders...) without mixing Fortran with C++ language. Fortran is still the best language for high performance computing for scientific purpose, like CFD computing. It is necessary a tool to deal with VTK standard directly by Fortran code. The library was made to fill this empty: it is a simple Fortran module able to export native Fortran data into VTK data format and to import VTK data into a Fortran code, both in ascii and binary file format.
The library provides an automatic way to deal with VTK data format: all the formatting processes is nested into the library and users communicate with it by a simple API passing only native Fortran data (native Fortran scalar, vector and matrix).
The library is still in developing and testing, this is first usable release, but there are not all the features of the stable release (the importer is totally absent and the exporter is not complete). Surely there are a lot of bugs and the programming style is not the best, but the exporters are far-complete.
The supported VTK features are:
Exporters:
Legacy standard:
Structured Points;
Structured Grid;
Unstructured Grid;
Polydata (missing);
Rectilinear Grid;
Field (missing);
XML standard:
Image Data (missing);
Polydata (missing);
Rectilinear Grid;
Structured Grid;
Unstructured Grid;
Parallel Image Data (missing);
Parallel Polydata (missing);
Parallel Rectilinear Grid (missing);
Parallel Structured Grid (missing);
Parallel Unstructured Grid (missing);
Importers are missing.
The library is an open source project, it is distributed under the GPL v3. Anyone is interest to use, to develop or to contribute to Lib_VTK_IO is welcome.
It can be found at: https://github.com/szaghi/Lib_VTK_IO
VTK_Standard
VTK, Visualization Toolkit, is an open source software that provides a powerful framework for the computer graphic, for the images processing and for 3D rendering. It is widely used in the world and so it has a very large community of users, besides the Kitware (The Kitware homepage can be found here: http://public.kitware.com) company provides professional support. The toolkit is written in C++ and a lot of porting/wrappers for Tcl/Tk, Java and Python are provided, unlucky there aren't wrappers for Fortran.
Because of its good features the VTK toolkit has been used to develop a large set of open source programs. For my work the most important family of programs is the scientific visualization programs. A lot of high-quality scientific visualization tool are available on the web but for me the best is ParaView: I think that it is one of the best scientific visualization program in the world and it is open source! Paraview is based on VTK.
Paraview
ParaView (The ParaView homepage can be found here: http://www.paraview.org) is an open source software voted to scientific visualization and able to use the power of parallel architectures. It has an architecture client-server in order to make easy the remote visualization of very large set of data. Because it is based on VTK it inherits all VTK features. ParaView is very useful for Computational Fluid Dynamics visualizations because it provides powerful post-processing tools, it provides a very large set of importers for the most used format like Plot3D and HDF (the list is very large). It is easy to extend ParaView because it supports all the scripting language supported by VTK.
Note:
All the Lib_VTK_IO functions are I4P integer functions: the returned integer output is 0 if the function calling has been completed right while it is >0 if some errors occur (the error handling is only at its embryonic phase). Therefore the functions calling must be done in the following way:
 ...
 integer(I4P):: E_IO
 ...
 E_IO = VTK_INI(....
 ...
Lib_VTK_IO programming style is based on two main principles: portable kind-precision of reals and integers variables and dynamic dispatching. Using dynamic dispatching Lib_VTK_IO has a simple API. The user calls a generic procedure (VTK_INI, VTK_GEO,...) and the library, depending on the type and number of the inputs passed, calls the correct internal function (i.e. VTK_GEO for R8P real type if the input passed is R8P real type). By this interface only few functions are used without the necessity of calling a different function for every different inputs type. Dynamic dispatching is based on the internal kind-precision selecting convention: Fortran 90/95 standard has introduced some useful functions to achieve the portability of reals and integers precision and Lib_VTK_IO uses these functions to define portable kind-precision; to this aim Lib_VTK_IO uses IR_Precision module.
Author:
Stefano Zaghi
Version:
1.0
Date:
2012-04-24
Copyright:
GNU Public License version 3.
Todo:
CompleteExporter: Complete the exporters
CompleteImporter: Complete the importers
DocExamples: Improve the documentation by means of examples
DocMakeFile: Create the documentation of makefile
g95_test: Test g95 compiler
Bug:
Array-Reshape:
Fortran allows automatic reshape of arrays, e.g. 2D array can be automatically (in the function calling) transformed to a 1D array with the same number of element of 2D array. The use of dynamic dispatching for Lib_VTK_IO functions by means of generic interfaces had disable this feature: dynamic dispatching use the array-shape information to detect, at compile-time, the correct function to be called inside the generic interface functions. Thus automatic reshaping of arrays at calling function phase is not allowed.
Instead an explicit reshape can be used by means of the Fortran built-in function reshape. As an example considering a call to the generic function VTK_VAR_XML an explicit array reshape could be:
E_IO = VTK_VAR_XML(NC_NN=nn,varname='u',var=reshape(u(ni1:ni2,nj1:nj2,nk1:nk2),(/nn/)))
where built in function reshape has explicitly being used in the calling to VTK_VAR_XML.
XML-Efficiency:
This is not properly a bug. There is an inefficiency when saving XML binary file. To write XML binary Lib_VTK_IO uses a temporary scratch file to save binary data while saving all formatting data to the final XML file. Only when all XML formatting data have been written the scratch file is rewind and the binary data is saved in the final tag of XML file as raw data. This approach is not efficient.
Definition at line 111 of file Lib_VTK_IO.f90.
Public Member Functions
integer(I4P) function, public VTK_INI (output_format, filename, title, mesh_topology)
Function for initializing VTK-legacy file.
integer(I4P) function, public VTK_CON (NC, connect, cell_type)
Function that must be used when unstructured grid is used, it saves the connectivity of the unstructured gird.
integer(I4P) function, public VTK_DAT (NC_NN, var_location)
Function that must be called before saving the data related to geometric mesh, this function initializes the saving of data variables indicating the type (node or cell centered) of variables that will be saved.
integer(I4P) function, public VTK_END ()
Function for finalizing open file, it has not inputs, Lib_VTK_IO manages the file unit without the user's action.
integer(I4P) function, public VTK_INI_XML (output_format, filename, mesh_topology, nx1, nx2, ny1, ny2, nz1, nz2)
Function for initializing VTK-XML file.
integer(I4P) function, public VTK_CON_XML (NC, connect, offset, cell_type)
Function that must be used when unstructured grid is used, it saves the connectivity of the unstructured gird.
integer(I4P) function, public VTK_DAT_XML (var_location, var_block_action)
Function that must be called before saving the data related to geometric mesh, this function initializes the saving of data variables indicating the type (node or cell centered) of variables that will be saved.
integer(I4P) function, public VTK_END_XML ()
This function is used to finalize the file opened and it has not inputs, Lib_VTK_IO manages the file unit without the user's action.
integer(I4P) function, public VTM_INI_XML (filename)
The VTK_VTM_XML function is used for initializing a VTM (VTK Multiblocks) XML file that is a wrapper to a set of VTK-XML files.
integer(I4P) function, public VTM_BLK_XML (block_action)
The VTM_BLK_XML function is used for opening or closing a block level of a VTM file.
integer(I4P) function, public VTM_WRF_XML (wrf_dir, vtk_xml_file_list)
The VTM_WRF_XML function is used for saving the list of VTK-XML wrapped files by the actual block of the mutliblock VTM file.
integer(I4P) function, public VTM_END_XML ()
Function for finalizing open file, it has not inputs, Lib_VTK_IO manages the file unit without the user's action.
Private Member Functions
integer function GetUnit ()
Function for getting a free logic unit.
character(len=len(string)) function Upper_Case (string)
Function for converting lower case characters of a string to upper case ones.
integer(I4P) function VTK_GEO_STRP_R8 (Nx, Ny, Nz, X0, Y0, Z0, Dx, Dy, Dz)
Function for saving mesh with STRUCTURED_POINTS topology (R8P).
integer(I4P) function VTK_GEO_STRP_R4 (Nx, Ny, Nz, X0, Y0, Z0, Dx, Dy, Dz)
Function for saving mesh with STRUCTURED_POINTS topology (R4P).
integer(I4P) function VTK_GEO_STRG_R8 (Nx, Ny, Nz, NN, X, Y, Z)
Function for saving mesh with STRUCTURED_GRID topology (R8P).
integer(I4P) function VTK_GEO_STRG_R4 (Nx, Ny, Nz, NN, X, Y, Z)
Function for saving mesh with STRUCTURED_GRID topology (R4P).
integer(I4P) function VTK_GEO_RECT_R8 (Nx, Ny, Nz, X, Y, Z)
Function for saving mesh with RECTILINEAR_GRID topology (R8P).
integer(I4P) function VTK_GEO_RECT_R4 (Nx, Ny, Nz, X, Y, Z)
Function for saving mesh with RECTILINEAR_GRID topology (R4P).
integer(I4P) function VTK_GEO_UNST_R8 (NN, X, Y, Z)
Function for saving mesh with UNSTRUCTURED_GRID topology (R8P).
integer(I4P) function VTK_GEO_UNST_R4 (NN, X, Y, Z)
Function for saving mesh with UNSTRUCTURED_GRID topology (R4P).
integer(I4P) function VTK_VAR_SCAL_R8 (NC_NN, varname, var)
Function for saving field of scalar variable (R8P).
integer(I4P) function VTK_VAR_SCAL_R4 (NC_NN, varname, var)
Function for saving field of scalar variable (R4P).
integer(I4P) function VTK_VAR_SCAL_I4 (NC_NN, varname, var)
Function for saving field of scalar variable (I4P).
integer(I4P) function VTK_VAR_VECT_R8 (vec_type, NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (R8P).
integer(I4P) function VTK_VAR_VECT_R4 (vec_type, NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (R4P).
integer(I4P) function VTK_VAR_VECT_I4 (NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (I4P).
integer(I4P) function VTK_VAR_TEXT_R8 (NC_NN, dimm, varname, textCoo)
Function for saving texture variable (R8P).
integer(I4P) function VTK_VAR_TEXT_R4 (NC_NN, dimm, varname, textCoo)
Function for saving texture variable (R4P).
integer(I4P) function VTK_GEO_XML_STRG_R8 (nx1, nx2, ny1, ny2, nz1, nz2, NN, X, Y, Z)
Function for saving mesh with StructuredGrid topology (R8P).
integer(I4P) function VTK_GEO_XML_STRG_R4 (nx1, nx2, ny1, ny2, nz1, nz2, NN, X, Y, Z)
Function for saving mesh with StructuredGrid topology (R4P).
integer(I4P) function VTK_GEO_XML_RECT_R8 (nx1, nx2, ny1, ny2, nz1, nz2, X, Y, Z)
Function for saving mesh with RectilinearGrid topology (R8P).
integer(I4P) function VTK_GEO_XML_RECT_R4 (nx1, nx2, ny1, ny2, nz1, nz2, X, Y, Z)
Function for saving mesh with RectilinearGrid topology (R4P).
integer(I4P) function VTK_GEO_XML_UNST_R8 (NN, NC, X, Y, Z)
Function for saving mesh with UnstructuredGrid topology (R8P).
integer(I4P) function VTK_GEO_XML_UNST_R4 (NN, NC, X, Y, Z)
Function for saving mesh with UnstructuredGrid topology (R4P).
integer(I4P) function VTK_GEO_XML_CLOSEP ()
Function for closing mesh block data.
integer(I4P) function VTK_VAR_XML_SCAL_R8 (NC_NN, varname, var)
Function for saving field of scalar variable (R8P).
integer(I4P) function VTK_VAR_XML_SCAL_R4 (NC_NN, varname, var)
Function for saving field of scalar variable (R4P).
integer(I4P) function VTK_VAR_XML_SCAL_I8 (NC_NN, varname, var)
Function for saving field of scalar variable (I8P).
integer(I4P) function VTK_VAR_XML_SCAL_I4 (NC_NN, varname, var)
Function for saving field of scalar variable (I4P).
integer(I4P) function VTK_VAR_XML_SCAL_I2 (NC_NN, varname, var)
Function for saving field of scalar variable (I2P).
integer(I4P) function VTK_VAR_XML_SCAL_I1 (NC_NN, varname, var)
Function for saving field of scalar variable (I1P).
integer(I4P) function VTK_VAR_XML_VECT_R8 (NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (R8P).
integer(I4P) function VTK_VAR_XML_VECT_R4 (NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (R4P).
integer(I4P) function VTK_VAR_XML_VECT_I8 (NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (I8P).
integer(I4P) function VTK_VAR_XML_VECT_I4 (NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (I4P).
integer(I4P) function VTK_VAR_XML_VECT_I2 (NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (I2P).
integer(I4P) function VTK_VAR_XML_VECT_I1 (NC_NN, varname, varX, varY, varZ)
Function for saving field of vectorial variable (I1P).
integer(I4P) function VTK_VAR_XML_LIST_R8 (NC_NN, N_COL, varname, var)
Function for saving field of list variable (R8P).
integer(I4P) function VTK_VAR_XML_LIST_R4 (NC_NN, N_COL, varname, var)
Function for saving field of list variable (R4P).
integer(I4P) function VTK_VAR_XML_LIST_I8 (NC_NN, N_COL, varname, var)
Function for saving field of list variable (I8P).
integer(I4P) function VTK_VAR_XML_LIST_I4 (NC_NN, N_COL, varname, var)
Function for saving field of list variable (I4P).
integer(I4P) function VTK_VAR_XML_LIST_I2 (NC_NN, N_COL, varname, var)
Function for saving field of list variable (I2P).
integer(I4P) function VTK_VAR_XML_LIST_I1 (NC_NN, N_COL, varname, var)
Function for saving field of list variable (I1P).
Private Attributes
integer(I4P), parameter maxlen = 500
Max number of characters of static string.
character(1), parameter end_rec = char(10)
End-character for binary-record finalize.
integer(I4P), parameter f_out_ascii = 0
Ascii-output-format parameter identifier.
integer(I4P), parameter f_out_binary = 1
Binary-output-format parameter identifier.
integer(I4P) f_out = f_out_ascii
Current output-format (initialized to ascii format).
character(len=maxlen) topology
Mesh topology.
integer(I4P) Unit_VTK
Internal logical unit.
integer(I4P) Unit_VTK_Append
Internal logical unit for raw binary XML append file.
integer(I4P) N_Byte
Number of byte to be written/read.
real(R8P) Tipo_R8 = 1._R8P
Prototype of R8P real.
real(R4P) Tipo_R4 = 1._R4P
Prototype of R4P real.
integer(I8P) Tipo_I8 = 1_I8P
Prototype of I8P integer.
integer(I4P) Tipo_I4 = 1_I4P
Prototype of I4P integer.
integer(I2P) Tipo_I2 = 1_I2P
Prototype of I2P integer.
integer(I1P) Tipo_I1 = 1_I1P
Prototype of I1P integer.
integer(I8P) ioffset
Offset pointer.
integer(I4P) indent
Indent pointer.
integer(I4P) Unit_VTM
Internal logical unit.
integer(I4P) blk
Block index.
integer(I4P) vtm_indent
Indent pointer.
Member Function/Subroutine Documentation
integer function Lib_VTK_IO::GetUnit () [private]
Function for getting a free logic unit.
The users of Lib_VTK_IO does not know which is the logical unit: Lib_VTK_IO uses this information without boring the users. The logical unit used is safe-free: if the program calling Lib_VTK_IO has others logical units used Lib_VTK_IO will never use these units, but will choice one that is free.
Returns:
Free_Unit
Definition at line 341 of file Lib_VTK_IO.f90.
character(len=len(string)) function Lib_VTK_IO::Upper_Case (character(len=len(string)), intent(in) string) [private]
Function for converting lower case characters of a string to upper case ones.
Lib_VTK_IO uses this function in order to achieve case-insensitive: all character variables used within Lib_VTK_IO functions are pre-processed by Uppper_Case function before these variables are used. So the users can call Lib_VTK_IO functions without pay attention of the case of the keywords passed to the functions: calling the function VTK_INI with the string E_IO = VTK_INI('Ascii',...) is equivalent to E_IO = VTK_INI('ASCII',...).
Returns:
Upper_Case
Parameters:
[in] string String to be converted.
Definition at line 375 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTK_INI (character(*), intent(in) output_format, character(*), intent(in) filename, character(*), intent(in) title, character(*), intent(in) mesh_topology)
Function for initializing VTK-legacy file.
Remarks:
This function must be the first to be called.
Note:
An example of usage is:
 ...
 E_IO=VTK_INI('Binary','example.vtk','VTK legacy file','UNSTRUCTURED_GRID')
 ...
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] output_format Output format: ASCII or BINARY.
[in] filename Name of file.
[in] title Title.
[in] mesh_topology Mesh topology.
Definition at line 402 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_STRP_R8 (integer(I4P), intent(in) Nx, integer(I4P), intent(in) Ny, integer(I4P), intent(in) Nz, real(R8P), intent(in) X0, real(R8P), intent(in) Y0, real(R8P), intent(in) Z0, real(R8P), intent(in) Dx, real(R8P), intent(in) Dy, real(R8P), intent(in) Dz) [private]
Function for saving mesh with STRUCTURED_POINTS topology (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] Nx Number of nodes in x direction.
[in] Ny Number of nodes in y direction.
[in] Nz Number of nodes in z direction.
[in] X0 X coordinate of origin.
[in] Y0 Y coordinate of origin.
[in] Z0 Z coordinate of origin.
[in] Dx Space step in x direction.
[in] Dy Space step in y direction.
[in] Dz Space step in z direction.
Definition at line 449 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_STRP_R4 (integer(I4P), intent(in) Nx, integer(I4P), intent(in) Ny, integer(I4P), intent(in) Nz, real(R4P), intent(in) X0, real(R4P), intent(in) Y0, real(R4P), intent(in) Z0, real(R4P), intent(in) Dx, real(R4P), intent(in) Dy, real(R4P), intent(in) Dz) [private]
Function for saving mesh with STRUCTURED_POINTS topology (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] Nx Number of nodes in x direction.
[in] Ny Number of nodes in y direction.
[in] Nz Number of nodes in z direction.
[in] X0 X coordinate of origin.
[in] Y0 Y coordinate of origin.
[in] Z0 Z coordinate of origin.
[in] Dx Space step in x direction.
[in] Dy Space step in y direction.
[in] Dz Space step in z direction.
Definition at line 485 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_STRG_R8 (integer(I4P), intent(in) Nx, integer(I4P), intent(in) Ny, integer(I4P), intent(in) Nz, integer(I4P), intent(in) NN, real(R8P), dimension(1:nn), intent(in) X, real(R8P), dimension(1:nn), intent(in) Y, real(R8P), dimension(1:nn), intent(in) Z) [private]
Function for saving mesh with STRUCTURED_GRID topology (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] Nx Number of nodes in x direction.
[in] Ny Number of nodes in y direction.
[in] Nz Number of nodes in z direction.
[in] NN Number of all nodes.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 521 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_STRG_R4 (integer(I4P), intent(in) Nx, integer(I4P), intent(in) Ny, integer(I4P), intent(in) Nz, integer(I4P), intent(in) NN, real(R4P), dimension(1:nn), intent(in) X, real(R4P), dimension(1:nn), intent(in) Y, real(R4P), dimension(1:nn), intent(in) Z) [private]
Function for saving mesh with STRUCTURED_GRID topology (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] Nx Number of nodes in x direction.
[in] Ny Number of nodes in y direction.
[in] Nz Number of nodes in z direction.
[in] NN Number of all nodes.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 556 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_RECT_R8 (integer(I4P), intent(in) Nx, integer(I4P), intent(in) Ny, integer(I4P), intent(in) Nz, real(R8P), dimension(1:nx), intent(in) X, real(R8P), dimension(1:ny), intent(in) Y, real(R8P), dimension(1:nz), intent(in) Z) [private]
Function for saving mesh with RECTILINEAR_GRID topology (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] Nx Number of nodes in x direction.
[in] Ny Number of nodes in y direction.
[in] Nz Number of nodes in z direction.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 591 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_RECT_R4 (integer(I4P), intent(in) Nx, integer(I4P), intent(in) Ny, integer(I4P), intent(in) Nz, real(R4P), dimension(1:nx), intent(in) X, real(R4P), dimension(1:ny), intent(in) Y, real(R4P), dimension(1:nz), intent(in) Z) [private]
Function for saving mesh with RECTILINEAR_GRID topology (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] Nx Number of nodes in x direction.
[in] Ny Number of nodes in y direction.
[in] Nz Number of nodes in z direction.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 637 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_UNST_R8 (integer(I4P), intent(in) NN, real(R8P), dimension(1:nn), intent(in) X, real(R8P), dimension(1:nn), intent(in) Y, real(R8P), dimension(1:nn), intent(in) Z) [private]
Function for saving mesh with UNSTRUCTURED_GRID topology (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NN Number of nodes.
[in] X X coordinates of all nodes.
[in] Y Y coordinates of all nodes.
[in] Z Z coordinates of all nodes.
Definition at line 683 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_UNST_R4 (integer(I4P), intent(in) NN, real(R4P), dimension(1:nn), intent(in) X, real(R4P), dimension(1:nn), intent(in) Y, real(R4P), dimension(1:nn), intent(in) Z) [private]
Function for saving mesh with UNSTRUCTURED_GRID topology (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NN number of nodes.
[in] X x coordinates of all nodes.
[in] Y y coordinates of all nodes.
[in] Z z coordinates of all nodes.
Definition at line 712 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTK_CON (integer(I4P), intent(in) NC, integer(I4P), dimension(:), intent(in) connect, integer(I4P), dimension(1:nc), intent(in) cell_type)
Function that must be used when unstructured grid is used, it saves the connectivity of the unstructured gird.
Note:
The vector connect must follow the VTK-legacy standard. It is passed as assumed-shape array because its dimensions is related to the mesh dimensions in a complex way. Its dimensions can be calculated by the following equation: where is connectivity vector dimension and is the number of vertices of cell. The VTK- legacy standard for the mesh connectivity is quite obscure at least at first sight. It is more simple analyzing an example. Suppose we have a mesh composed by 2 cells, one hexahedron (8 vertices) and one pyramid with square basis (5 vertices) and suppose that the basis of pyramid is constitute by a face of the hexahedron and so the two cells share 4 vertices. The above equation !> gives . The connectivity vector for this mesh can be:
first cell
connect(1) = 8 number of vertices of cell
connect(2) = 0 identification flag of vertex of 1 cell
connect(3) = 1 identification flag of vertex of 1 cell
connect(4) = 2 identification flag of vertex of 1 cell
connect(5) = 3 identification flag of vertex of 1 cell
connect(6) = 4 identification flag of vertex of 1 cell
connect(7) = 5 identification flag of vertex of 1 cell
connect(8) = 6 identification flag of vertex of 1 cell
connect(9) = 7 identification flag of vertex of 1 cell
second cell
connect(10) = 5 number of vertices of cell
connect(11) = 0 identification flag of vertex of 2 cell
connect(12) = 1 identification flag of vertex of 2 cell
connect(13) = 2 identification flag of vertex of 2 cell
connect(14) = 3 identification flag of vertex of 2 cell
connect(15) = 8 identification flag of vertex of 2 cell
Note that the first 4 identification flags of pyramid vertices as the same of the first 4 identification flags of the hexahedron because the two cells share this face. It is also important to note that the identification flags start form $0$ value: this is impose to the VTK standard. The function VTK_CON does not calculate the connectivity vector: it writes the connectivity vector conforming the VTK standard, but does not calculate it. The vector variable cell_type must conform the VTK-legacy standard (see the file VTK-Standard at the Kitware homepage). It contains the type of each cells. For the above example this vector is:
first cell
cell_type(1) = 12 hexahedron type of cell
second cell
cell_type(2) = 14 pyramid type of cell
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC Number of cells.
[in] connect Mesh connectivity.
[in] cell_type VTK cell type.
Definition at line 777 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTK_DAT (integer(I4P), intent(in) NC_NN, character(*), intent(in) var_location)
Function that must be called before saving the data related to geometric mesh, this function initializes the saving of data variables indicating the type (node or cell centered) of variables that will be saved.
Note:
A single file can contain both cell and node centered variables. In this case the VTK_DAT function must be called two times, before saving cell-centered variables and before saving node-centered variables. Examples of usage are:
Node piece:
 ...
 E_IO=VTK_DAT(50,'node')
 ...
Cell piece:
 ...
 E_IO=VTK_DAT(50,'cell')
 ...
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes of field.
[in] var_location Location of saving variables: cell for cell-centered, node for node-centered.
Definition at line 824 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_SCAL_R8 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, real(R8P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of nodes or cells.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 858 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_SCAL_R4 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, real(R4P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of nodes or cells.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 885 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_SCAL_I4 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I4P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (I4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of nodes or cells.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 912 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_VECT_R8 (character(*), intent(in) vec_type, integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, real(R8P), dimension(1:nc_nn), intent(in) varX, real(R8P), dimension(1:nc_nn), intent(in) varY, real(R8P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] vec_type Vector type: vect = generic vector , norm = normal vector.
[in] NC_NN Number of nodes or cells.
[in] varname Variable name.
[in] varX X component of vector.
[in] varY Y component of vector.
[in] varZ Z component of vector.
Definition at line 939 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_VECT_R4 (character(*), intent(in) vec_type, integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, real(R4P), dimension(1:nc_nn), intent(in) varX, real(R4P), dimension(1:nc_nn), intent(in) varY, real(R4P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] vec_type Vector type: vect = generic vector , norm = normal vector.
[in] NC_NN Number of nodes or cells.
[in] varname Variable name.
[in] varX X component of vector.
[in] varY Y component of vector.
[in] varZ Z component of vector.
Definition at line 978 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_VECT_I4 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I4P), dimension(1:nc_nn), intent(in) varX, integer(I4P), dimension(1:nc_nn), intent(in) varY, integer(I4P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (I4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of nodes or cells.
[in] varname Variable name.
[in] varX X component of vector.
[in] varY Y component of vector.
[in] varZ Z component of vector.
Definition at line 1017 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_TEXT_R8 (integer(I4P), intent(in) NC_NN, integer(I4P), intent(in) dimm, character(*), intent(in) varname, real(R8P), dimension(1:nc_nn,1:dimm), intent(in) textCoo) [private]
Function for saving texture variable (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of nodes or cells.
[in] dimm Texture dimensions.
[in] varname Variable name.
[in] textCoo Texture.
Definition at line 1045 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_TEXT_R4 (integer(I4P), intent(in) NC_NN, integer(I4P), intent(in) dimm, character(*), intent(in) varname, real(R4P), dimension(1:nc_nn,1:dimm), intent(in) textCoo) [private]
Function for saving texture variable (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of nodes or cells.
[in] dimm Texture dimensions.
[in] varname Variable name.
[in] textCoo Texture.
Definition at line 1076 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTK_END ()
Function for finalizing open file, it has not inputs, Lib_VTK_IO manages the file unit without the user's action.
Note:
An example of usage is:
 ...
 E_IO=VTK_END()
 ...
Returns:
E_IO: integer(I4P) error flag
Definition at line 1116 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTK_INI_XML (character(*), intent(in) output_format, character(*), intent(in) filename, character(*), intent(in) mesh_topology, integer(I4P), intent(in), optional nx1, integer(I4P), intent(in), optional nx2, integer(I4P), intent(in), optional ny1, integer(I4P), intent(in), optional ny2, integer(I4P), intent(in), optional nz1, integer(I4P), intent(in), optional nz2)
Function for initializing VTK-XML file.
The XML standard is more powerful than legacy one. It is more flexible and free but on the other hand is more (but not so more using a library like Lib_VTK_IO...) complex than legacy standard. The output of XML functions is a well-formated XML file at least for the ascii format (in the binary format Lib_VTK_IO uses raw-data format that does not produce a well formated XML file). Note that the XML functions have the same name of legacy functions with the suffix XML.
Remarks:
This function must be the first to be called.
Note:
An example of usage is:
 ...
 integer(I4P):: nx1,nx2,ny1,ny2,nz1,nz2
 ...
 E_IO = VTK_INI_XML('BINARY','XML_RECT_BINARY.vtr','RectilinearGrid',nx1=nx1,nx2=nx2,ny1=ny1,ny2=ny2,nz1=nz1,nz2=nz2)
 ...
Note that the file extension is necessary in the file name. The XML standard has different extensions for each different topologies (e.g. vtr for rectilinear topology). See the VTK-standard file for more information.
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] output_format Output format: ASCII or BINARY.
[in] filename File name.
[in] mesh_topology Mesh topology.
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
Definition at line 1144 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_XML_STRG_R8 (integer(I4P), intent(in) nx1, integer(I4P), intent(in) nx2, integer(I4P), intent(in) ny1, integer(I4P), intent(in) ny2, integer(I4P), intent(in) nz1, integer(I4P), intent(in) nz2, integer(I4P), intent(in) NN, real(R8P), dimension(1:nn), intent(in) X, real(R8P), dimension(1:nn), intent(in) Y, real(R8P), dimension(1:nn), intent(in) Z) [private]
Function for saving mesh with StructuredGrid topology (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] NN Number of all nodes
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 1239 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_XML_STRG_R4 (integer(I4P), intent(in) nx1, integer(I4P), intent(in) nx2, integer(I4P), intent(in) ny1, integer(I4P), intent(in) ny2, integer(I4P), intent(in) nz1, integer(I4P), intent(in) nz2, integer(I4P), intent(in) NN, real(R4P), dimension(1:nn), intent(in) X, real(R4P), dimension(1:nn), intent(in) Y, real(R4P), dimension(1:nn), intent(in) Z) [private]
Function for saving mesh with StructuredGrid topology (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] NN Number of all nodes.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 1295 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_XML_RECT_R8 (integer(I4P), intent(in) nx1, integer(I4P), intent(in) nx2, integer(I4P), intent(in) ny1, integer(I4P), intent(in) ny2, integer(I4P), intent(in) nz1, integer(I4P), intent(in) nz2, real(R8P), dimension(nx1:nx2), intent(in) X, real(R8P), dimension(ny1:ny2), intent(in) Y, real(R8P), dimension(nz1:nz2), intent(in) Z) [private]
Function for saving mesh with RectilinearGrid topology (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 1351 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_XML_RECT_R4 (integer(I4P), intent(in) nx1, integer(I4P), intent(in) nx2, integer(I4P), intent(in) ny1, integer(I4P), intent(in) ny2, integer(I4P), intent(in) nz1, integer(I4P), intent(in) nz2, real(R4P), dimension(nx1:nx2), intent(in) X, real(R4P), dimension(ny1:ny2), intent(in) Y, real(R4P), dimension(nz1:nz2), intent(in) Z) [private]
Function for saving mesh with RectilinearGrid topology (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] nx1 Initial node of x axis.
[in] nx2 Final node of x axis.
[in] ny1 Initial node of y axis.
[in] ny2 Final node of y axis.
[in] nz1 Initial node of z axis.
[in] nz2 Final node of z axis.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 1431 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_XML_UNST_R8 (integer(I4P), intent(in) NN, integer(I4P), intent(in) NC, real(R8P), dimension(1:nn), intent(in) X, real(R8P), dimension(1:nn), intent(in) Y, real(R8P), dimension(1:nn), intent(in) Z) [private]
Function for saving mesh with UnstructuredGrid topology (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NN Number of nodes.
[in] NC Number of cells.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 1511 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_XML_UNST_R4 (integer(I4P), intent(in) NN, integer(I4P), intent(in) NC, real(R4P), dimension(1:nn), intent(in) X, real(R4P), dimension(1:nn), intent(in) Y, real(R4P), dimension(1:nn), intent(in) Z) [private]
Function for saving mesh with UnstructuredGrid topology (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NN Number of nodes.
[in] NC Number of cells.
[in] X X coordinates.
[in] Y Y coordinates.
[in] Z Z coordinates.
Definition at line 1572 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_GEO_XML_CLOSEP () [private]
Function for closing mesh block data.
Returns:
E_IO: integer(I4P) error flag
Definition at line 1633 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTK_CON_XML (integer(I4P), intent(in) NC, integer(I4P), dimension(:), intent(in) connect, integer(I4P), dimension(1:nc), intent(in) offset, integer(I1P), dimension(1:nc), intent(in) cell_type)
Function that must be used when unstructured grid is used, it saves the connectivity of the unstructured gird.
Note:
The vector connect must follow the VTK-legacy standard. It is passed as assumed-shape array because its dimensions is related to the mesh dimensions in a complex way. Its dimensions can be calculated by the following equation: . Note that this equation is different from the legacy one. The XML connectivity convention is quite different from the legacy standard. As an example suppose we have a mesh composed by 2 cells, one hexahedron (8 vertices) and one pyramid with square basis (5 vertices) and suppose that the basis of pyramid is constitute by a face of the hexahedron and so the two cells share 4 vertices. The above equation gives . The connectivity vector for this mesh can be:
first cell
connect(1) = 0 identification flag of vertex of 1 cell
connect(2) = 1 identification flag of vertex of 1 cell
connect(3) = 2 identification flag of vertex of 1 cell
connect(4) = 3 identification flag of vertex of 1 cell
connect(5) = 4 identification flag of vertex of 1 cell
connect(6) = 5 identification flag of vertex of 1 cell
connect(7) = 6 identification flag of vertex of 1 cell
connect(8) = 7 identification flag of vertex of 1 cell
second cell
connect(9) = 0 identification flag of vertex of 2 cell
connect(10) = 1 identification flag of vertex of 2 cell
connect(11) = 2 identification flag of vertex of 2 cell
connect(12) = 3 identification flag of vertex of 2 cell
connect(13) = 8 identification flag of vertex of 2 cell
Therefore this connectivity vector convention is more simple than the legacy convention, now we must create also the offset vector that contains the data now missing in the connect vector. The offset vector for this mesh can be:
first cell
offset(1) = 8 => summ of nodes of cell
second cell
offset(2) = 13 => summ of nodes of and cells
The value of every cell-offset can be calculated by the following equation: where is the value of cell and is the number of vertices of cell. The function VTK_CON_XML does not calculate the connectivity and offset vectors: it writes the connectivity and offset vectors conforming the VTK-XML standard, but does not calculate them. The vector variable cell_type must conform the VTK-XML standard (see the file VTK-Standard at the Kitware homepage) that is the same of the legacy standard. It contains the type of each cells. For the above example this vector is:
first cell
cell_type(1) = 12 hexahedron type of cell
second cell
cell_type(2) = 14 pyramid type of cell
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC Number of cells.
[in] connect Mesh connectivity.
[in] offset Cell offset.
[in] cell_type VTK cell type.
Definition at line 1693 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTK_DAT_XML (character(*), intent(in) var_location, character(*), intent(in) var_block_action)
Function that must be called before saving the data related to geometric mesh, this function initializes the saving of data variables indicating the type (node or cell centered) of variables that will be saved.
Note:
A single file can contain both cell and node centered variables. In this case the VTK_DAT_XML function must be called two times, before saving cell-centered variables and before saving node-centered variables. Examples of usage are:
Opening node piece:
 ...
 E_IO=VTK_DAT_XML('node','OPEN')
 ...
Closing node piece:
 ...
 E_IO=VTK_DAT_XML('node','CLOSE')
 ...
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] var_location Location of saving variables: CELL for cell-centered, NODE for node-centered.
[in] var_block_action Variables block action: OPEN or CLOSE block.
Definition at line 1774 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_SCAL_R8 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, real(R8P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 1833 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_SCAL_R4 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, real(R4P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 1872 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_SCAL_I8 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I8P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (I8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 1911 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_SCAL_I4 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I4P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (I4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 1950 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_SCAL_I2 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I2P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (I2P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 1989 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_SCAL_I1 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I1P), dimension(1:nc_nn), intent(in) var) [private]
Function for saving field of scalar variable (I1P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] var Variable to be saved.
Definition at line 2028 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_VECT_R8 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, real(R8P), dimension(1:nc_nn), intent(in) varX, real(R8P), dimension(1:nc_nn), intent(in) varY, real(R8P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] varX X component.
[in] varY Y component.
[in] varZ Z component.
Definition at line 2067 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_VECT_R4 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, real(R4P), dimension(1:nc_nn), intent(in) varX, real(R4P), dimension(1:nc_nn), intent(in) varY, real(R4P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] varX X component.
[in] varY Y component.
[in] varZ Z component.
Definition at line 2108 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_VECT_I8 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I8P), dimension(1:nc_nn), intent(in) varX, integer(I8P), dimension(1:nc_nn), intent(in) varY, integer(I8P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (I8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] varX X component.
[in] varY Y component.
[in] varZ Z component.
Definition at line 2149 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_VECT_I4 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I4P), dimension(1:nc_nn), intent(in) varX, integer(I4P), dimension(1:nc_nn), intent(in) varY, integer(I4P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (I4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] varX X component.
[in] varY Y component.
[in] varZ Z component.
Definition at line 2190 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_VECT_I2 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I2P), dimension(1:nc_nn), intent(in) varX, integer(I2P), dimension(1:nc_nn), intent(in) varY, integer(I2P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (I2P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] varX X component.
[in] varY Y component.
[in] varZ Z component.
Definition at line 2231 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_VECT_I1 (integer(I4P), intent(in) NC_NN, character(*), intent(in) varname, integer(I1P), dimension(1:nc_nn), intent(in) varX, integer(I1P), dimension(1:nc_nn), intent(in) varY, integer(I1P), dimension(1:nc_nn), intent(in) varZ) [private]
Function for saving field of vectorial variable (I1P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] varname Variable name.
[in] varX X component.
[in] varY Y component.
[in] varZ Z component.
Definition at line 2272 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_LIST_R8 (integer(I4P), intent(in) NC_NN, integer(I4P), intent(in) N_COL, character(*), intent(in) varname, real(R8P), dimension(1:nc_nn,1:n_col), intent(in) var) [private]
Function for saving field of list variable (R8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] N_COL Number of columns.
[in] varname Variable name.
[in] var Components.
Definition at line 2313 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_LIST_R4 (integer(I4P), intent(in) NC_NN, integer(I4P), intent(in) N_COL, character(*), intent(in) varname, real(R4P), dimension(1:nc_nn,1:n_col), intent(in) var) [private]
Function for saving field of list variable (R4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] N_COL Number of columns.
[in] varname Variable name.
[in] var Components.
Definition at line 2360 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_LIST_I8 (integer(I4P), intent(in) NC_NN, integer(I4P), intent(in) N_COL, character(*), intent(in) varname, integer(I8P), dimension(1:nc_nn,1:n_col), intent(in) var) [private]
Function for saving field of list variable (I8P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] N_COL Number of columns.
[in] varname Variable name.
[in] var Components.
Definition at line 2407 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_LIST_I4 (integer(I4P), intent(in) NC_NN, integer(I4P), intent(in) N_COL, character(*), intent(in) varname, integer(I4P), dimension(1:nc_nn,1:n_col), intent(in) var) [private]
Function for saving field of list variable (I4P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] N_COL Number of columns.
[in] varname Variable name.
[in] var Components.
Definition at line 2454 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_LIST_I2 (integer(I4P), intent(in) NC_NN, integer(I4P), intent(in) N_COL, character(*), intent(in) varname, integer(I2P), dimension(1:nc_nn,1:n_col), intent(in) var) [private]
Function for saving field of list variable (I2P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] N_COL Number of columns.
[in] varname Variable name.
[in] var Components.
Definition at line 2501 of file Lib_VTK_IO.f90.
integer(I4P) function Lib_VTK_IO::VTK_VAR_XML_LIST_I1 (integer(I4P), intent(in) NC_NN, integer(I4P), intent(in) N_COL, character(*), intent(in) varname, integer(I1P), dimension(1:nc_nn,1:n_col), intent(in) var) [private]
Function for saving field of list variable (I1P).
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] NC_NN Number of cells or nodes.
[in] N_COL Number of columns.
[in] varname Variable name.
[in] var Components.
Definition at line 2548 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTK_END_XML ()
This function is used to finalize the file opened and it has not inputs, Lib_VTK_IO manages the file unit without the user's action.
Note:
An example of usage is:
 ...
 E_IO=VTK_END_XML()
 ...
Returns:
E_IO: integer(I4P) error flag
Definition at line 2600 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTM_INI_XML (character(*), intent(in) filename)
The VTK_VTM_XML function is used for initializing a VTM (VTK Multiblocks) XML file that is a wrapper to a set of VTK-XML files.
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] filename File name of output VTM file.
Definition at line 2683 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTM_BLK_XML (character(*), intent(in) block_action)
The VTM_BLK_XML function is used for opening or closing a block level of a VTM file.
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] block_action Block action: OPEN or CLOSE block.
Definition at line 2712 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTM_WRF_XML (character(*), intent(in), optional wrf_dir, character(*), dimension(:), intent(in) vtk_xml_file_list)
The VTM_WRF_XML function is used for saving the list of VTK-XML wrapped files by the actual block of the mutliblock VTM file.
Returns:
E_IO: integer(I4P) error flag
Parameters:
[in] wrf_dir Directory into which wrapped VTK-XML are (optional).
[in] vtk_xml_file_list List of VTK-XML wrapped files.
Definition at line 2735 of file Lib_VTK_IO.f90.
integer(I4P) function, public Lib_VTK_IO::VTM_END_XML ()
Function for finalizing open file, it has not inputs, Lib_VTK_IO manages the file unit without the user's action.
Returns:
E_IO: integer(I4P) error flag
Definition at line 2767 of file Lib_VTK_IO.f90.
Member Data Documentation
integer(I4P), parameter Lib_VTK_IO::maxlen = 500 [private]
Max number of characters of static string.
Definition at line 312 of file Lib_VTK_IO.f90.
character(1), parameter Lib_VTK_IO::end_rec = char(10) [private]
End-character for binary-record finalize.
Definition at line 313 of file Lib_VTK_IO.f90.
integer(I4P), parameter Lib_VTK_IO::f_out_ascii = 0 [private]
Ascii-output-format parameter identifier.
Definition at line 314 of file Lib_VTK_IO.f90.
integer(I4P), parameter Lib_VTK_IO::f_out_binary = 1 [private]
Binary-output-format parameter identifier.
Definition at line 315 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::f_out = f_out_ascii [private]
Current output-format (initialized to ascii format).
Definition at line 316 of file Lib_VTK_IO.f90.
character(len=maxlen) Lib_VTK_IO::topology [private]
Mesh topology.
Definition at line 317 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::Unit_VTK [private]
Internal logical unit.
Definition at line 318 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::Unit_VTK_Append [private]
Internal logical unit for raw binary XML append file.
Definition at line 319 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::N_Byte [private]
Number of byte to be written/read.
Definition at line 320 of file Lib_VTK_IO.f90.
real(R8P) Lib_VTK_IO::Tipo_R8 = 1._R8P [private]
Prototype of R8P real.
Definition at line 321 of file Lib_VTK_IO.f90.
real(R4P) Lib_VTK_IO::Tipo_R4 = 1._R4P [private]
Prototype of R4P real.
Definition at line 322 of file Lib_VTK_IO.f90.
integer(I8P) Lib_VTK_IO::Tipo_I8 = 1_I8P [private]
Prototype of I8P integer.
Definition at line 323 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::Tipo_I4 = 1_I4P [private]
Prototype of I4P integer.
Definition at line 324 of file Lib_VTK_IO.f90.
integer(I2P) Lib_VTK_IO::Tipo_I2 = 1_I2P [private]
Prototype of I2P integer.
Definition at line 325 of file Lib_VTK_IO.f90.
integer(I1P) Lib_VTK_IO::Tipo_I1 = 1_I1P [private]
Prototype of I1P integer.
Definition at line 326 of file Lib_VTK_IO.f90.
integer(I8P) Lib_VTK_IO::ioffset [private]
Offset pointer.
Definition at line 327 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::indent [private]
Indent pointer.
Definition at line 328 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::Unit_VTM [private]
Internal logical unit.
Definition at line 329 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::blk [private]
Block index.
Definition at line 330 of file Lib_VTK_IO.f90.
integer(I4P) Lib_VTK_IO::vtm_indent [private]
Indent pointer.
Definition at line 331 of file Lib_VTK_IO.f90.
module Lib_WENO
This module contains the definition of procedures for computing WENO reconstruction with a user-defined order.
Todo:
DocComplete: Complete the documentation of internal procedures
Definition at line 8 of file Lib_WENO.f90.
Public Member Functions
subroutine, public weno_init (myrank, global, block, S)
Subroutine for initialization of WENO coefficients.
pure function, public noweno_central (S, V)
Function for computing central difference reconstruction of order instead of WENO one.
pure function, public weno_optimal (S, V)
Function for computing WENO reconstruction with optimal weights (without smoothness indicators computations) of order.
pure function, public weno (S, V)
Function for computing WENO reconstruction of order.
Private Member Functions
pure function weno_polynomials (S, V)
pure function weno_weights (S, V)
pure function weno_convolution (S, VP, w)
recursive pure function udiff (p, v)
Private Attributes
real(R_P), dimension(:,:),
allocatable weno_c
real(R_P), dimension(:,:),
allocatable weno_a
real(R_P), dimension(:,:,:),
allocatable weno_p
real(R_P), dimension(:,:,:),
allocatable weno_d
real(R_P) weno_eps
integer(I_P) weno_odd
integer(I_P) weno_exp
Member Function/Subroutine Documentation
subroutine, public Lib_WENO::weno_init (integer(I_P), intent(in) myrank, type(Type_Global), intent(in) global, type(Type_Block), dimension(1:global%mesh%nb), intent(in) block, integer(I1P), intent(in) S)
Subroutine for initialization of WENO coefficients.
Parameters:
[in] myrank Actual rank process.
[in] global Global-level data.
[in] block Block-level data.
[in] S Number of stencils used.
Definition at line 36 of file Lib_WENO.f90.
References get_min_sstep().
pure function, public Lib_WENO::noweno_central (integer(I_P), intent(in) S, real(R_P), dimension (1:2,0:2*s), intent(in) V)
Function for computing central difference reconstruction of order instead of WENO one.
Parameters:
[in] S Number of stencils used.
[in] V Variable to be reconstructed.
Definition at line 283 of file Lib_WENO.f90.
pure function, public Lib_WENO::weno_optimal (integer(I_P), intent(in) S, real(R_P), dimension (1:2,1-s:-1+s), intent(in) V)
Function for computing WENO reconstruction with optimal weights (without smoothness indicators computations) of order.
Parameters:
[in] S Number of stencils used.
[in] V Variable to be reconstructed.
Definition at line 306 of file Lib_WENO.f90.
pure function, public Lib_WENO::weno (integer(I_P), intent(in) S, real(R_P), dimension (1:2,1-s:-1+s), intent(in) V)
Function for computing WENO reconstruction of order.
Parameters:
[in] S Number of stencils used.
[in] V Variable to be reconstructed.
Definition at line 328 of file Lib_WENO.f90.
pure function Lib_WENO::weno_polynomials (integer(I_P), intent(in) S, real(R_P), dimension (1:2,1-s:-1+s), intent(in) V) [private]
Definition at line 349 of file Lib_WENO.f90.
pure function Lib_WENO::weno_weights (integer(I_P), intent(in) S, real(R_P), dimension (1:2,1-s:-1+s), intent(in) V) [private]
Definition at line 376 of file Lib_WENO.f90.
pure function Lib_WENO::weno_convolution (integer(I_P), intent(in) S, real(R_P), dimension(1:2,0:s-1), intent(in) VP, real(R_P), dimension (1:2,0:s-1), intent(in) w) [private]
Definition at line 434 of file Lib_WENO.f90.
recursive pure function Lib_WENO::udiff (integer(I_P), intent(in) p, real(R_P), dimension(1:p+1), intent(in) v) [private]
Definition at line 460 of file Lib_WENO.f90.
Member Data Documentation
real(R_P), dimension(:,:), allocatable Lib_WENO::weno_c [private]
Definition at line 26 of file Lib_WENO.f90.
real(R_P), dimension(:,:), allocatable Lib_WENO::weno_a [private]
Definition at line 27 of file Lib_WENO.f90.
real(R_P), dimension(:,:,:), allocatable Lib_WENO::weno_p [private]
Definition at line 28 of file Lib_WENO.f90.
real(R_P), dimension(:,:,:), allocatable Lib_WENO::weno_d [private]
Definition at line 29 of file Lib_WENO.f90.
real(R_P) Lib_WENO::weno_eps [private]
Definition at line 30 of file Lib_WENO.f90.
integer(I_P) Lib_WENO::weno_odd [private]
Definition at line 31 of file Lib_WENO.f90.
integer(I_P) Lib_WENO::weno_exp [private]
Definition at line 32 of file Lib_WENO.f90.